### ISSUE TITLE
Windows release for CPU

### ISSUE THREAD

**Issue by ichDaheim** [TabbyML/tabby#1023]
**Please describe the feature you want**
The new windows release is great stuff. Many, many thanks @darknight !! 
Unfortunately it runs only if you have a Nvidia graphics card with CUDA installed. 
Could you provide a version for the "gpu poor" people ;-) (for cpu only) as well? 

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
This should be an easy one by following existing `windows` example in https://github.com/TabbyML/tabby/blob/main/.github/workflows/release.yml - just need to add new item to matrix that:
1. Build in windows without cuda installed.
2. do not set `--features cuda`

**Comment by ichDaheim** [comment]
feat: windows release for cpu #1045 

gave it a try
