### ISSUE TITLE
recipe to integrate with vim-cmp ?

### ISSUE THREAD

**Issue by pjz** [TabbyML/tabby#1024]
**Please describe the feature you want**

Anyone have a recipe to integrate with nvim-cmp? Right now they both use Tab which conflicts: I see the tabby completion, but then the nvim-cmp completions also show, and end up preferred for selection. nvim-cmp, though, is extensible, so it should be possible to add tabby as a completion source... if that's the right way to do it.

**Additional context**

Even a way to get them to coexist nicely would be nice.

---
Please reply with a 👍 if you want this feature.

**Comment by ms-jpq** [comment]
https://github.com/ms-jpq/coq.thirdparty/blob/3p/lua/coq_3p/tabby/init.lua

I made it for https://github.com/ms-jpq/coq_nvim.

Its pretty easy, just make the RPC calls yourself
