### ISSUE TITLE
Code chat in IDE Extension

### ISSUE THREAD

**Issue by p91paul** [TabbyML/tabby#1025]
In addition to completion, would be nice to have code chat in the IDE extension. Ideally, the chat should prioritize putting the currently selected lines/functions/files in the prompt context (the chat playground in the browser cannot do that, you need to copy paste code for it to be useful).

**Additional context**
I saw https://github.com/TabbyML/tabby/issues/506, so I know doing this is already in your plans. This issue is mainly for me and maybe others to follow progress and know when it's implemented!

---
Please reply with a 👍 if you want this feature.

**Comment by icycodes** [comment]
Thank you for bringing up this topic. Some other AI code assistant plugins already offer this feature, and I agree that integrating a chat view into IDEs could be useful.   
However, effectively combining the project code context with the conversation context may present some challenges. I am planning to explore approaches in the coming weeks to address this.

**Comment by RobertBiehl** [comment]
> Thank you for bringing up this topic. Some other AI code assistant plugins already offer this feature, and I agree that integrating a chat view into IDEs could be useful. However, effectively combining the project code context with the conversation context may present some challenges. I am planning to explore approaches in the coming weeks to address this.

To maybe simplify at first and keep the IDE out of the loop, does the exiting chat in tabby at http://localhost:8080/playground already use the code index? If not, what do you think it would take to make it use it? Could queries for the index be created from free form queries in a chat or just code symbols?

**Comment by wsxiaoys** [comment]
This will be released as part of vscode 1.7

**Comment by jtbr** [comment]
I've briefly tried the VS code plugin 1.7.2's chat functionality. It's a great start. But I second @p91paul : the ability to include code as context (perhaps by default the open editor window, e.g.) to the chat LLM is going to be a huge improvement. (It would also be helpful to be able structure the question with multiple lines and markdown or code snippets)
