### ISSUE TITLE
[TAB-441] Job management

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#1041]
Requires implementation of https://github.com/TabbyML/tabby/issues/1037

Steps
- [x] #1117
- [x] #1118

<sub>[TAB-441](https://linear.app/tabbyml/issue/TAB-441/job-management)</sub>

**Comment by bobsongplus** [comment]
I could pick step1 in this issue to implement GraphQL API if no one has started. 😄

**Comment by wsxiaoys** [comment]
@darknight is working on this - Thanks for offering the help!
