### ISSUE TITLE
Invalid Model Id

### ISSUE THREAD

**Issue by linpan** [TabbyML/tabby#1048]
docker image: 
![CleanShot 2023-12-15 at 11 12 25](https://github.com/TabbyML/tabby/assets/6077601/38ba1382-ff83-456c-bb6c-b69abc313209)

![image](https://github.com/TabbyML/tabby/assets/6077601/982762b3-b6a1-404b-a896-b725034e9762)

**Comment by wsxiaoys** [comment]
Have you tried `ls /nfs/tesla/CodeLlama-13b` command **inside** your container?

**Comment by linpan** [comment]
sorry, forgot it. -v .  i have anthoer issue: 
![CleanShot 2023-12-15 at 16 39 17](https://github.com/TabbyML/tabby/assets/6077601/9dc01322-1c89-423b-8cae-92915791121e)

**Comment by wsxiaoys** [comment]
As error message suggested - have you checked if the downloaded model exists and is correct?

**Comment by Crescentz** [comment]
> docker image: ![CleanShot 2023-12-15 at 11 12 25](https://private-user-images.githubusercontent.com/6077601/290714659-38ba1382-ff83-456c-bb6c-b69abc313209.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDkxOTUsIm5iZiI6MTcxNjcwODg5NSwicGF0aCI6Ii82MDc3NjAxLzI5MDcxNDY1OS0zOGJhMTM4Mi1mZjgzLTQ1NmMtYmI2Yy1iNjlhYmMzMTMyMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDczNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjdhMWQ0YWM4Nzg3MWE2MTUxNjYyNjk0NDhkMThmMTEyZDY4NTI0ODYwN2M2MmJkOWRlOTZhOGM5ZTI0ZjNhZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5FPWJZWp9mPFoXs-V3lia5FJXOT4h0QBiEr66YTw5kU)
> 
> ![image](https://private-user-images.githubusercontent.com/6077601/290714620-982762b3-b6a1-404b-a896-b725034e9762.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY3MDkxOTUsIm5iZiI6MTcxNjcwODg5NSwicGF0aCI6Ii82MDc3NjAxLzI5MDcxNDYyMC05ODI3NjJiMy1iNmExLTQwNGItYTg5Ni1iNzI1MDM0ZTk3NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjZUMDczNDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTkzMjNkYjI1M2ZlOGFhNGUyNjMwZGJlNTVhNTc1YzFiNDA3MGJmOTIwMDgwZDQ2N2U0ZTU3NGYwYmVjMTFhYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.h9d1bkWaAk1cQhzzuKKdVkAwbwWQSEtyz0hkIULfhMk)

how to reslove it , pls
