### ISSUE TITLE
Support of tess-coder based models?

### ISSUE THREAD

**Issue by jooray** [TabbyML/tabby#1063]
**Please describe the feature you want**

There is Tess-coder based on Mistral-7B.

Both the base model and the dataset for fine tune are open source.

https://huggingface.co/migtissera/Tess-Coder-7B-Mistral-v1.0
---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Hi! You might consider following the `How can I convert my own model for use with Tabby` in https://tabby.tabbyml.com/docs/faq/ to utilize this model
