### ISSUE TITLE
Free up VRAM if not in use

### ISSUE THREAD

**Issue by senscarlos** [TabbyML/tabby#1090]
Would be great to have the option to unload the model(s) from VRAM if tabby is not being used for some time.

To allow other things to run instead. For example during part of the day I use Tabby and during another time ollama for a chat interface. There's no place (or reason) to have them both loaded at the same time.

**Comment by wsxiaoys** [comment]
Related discussion and a solution in https://github.com/TabbyML/tabby/issues/624
