### ISSUE TITLE
Tabbyml docker image scheduler issue

### ISSUE THREAD

**Issue by akinlong** [TabbyML/tabby#1119]
**Describe the bug**
Issue occured when invoke tabby scheduler --now in docker image v0.7.0

**Information about your version**
Please provide output of `tabby --version`
![image](https://github.com/TabbyML/tabby/assets/11705474/c94685a9-c0df-4692-9222-b556e15ea7f5)

**Information about your GPU**
Please provide output of `nvidia-smi`
![image](https://github.com/TabbyML/tabby/assets/11705474/3a1bad70-dd99-49a1-9b14-3477976d8bbf)

**Additional context**
I am runing a docker based tabbyml, everything works fine. Once I am trying to follow https://tabby.tabbyml.com/docs/configuration/#repository-context-for-code-completion to use my own repository to enhance the repository level context for code completion, the error occurs, below is the error snapshot
![image](https://github.com/TabbyML/tabby/assets/11705474/ec911f9b-53e7-4296-8146-19af6ae6899b)

below is my configuration file location and the contents.
![image](https://github.com/TabbyML/tabby/assets/11705474/3fc15f58-8eb6-43e1-bba6-3292bed82bfc)

Any suggestions?

**Comment by wsxiaoys** [comment]
assuming you're using `tabbyml/tabby:0.7.0`.

Could you verify if `TABBO_ROOT` environment variable is set to `/data`? If so, the config.toml needs to be put at `/data/config.toml`

**Comment by akinlong** [comment]
> assuming you're using `tabbyml/tabby:0.7.0`.
> 
> Could you verify if `TABBO_ROOT` environment variable is set to `/data`? If so, the config.toml needs to be put at `/data/config.toml`

Cool! That works for me.

I think this should be updated on the wiki page, thanks a lot!
