### ISSUE TITLE
[TabbyML][EE][Playground] Chat completion result could not be shown at playground chat panel

### ISSUE THREAD

**Issue by hungle-i3** [TabbyML/tabby#1146]
**Describe the bug**
Chat completion result could not be shown at playground chat panel

**Information about your version**
[20131229 Docker nightly build ](https://hub.docker.com/layers/tabbyml/tabby/20231229/images/sha256-2e7b5502103e75d6c250772c2549d5e63abef894d87fa67600caa9371472975c?context=explore)

**Information about your GPU**
Please provide output of `nvidia-smi`
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0 Off |                  N/A |
|  0%   36C    P8              12W / 350W |  20196MiB / 24576MiB |      0%      Default |

**Additional context**
v1beta chat completion api return successfully but result could not be shown on the chat panel. 

<img width="1641" alt="Screen Shot 2023-12-30 at 16 18 53" src="https://github.com/TabbyML/tabby/assets/76546525/8a271e1f-3fcd-4f1d-8eb5-4d63ffebe632">

**Comment by wsxiaoys** [comment]
Thanks for reporting the issue - in https://github.com/TabbyML/tabby/pull/1094 and https://github.com/TabbyML/tabby/pull/1109 we've updated the implementation of `/v1beta/chat` to be openai compatible, but hasn't updated the embed tabby-ui implementation.

Sending out https://github.com/TabbyML/tabby/pull/1147 to fix the nightly build. in the mean time, consider use tag `0.7.0` from docker registry.
