### ISSUE TITLE
tabbyml vscode extension open-vsx.org share request

### ISSUE THREAD

**Issue by awslife** [TabbyML/tabby#116]
The Visual Studio Code Marketplace is not available where the OSS version of vscode is used due to licensing issues. As an alternative, open-vsx.org is heavily used. Please register the tabby extension with open-vsx.org as well.

**Comment by awslife** [comment]
I checked the tabbyml extension posted on open-vsx.org . Thank you for handling this ASAP.

**Comment by icycodes** [comment]
Published [vscode-tabby on open-vsx.org](https://open-vsx.org/extension/TabbyML/vscode-tabby) and [claimed namespace TabbyML](https://github.com/EclipseFdn/open-vsx.org/issues/1798). This issue can be closed as as completed.
