### ISSUE TITLE
Why cuda doen't work?

### ISSUE THREAD

**Issue by musica2016** [TabbyML/tabby#1163]
**Describe the bug**

**Information about your version**
```
**~/tabby$ target/debug/tabby --version
tabby 0.7.0**
```

**Information about your GPU**
`NVIDIA-SMI 545.23.08              Driver Version: 537.70       CUDA Version: 12.2     `

**Additional context**
```
target/debug/tabby  serve  --model TabbyML/StarCoder-1B --port 8181   --device cuda
error: invalid value 'cuda' for '--device <DEVICE>'
  [possible values: cpu]

  tip: a similar value exists: 'cpu'

For more information, try '--help'.
```
```
cat /etc/issue
Ubuntu 22.04.3 LTS \n \l
```

I run serve command in wsl

**Comment by wsxiaoys** [comment]
Hi - it seems that you're not building tabby with cuda feature.

You might refer the build command in docker https://github.com/TabbyML/tabby/blob/0977b78e6555a3faa7ec825046f461c15fd9315d/Dockerfile#L39

**Comment by musica2016** [comment]
> Hi - it seems that you're not building tabby with cuda feature.
> 
> You might refer the build command in docker
> 
> https://github.com/TabbyML/tabby/blob/0977b78e6555a3faa7ec825046f461c15fd9315d/Dockerfile#L39
Thx. I figure it out following your information.

**Comment by wwa132** [comment]
What could be causing the CUDA error 222 with unsupported toolchain? - https://slack.tabbyml.com/PR5GBBa1VOj
