### ISSUE TITLE
[TAB-443] Provide a way to deactivate a user

### ISSUE THREAD

**Issue by PeterTucker** [TabbyML/tabby#1171]
**Please describe the feature you want**
There is no way to  deactivate a user (member). I looked in Team Management and there are no options.

**Additional context**

![New Project](https://uploads.linear.app/36e8c471-0050-4ed1-a34b-9a4f22609cd1/78a3671d-b669-4877-88ae-1b7b9325e46f/48564dc3-04cb-4432-81e3-9dbcd7e6df91?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzM2ZThjNDcxLTAwNTAtNGVkMS1hMzRiLTlhNGYyMjYwOWNkMS83OGEzNjcxZC1iNjY5LTQ4NzctODhhZS0xYjdiOTMyNWU0NmYvNDg1NjRkYzMtMDRjYi00NDMyLTgxZTMtOWRiY2Q3ZTZkZjkxIiwiaWF0IjoxNzA1NTExODAxLCJleHAiOjE3MDU1OTgyMDF9.m5cUEcgDvDIeuuZkVl_eo_NoLBUEVgyb62Hgzz33C2c)

- [X] Backend support: @jmarcuse
- [ ] Frontend support: @jueliang

<sub>From [SyncLinear.com](https://synclinear.com) | [TAB-443](https://linear.app/tabbyml/issue/TAB-443/provide-a-way-to-deactivate-a-user)</sub>

**Comment by liangfung** [comment]
@jmarcuse `schema.graphql` has not been updated yet.
@wsxiaoys Woud it be possible to consider automating the execution within some hooks?

**Comment by wsxiaoys** [comment]
offline resolved
