### ISSUE TITLE
Adding installation guide for windows user, using binary distribution (instead of docker)

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#1179]
**Please describe the feature you want**

Many Windows Tabby users are not aware of our Windows distribution. It would be beneficial to have a Windows-specific installation tutorial on our website at https://tabby.tabbyml.com/docs/installation/.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Might also be a good chance to add tabby's windows distribution to choco

**Comment by awongCM** [comment]
> Might also be a good chance to add tabby's windows distribution to [choco](https://chocolatey.org/)

Yes. I can't wait to see that this gets through to choco. I've shown my colleagues at work today explaining the potential behind this.  They're hugely interested when compared to other big cloud AI-assisted tools like TabNine or Copilot, especially since we're all running in a windows environment.

**Comment by gregegg** [comment]
Count me in as "unaware of Windows".  Can you give me a breadcrumb to follow on the windows distribution?  What is the first step to installing on windows, without docker?

**Comment by wwayne** [comment]
Hey there, I sent a PR for the Windows installation https://github.com/TabbyML/tabby/pull/1640
Pls feel free to let me know if you got any questions

**Comment by awongCM** [comment]
> > Might also be a good chance to add tabby's windows distribution to [choco](https://chocolatey.org/)
> 
> Yes. I can't wait to see that this gets through to choco. I've shown my colleagues at work today explaining the potential behind this. They're hugely interested when compared to other big cloud AI-assisted tools like TabNine or Copilot, especially since we're all running in a windows environment.

Thanks for the update.  It's great news to hear that is now available for Windows to download.

In spite of this, I'm not able to run it locally on my company's laptop as I'm working at a financial institution.  They're known for being risk-averse when comes downloading a software does not meet the security assessment requirements where it's safe to use.  

Would you be able to help with this query?  What can I do to ensure the security team that TabbyML is safe to use and free from being hackable in order for them to grant an exemption?

Thanks.  I'll look forward to hearing your thoughts on it.
