### ISSUE TITLE
[TAB-444] Create an tutorial blog post on rocm support, using binary distribution or docker

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#1180]
**Please describe the feature you want**

Similar to https://tabby.tabbyml.com/blog/deploy-tabby-to-huggingface-space

---
Please reply with a 👍 if you want this feature.

<sub>[TAB-444](https://linear.app/tabbyml/issue/TAB-444/create-an-tutorial-blog-post-on-rocm-support-using-binary-distribution)</sub>

**Comment by boxbeam** [comment]
Link is dead

**Comment by boxbeam** [comment]
Found the working link: https://tabby.tabbyml.com/blog/deploy-tabby-to-huggingface-space.md
