### ISSUE TITLE
Webserver: `/repositories/{name}/meta/{path}` returns 404 while requesting a existing file

### ISSUE THREAD

**Issue by liangfung** [TabbyML/tabby#1182]
404 urls:
/repositories/https_github.com_TabbyML_tabby.git/meta/crates/tabby-scheduler/queries/go.scm
/repositories/https_github.com_TabbyML_tabby.git/meta/website/package.json
...

Except: Return meta info of file

**Comment by darknight** [comment]
@liangfung what does your `[[repositories]]` look like in `~/.tabby/config.toml`?

**Comment by jueliang0209** [comment]
> @liangfung what does your `[[repositories]]` look like in `~/.tabby/config.toml`?

@darknight 
[[repositories]]
git_url = "https://github.com/TabbyML/tabby.git"

[[repositories]]
git_url = "https://github.com/OpenNMT/CTranslate2.git"

**Comment by liangfung** [comment]
> @liangfung what does your `[[repositories]]` look like in `~/.tabby/config.toml`?

@darknight 
[[repositories]]
git_url = "https://github.com/TabbyML/tabby.git"

[[repositories]]
git_url = "https://github.com/OpenNMT/CTranslate2.git"

**Comment by wsxiaoys** [comment]
When meta is missing in files.json, but does exist locally, shall we return something for meta request?

**Comment by darknight** [comment]
> When meta is missing in files.json, but does exist locally, shall we return something for meta request?

One possible way is return some default response for existing file without meta info, something like:

```
{
	"git_url": "https://github.com/TabbyML/tabby.git",
	"filepath": "crates/tabby-scheduler/queries/go.scm",
	"language": "",
	"max_line_length": 0,
	"avg_line_length": 0.0,
	"alphanum_fraction": 0.0,
	"tags": []
}
```

**Comment by wsxiaoys** [comment]
@liangfung what would you suggest?

**Comment by darknight** [comment]
As discussed with @wsxiaoys , for the short term solution, we're gonna ignore files without meta info in dir resolve response.

Will make the patch soon.

cc: @liangfung

**Comment by liangfung** [comment]
@darknight If it's possible to resolve `language` field and return it?
