### ISSUE TITLE
code completion inoperative 

### ISSUE THREAD

**Issue by yangyongyongyong** [TabbyML/tabby#1195]
i install with mac:
```
brew install tabbyml/tabby/tabby

# Start server with StarCoder-1B
tabby serve --device metal --model TabbyML/StarCoder-1B
```

vi ~/.tabby/config.toml
```
[[repositories]]
name = "repository_b"
git_url = "file:///Users/thomas990p/DataGripProjects/tuya/tuyaluca/tmp"
```

/Users/thomas990p/DataGripProjects/tuya/tuyaluca/tmp/1.sql  :
```
create table tb1_u1_s1_m2(id int, name12 string, age33 int) comment 'APPOT表';
```

then i install tabby in jetbrainsidea and config local server .
![image](https://github.com/TabbyML/tabby/assets/46118358/0455245a-b63d-4dcd-b566-bbf17845e337)

and when i insert text in before line,it work:
![image](https://github.com/TabbyML/tabby/assets/46118358/3a007681-b2ff-4ba5-ad83-7e0c2679f469)

Repository context for code completion referred to https://tabby.tabbyml.com/docs/configuration:
```
vi ~/.tabby/config.toml 
sudo tabby scheduler --now
```

**Comment by yangyongyongyong** [comment]
By the way, can multiple people use the tabby plugin to link to the same tabby local server?

**Comment by yangyongyongyong** [comment]
(base) thomas990p@thomas990p bin % tabby  -V
tabby 0.7.0

**Comment by wsxiaoys** [comment]
SQL itself doesn't utilize repository context at the moment, filing https://github.com/TabbyML/tabby/issues/1195 to track

**Comment by wsxiaoys** [comment]
> By the way, can multiple people use the tabby plugin to link to the same tabby local server?

Yes, you might wanna utilize the team management feature introduced in 0.7.0: https://github.com/TabbyML/tabby/releases/tag/v0.7.0

**Comment by yangyongyongyong** [comment]
My original goal was to realize the auto-complete function of sql by storing the database schema in the configuration file.

**Comment by yangyongyongyong** [comment]
Consulting: What length of prefix in "segments": {"prefix": Can I place ddl into prefix to avoid the problem that file context is not currently supported?
