### ISSUE TITLE
Issues with Local Development Environment for IntelliJ Tabby Plugin

### ISSUE THREAD

**Issue by moqimoqidea** [TabbyML/tabby#1209]
Hello:

I've been working on testing the Tabby plugin for IntelliJ on my local machine. The plugin operates by utilizing the `tabby-agent` to enable its functionalities. I have a Grafana monitoring setup and I'm looking to modify the `tabby-agent` code. My goal is to send the context duration data to my Grafana instance whenever code completion is triggered in IntelliJ.

However, I encountered a problem: even without any changes in the main branch, running the `preupgrade-agent` and `upgrade-agent` scripts in the `package.json` of the IntelliJ plugin project, followed by executing `runIde` with Gradle, results in an inability to connect to the server. This issue also seems to affect the functioning of the packaged IntelliJ plugin, preventing me from adding new features to both `tabby-agent` and the IntelliJ plugin.

I'm seeking advice on how to resolve this issue. Any help or suggestions would be greatly appreciated.

Thank you!

**Comment by wsxiaoys** [comment]
Hey - would you consider sending data to grafana by integrating it with events data under `/events`? It should contains all the context we used for code completion

**Comment by moqimoqidea** [comment]
Yes, I'm looking to extend the Grafana monitoring to track the current client's runtime status, particularly response times, by inheriting from `/events`. The current codebase includes statistics for anonymous usage information, which, when enabled, sends data to `/events`. Could we modify this to allow sending the relevant `/events` data to a list of URLs?

In such a scenario, if a user has configured additional URLs and the necessary authentication, this could facilitate the integration of monitoring capabilities. Ideally, this would be the foundation for integrating various types of telemetry, such as Traces, Metrics, Logs, potentially utilizing tools like Grafana, Prometheus, or OpenTelemetry.

**Comment by wsxiaoys** [comment]
to clarify, I was referring the events data under `~/.tabby/events`. It should contains sufficient enough informations to compute stuff like anonymous usage, response time, etc

**Comment by moqimoqidea** [comment]
oh, i saw jsons file on  ~/.tabby/events, thank you.
