### ISSUE TITLE
Securing access to both the admin panel and the server

### ISSUE THREAD

**Issue by thibautrey** [TabbyML/tabby#121]
**Please describe the feature you want**

How would one achieve securing the admin panel as well as the server. How would we be able to setup the vscode extension to provide such authentication?

**Comment by wsxiaoys** [comment]
The same feature request has been raised in our internal discussions.

Currently, we are confident that we will provide minimum secure access to the admin panel.

**Comment by vasja1996** [comment]
> **Please describe the feature you want**
> 
> How would one achieve securing the admin panel as well as the server. How would we be able to setup the vscode extension to provide such authentication?

good
