### ISSUE TITLE
Missing completion when infilling Jupyter Notebooks

### ISSUE THREAD

**Issue by Exaphis** [TabbyML/tabby#1221]
**Describe the bug**
When triggering completions at the end of a cell in the middle of a Jupyter Notebook in VS Code, no completions show up even though a valid result is generated by the Tabby server.

For example, given a notebook with two cells:
```
def fib(n):
< CURSOR HERE
```

```
# print hello world
print("Hello World")
```

Manually triggering Tabby gives me no completion result. Logging the prompt/generated result in the server gives me this, which shows me a valid completion result was generated:
```
PREFIX: def fib(n):
 , SUFFIX: Some("# print hello world\nprint(\"Hello World\")\n\n")
PROMPT: <fim_prefix>def fib(n):
 <fim_suffix># print hello world
print("Hello World")

<fim_middle>
GENERATED:    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)
```

This does not happen in a normal file (tested with the below contents):
```
def fib(n):
< CURSOR HERE
# print hello world
print("Hello World")
```

Triggering completion here gives me the following ghost text:
```
    if n <= 1:
        return n
    else:
        return fib(n-1) + fib(n-2)
```

Looks like there is a missing newline at the start of the suffix - could this cause the agent to prevent the result from being shown?

**Information about your version**
tabby 0.7.0

**Information about your GPU**
Apple M1 (Metal)

**Additional context**
Run with `cargo run serve --model TabbyML/StarCoder-1B --device metal`

**Comment by icycodes** [comment]
Hi @Exaphis,

Thank you for reporting this issue and providing detailed debugging logs.   
Your idea is correct. The bug is caused by the missing newline at the start of the suffix.
