### ISSUE TITLE
replit model converter for ctranslate2 backend

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#123]
Related: https://huggingface.co/replit/replit-code-v1-3b

Looking at https://huggingface.co/replit/replit-code-v1-3b/blob/main/replit_lm.py, it seems to be a standard GPT model adapted from https://github.com/mosaicml/examples/blob/52cd4fef69497f225a034fcd10692f8613732d10/examples/llm/src/models/mosaic_gpt/mosaic_gpt.py

**Comment by LoopControl** [comment]
:+1:  Would love to see support for replit 1.3B
