### ISSUE TITLE
Tabby initialization failed in neovim

### ISSUE THREAD

**Issue by neva-ops** [TabbyML/tabby#1231]
**Describe the bug**
I can't use Tabby in neovim.
When type ':Tabby' I get error:
```
Tabby initialization failed.                                                                                                            
Tabby agent script not found. Please reinstall Tabby plugin. 
```

**Information about your version**
Tabby server run in docker.
Version 0.7.0.

**Information about your GPU**
I don't use GPU.

**Additional context**
Node version v18.19.0
In init.vim I set path for node.
`let g:tabby_node_binary = '/usr/bin/node'`

**Comment by jbigler** [comment]
That error sounds like it's unable to find the tabby-agent.js file. 
Do you use a package manager?
I use lazy and it is located at: `~/.local/share/nvim/lazy/vim-tabby/node_scripts/tabby-agent.js`

**Comment by neva-ops** [comment]
I use vim-plug.
tabby-agent.js located at `.local/share/nvim/plugged/vim-tabby/node_scripts/tabby-agent.js`.

**Comment by jbigler** [comment]
I just tested a clean config of Neovim 0.9.2 and node 18.18.2.
I only installed vim-plug and the tabby-vim plugin.
My .config/nvim/init.vim looks like this:
```
filetype plugin on

call plug#begin()
	" Tabby plugin
	Plug 'TabbyML/vim-tabby'
	" Add config here. Example config:
	let g:tabby_keybinding_accept = '<Tab>'

call plug#end()
```
And everything works fine.
You may want to try making a backup of your nvim config and trying from a clean start.

**Comment by neva-ops** [comment]
Problem in string `let g:tabby_node_script = expand('<script>:h:h:h') . '/node_scripts/tabby-agent.js'` in vim-tabby/autoload/tabby/globals.vim.
When I set absolute path in init.vim for tabby_node_script in init.vim and comment out string in globals.vim tabby start to work.
Most likely the problem is in the expand function.
