### ISSUE TITLE
Can't find `node_scripts/tabby-agent.js` unobfuscated source code

### ISSUE THREAD

**Issue by iyesin** [TabbyML/tabby#1237]
**Describe the bug**
I can't find human-readable unobfuscated source code of `node_scripts/tabby-agent.js` file. 

**Information about your version**
tabby 0.7.0

**Information about your GPU**
none

**Additional context**
I want to audit the code I starting on my computer and want to read unobfuscated code.
Same applies to WASM code as well.

**Comment by wsxiaoys** [comment]
They're locates at https://github.com/TabbyML/tabby/tree/main/clients/tabby-agent

cc @icycodes maybe good to add some document line at top of the generated bundle file?
