### ISSUE TITLE
[TAB-450] implement auto reloading for meta in `/repositories`

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#1245]
**Please describe the feature you want**

Records as todo here: [https://github.com/TabbyML/tabby/blob/647abdc5d594f41a9bf0be2c7730c31dae4162b6/ee/tabby-webserver/src/repositories/resolve.rs#L105](https://github.com/TabbyML/tabby/blob/647abdc5d594f41a9bf0be2c7730c31dae4162b6/ee/tabby-webserver/src/repositories/resolve.rs#L105)

**Additional context**
I would imagine reloading could happens automatically when we detect a file mtime changes when requesting metadata.

---

Please reply with a 👍 if you want this feature.

<sub>From [SyncLinear.com](https://synclinear.com) | [TAB-450](https://linear.app/tabbyml/issue/TAB-450/[tab-450]-implement-auto-reloading-logic-for-meta-info)</sub>

**Comment by boxbeam** [comment]
My current idea for this is to expose some kind of API in the scheduler that allows registering callbacks to be run before/after certain jobs. Then we could use a callback to update the repository metadata after the scheduled job runs. Do we want a design like that, or just polling?

**Comment by wsxiaoys** [comment]
I would say just time based polling is good. But do take this opportunity to refactor `META` out into some struct / class to manage lifecycle proper (and testable)
