### ISSUE TITLE
Failed to start DAG: exit status 1/runner: entry failed analytic: exit status 1

### ISSUE THREAD

**Issue by JasonFeng02** [TabbyML/tabby#125]
**Describe the bug**
running tabby server but client cant output anything generate

**Information about your GPU**
![image](https://github.com/TabbyML/tabby/assets/92613744/748d9ac2-4640-4608-8012-758f03245314)

**Additional context**
2023-05-09 12:27:00,172 DEBG 'dagu_scheduler' stdout output:
2023/05/09 12:27:00 Failed to start DAG: exit status 1

2023-05-09 12:27:00,172 DEBG 'dagu_scheduler' stdout output:
2023/05/09 12:27:00 runner: entry failed analytic: exit status 1

2023-05-09 12:30:00,059 DEBG 'dagu_scheduler' stdout output:
2023/05/09 12:30:00 [2023-05-09 12:30:00] start analytic

2023-05-09 12:30:00,063 DEBG 'dagu_scheduler' stdout output:
2023/05/09 12:30:00 server is running at "/tmp/@dagu-analytic-af09eed2a725067a7f323f1fc0f93c29.sock"

2023-05-09 12:30:00,063 DEBG 'dagu_scheduler' stdout output:
2023/05/09 12:30:00 start running: Collect Tabby

2023-05-09 12:30:00,137 DEBG 'dagu_scheduler' stdout output:
2023/05/09 12:30:00 Collect Tabby failed

2023-05-09 12:30:00,164 DEBG 'dagu_scheduler' stdout output:
2023/05/09 12:30:00 schedule finished.

2023-05-09 12:30:00,168 DEBG 'dagu_scheduler' stdout output:
![image](https://github.com/TabbyML/tabby/assets/92613744/65b4fdb6-c988-46ff-9d70-1ae8852ba4a0)

**Comment by JasonFeng02** [comment]
i deploy tabby on an independent linux server with nvidia GPUs ,which IP on 192.168.1.225,http://192.168.1.225:5000 could be able to access

![image](https://github.com/TabbyML/tabby/assets/92613744/d010d82c-f84d-4466-a111-cc2938ee6adc)
![image](https://github.com/TabbyML/tabby/assets/92613744/9e82bd25-428f-4a62-8d7a-77521cf9d337)

**Comment by JasonFeng02** [comment]
> i deploy tabby on an independent linux server with nvidia GPUs ,which IP on 192.168.1.225,http://192.168.1.225:5000 could be able to access
> 
> ![image](https://user-images.githubusercontent.com/92613744/237577361-d010d82c-f84d-4466-a111-cc2938ee6adc.png) ![image](https://user-images.githubusercontent.com/92613744/237577382-9e82bd25-428f-4a62-8d7a-77521cf9d337.png)

**Comment by JasonFeng02** [comment]
The tabbyserver's openapi page could be seen at http:192.168.1.225:5000 as well

**Comment by JasonFeng02** [comment]
obviously not,extension on vsc output nothing and no vram been allocated by tabby

**Comment by wsxiaoys** [comment]
Could you provide more information, e.g screenshot of admin page (http://localhost:5000/_admin) ?

**Comment by JasonFeng02** [comment]
![image](https://github.com/TabbyML/tabby/assets/92613744/deb6f6ab-89ed-4b16-88b8-731588299912)

**Comment by JasonFeng02** [comment]
![image](https://github.com/TabbyML/tabby/assets/92613744/dca55f35-88ef-4ee6-b477-465227a17c0d)

**Comment by wsxiaoys** [comment]
Thanks for the information.

It appears that you are using a Maxwell GPU (GTX Titan X), while Tabby currently only supports Pascal or newer GPUs. As a result, the Triton job failed to launch.

**Comment by JasonFeng02** [comment]
thanks :) maybe I should change another GPU to deploy ,thanks for your assist
