### ISSUE TITLE
error: creating server: Internal - failed to load all models

### ISSUE THREAD

**Issue by aphrodite1028** [TabbyML/tabby#126]
according https://github.com/TabbyML/tabby#get-started-server to start a docker container not running

Nvidia GPU is Tesla P40 GPU Driver is 470.57.02

**Comment by aphrodite1028** [comment]
mpirun -n 1 /opt/tritonserver/bin/tritonserver always crash

**Comment by wsxiaoys** [comment]
could you share the detailed output / screenshot?
