### ISSUE TITLE
[TAB-461] Refactor database code to use sqlx instead of rusqlite

### ISSUE THREAD

**Issue by boxbeam** [TabbyML/tabby#1272]
Switch all database code to use sqlx instead of rusqlite.

- [X] Create full db schema matching current spec using sqlx commands (`cargo sqlx`)
- [X] Remove rusqlite dependency and add sqlx dependency
- [X] Migrate all code and tests to use sqlx instead
- [X] Ensure migration path for users upgrading to the sqlx version
- [ ] Split Prod / Dev environment for tabby webserver

Reference: [https://github.com/TabbyML/tabby/pull/1207](https://github.com/TabbyML/tabby/pull/1207)

<sub>From [SyncLinear.com](https://synclinear.com) | [TAB-461](https://linear.app/tabbyml/issue/TAB-461/refactor-database-code-to-use-sqlx-instead-of-rusqlite)</sub>

**Comment by wsxiaoys** [comment]
@jmarcuse prod / dev environment split is still not done

**Comment by boxbeam** [comment]
@wsxiaoys Could you please provide more specific details about what you want implemented? I'm not clear on it from just that description.
