### ISSUE TITLE
The data type of the `extensions` field in the response of GraphQL.

### ISSUE THREAD

**Issue by liangfung** [TabbyML/tabby#1275]
Returning `extensions` field as a structured map may be more reasonable.

<img width="1305" alt="image" src="https://github.com/TabbyML/tabby/assets/17516233/36df8359-d65b-41dc-b638-7b10d7b1d33f">

**Comment by liangfung** [comment]
@wsxiaoys

**Comment by wsxiaoys** [comment]
This is caused by https://github.com/TabbyML/tabby/blob/f0c2de90cadca3b0d0e9595002905d9e164723df/ee/tabby-webserver/src/schema/mod.rs#L74

Hi @boxbeam, could you take this fix?

**Comment by boxbeam** [comment]
Not quite sure what is wanted here - do we want a map like `{"reason": "Unauthorized"}`?

**Comment by wsxiaoys** [comment]
Let's follow the practice here by returning a standard code (`UNAUTHORIZED`)

https://www.apollographql.com/docs/apollo-server/data/errors/#custom-errors
