### ISSUE TITLE
tabby-schedule reports "Cannot read error"

### ISSUE THREAD

**Issue by rzuckerm** [TabbyML/tabby#1287]
**Describe the bug**
For `tabby-scheduler --now`, I'm seeing numerous errors like this:
```
2024-01-23T22:19:33.475990Z ERROR tabby_scheduler::dataset: crates/tabby-scheduler/src/dataset.rs:65: Cannot read <some-relative-path>
```

where: `<some-relative-path>` is the path to some file that is known to contain valid source code (like C, C++, etc.)

**Information about your version**
Please provide output of `tabby --version`
`tabby 0.7.0`

**Information about your GPU**
Please provide output of `nvidia-smi`
```
Wed Jan 24 15:15:01 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        On  | 00000000:01:00.0 Off |                  Off |
|  0%   39C    P8              25W / 450W |  17208MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+
```

**Additional context**
I have cloned numerous GitHub repositories from our internal GitHub enterprise server to a local directories for each organization and repository that I want to index with Tabby. I've removed as many non-code files (audio, video, compressed archives, Microsoft Office files, binary files etc.) as I could. Each repository is stored in its own directory in the form of `/data/github/<org>/<repo>`. My configuration file is a collection of entries like this:
```
[[repositories]]
name = "<org>/<repo>"
git_url = "file:///data/github/<base-path>/<org>/<repo>"
```

Since the error message does not indicate what the problem is, and it does not give the full path, I have no idea why the file is causing problems. It would be nice if those details were provided.

**Comment by rzuckerm** [comment]
I'm also wondering if I really need to list all the repositories in the `config.toml` file. Would it be better to just do something like this?
```
[[repositories]]
name = "github"
git_url = "file:///data/github"
```

**Comment by boxbeam** [comment]
I've created a PR relating to this issue to get more info when the file operation fails. Would you be able to clone the repository and run using these commands:

```
git checkout 1287-more-error-info
cargo run --release -- <your flags here>
```

This should provide more info about why the file could not be opened, which should help us resolve this.

**Comment by rzuckerm** [comment]
Thanks @boxbeam . I did some experimentation on the files that the scheduler was complaining about, and it turned out that the files had non-UTF-8 characters in them. I'm modifying my script to remove all files like this.

**Comment by boxbeam** [comment]
That's good information, thank you!

**Comment by boxbeam** [comment]
Leaving this open, I will fix the compatibility with non utf8 characters
