### ISSUE TITLE
How can I enable other users to use the playground?

### ISSUE THREAD

**Issue by ai2ys** [TabbyML/tabby#1305]
Hi,
I upgraded to TabbyML version 0.7.0.
Earlier it was possible to access the playground just using the link. Now there is a login. I created an admin user on my first login.
But how can I enable other to be able to use it? I added their email addresses in "Team Mangement" but no mail client is configured, so probably no email will be send. 
What has to get setup, so be able to invite team members? Where can information be found on this topic?

**Comment by wsxiaoys** [comment]
You can copy the invitation link and share it with your team members. They will be able to register using the invitation link.

Recording: https://jam.dev/c/a62c7305-48b3-4baa-8222-872b128ba336

**Comment by ai2ys** [comment]
> You can copy the invitation link and share it with your team members. They will be able to register using the invitation link.
> 
> Recording: https://jam.dev/c/a62c7305-48b3-4baa-8222-872b128ba336

Thank you for the information.
Is there any written documentation available on this?

**Comment by wsxiaoys** [comment]
We have not yet begun to document these enterprise features, such as user management. However, these tasks need to be completed before the 1.0 release.
