### ISSUE TITLE
PyCharm Tabby: Authorization required, please set your personal token in settings

### ISSUE THREAD

**Issue by maxavd85** [TabbyML/tabby#1313]
**Describe the bug**
This had never happened before and suddenly it appeared. I tried to find the token but it didn't work. I went to the address 0.0.0.0:8080 and there was also nowhere to write a token.

**Information about your version**
Please provide output of `tabby --version` pycharm tabby version 1.2.0

**Information about your GPU**
Please provide output of `nvidia-smi` nvidia 3080 

**Additional context**

**Comment by wsxiaoys** [comment]
Hi, could you follow the instruction and provide the output of `tabby --version`?

**Comment by maxavd85** [comment]
> Hi, could you follow the instruction and provide the output of `tabby --version`?

In the terminal it says

:~$ tabby --version
Command "tabby" not found. Did you mean:
   command 'ktabby' from deb kgames (2.2-1)
Try: sudo apt install <deb name>

Or where should I write this?

**Comment by wsxiaoys** [comment]
Could you share the command you used to start tabby?

**Comment by maxavd85** [comment]
> Could you share the command you used to start tabby?

I don’t know, it somehow starts in my PyCharm. I also run Docker.

2024-01-27T07:07:21.912587Z  INFO tabby_download: crates/tabby-download/src/lib.rs:66: Start downloading model `TabbyML/CodeLlama-7B`
2024-01-27T07:07:21.914491157Z 2024-01-27T07:07:21.914357Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:129: Starting server, this might takes a few minutes...
2024-01-27T07:08:10.662763837Z 2024-01-27T07:08:10.662452Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:136: Listening at 0.0.0.0:8080

**Comment by maxavd85** [comment]
This is in the docker terminal

root@52b707c363a8:/# tabby --version
bash: tabby: command not found
root@52b707c363a8:/#

**Comment by maxavd85** [comment]
In PyCharm, I have a services tab, there is docker, and several models are installed there, and I launch them when I turn on PyCharm.

**Comment by maxavd85** [comment]
Or is it the model? Do I need to remove it and download Docker again?

**Comment by maxavd85** [comment]
I downloaded a new version of Docker, but it didn't help.

Adding the config.toml file to .tabby/agent did not help.

I added a token to both config.toml and the same token in PyCharm did not help.

**Comment by wsxiaoys** [comment]
>> Could you share the command you used to start tabby?

> I don’t know, it somehow starts in my PyCharm. I also run Docker.

I'm referring to the Tabby server, which in this case is likely being started by Docker. Could you share the command you use to start the Tabby Docker container?

**Comment by maxavd85** [comment]
> > > Could you share the command you used to start tabby?
> 
> > I don’t know, it somehow starts in my PyCharm. I also run Docker.
> 
> I'm referring to the Tabby server, which in this case is likely being started by Docker. Could you share the command you use to start the Tabby Docker container?

I just press play.

![tabby_start](https://github.com/TabbyML/tabby/assets/45529614/f6fb3cb9-4a8c-4fa4-b8b5-577e2a133e9c)

**Comment by maxavd85** [comment]
Now I’ve deleted everything again and downloaded it again.

Here is the command from the site, I only added the container name

docker run --name CodeLlama-13B -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/CodeLlama-13B --device cuda

**Comment by maxavd85** [comment]
Now I tried to start the container with the server with the command

docker start container_id

The same thing, it asks to enter a personal token, although I entered it both in the config and in PyCharm. Still doesn't work.

**Comment by maxavd85** [comment]
By the way, I noticed when you switch to

http://0.0.0.0:8080/swagger-ui/

There are two servers there, and I tried to go to https://playground.app.tabbyml.com/ and I get a json response

{
"error": "Unauthorized"
}

Maybe he's trying to get at him? Is there any way to remove it? I tried to select localhost:8080 from the list but something does not switch.

![tabby_servers_1](https://github.com/TabbyML/tabby/assets/45529614/09ab9510-3f42-416c-b9ae-43788c143aa5)

![tabby_servers_2](https://github.com/TabbyML/tabby/assets/45529614/6c2b082a-6fc8-4a41-9656-0611d8d7ded8)

**Comment by wsxiaoys** [comment]
you're running at a (very) stale version of tabby - consider upgrading to latest release (`tabbyml/tabby:0.7.0`), or the 0.8 rc (`tabbym/tabby:0.8.0-rc.0`)

**Comment by icycodes** [comment]
It looks like the same issue with #1159. 
I drafted a PR to make clients compatible with server versions that only support POST `/v1/health`. #1267

**Comment by maxavd85** [comment]
> you're running at a (very) stale version of tabby - consider upgrading to latest release (`tabbyml/tabby:0.7.0`), or the 0.8 rc (`tabbym/tabby:0.8.0-rc.0`)

Please tell me how to update? In PyCharm this is the latest version of the plugin and it seems to be 1.2.0.

**Comment by maxavd85** [comment]
I am using this command to install the server

docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda

But there is no choice of server version.

**Comment by icycodes** [comment]
> I am using this command to install the server
> 
> docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda
> 
> But there is no choice of server version.
> 
> I have Linux Mint and I understand that this command will not work for me
> 
> brew install tabbyml/tabby/tabby
> 
> This command doesn't work either.
> 
> sudo apt install tabby

You can run 
```
docker pull tabbyml/tabby
```
to update the tabby server docker image.

**Comment by maxavd85** [comment]
> > I am using this command to install the server
> > docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda
> > But there is no choice of server version.
> > I have Linux Mint and I understand that this command will not work for me
> > brew install tabbyml/tabby/tabby
> > This command doesn't work either.
> > sudo apt install tabby
> 
> You can run
> 
> ```
> docker pull tabbyml/tabby
> ```
> 
> to update the tabby server docker image.

Thank you! And then just run this container and everything will work?

**Comment by maxavd85** [comment]
> You can run
> 
> ```
> docker pull tabbyml/tabby
> ```
> 
> to update the tabby server docker image.

I created a container, but it doesn’t start, and the last one started and still says that authentication is required.

**Comment by icycodes** [comment]
> > You can run
> > ```
> > docker pull tabbyml/tabby
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > to update the tabby server docker image.
> 
> I created a container, but it doesn’t start, and the last one started and still says that authentication is required.
> 
> For some reason it didn’t help, or I’m doing something wrong.
> 
> Please excuse me, I don’t understand what to do. Please tell me. This container won't start. ![tabby_new_server](https://private-user-images.githubusercontent.com/45529614/300324464-e0343938-0f07-4435-9f32-e870ffee6b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTkxOTIsIm5iZiI6MTcwNjQ5ODg5MiwicGF0aCI6Ii80NTUyOTYxNC8zMDAzMjQ0NjQtZTAzNDM5MzgtMGYwNy00NDM1LTlmMzItZTg3MGZmZWU2YjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YzlhOTNmYmJjOWQ0Yjk0Mjg3ZTBjMmNjYmJkNzYwZDRjNTkxYzQyMWY5MGJmYmY4YTNkZjkyNmVmN2FlNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J7F2T_s9teeOqR0ZR32vD6steznKJD9wHHT0iq-fXR0)

Once the new docker image is successfully pulled, you can proceed to restart the Tabby server using the same command you have used before. 
```
docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda
```
This command will create a container running the Tabby server.

**Comment by maxavd85** [comment]
> > > You can run
> > > ```
> > > docker pull tabbyml/tabby
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > to update the tabby server docker image.
> > 
> > 
> > I created a container, but it doesn’t start, and the last one started and still says that authentication is required.
> > For some reason it didn’t help, or I’m doing something wrong.
> > Please excuse me, I don’t understand what to do. Please tell me. This container won't start. ![tabby_new_server](https://private-user-images.githubusercontent.com/45529614/300324464-e0343938-0f07-4435-9f32-e870ffee6b8f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0OTkxOTIsIm5iZiI6MTcwNjQ5ODg5MiwicGF0aCI6Ii80NTUyOTYxNC8zMDAzMjQ0NjQtZTAzNDM5MzgtMGYwNy00NDM1LTlmMzItZTg3MGZmZWU2YjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAzMjgxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YzlhOTNmYmJjOWQ0Yjk0Mjg3ZTBjMmNjYmJkNzYwZDRjNTkxYzQyMWY5MGJmYmY4YTNkZjkyNmVmN2FlNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J7F2T_s9teeOqR0ZR32vD6steznKJD9wHHT0iq-fXR0)
> 
> Once the new docker image is successfully pulled, you can proceed to restart the Tabby server using the same command you have used before.
> 
> ```
> docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda
> ```
> 
> This command will create a container running the Tabby server.

Thank you very much! The server has been updated, but still requires authentication. Although there is a token in the configs everywhere. I'll try to comment out the lines.

**Comment by maxavd85** [comment]
Thank you very much again! Finally it worked!))) I commented out the tokens in the configs and deleted them in the IDE and finally it worked!
