### ISSUE TITLE
Official image unraid docker no-start

### ISSUE THREAD

**Issue by alex12342** [TabbyML/tabby#1314]
**Describe the bug**

Installed via unraid app plugin. Upon starting I get the error:

thread 'main' panicked at crates/tabby-common/src/registry.rs:80:32:
Invalid model_id <TabbyML/SantaCoder-1B>

**Information about your version**

Can't Start to find out

**Information about your GPU**

CPU only setup

**Additional context**

none

**Comment by wsxiaoys** [comment]
Hi, SantaCoder-1B is no longer a supported model in official registry. checkout https://github.com/TabbyML/registry-tabby for a complete list of supported models
