### ISSUE TITLE
Need to deploy segmented GGUF files on the server.

### ISSUE THREAD

**Issue by moqimoqidea** [TabbyML/tabby#1318]
**Please describe the feature you want:**

I am currently facing a challenge in deploying a large model, specifically a 67GB model, on a Tabby server. The issue arises due to Hugging Face's limitation of 50GB per single file. As a result, the model's GGUF file had to be split into two separate files. 

I'm uncertain about the correct procedure to declare this in the `models.json` file of `regstry-tabby`. While I understand that the `urls` field can accommodate multiple URLs, it's unclear if these URLs are intended to be used as alternate addresses or can be used to reference parts of a split file. 

The main question is: For a model split into multiple parts, how should these parts be listed in the `models.json`? Should they be comma-separated within a single URL entry, and does Tabby support any automated concatenation (`cat`) and removal (`remove`) operations for such cases?

This clarification will be highly beneficial for deploying large models efficiently.

**Additional context:**

Here are the relevant links for more context:
- Model to be deployed: [Hugging Face - openbuddy-deepseek-67b-v15-base-GGUF](https://huggingface.co/TheBloke/openbuddy-deepseek-67b-v15-base-GGUF)
- Files are split and require joining: [Hugging Face - File Merging Query](https://huggingface.co/TheBloke/openbuddy-deepseek-67b-v15-base-GGUF#q6_k-and-q8_0-files-are-split-and-require-joining)

---

Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
A partitioned url list could be added to `ModelInfo` for supporting such use cases:

https://github.com/TabbyML/tabby/blob/639960606c65adee4ea0868ce8403a5ec340664b/crates/tabby-common/src/registry.rs#L15

Happy to review the PR if anyone interested in contributing

**Comment by wsxiaoys** [comment]
@boxbeam would you like to take this as part of `tabby model` refactoring?

**Comment by boxbeam** [comment]
> @boxbeam would you like to take this as part of `tabby model` refactoring?

This sounds like it would be a better target for a new `registry` subcommand which allows you to edit the registry. I need to clarify that for myself, how about we discuss it tomorrow and make it into a new task?

**Comment by moqimoqidea** [comment]
> @moqimoqidea Please provide the links for a segmented model so I can test this - I don't see where to actually download the `-split-a` and `-split-b` model files from the huggingface page.

**Additional context:**

Here are the relevant links for more context:
- Model to be deployed: [Hugging Face - openbuddy-deepseek-67b-v15-base-GGUF](https://huggingface.co/TheBloke/openbuddy-deepseek-67b-v15-base-GGUF)
- Files are split and require joining: [Hugging Face - File Merging Query](https://huggingface.co/TheBloke/openbuddy-deepseek-67b-v15-base-GGUF#q6_k-and-q8_0-files-are-split-and-require-joining)

detail:

Q6_K and Q8_0 files are split and require joining
Note: HF does not support uploading files larger than 50GB. Therefore I have uploaded the Q6_K and Q8_0 files as split files.

Click for instructions regarding Q6_K and Q8_0 files
q6_K
Please download:

openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-a
openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-b
q8_0
Please download:

openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-a
openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-b
To join the files, do the following:

Linux and macOS:

```sh
cat openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-* > openbuddy-deepseek-67b-v15-base.Q6_K.gguf && rm openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-*
cat openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-* > openbuddy-deepseek-67b-v15-base.Q8_0.gguf && rm openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-*
```

Windows command line:

```sh
COPY /B openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-a + openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-b openbuddy-deepseek-67b-v15-base.Q6_K.gguf
del openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-a openbuddy-deepseek-67b-v15-base.Q6_K.gguf-split-b

COPY /B openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-a + openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-b openbuddy-deepseek-67b-v15-base.Q8_0.gguf
del openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-a openbuddy-deepseek-67b-v15-base.Q8_0.gguf-split-b

```
