### ISSUE TITLE
[TAB-465] add `total_count` for RelayConnection

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#1323]
[https://github.com/TabbyML/tabby/blob/f6c61651c8992dfd7f1b088d4c3a04dc6dca619e/crates/juniper-axum/src/relay/connection.rs#L14](https://github.com/TabbyML/tabby/blob/f6c61651c8992dfd7f1b088d4c3a04dc6dca619e/crates/juniper-axum/src/relay/connection.rs#L14)

cc @liangfung 

ref: [https://graphql.org/learn/pagination/](https://graphql.org/learn/pagination/)

<sub>From [SyncLinear.com](https://synclinear.com) | [TAB-465](https://linear.app/tabbyml/issue/TAB-465/add-total-count-for-relayconnection)</sub>

**Comment by wsxiaoys** [comment]
this will make @liangfung's refactor with [TAB-439](https://linear.app/tabbyml/issue/TAB-439/provide-abstraction-of-pagination-in-webserver-graphql-api)  easier

**Comment by boxbeam** [comment]
https://tabbymlcom.larksuite.com/docx/EvCed4cbeoNKGSxL0BEuAQUgsKh

**Comment by wsxiaoys** [comment]
lowered the priority as this no longer block 439
