### ISSUE TITLE
Cannot find the exact evaluation results from the original paper

### ISSUE THREAD

**Issue by zhimin-z** [TabbyML/tabby#1369]
Upon examining the third leaderboard at https://leaderboard.tabbyml.com, I noticed discrepancies between the results displayed and those reported in [CrossCodeEval](https://arxiv.org/abs/2310.11248). However, the leaderboard explicitly states that the numbers in this section are derived from [CrossCodeEval](https://crosscodeeval.github.io). Could you clarify why there is a mismatch between the leaderboard results and the findings presented in the original research?
![image](https://github.com/TabbyML/tabby/assets/8592144/764f14c5-1693-40cd-afbc-d645725c93db)
![image](https://github.com/TabbyML/tabby/assets/8592144/08ba443c-d7e7-415f-b4f6-6ba96cab4732)

**Comment by wsxiaoys** [comment]
it is averaging across 4 programming languages

![9e65c0822a59c71d37281e880038c084](https://github.com/TabbyML/tabby/assets/388154/9a4bd5bb-de97-454b-aeb8-7ddb53deec5c)

**Comment by zhimin-z** [comment]
> it is averaging across 4 programming languages
> 
> ![9e65c0822a59c71d37281e880038c084](https://private-user-images.githubusercontent.com/388154/302057114-9a4bd5bb-de97-454b-aeb8-7ddb53deec5c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY5ODg5MDcsIm5iZiI6MTcwNjk4ODYwNywicGF0aCI6Ii8zODgxNTQvMzAyMDU3MTE0LTlhNGJkNWJiLWRlOTctNDU0Yi1hZWI4LTdkZGI1M2RlZWM1Yy5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDNUMTkzMDA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTZiMTc3ZjZiMjExYTU5ODkwM2VlM2IyMDBmMzViODc1MTRiOWQ1Zjg3ZDhmODRlMmU1NThjMDJhNWJhNDgwMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.d0FA8L8BrUhNkG8T63E-3y_wCz4PbcXxebqrEt7-NNk)

Thank you for your feedback. However, I believe explicitly specifying these details will enhance clarity and understanding.

**Comment by wsxiaoys** [comment]
Thanks for the feedback! Will considering update it a bit.
