### ISSUE TITLE
Add DeepseekCoder-33B (instruct or base from TheBloke in GGUF Q4_K_M)

### ISSUE THREAD

**Issue by pervrosen** [TabbyML/tabby#1398]
I want DeepseekCoder-33B enabled. Either "base" or "instruct"-model. Example model given below. 

I guess you need to: 
1) add this model to https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json + calculate sha256sum on the gguf file.
2) remove the hard coded link in the registry.rs (pub static GGML_MODEL_RELATIVE_PATH: &str = "ggml/q8_0.v2.gguf";) or rename file to this. Please use a "better" quantized file eg q4_K_M.gguf and not q8.

Example targets are:
https://huggingface.co/TheBloke/deepseek-coder-33B-instruct-GGUF/blob/main/deepseek-coder-33b-instruct.Q4_K_M.gguf
https://huggingface.co/TheBloke/deepseek-coder-33B-base-GGUF/blob/main/deepseek-coder-33b-base.Q4_K_M.gguf

OR remove the code dependency to https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json so people can point directly towards a gguf file - local or remote. (Then we can drop the model lock-in?) See below how to get the "chat template" with python

```python
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("facebook/blenderbot-400M-distill")
print(tokenizer.default_chat_template)
```

Thank you for a great project!
---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Hello! You can avoid dependency on the file located at https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json by creating a fork of your own registry. For instructions on how to convert your own model for use with Tabby, please refer to the "How can I convert my own model for use with Tabby?" section in https://tabby.tabbyml.com/docs/faq/.

As an example, I use the Q4_K_M CodeLlama-70B model for my personal registry, which you can find here: https://github.com/wsxiaoys/registry-tabby/blob/e9b46bc14eed06f10c27467263b405ddabbae428/models.json#L53.

**Comment by pervrosen** [comment]
Aaah! I think I understand now. Will try tomorrow. Then the only thing left is the hard coded GGML_MODEL_RELATIVE_PATH. Did you rename your gguf-file?

**Comment by pervrosen** [comment]
Thank you for your quick response. Much appreciated!
