### ISSUE TITLE
Docker server exits with `error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Disane87** [TabbyML/tabby#1426]
**Describe the bug**
After the latest update the docker container exists with this error:
> /opt/tabby/bin/tabby: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
/opt/tabby/bin/tabby: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory

**Information about your version**
I use the latest version but on an unraid system. 

**Information about your GPU**
I dont use the gpu I use the cpu `serve` like stated in the docs: (https://tabby.tabbyml.com/docs/installation/docker)

> docker run
  -d
  --name='TabbyML'
  --net='bridge'
  --privileged=true
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="FRATHIEL-UNRAID"
  -e HOST_CONTAINERNAME="TabbyML"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:8945]/'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/quimnut/unraid-docker-templates/master/quimnut/tabby.png'
  -p '8080:8945/tcp'
  -v '/mnt/user/appdata/TabbyML':'/data':'rw' 'tabbyml/tabby' serve
  --model TabbyML/StarCoder-1B
40f973c3b57ac92951e9ae5bb5f6e0f2e9d3aca015f2eb4dbf6908ad4bf30dad

**Additional context**
It just worked fine until the latest update (can't really figure out of the update is the cause but since the new update the container doesn't start).

Anything I could check or provide to get around this issue?

**Comment by wsxiaoys** [comment]
Hello! This is a known issue for running CPU device with docker image(due to an upstream change). As a quick workaround, please override your entry point by using `--entrypoint /opt/tabby/bin/tabby-cpu`. I'll update the documentation in a follow-up PR.

**Comment by Disane87** [comment]
it works, thank you!

**Comment by plohoj** [comment]
@wsxiaoys You probably added the documentation in the wrong area. You edited docker-compose.yml for CUDA, not CPU

**Comment by Disane87** [comment]
> @wsxiaoys You probably added the documentation in the wrong area. You edited docker-compose.yml for CUDA, not CPU

It's all under CPU. Everything is fine.

**Comment by plohoj** [comment]
Check it out at https://tabby.tabbyml.com/docs/installation/docker-compose. Entrypoint is now added in the tab for CUDA. With this configuration I couldn't get it to work. But everything worked after removing this line

There is no entrypoint in the CPU tab

**Comment by wsxiaoys** [comment]
Fixed in #1441, Thanks everyone

**Comment by Geremia** [comment]
@wsxiaoys I get this error when I want to use the GPU: #2239
