### ISSUE TITLE
supply free trial openAPI so we can try it even we donot have GPU

### ISSUE THREAD

**Issue by shixin-guo** [TabbyML/tabby#145]
**Please describe the feature you want**
I want to try tabby in my IDE, I do not have a cloud service or Nvidia GPU.
can we supply some open APIs that we can free trial, not need very stable, only let us try it easier

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
team is working on this, stay tuned :)

cc @vodkaslime

**Comment by prologic** [comment]
This kind of defeats the point of self hosting right?

**Comment by wsxiaoys** [comment]
For anyone who doesn't have a GPU, you can now follow https://tabby.tabbyml.com/docs/installation/hugging-face/ to create a private instance of Tabby on the Hugging Face platform.
