### ISSUE TITLE
Is NVIDIA P106-100 supported ?

### ISSUE THREAD

**Issue by arek125** [TabbyML/tabby#1467]
Hello

**Describe the bug**
Is NVIDIA P106-100 supported ?
I run server on debian with default docker command.
Server is running fine but completions in VS Code are not showing up. No errors there.
Also docker is showing a warnings like below.

**Information about your GPU**
![image](https://github.com/TabbyML/tabby/assets/18678192/b3c44867-a827-4265-ad2e-44a3173ed584)

**Comment by wsxiaoys** [comment]
Tabby requires a compute capability of >= 6.1 for now; therefore, it is likely that the P106 is not sufficiently new for this requirement.
