### ISSUE TITLE
Issue with Quality in code generation

### ISSUE THREAD

**Issue by surapuramakhil** [TabbyML/tabby#1473]
**Describe the bug**
I am not sure it's issue with code generation models or issue with passing inputs correctly to those models or problem with context. Here is what I have found.

Tested in TabbyML playground https://tabby.tabbyml.com/playground

code generation works great 

![Screenshot (223)](https://github.com/TabbyML/tabby/assets/9161543/b92468eb-aa54-4c51-bc14-aebc8ad37242)

it generate mostly garbage when there is other code

![image](https://github.com/TabbyML/tabby/assets/9161543/f759de75-7e3f-4448-9100-13066064bf2f)

There are some other code quality issue with code generation

- wrong use of variable name etc and lot more

**Information about your version**
Please provide output of `tabby --version`

**Information about your GPU**
Please provide output of `nvidia-smi`

**Additional context**

**Comment by wsxiaoys** [comment]
The behavior is somewhat expected, given that the model used in the playground is a small one, primarily for demonstration purposes.
