### ISSUE TITLE
ROCm Build Fails unless I add lib path println!("cargo:rustc-link-search=native={}/lib", rocm_root);

### ISSUE THREAD

**Issue by NinjaPerson24119** [TabbyML/tabby#1481]
**Describe the bug**

Needs `println!("cargo:rustc-link-search=native={}/lib", rocm_root);`

Otherwise get error `note: /usr/bin/ld: cannot find -lamdhip64: No such file or directory`

On Arch my paths are setup like
```
export PATH=$PATH:/opt/rocm/bin:/opt/rocm/opencl/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/rocm/lib
```

**Information about your version**
Please provide output of `tabby --version`

**Information about your GPU**
Please provide output of `nvidia-smi`

**Additional context**

**Comment by NinjaPerson24119** [comment]
Similarly, CUDA fails without adding `println!(r"cargo:rustc-link-search=native={}", "/opt/cuda/lib64");`. It appears that `CUDA_PATH` is not searched recursively.

**Comment by wsxiaoys** [comment]
For ROCm: Feel free to submit a PR to address the issue.
For CUDA: It appears that the optimal solution is to extract a `CUDA_PATH` environment variable, similar to ROCm.
