### ISSUE TITLE
Getting error when loading 7b model in GPU based machine

### ISSUE THREAD

**Issue by samavedulark** [TabbyML/tabby#1498]
I am getting below error when trying to use 7B models.
Models tried. 
TabbyML/DeepseekCoder-6.7B
TabbyML/CodeLlama-7B

docker command used
docker run -it -e LLAMA_CPP_PARALLELISM=1 --gpus all -p 9694:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/DeepseekCoder-6.7B --device cuda

System has 4 NVIDIA A100 80GB GPU's.

Error:
2024-02-20T04:43:24.817598Z  INFO tabby::serve: crates/tabby/src/serve.rs:116: Starting server, this might take a few minutes...
2024-02-20T04:43:24.821176Z  INFO tabby::services::code: crates/tabby/src/services/code.rs:53: Index is ready, enabling server...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 4 CUDA devices:
  Device 0: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
  Device 1: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
  Device 2: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
  Device 3: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
ggml_backend_cuda_buffer_type_alloc_buffer: allocating 1640.75 MiB on device 1: cudaMalloc failed: out of memory
2024-02-20T04:43:32.423773Z ERROR llama_cpp_bindings: crates/llama-cpp-bindings/src/lib.rs:65: Unable to load model: /data/models/TabbyML/DeepseekCoder-6.7B/ggml/q8_0.v2.gguf

Nvidia-smi output

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe           On | 00000000:4F:00.0 Off |                    0 |
| N/A   34C    P0               53W / 300W|      0MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe           On | 00000000:52:00.0 Off |                    0 |
| N/A   39C    P0               76W / 300W|  78743MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe           On | 00000000:D5:00.0 Off |                    0 |
| N/A   35C    P0               55W / 300W|      0MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe           On | 00000000:D6:00.0 Off |                    0 |
| N/A   35C    P0               57W / 300W|      0MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    1   N/A  N/A    938599      C   /usr/bin/python3                          78740MiB |

**Comment by wsxiaoys** [comment]
Hi, could you share the output of  `docker run -it  tabbyml/tabby -V`? Besides, could you try assign a different GPU to tabby, e.g assign GPU 0 to tabby

```
docker run -it -e LLAMA_CPP_PARALLELISM=1 -e NVIDIA_VISIBLE_DEVICES=0 --gpus all -p 9694:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/DeepseekCoder-6.7B --device cuda
```

**Comment by samavedulark** [comment]
tabby 0.8.3

**Comment by samavedulark** [comment]
I gave this command and it is working 
docker run -it -e LLAMA_CPP_PARALLELISM=1 --gpus 'device=2' -p 9694:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/DeepseekCoder-6.7B --device cuda

Output
2024-02-20T05:40:29.005590Z  INFO tabby::serve: crates/tabby/src/serve.rs:116: Starting server, this might take a few minutes...
2024-02-20T05:40:29.052003Z  INFO tabby::services::code: crates/tabby/src/services/code.rs:53: Index is ready, enabling server...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA A100 80GB PCIe, compute capability 8.0, VMM: yes
2024-02-20T05:40:36.125426Z  INFO tabby::routes: crates/tabby/src/routes/mod.rs:35: Listening at 0.0.0.0:8080
