### ISSUE TITLE
Support Google Gemma-7b

### ISSUE THREAD

**Issue by moqimoqidea** [TabbyML/tabby#1518]
Please describe the feature you want
Support the latest Gemma coder models. There are two models: base and instruct tuned.

* https://huggingface.co/google/gemma-7b
* https://huggingface.co/google/gemma-7b-it

llama.cpp already support, see https://github.com/ggerganov/llama.cpp/pull/5631

Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
With https://github.com/TabbyML/tabby/pull/1805 in 0.10, Gemma model will be supported (though we might not adding it to official registry as it's not supporting FIM)

**Comment by jdekarske** [comment]
CodeGemma has FIM https://ai.google.dev/gemma/docs/formatting#formatting-fim

**Comment by wsxiaoys** [comment]
Yes - it's tracked in https://github.com/TabbyML/tabby/issues/1807
