### ISSUE TITLE
Add current project for indexing via editor

### ISSUE THREAD

**Issue by G07cha** [TabbyML/tabby#1538]
**Please describe the feature you want**

Tabby supports repository level context for code completion via project indexing. To index a project I need to manually add it to `~/.tabby/config.toml`, it might be handy to have a shortcut in the editor that will add a currently open project to the config file so that it can be picked up for indexing by the scheduler later.

**Additional context**

I primarily use VSCode so not sure if this sort of feature will be applicable to all editors Tabby supports.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
This has been implemented for some degree (recent changed files / active tabs are considered for code completions).
