### ISSUE TITLE
deepseek-coder-1.3b-instruct

### ISSUE THREAD

**Issue by Tentaklecake** [TabbyML/tabby#1541]
**Please describe the feature you want**
adding deepseek-coder-1.3b-instruct  to https://github.com/TabbyML/registry-tabby/blob/main/models.json.

**Additional context**
https://github.com/deepseek-ai/DeepSeek-Coder/blob/main/pictures/HumanEval.png
deepseek-coder-1.3b-instruct shows twice the best result when coding in Python than deepseek-coder-1.3b-base

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
This should be a straightforward pull request to the chat models section at https://github.com/wsxiaoys/registry-tabby
