### ISSUE TITLE
Illegal instruction in the new builds

### ISSUE THREAD

**Issue by ainub** [TabbyML/tabby#1570]
[v0.8.0](https://github.com/TabbyML/tabby/releases/tag/v0.8.0) is working.

v0.8.3 + 
Since v0.8.0 you have changed the platform compilation flags or something because now it throws:
traps: tabby_x86_64-ma[448] trap invalid opcode ip:55aba0fcd521 sp:7ffe26278b80 error:0 in tabby_x86_64-manylinux2014-cuda117[55aba0f2a000+1a6f000]

The CPU architecture is no longer working for i7-6xxx
[  172.241350] RIP: 0033:0x55aba0fcd521
[  172.241682] Code: 4c 89 e6 ba 6e 02 00 00 48 8d 3d fa c1 2d 04 e8 d5 29 93 01 4c 89 ef 48 8d 15 cb 5e 12 04 48 8d 35 e4 c1 2d 04 e8 df d1 f5 ff <62> f1 7d 48 6f 05 95 5a 90 03 48 b8 5f 20 00 00 5f 20 00 00 48 89
[  172.243450] RSP: 002b:00007ffe26278b80 EFLAGS: 00010202
[  172.243983] RAX: 0000000000000000 RBX: 00007ffe26279ba0 RCX: 00000000000001c0
[  172.244789] RDX: 35a72ddede8c3fba RSI: 000055aba7006ce0 RDI: 0000000000000000
[  172.245486] RBP: 00007ffe2627b270 R08: 0000000000000000 R09: 0000000000000000
[  172.246068] R10: 0000000000000000 R11: 0000000000000136 R12: 00007ffe26279cc0
[  172.246835] R13: 000055aba28e8930 R14: 00007ffe2627b328 R15: 0000000000000001
[  172.247619] FS:  00007fbdf6e90000 GS:  0000000000000000

**Comment by wsxiaoys** [comment]
Hi - could you link the binary of 0.8.0 / 0.8.3 you used?

Here's the diff between 0.8.0 and 0.8.3, as you could see there is no change on building flags 👀 
https://github.com/TabbyML/tabby/compare/v0.8.0...v0.8.3

**Comment by ainub** [comment]
- os: ubuntu-latest
          - os: dimerun-k3-ubuntu2204
          Seems to be the enemy :)

**Comment by ainub** [comment]
0x00005555557fb791 <_Z41__static_initialization_and_destruction_0ii.constprop.0+177>:        vmovdqa32 0x32b9625(%rip),%zmm0
vmovdqa32 is the reason :)
So it seems that when you changed the OS target, they changed the CPU architecture that you compile on. The new CPU you compile on has AVX512VL that was introduce in Skylake-X smth, i9 + or so, too much documentation to go through :))
So it is probably again, from the llama2.cpp compilation flags that is optimizing for the architecture you compile on that has now changed from AVX2 to AVX512VL :))

**Comment by wsxiaoys** [comment]
Hey @ainub 

Could you try binary from https://github.com/TabbyML/tabby/actions/runs/8088035324 to see if they're working for you?

**Comment by ainub** [comment]
> Hey @ainub
> 
> Could you try binary from https://github.com/TabbyML/tabby/actions/runs/8088035324 to see if they're working for you?

Hello,
I tested, yes. This version is working as intended on i7-6xxx platforms. Seems back to normal, thank you.

**Comment by wsxiaoys** [comment]
Will be in release since https://github.com/TabbyML/tabby/releases/tag/v0.9.0-rc.2

**Comment by ainub** [comment]
Good news is that the latest nightly build is also working on older CPU architectures that don't have AVX2
Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz

https://github.com/TabbyML/tabby/releases/download/nightly/tabby_x86_64-manylinux2014-cuda122
