### ISSUE TITLE
"invalid magic characters" if model was downloaded during huggingface maintenance window

### ISSUE THREAD

**Issue by suess-ecbm** [TabbyML/tabby#1581]
**Describe the bug**
During maintenance, huggingface.co models cannot be downloaded. Download attempts lead to the maintenance website being saved to disk instead of the model file.

```
➤ # Start server with StarCoder-1B
> tabby serve --device metal --model TabbyML/DeepseekCoder-6.7B

Writing to new file.
2024-02-28T22:39:07.432479Z  INFO tabby::serve: crates/tabby/src/serve.rs:116: Starting server, this might take a few minutes...
gguf_init_from_file: invalid magic characters '<!DO'
2024-02-28T22:39:07.552864Z ERROR llama_cpp_bindings: crates/llama-cpp-bindings/src/lib.rs:65: Unable to load model: /Users/username/.tabby/models/TabbyML/DeepseekCoder-6.7B/ggml/q8_0.v2.gguf
```

**Information about your version**
Please provide output of `tabby --version`
```
> tabby --version
tabby 0.8.3
```

**Information about your GPU**
Running on Macbook M1.

**Additional context**
![grafik](https://github.com/TabbyML/tabby/assets/54807584/e9a363da-9f52-4746-bbc3-a99957ddb5a4)

**Comment by wsxiaoys** [comment]
tracked in TAB-534

**Comment by suess-ecbm** [comment]
Found a related issue, seems like the same root cause:
https://github.com/TabbyML/tabby/issues/1575
