### ISSUE TITLE
support starcoder2

### ISSUE THREAD

**Issue by rburgstaller** [TabbyML/tabby#1587]
https://techcrunch.com/2024/02/28/starcoder-2-is-a-code-generating-ai-that-runs-on-most-gpus

https://github.com/bigcode-project/starcoder2

**Comment by wsxiaoys** [comment]
ref: https://github.com/TabbyML/tabby/issues/1230

**Comment by wsxiaoys** [comment]
also pending on https://github.com/ggerganov/llama.cpp/pull/5795

**Comment by wsxiaoys** [comment]
added https://github.com/wsxiaoys/registry-tabby, runnable with `--model wsxiaoys/StarCoder-3B` for nightly build.

**Comment by aaronstevenson408** [comment]
@wsxiaoys having trouble getting it to run , i can run the normal models on the nightly build , but for some reason can't get starcoder2 to work, used your repo and my fork , also have tried manually downloading it. 

https://huggingface.co/brittlewis12/starcoder2-3b-GGUF
https://huggingface.co/second-state/StarCoder2-3B-GGUF
are the repos i've gotten from. 
keeps erroring 1 , but that isn't enough to go off of
i'm running a docker nightly image  updated 8 hours ago
any ideas on getting it to run , i'm excited to get it running

**Comment by wsxiaoys** [comment]
Hey @aaronstevenson408 , could you try this docker images `ghcr.io/tabbyml/tabby:main-ef15f97`? Just realized the docker tag for nightly is not updated yet.

**Comment by aaronstevenson408** [comment]
Seems like it worked ty

**Comment by rudiservo** [comment]
Is the prompt_template the same has starcoder 1?
It seems to have issues to autocomplete in the middle of writing a word and only triggering on new line.

**Comment by CleyFaye** [comment]
> added https://github.com/wsxiaoys/registry-tabby, runnable with `--model wsxiaoys/StarCoder-3B` for nightly build.

I am not sure if here is the right place to report this, but the three size for StarCoder2 all have the name "StarCoder2-3B" there.

**Comment by wsxiaoys** [comment]
> > added https://github.com/wsxiaoys/registry-tabby, runnable with `--model wsxiaoys/StarCoder-3B` for nightly build.
> 
> I am not sure if here is the right place to report this, but the three size for StarCoder2 all have the name "StarCoder2-3B" there.

Thanks for reporting - fixed

**Comment by jeromepl** [comment]
Hi @wsxiaoys, is it now possible to run StarCoder v2 from tabby directly with something like:
`tabby serve --device metal --model TabbyML/StarCoderV2-3B`? If not, what is the best way to run StarCoder v2 today?

**Comment by rudiservo** [comment]
@jeromepl you can you can either make you own repo registry-tabby or use one already available
https://github.com/wsxiaoys/registry-tabby

`tabby serve --device metal --model wsxiaoys/StarCoder2-15B`

**Comment by RiQuY** [comment]
Is this still pending to be implemented on the official model registry?

**Comment by wsxiaoys** [comment]
Just added the Starcoder2-3B / Starcoder2-7B to the official registry. Enjoy!

**Comment by rudiservo** [comment]
@wsxiaoys could you add the 15B? It's actually quite usable on a 4090 or a 7900XTX.

**Comment by wsxiaoys** [comment]
@rudiservo you could still maintain that in a forked registry. For tabby official registry we prefer not to include models go beyond 10B atm.

**Comment by rudiservo** [comment]
@wsxiaoys yes I already have one, I was just suggesting it since more people might be interested in it and given my experience with the model, also the quality between 7B and 15B is a bit noticeable.

It is quite usable with Tabby, but you do need more than 16GB of VRAM, currently the 7900XTX can handle it quite well.

**Comment by den-run-ai** [comment]
I see StarCoder2-7B and StarCoder2-15B in the Tabby leaderboard, but only 7B is available on Mac:

tabby serve --device metal --model StarCoder2-15B
thread 'main' panicked at crates/tabby-common/src/registry.rs:92:32:
Invalid model_id <TabbyML/StarCoder2-15B>
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by den-run-ai** [comment]
It looks like the StarCoder2 15B quantized model is available in HuggingFace:

https://huggingface.co/nold/starcoder2-15b-GGUF
