### ISSUE TITLE
Agent: Update the `getCompletion` Interface to Acquire More Editor Context

### ISSUE THREAD

**Issue by icycodes** [TabbyML/tabby#161]
We should give more context (full documents) to agent, this is useful to 
* Filter out completion content duplicated with lines after the cursor #138
* Improve completion prompt #160

**Comment by wsxiaoys** [comment]
As mentioned in issue #163, the suggestions for what should be included in the prompt should be provided by our modeling experts. However, I agree that the agent itself could implement its own filtering logic based on the context.
