### ISSUE TITLE
Tabby server offline deployment 

### ISSUE THREAD

**Issue by pyh1998** [TabbyML/tabby#1623]
**Please describe the feature you want**
I can't access the internet from my computer at work. Once I have imported the docker image and downloaded the relevant models, I am unable to deploy the tabby server as it has to access github and hugginface to get the models.
I would like a way to deploy the models and tabby serve completely offline!

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
One approach is to create your own Docker image and embed the model as part of the build process. For example, you could run the `tabby download` command as one step in the Docker build process.

If anyone is interested in contributing an example, feel free to send out an PR.

**Comment by pyh1998** [comment]
> One approach is to create your own Docker image and embed the model as part of the build process. For example, you could run the `tabby download` command as one step in the Docker build process.
> 
> If anyone is interested in contributing an example, feel free to send out an PR.

Thank you for your reply! If I want to make changes based on the original image, which code in which files should I modify to use my own local model instead of pulling from github and huggginface?

**Comment by wwayne** [comment]
Hi @pyh1998 I tried to set up the offline scenario locally. Here are the steps I followed:
1. On a computer with internet access, create a new **Dockerfile**.
```dockerfile
FROM tabbyml/tabby

RUN /opt/tabby/bin/tabby-cpu download --model TabbyML/StarCoder-1B
```
2. Build the Docker image which containing the model
```bash
docker build -t tabby-offline .
```
3. Save the Docker image to a tar file:
```bash
docker save -o tabby-offline.tar tabby-offline
```
4. Copy the `tabby-offline.tar` file to the computer without internet access.
5. On the offline computer, load the Docker image from the tar file:
```bash
docker load -i tabby-offline.tar
```
6. Run the Tabby container
```bash
docker run -it \
  --gpus all -p 8080:8080 -v $HOME/.tabby:/data \
  tabby-offline \
  serve --model TabbyML/StarCoder-1B --device cuda
```

**Comment by wwayne** [comment]
We have a new blog post for this topic https://tabby.tabbyml.com/blog/ , closing the issue
