### ISSUE TITLE
`events` logs are world-readable, contain all text sent to the model, and can't be turned off

### ISSUE THREAD

**Issue by adamnovak** [TabbyML/tabby#1631]
**Describe the bug**
Tabby logs all input to the model to `events` files (see #959).

These files are created with ordinary default file permissions, which by default on many systems (including mine) makes them world-readable. Other unprivileged users on the system can read them.

If I have Tabby enabled in my editor and open and type in a file containing secrets, those secrets will be sent to Tabby to generate completions and then logged to the world-readable `events` logs, where other users can access them.

**Information about your version**
I last tested this with Tabby v0.7.0.

**Information about your GPU**
N/A

**Additional context**
I've been using Tabby on our lab's shared GPU machines, which are classic multi-user, multi-tenant Unix machines where multiple users can do things like access local ports, the filesystem, and the command lines of running processes.

But if I can't draw a security boundary around Tabby that lets it safely handle secret text on a multi-user system, and I can't configure the Tabby vim plugin to not operate on certain filetypes or file names to keep secrets out of Tabby, then I can't use Tabby in my environment.

**Comment by wsxiaoys** [comment]
Thank you for the bug report. It does make sense to set the permissions to 600 instead of 644.

@boxbeam could you take a look?
