### ISSUE TITLE
Invalid characters in repository with private repositories github_pat_...

### ISSUE THREAD

**Issue by ipty** [TabbyML/tabby#1641]
**Describe the bug**
Scheduler has problems with private repositories with personal access token as url: https://github_pat_xxxxx...@github.com/xxx.git

**Information about your version**
0.9.0 on mac sonoma

**Additional context**
Prior to version 0.9.0 fetching private repositories configured in config.toml
like https://github_pat_xxxxx...@github.com/xxx.git was never a problem.

Since 0.9.0 i get:

Warning: Could not parse the Tabby configuration at /Users/user/.tabby/config.toml
Syncing 0 repositories...
Reason: Invalid characters in repository name: https_github_pat_xxxx@github.com/xxx.git
Falling back to default config, please resolve the errors and restart Tabby

Greetings & by the way: thanks for your great work!

**Comment by boxbeam** [comment]
Thanks for the bug report! I've put up a PR that should fix this.

**Comment by wsxiaoys** [comment]
Hi @ipty, as an intermediate workaround, you could fill the `name` field in config.toml, example: https://tabby.tabbyml.com/docs/configuration/#repository-context-for-code-completion

**Comment by ipty** [comment]
Changing the config.toml from

[[repositories]]
git_url = "https://github_pat_1xxxxxxxxxx@github.com/vendor/myapp.git"

to:
[[repositories]]
name="myapp"
git_url = "https://github_pat_1xxxxxxxxxx@github.com/vendor/myapp.git"

does the trick.

For any one who does not know what is meant by filling the "name" field
