### ISSUE TITLE
Add a --chat-device flag for serve command

### ISSUE THREAD

**Issue by SpeedCrash100** [TabbyML/tabby#1659]
Add the _--chat-device_ flag to _serve_ subcommand to allow use different device for chat.
* If the flag is not given, then chat model should use _--device_ as it is now.
* If the flag is specified but chat model is not selected, give a warning, I guess

### The reasoning
I use Tabby for both chat and completions. Completions is the main usage and I give it the best model my GPU can handle leaving chat model to CPU. I see no reasons to lose quality of main usage just to handle chat and completions model simultaneously.  

Previously, I solved this by running workers for each model. I was able to run 1 worker for chat and completions and if I really need to dynamically redeploy workers to use GPU for chat when I really need to.  However, this is now an enterprise feature and I cannot use it to do that anymore. 

### Alternative solution
Rework subscriptions plan to count workers per type (chat, completions) and allow  1 worker per type in community license. When the _serve_ subcommand is used with models, web-server instance should be counted as workers to avoid scaling without license.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Thank you for the FR. One QQ: Since you're using Tabby locally, there shouldn't be a scenario in which you're running chat and completion workloads simultaneously. Therefore, would it not be more sensible to use the GPU for both the completion model and the chat model?

**Comment by SpeedCrash100** [comment]
The problem here is VRAM, I have only 12GB and 7B models consumes nearly all of it. I am not sure how Nvidia CUDA handles it but ROCm do not allow run new models if GPU VRAM runs out so I have to move chat model to CPU to use good enough 7B model for completions
