### ISSUE TITLE
Jetbrains Rider IDE Plugin: Completion is not removed when typing

### ISSUE THREAD

**Issue by Nitschi** [TabbyML/tabby#1668]
### Description

Sometimes typing does not remove the completion that tabby made, leading to distracting text that is stuck to the right side of the text cursor.
Happens in both automatic and manual mode.

![image](https://github.com/TabbyML/tabby/assets/5908114/9bfca394-6592-4319-b1eb-9a32e77f7c97)

Re-triggering tabby completion (Ctrl + \) removes it.
(+ Automatic mode often does not trigger correctly, which might help mitigate the problem somewhat)

It seems to work fine in some other files I've tried.

### Version
tabby 0.9.0
Plugin: 1.4.0 in Jetbrains Rider 2023.3.3
Tabby runs remotely on machine in my company

### nvidia-smi
```
Wed Mar 13 18:37:20 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.07             Driver Version: 535.161.07   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:01:00.0 Off |                  Off |
|  0%   47C    P8              19W / 450W |  21283MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A     32838      C   /opt/tabby/bin/tabby                      21276MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by wsxiaoys** [comment]
@icycodes fyi

**Comment by icycodes** [comment]
Hi @Nitschi 
Thank you for reporting this bug. It appears that the caret listener is not functioning correctly for some unknown reason.

Could you please provide some steps to reproduce this problem, or would you mind sharing your editor log? This information will greatly assist in addressing the issue. You can refer to [this documentation](https://tabby.tabbyml.com/docs/extensions/troubleshooting#intellij-platform-ides-logs) for guidance about the editor log.
