### ISSUE TITLE
Schedule [swc.rs] failed.

### ISSUE THREAD

**Issue by xusd320** [TabbyML/tabby#1678]
**Describe the bug**
Schedule [swc.rs](https://github.com/swc-project/swc) failed. Throw an error of "An index exists but the schema does not match".
<img width="1477" alt="image" src="https://github.com/TabbyML/tabby/assets/16577489/a9ceee87-581e-4a8a-b477-f9022b4b938d">

**Information about your version**
tabby version: 0.8.3

**Information about your GPU**
Apple M2 Pro

**Additional context**
My config.toml
<img width="478" alt="image" src="https://github.com/TabbyML/tabby/assets/16577489/f1430b2e-b7fa-4219-86d6-f838ab43374b">

**Comment by wsxiaoys** [comment]
Hey - could remove the `~/.tabby/index` directory and retry?

**Comment by xusd320** [comment]
> Hey - could you remove the `~/.tabby/index` directory and retry?

That's ok, thanks!
