### ISSUE TITLE
Pycharm Professional - Remote Development with Tabby

### ISSUE THREAD

**Issue by asusdisciple** [TabbyML/tabby#1756]
**Describe the bug**
I tried using Tabby on a remote machine with the Pycharm remote development feature, which starts an instance of Pycharm on the server, which can be accessed from my local machine. You can define client and server side plugins in the settings there. I tried various combinations where I installed tabby on the client/server side or both, but neither did work because it could not connect
 to the server (red icon with error message). However when I used the "check connection" button on the client, it said the connection is working. 

It would be interesting if you can reproduce this with a client/server setup and pycharm pro/ultimate. Also the model is running on the same server where my pycharm instance is running.

Also I am not sure but from my perspective, shouldnt it be enough to use tabby from the client side to access code?

**Information about your version**
Newest version

**Information about your GPU**
V100 32GB

**Additional context**
Ubuntu 22.04

**Comment by wsxiaoys** [comment]
Related: https://github.com/orgs/community/discussions/27961

**Comment by wwayne** [comment]
Hi, not sure if it helps, but you might take a try on forwarding the 8080 port via the JetBrains Gateway.

https://www.jetbrains.com/help/fleet/forward-ports.html
