### ISSUE TITLE
can I use the mirror of hf-mirror.com 

### ISSUE THREAD

**Issue by verigle** [TabbyML/tabby#1781]
**Please describe the feature you want**

use the mirrror of hf-mirror.com

**Additional context**
I try set environment `TABBY_DOWNLOAD_HOST: hf-mirror.com`, the error is that:
```
Failed to fetch model 'TabbyML/DeepseekCoder-6.7B' due to 'Invalid mirror <hf-mirror.com> for model urls: ["https://huggingface.co/TheBloke/deepseek-coder-6.7B-base-GGUF/resolve/main/deepseek-coder-6.7b-base.Q8_0.gguf"]'

```
---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
You might create your own registry with urls from `hf-mirror.com`. See "How can I convert my own model for use with Tabby?" in https://tabby.tabbyml.com/docs/faq for details

**Comment by verigle** [comment]
I just want to replace the domain of url "huggingface.co" to "hf-mirror.com" for regiested model "[TabbyML/DeepseekCoder-6.7B](https://huggingface.co/deepseek-ai/deepseek-coder-6.7b-base)"
https://tabby.tabbyml.com/docs/models/

**Comment by marykt** [comment]
> You might create your own registry with urls from `hf-mirror.com`. See "How can I convert my own model for use with Tabby?" in https://tabby.tabbyml.com/docs/faq for details

maybe the huggingface.co in the URL should be replaced with the mirror site ? These mirror sites are simply download sites and not hosting sites.
