### ISSUE TITLE
Support for CodeGemma

### ISSUE THREAD

**Issue by danny-su** [TabbyML/tabby#1807]
https://huggingface.co/google/codegemma-2b

**Comment by wsxiaoys** [comment]
Related: https://github.com/TabbyML/tabby/pull/1805

**Comment by wsxiaoys** [comment]
You can test code gemma with model id `wsxiaoys/CodeGemma-2B` and `wsxiaoys/CodeGemma-7B` on [0.10-rc](https://github.com/TabbyML/tabby/releases/tag/v0.10.0-rc.4) version now
