### ISSUE TITLE
Linux Permissions Errors

### ISSUE THREAD

**Issue by InkBrownell** [TabbyML/tabby#1808]
**Describe the bug**
I tried running tabby two ways:

Docker image. This creates `$HOME/.tabby`, but owned by `root:root`. Subdirectory (`$HOME/.tabby/models/TabbyML`) creation fails.
```
➜ docker run --entrypoint /opt/tabby/bin/tabby-cpu -it \
        -p 8080:8080 -v $HOME/.tabby:/data \
        -e RUST_BACKTRACE=1 \
        tabbyml/tabby serve --model StarCoder-1B
thread 'main' panicked at /root/workspace/crates/tabby-common/src/registry.rs:61:21:
Failed to fetch model organization <TabbyML>: Failed to create dir "/data/models/TabbyML"

Caused by:
    Permission denied (os error 13)
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: tabby_common::registry::ModelRegistry::new::{{closure}}
   3: tabby_download::download_model::{{closure}}
   4: tabby::services::model::download_model_if_needed::{{closure}}
   5: tabby::main::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tabby::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

 Fixing ownership with chown doesn't resolve the issue, but creating the subdirectory manually results in a different error.
 
 ```
 ➜ mkdir -p $HOME/.tabby/models/TabbyML
 
 ➜ docker run --entrypoint /opt/tabby/bin/tabby-cpu -it \
        -p 8080:8080 -v $HOME/.tabby:/data \
        -e RUST_BACKTRACE=1 \
        tabbyml/tabby serve --model StarCoder-1B
thread 'main' panicked at /root/workspace/crates/tabby-common/src/registry.rs:61:21:
Failed to fetch model organization <TabbyML>: Failed to convert JSON to file

Caused by:
    Other (cause; Permission denied (os error 13))
    HISTORY:
      [0] at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serdeconv-0.4.1/src/convert_json.rs:53
    
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at ./rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: tabby_common::registry::ModelRegistry::new::{{closure}}
   3: tabby_download::download_model::{{closure}}
   4: tabby::services::model::download_model_if_needed::{{closure}}
   5: tabby::main::{{closure}}
   6: tokio::runtime::park::CachedParkThread::block_on
   7: tabby::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Build from source. This appears to work inasmuch as the server runs without crashing. The IDE plugin claims to connect to the server successfully. However, while it does get the fans on my laptop spinning, it doesn't provide code completions. Every time the cursor pauses and I would expect a completion, an error appears in the server console output instead and the CPU grinds at 50% for ~30 seconds (shame on me for trying to do CPU inference on a laptop). 

```
➜ RUST_BACKTRACE=1 cargo run serve --model TabbyML/StarCoder-1B
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/tabby serve --model TabbyML/StarCoder-1B`
Writing to new file.
🎯 Downloaded https://huggingface.co/TabbyML/models/resolve/main/starcoderbase-1B.Q8_0.gguf to /home/autopilot/.tabby/models/TabbyML/StarCoder-1B/ggml/q8_0.v2.gguf.tmp
   00:00:29 ▕████████████████████▏ 1.23 GiB/1.23 GiB  42.96 MiB/s  ETA 0s.                                                                                                                                                                    2024-04-10T09:05:11.894911Z  INFO tabby::serve: crates/tabby/src/serve.rs:123: Starting server, this might take a few minutes...
2024-04-10T09:05:11.896462Z DEBUG tabby::services::code: crates/tabby/src/services/code.rs:57: Source code index is not ready `Failed to open the directory: 'DoesNotExist("/home/autopilot/.tabby/index")'`
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 136.00 MiB

  TELEMETRY

  As an open source project, we collect usage statistics to inform development priorities. For more
  information, read https://tabby.tabbyml.com/docs/configuration#usage-collection
  
  We will not see or any code in your development process.

  Welcome to Tabby!

  If you have any questions or would like to engage with the Tabby team, please join us on Slack
  (https://links.tabbyml.com/join-slack-terminal).


2024-04-10T09:05:24.254078Z  INFO tabby::routes: crates/tabby/src/routes/mod.rs:35: Listening at 0.0.0.0:8080
2024-04-10T09:06:11.898333Z DEBUG tabby::services::code: crates/tabby/src/services/code.rs:57: Source code index is not ready `Failed to open the directory: 'DoesNotExist("/home/autopilot/.tabby/index")'`
2024-04-10T09:07:11.899988Z DEBUG tabby::services::code: crates/tabby/src/services/code.rs:57: Source code index is not ready `Failed to open the directory: 'DoesNotExist("/home/autopilot/.tabby/index")'`
2024-04-10T09:08:11.901646Z DEBUG tabby::services::code: crates/tabby/src/services/code.rs:57: Source code index is not ready `Failed to open the directory: 'DoesNotExist("/home/autopilot/.tabby/index")'`
2024-04-10T09:09:11.902990Z DEBUG tabby::services::code: crates/tabby/src/services/code.rs:57: Source code index is not ready `Failed to open the directory: 'DoesNotExist("/home/autopilot/.tabby/index")'`
2024-04-10T09:10:11.905282Z DEBUG tabby::services::code: crates/tabby/src/services/code.rs:57: Source code index is not ready `Failed to open the directory: 'DoesNotExist("/home/autopilot/.tabby/index")'`
```

Running from source doesn't suffer from the docker issue of creating files owned by root. As you might expect, creating `$HOME/.tabby/index` manually results in complaints about yet another file (`$HOME/.tabby/index/meta.json`).

**Information about your version**
tabby 0.9.1 (docker image)

Commit df797d1b, tabby 0.10.0-dev.0 (run from source)

**Information about your GPU**
N/A, running CPU only.

**Additional context**
Node: v20.12.0
IDE: Pycharm Professional 2023.3.5
OS: Fedora 39

**Comment by manti-by** [comment]
Has the same issue

**Information about your version**
Commit https://github.com/TabbyML/tabby/commit/7ff97a51c3201ea1c5381c1badb78cbef4c05c69, tabby 0.10.0-dev.0 (run from source)

**Information about your GPU**
GeForce RTX 2060 Rev. A, driver Version: 535.161.08, CUDA Version: 12.2.

**Additional context**
Node: v20.12.1
IDE: Pycharm Professional 2024.1
OS: Ubuntu 22.04

**Comment by wsxiaoys** [comment]
@InkBrownell / @manti-by 

Error is thrown from https://github.com/TabbyML/tabby/blob/d6130c29698266c0643c56ee9ebdd1057b6f96b4/crates/tabby-common/src/registry.rs#L35

Could you help verify if you have internet access to https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json in docker container environment?

**Comment by wsxiaoys** [comment]
@manti-by @InkBrownell 

The error was thrown from https://github.com/TabbyML/tabby/blob/d6130c29698266c0643c56ee9ebdd1057b6f96b4/crates/tabby-common/src/registry.rs#L41

Could you help verify if you can create the directory manually (~/.tabby/TabbyML) in docker environment? Could you also share the permission info (output of `ls -l /data`) in container?

**Comment by manti-by** [comment]
@wsxiaoys Hi, I run everything in a local environment (native rust, not docker).
The problem [somewhere in configuration](https://github.com/TabbyML/tabby/blob/main/crates/tabby/src/services/code.rs#L57) and/or models loader because I have `~/.tabby/models/TabbyML/models.json` but app tries to open `~/.tabby/index/meta.json`.
![Screenshot from 2024-04-10 22-40-14](https://github.com/TabbyML/tabby/assets/338943/939da1e6-2b30-47ad-9b1a-56352493c5d8)

**Comment by wsxiaoys** [comment]
> 2024-04-10T09:06:11.898333Z DEBUG tabby::services::code: crates/tabby/src/services/code.rs:57: Source code index is not ready `Failed to open the directory: 'DoesNotExist("/home/autopilot/.tabby/index")'`

This message only presents for cargo run - which is expected. A background thread will always try to check if an index is ready to load for repository context.

You can safely ignore this message (as its warning level is `DEBUG`)

**Comment by InkBrownell** [comment]
> Could you help verify if you can create the directory manually (~/.tabby/TabbyML) in docker environment? Could you also share the permission info (output of `ls -l /data`) in container?

```
➜ rm -rf ~/.tabby

➜ docker run --entrypoint /bin/bash -it \
        -p 8080:8080 -v $HOME/.tabby:/data \
        tabbyml/tabby
root@d38d535c6409:/# ls -l /
total 52
-rw-r--r--.   1 root root 17294 Nov 10 07:03 NGC-DL-CONTAINER-LICENSE
lrwxrwxrwx.   1 root root     7 Oct  4  2023 bin -> usr/bin
drwxr-xr-x.   1 root root     0 Apr 18  2022 boot
-rw-r--r--.   1 root root  4332 Nov 10 07:04 cuda-keyring_1.0-1_all.deb
drwxr-xr-x.   1 root root     0 Apr 10 21:22 data
drwxr-xr-x.   5 root root   360 Apr 10 21:24 dev
drwxr-xr-x.   1 root root    56 Apr 10 21:24 etc
drwxr-xr-x.   1 root root     0 Apr 18  2022 home
lrwxrwxrwx.   1 root root     7 Oct  4  2023 lib -> usr/lib
lrwxrwxrwx.   1 root root     9 Oct  4  2023 lib32 -> usr/lib32
lrwxrwxrwx.   1 root root     9 Oct  4  2023 lib64 -> usr/lib64
lrwxrwxrwx.   1 root root    10 Oct  4  2023 libx32 -> usr/libx32
drwxr-xr-x.   1 root root     0 Oct  4  2023 media
drwxr-xr-x.   1 root root     0 Oct  4  2023 mnt
drwxr-xr-x.   1 root root    10 Mar 20 05:51 opt
dr-xr-xr-x. 441 root root     0 Apr 10 21:24 proc
drwx------.   1 root root    30 Oct  4  2023 root
drwxr-xr-x.   1 root root    32 Oct  4  2023 run
lrwxrwxrwx.   1 root root     8 Oct  4  2023 sbin -> usr/sbin
drwxr-xr-x.   1 root root     0 Oct  4  2023 srv
dr-xr-xr-x.  13 root root     0 Apr 10 07:49 sys
drwxrwxrwt.   1 root root     0 Oct  4  2023 tmp
drwxr-xr-x.   1 root root     6 Oct  4  2023 usr
drwxr-xr-x.   1 root root    22 Oct  4  2023 var
root@d38d535c6409:/# ls -l /data
ls: cannot open directory '/data': Permission denied
root@d38d535c6409:/# mkdir -p /data/models/TabbyML
mkdir: cannot create directory '/data/models': Permission denied
```

Permissions look good but still can't open the volume mount. SELinux causing issues?

**Comment by wsxiaoys** [comment]
Right - the permission error should be caused by your container runtime's security settings.

**Comment by Kazade** [comment]
In case anyone else hits this, on Fedora you need to add `:Z` to the of the volume definition (e.g. `-v $HOME/.tabby:/data:Z`) and everything will work as expected (because Fedora uses SELinux)

**Comment by datGryphon** [comment]
Following up on this.

I had a related permissions issue that isn't really a Tabby bug, but I will leave it here incase it helps anyone else:

I am on Windows 11 running Ubuntu 22.04 in WSL2 with the NVIDIA tool kit with WSL integration installed for Docker Desktop. 

When I launched a Tabby container with the suggested bind-mount method in the docs, the files that were created by the resulting container would have 640 root:root permissions because they were owned by the container managed outside of the WSL2 instance I was launching the container from.

The solution for this was to use a external docker volume for the /data folder that could also be managed outside of WSL2 by Docker Desktop. 

I also needed to use the `:Z` fix mentioned above in combination with this to get local bind mounts to work correctly with this fix. 

`docker volume create tabby-data`

```yaml
services:
  tabby:
    # ...
    image: registry.tabbyml.com/tabbyml/tabby
    command: # ...
    volumes:
      - tabby-data:/data
      - "$HOME/my_proj:/my_proj:Z"
    # ...

volumes:
  tabby-data:
    external: true
```

now the files in the persisted /data folder can be properly accessed after restarting the service.
