### ISSUE TITLE
bug(ee): Bisected - DB migration error when starting Tabby using 'cargo run'

### ISSUE THREAD

**Issue by RiQuY** [TabbyML/tabby#1817]
**Describe the bug**
Tabby shows the following error when trying to launch it using `cargo run`.

```
thread 'main' panicked at /media/Almacen/Programas/tabby/ee/tabby-webserver/src/handler.rs:39:14:
Must be able to initialize db: migration 16 was previously applied but has been modified
```
Full error log: https://gist.github.com/RiQuY/b80fb96dbe66bf00aae21c575633022e

**Information about your version**

The version used is the commit https://github.com/TabbyML/tabby/commit/7ff97a51c3201ea1c5381c1badb78cbef4c05c69 on main branch.

PD: I bisected the error, look at the end of this message.

**Steps to reproduce**

1.  Use OpenSUSE Tumbleweed
2.  Clone the repo and cd to the tabby folder: git clone --recurse-submodules https://github.com/TabbyML/tabby
3. Install the requirements mentioned in https://github.com/TabbyML/tabby/blob/main/CONTRIBUTING.md#local-setup (protobuf-devel)
4. Run `cargo build --features static-ssl`
5. Run `cargo run --features static-ssl --features vulkan serve --model TabbyML/StarCoder2-3B --chat-model TabbyML/WizardCoder-3B --device vulkan --webserver`
6. The command throws an error.

**Information about your system**

```
> inxi -GSC -xx
System:
  Host: localhost.localdomain Kernel: 6.8.2-1-default arch: x86_64 bits: 64
    compiler: gcc v: 13.2.1
  Desktop: KDE Plasma v: 6.0.3 tk: Qt v: N/A wm: kwin_wayland dm: 1: GDM
    2: SDDM note: stopped Distro: openSUSE Tumbleweed 20240404
CPU:
  Info: 8-core model: AMD Ryzen 7 1700X bits: 64 type: MT MCP arch: Zen rev: 1
    cache: L1: 768 KiB L2: 4 MiB L3: 16 MiB
  Speed (MHz): avg: 3045 high: 3442 min/max: 2200/3400 boost: enabled cores:
    1: 2927 2: 2938 3: 2795 4: 2983 5: 3399 6: 2795 7: 2813 8: 3031 9: 3378
    10: 3381 11: 2795 12: 3293 13: 3442 14: 2823 15: 3014 16: 2916
    bogomips: 108608
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: Blackmagic Design Intensity Pro 4K driver: N/A pcie:
    speed: 2.5 GT/s lanes: 4 bus-ID: 04:00.0 chip-ID: bdbd:a139
  Device-2: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    vendor: XFX Pine driver: amdgpu v: kernel arch: RDNA-1 pcie: speed: 16 GT/s
    lanes: 16 ports: active: DP-1,HDMI-A-1 empty: DP-2,DP-3 bus-ID: 0a:00.0
    chip-ID: 1002:731f
  Device-3: Logitech StreamCam
    driver: hid-generic,snd-usb-audio,usbhid,uvcvideo type: USB rev: 3.2
    speed: 5 Gb/s lanes: 1 bus-ID: 6-4.2:4 chip-ID: 046d:0893
  Display: wayland server: X.org v: 1.21.1.12 with: Xwayland v: 23.2.5
    compositor: kwin_wayland driver: X: loaded: modesetting unloaded: fbdev,vesa
    dri: radeonsi gpu: amdgpu display-ID: 0
  Monitor-1: DP-1 model: LG (GoldStar) 27GL850 res: 2560x1440 dpi: 109
    diag: 685mm (27")
  Monitor-2: HDMI-A-1 model: Acer G237HL res: 1920x1080 dpi: 96
    diag: 584mm (23")
  API: EGL v: 1.5 platforms: device: 0 drv: radeonsi device: 1 drv: swrast
    surfaceless: drv: radeonsi wayland: drv: radeonsi x11: drv: radeonsi
    inactive: gbm
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.3 glx-v: 1.4
    direct-render: yes renderer: AMD Radeon RX 5700 XT (radeonsi navi10 LLVM
    18.1.2 DRM 3.57 6.8.2-1-default) device-ID: 1002:731f display-ID: :1.0
  API: Vulkan v: 1.3.280 surfaces: xcb,xlib,wayland device: 0
    type: discrete-gpu driver: N/A device-ID: 1002:731f
```

**Additional context**

I had a previous deployment of Tabby working on my machine on the version https://github.com/TabbyML/tabby/commit/f628f5cacd7b4bb5e35c9dd5a8a1cd1c9defed42, to update it I ran the following commands:

- `cargo clean`
- `git pull`
- `git submodule update --recursive --init`

I bisected the error and I found that the following commit is where the problem originates: 
```
86bbafc9f0d9c277d2df2e57b03807fc86772b1b is the first bad commit
commit 86bbafc9f0d9c277d2df2e57b03807fc86772b1b
Author: Meng Zhang <meng@tabbyml.com>
Date:   Tue Apr 9 21:28:55 2024 -0700

    fix(db): fix oauth credential update logic issue caused by pr/1622 (#1806)
    
    * test: add regression test for two different provider
    
    * fix(db): fix oauth credential update logic issue caused by pr/1622
    
    * [autofix.ci] apply automated fixes
    
    ---------
    
    Co-authored-by: autofix-ci[bot] <114827586+autofix-ci[bot]@users.noreply.github.com>

 .../migrations/0016_merge-oauth-tables.up.sql      |  14 ++++---
 ee/tabby-db/schema.sqlite                          | Bin 139264 -> 143360 bytes
 ee/tabby-db/src/oauth_credential.rs                |  45 ++++++++++++---------
 3 files changed, 36 insertions(+), 23 deletions(-)
```

**Comment by wsxiaoys** [comment]
This is a somewhat expected experience when running Tabby with `cargo run`.

Full context: We manage sqlite migrations with sqlx, but consistency is only maintained from one release version to the next. This means certain migrations might be modified or dropped if there's no easy way to iterate on a new migration.

As a workaround, you might:
1. Delete the `~/.tabby/ee/dev-db.sqlite` directory and set it up again.
2. Run Tabby only with released versions.

**Comment by RiQuY** [comment]
> As a workaround, you might:
> 
>     1. Delete the `~/.tabby/ee/dev-db.sqlite` directory and set it up again.

Thanks, that fixed the issue. I'm using Tabby from main branch because Vulkan is not in the docs yet I assumed that it is an experimental feature and it needs the most recent changes to function properly.

**Comment by wsxiaoys** [comment]
We plan to release vulkan manylinux2014 build starting from v0.10 - if interested, consider give it 0.10-rc a try:
https://github.com/TabbyML/tabby/releases/tag/v0.10.0-rc.2

The binary name is [tabby_x86_64-manylinux2014-vulkan](https://github.com/TabbyML/tabby/releases/download/v0.10.0-rc.2/tabby_x86_64-manylinux2014-vulkan)
