### ISSUE TITLE
docker run failed, container exited immediately

### ISSUE THREAD

**Issue by CurisZhou** [TabbyML/tabby#1850]
**Describe the bug: docker run failed, container exited immediately**
Hey, I used `tabby 0.10.0-dev.0` to build my own docker image (`tabby_server_cuda12_2_v2:latest`), since the version of CUDA on my server is `12.2` (`Driver version is 535.54.03`).  

The system of my server is `RedHat7.9(Centos7)`,  and the server in an `Air-Gapped environment (offline deployment)` . Hence, I had downloaded the `deepseek-coder-6.7b-base.Q8_0.gguf` model file in my server (put it in the `/data/tabby-server/deepseek-coder-6.7b-base/ggml` folder), and put the `tabby.json` file in the `/data/tabby-server/deepseek-coder-6.7b-base` folder.

Then , I used the below docker command to start tabby server container:
`docker run -it --rm --gpus='"device=3"' -p 3620:3620 -e RUST_BACKTRACE=1 -v /data/tabby-server/deepseek-coder-6.7b-base:/data/models/TabbyML/DeepseekCoder-6.7B tabby_server_cuda12_2_v2:latest serve --model /data/models/TabbyML/DeepseekCoder-6.7B --device cuda`

After running above docker command, only outputted below few info, and container exited immediately: 
```
INFO tabby::services::model: crates/tabby/src/services/model/mod.rs:121: Loading model from local path /data/models/TabbyML/DeepseekCoder-6.7B
INFO tabby::serve: crates/tabby/src/serve/mod.rs:123: Starting server, this might takes a few minutes...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: Tesla V100-SXM2-16GB, compute capability 7.0, VMM: yes

```

**Information about your tabby version**
I used `tabby 0.10.0-dev.0` to build my private docker image with `"CUDA_VERSION=12.2.0"` build-arg.

**Information about your GPU**
The GPU type of my server is `V100-SXM2-16GB`, and version of CUDA driver is 12.2.

Is there anything I did wrong?

**Comment by wsxiaoys** [comment]
Hi, could you share the directory structure of your `/data/tabby-server/deepseek-coder-6.7b-base`? For example, execute `find /data/tabby-server/deepseek-coder-6.7b-base` on your server to generate a directory tree.

**Comment by CurisZhou** [comment]
> Hi, could you share the directory structure of your `/data/tabby-server/deepseek-coder-6.7b-base`? For example, execute `find /data/tabby-server/deepseek-coder-6.7b-base` on your server to generate a directory tree.

@wsxiaoys Thank you so much for getting back from you so quickly.

After running `find /data/tabby-server/deepseek-coder-6.7b-base`, it outputs below info:

```
/data/tabby-server/deepseek-coder-6.7b-base
/data/tabby-server/deepseek-coder-6.7b-base/.ipynb_checkpoints
/data/tabby-server/deepseek-coder-6.7b-base/.ipynb_checkpoints/tabby-checkpoint.json
/data/tabby-server/deepseek-coder-6.7b-base/ggml
/data/tabby-server/deepseek-coder-6.7b-base/ggml/.ipynb_checkpoints
/data/tabby-server/deepseek-coder-6.7b-base/ggml/deepseek-coder-6.7b-base.Q8_0.gguf
/data/tabby-server/deepseek-coder-6.7b-base/tabby.json
```

**Comment by wsxiaoys** [comment]
The directory structure is malformed, see https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md for details.

You need to rename `/data/tabby-server/deepseek-coder-6.7b-base/ggml/deepseek-coder-6.7b-base.Q8_0.gguf` to `/data/tabby-server/deepseek-coder-6.7b-base/ggml/q8_0.v2.gguf`

**Comment by CurisZhou** [comment]
> The directory structure is malformed, see https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md for details.
> 
> You need to rename `/data/tabby-server/deepseek-coder-6.7b-base/ggml/deepseek-coder-6.7b-base.Q8_0.gguf` to `/data/tabby-server/deepseek-coder-6.7b-base/ggml/q8_0.v2.gguf`

@wsxiaoys Thanks so much! That works. I ignored there was a naming rule for the model file.
