### ISSUE TITLE
> You could just run `tabby download --model TabbyML/DeepseekCoder-6.7B` to download the model

### ISSUE THREAD

**Issue by hytxx** [TabbyML/tabby#1859]
> You could just run `tabby download --model TabbyML/DeepseekCoder-6.7B` to download the model

I tried, but the download option seems not working without GPU device.

![image](https://github.com/TabbyML/tabby/assets/11705474/2cc61728-3371-459c-9a03-cfeb842b6bdf)

_Originally posted by @akinlong in https://github.com/TabbyML/tabby/issues/1188#issuecomment-1886056681_

**Comment by wsxiaoys** [comment]
Hi, it's responded in https://github.com/TabbyML/tabby/issues/1188#issuecomment-1886073325
