### ISSUE TITLE
docker  model amount

### ISSUE THREAD

**Issue by linpan** [TabbyML/tabby#1873]
i down model form hg, https://huggingface.co/bigcode/starcoderbase-1b, how config docker run amount model path ?

**Comment by linpan** [comment]
Where are models stored in docker?

**Comment by icycodes** [comment]
Hi, @linpan 
> i down model form hg, https://huggingface.co/bigcode/starcoderbase-1b, how config docker run amount model path ?
You can refer to [MODEL_SPEC.md](https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md) for information on setting up a local model. Then specify the local path using `--model` to inform Tabby to use the local model.

> Where are models stored in docker?
By default, the models are stored in `~/.tabby/models` on the host, which should be mounted as `/data/models` in the container. However, if you are using a local model, you can mount it to any path you prefer.
