### ISSUE TITLE
[TAB-613] Signup UX is poor

### ISSUE THREAD

**Issue by deanishe** [TabbyML/tabby#1901]
**Describe the bug**
Tabby has a bunch of rules regarding what it will accept as a password. These rules are kept secret from the user until they break one.

I've just tried — and failed — to sign up on a local instance three times because Tabby didn't like my password. Three different passwords, and a different reason it didn't like each one.

Then I gave up and came here to gripe about it.

It's not fun filling out a form multiple times because the application won't tell me its rules up front.

Please add them to the signup form.

**Information about your version**
0.9.1

**Information about your GPU**
NA

**Additional context**
None.

<sub>[TAB-613](https://linear.app/tabbyml/issue/TAB-613/signup-ux-is-poor)</sub>

**Comment by wsxiaoys** [comment]
Thank you for the suggestion; it's definitely something we should work on improving.

**Comment by wsxiaoys** [comment]
[https://github.com/TabbyML/tabby/blob/0814898b3e1eadf02c4609bfac19a18cd702d51e/ee/tabby-webserver/src/schema/auth.rs#L467](https://github.com/TabbyML/tabby/blob/0814898b3e1eadf02c4609bfac19a18cd702d51e/ee/tabby-webserver/src/schema/auth.rs#L467)

We should added password rule to sign up form

**Comment by wsxiaoys** [comment]
Released in [0.10](https://github.com/TabbyML/tabby/releases/tag/v0.10.0)

<img width="435" alt="image" src="https://github.com/TabbyML/tabby/assets/388154/d62ad03c-f7d5-495c-857b-c3e14587f881">
