### ISSUE TITLE
code completion response return empty text

### ISSUE THREAD

**Issue by azsane** [TabbyML/tabby#1933]
**enviroment** 
gpu : nvidia titan rtx (compute capability 7.5)
os  : ubuntu 22.04 
driver version :550.76 
docker image  version:0.10.0

**problem encounted**
i'm trying to run CodeGemma-7B for code completion,but it doesn't correctly function

directly requesting the /v1/completions api with the default example promt returns response with empty text  field as below
{
   "id":"xxxx",
   "choices":[
     "index":0,
     "text":""
   ]
}

it's quite strange so i just tried another models like starcoder 1 、2
startcoder 1 is ok  but 2 is same with codegemma
it seems that model with tensor type bf16 marked on huggingface doesn't function

but if i run llama.cpp:server-cuda docker , codegemma can generate right result
and on another machine with all enviroment same but gpu changed to a10, tabby also returns the right result

**question**
i can't find any log when tabby is handling request
so here to ask the question
the 8 bit quantized gguf format file , does it require the same compute capability as bf16 requires?

**Comment by wsxiaoys** [comment]
Could you share the command for starting tabby with CodeGemma-7B?

**Comment by azsane** [comment]
the command is simply running the docker

docker run -it --rm --name tabby --gpus all -p 8080:8080 -v /cache/data:/data tabbyml/tabby:0.10.0 serve --model TabbyML/tabby:0.10.0 --device cuda

**Comment by azsane** [comment]
i've tried the command,but the result is the same

**Comment by wsxiaoys** [comment]
It's likely due to the insufficient VRAM on a relatively old GPU. Can you share the output of nvidia-smi?

**Comment by azsane** [comment]
after loading model ,the nvidia-smi outputs as flow
![image](https://github.com/TabbyML/tabby/assets/9714904/3a768fa1-29e0-4ae5-ab4e-90b8833279b0)

**Comment by azsane** [comment]
finally i found that there were some hardware problems with the gpu,it failed in floating calculation but double calcuation without any problem
