### ISSUE TITLE
Tabby VSCode Extension latest v.1.5.3 as of 23Apr2024 bug

### ISSUE THREAD

**Issue by RookyCoder** [TabbyML/tabby#1936]
First of all, such a great repo and product.

I am using **Tabby v0.4.1 with VScode V1.88.1** successfully. However, some or several things before I could run it smoothly.
Spent quite an extensive duration for docker especially CUDA version on docker compose. Not NVIDIA CUDA toolkit, but NVIDIA container toolkit after tons of reading and trial and errorssss.

**Describe the bug**
some confliction(s) lying VScode v1.88.1 dont know which one causes it but once reverts it from v1.5.3 to v0.4.1 ( why this ver? because I have a rig and ran it successfully via VScode v.1.80.1 with Tabby v0.4.1

**Information about your version**

Figuring it out after some trials, finally work it out.
v - 0.9.1

**Information about your GPU**
Wed Apr 24 00:32:23 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 551.78                 Driver Version: 551.78         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti   WDDM  |   00000000:01:00.0  On |                  N/A |
|  0%   37C    P8             17W /  220W |    7966MiB /   8192MiB |      3%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A       352    C+G   ...on\119.0.2151.58\msedgewebview2.exe      N/A      |
|    0   N/A  N/A      2180    C+G   ...\Docker\frontend\Docker Desktop.exe      N/A      |
|    0   N/A  N/A      2232    C+G   ...t.LockApp_cw5n1h2txyewy\LockApp.exe      N/A      |
|    0   N/A  N/A      3420    C+G   ...Programs\Microsoft VS Code\Code.exe      N/A      |
|    0   N/A  N/A      6740    C+G   ...US\ArmouryDevice\asus_framework.exe      N/A      |
|    0   N/A  N/A      8172    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe      N/A      |
|    0   N/A  N/A      8428    C+G   ...nt.CBS_cw5n1h2txyewy\SearchHost.exe      N/A      |
|    0   N/A  N/A     10860    C+G   ...2txyewy\StartMenuExperienceHost.exe      N/A      |
|    0   N/A  N/A     13628    C+G   ...crosoft\Edge\Application\msedge.exe      N/A      |
|    0   N/A  N/A     14216    C+G   ...5n1h2txyewy\ShellExperienceHost.exe      N/A      
+----------------------------------------------------------------------------------------
---------------------------------------------------------------+
**Additional context**

Other than that nothing else, haven't discovered it or realized it as a bug.
Sorry for my English, but try my best to explain what was it. Good project, so have to report it even though my bad expression.

**Comment by wsxiaoys** [comment]
Hello, thank you for the bug report. Could you please try the following steps:

1. Upgrade to version 0.10. Consider using the Windows binary distribution directly to avoid the hassle associated with Docker (CUDA 12). You can find it here: https://github.com/TabbyML/tabby/releases/tag/v0.10.0

2. Please share whether you can generate a code completion result using `https://localhost:8080/swagger-ui`. Preferably, provide a recording of the process using jam.dev.

**Comment by RookyCoder** [comment]
> Hello, thank you for the bug report. Could you please try the following steps:
> 
> 1. Upgrade to version 0.10. Consider using the Windows binary distribution directly to avoid the hassle associated with Docker (CUDA 12). You can find it here: https://github.com/TabbyML/tabby/releases/tag/v0.10.0
> 2. Please share whether you can generate a code completion result using `https://localhost:8080/swagger-ui`. Preferably, provide a recording of the process using jam.dev.



> Hello, thank you for the bug report. Could you please try the following steps:
> 
> 1. Upgrade to version 0.10. Consider using the Windows binary distribution directly to avoid the hassle associated with Docker (CUDA 12). You can find it here: https://github.com/TabbyML/tabby/releases/tag/v0.10.0
> 2. Please share whether you can generate a code completion result using `https://localhost:8080/swagger-ui`. Preferably, provide a recording of the process using jam.dev.

First of all, thanks for get in touch but i have tried it and hard for me to understand how to do it esp step 1. I tried download the corresponding msvc.exe and executed it. A blink of a cmd window popped up but instantly closed then nothing happened, After i restarted the local server and found that the tabby version still the same. I honestly dont know what the binary is and how to do it properly. Please advise.

> 2. For this one, i checked both version in different scenario and executed the verification procedures as in this link of the guide. https://tabby.tabbyml.com/docs/extensions/troubleshooting/#verify-tabby-server-status
