### ISSUE TITLE
how can i upload gguf file to run tabby rather than download from huggingface?

### ISSUE THREAD

**Issue by HaoGuo98** [TabbyML/tabby#2000]
**Please describe the feature you want**
i want to use tabby in linux server,but the server can not visit huggingface. I use the guide command of docker install and shows Failed to fetch model '<any model>' due to 'Failed to fetch url...   so i  download the gguf file. which directory should i put the gguf file in? what command should i use to start the server?

**Additional context**
I find the huggingface/tabby project seems to be different to https://github.com/TabbyML/tabby/issues/710. it seems like the project now provide gguf file directly.
---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
You might follow https://tabby.tabbyml.com/blog/2024/03/25/deploy-tabby-in-air-gapped-environment-with-docker instructions to build an image with model predownloaded.

**Comment by HaoGuo98** [comment]
thanks i visit modelscope instead. using command: docker run -it --gpus all -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby  serve --model TabbyML/StarCoder-1B --device cuda

by the way, how to stop the server? ctrl+c seems not work.

**Comment by HaoGuo98** [comment]
> thanks i visit modelscope instead. using command: docker run -it --gpus all -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda
> 
> by the way, how to stop the server? ctrl+c seems not work.

**Comment by user-vm** [comment]
> thanks i visit modelscope instead. using command: docker run -it --gpus all -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda
> 
> by the way, how to stop the server? ctrl+c seems not work.

I just do this by killing all docker processes in a new terminal with `docker kill $(docker ps -q)`. If you have multiple docker containers running, you can find the correct one via `docker ps`. This is quite clunky. There was a request in #830 to fix Ctrl-C but it was closed as not planned.
The binary releases (non-docker) do not have this issue.

**Comment by wsxiaoys** [comment]
Right - this issue is mostly related to Docker and signal handling, and we have a sufficiently good workaround: using 'docker kill'.
