### ISSUE TITLE
Support for corporate proxy in VS Code extension 

### ISSUE THREAD

**Issue by eliasfroehner** [TabbyML/tabby#2086]
I would like to have corporate proxy support. Otherwise, I cannot use it in my company.

Additional context
Many companies use corporate proxies to monitor and control the internet traffic of their employees. Without proxy support, I unfortunately cannot use the product in my work environment. Implementing a proxy feature would allow me to use the product in the office as well.

**Comment by wsxiaoys** [comment]
Tabby can be deployed on-prem with no access to internet. Would that be an alternative?

https://tabby.tabbyml.com/blog/2024/03/25/deploy-tabby-in-air-gapped-environment-with-docker/

**Comment by eliasfroehner** [comment]
Hi,
unfortunately, that won't work for me. The Tabby server is installed on a cloud server, and I need to access it through the VS Code extension. The proxy is in between, so an on-premise deployment is not a viable alternative in my case. Please accept my apologies for not being clear enough in my initial request.

**Comment by wsxiaoys** [comment]
Added @icycodes to comment, also noticed this is documented at https://tabby.tabbyml.com/docs/extensions/troubleshooting/#proxy-settings

**Comment by eliasfroehner** [comment]
Hi @wsxiaoys,
thank you for pointing me to https://tabby.tabbyml.com/docs/extensions/troubleshooting/#proxy-settings.  I have unfortunately used several configurations with Nginx as a reverse proxy, but I could not get it to work. I would find it very helpful if an example configuration was included in the documentation for a reverse proxy. 

My setup is:
client (VS Code extension) <-> HTTP corporate Proxy (Port 4900 without authentication) <-> cloud server (tabby server)

Thank you very much.

**Comment by wsxiaoys** [comment]
Being addressed in https://github.com/TabbyML/tabby/issues/2893

**Comment by wsxiaoys** [comment]
released in vscode 1.10.2
