### ISSUE TITLE
Configurable gitlab `host`

### ISSUE THREAD

**Issue by LLukas22** [TabbyML/tabby#2109]
**Please describe the feature you want**

It would be a nice addition if the GitLab host were configurable, to easily point the Tabby server to a self-hosted GitLab instance.

**Additional context**

Since it is unlikely that a single Tabby instance needs to access both a self-hosted and the public GitLab instance, it would probably be enough to make the host configurable via, for example, a `GITLAB_HOST` environment variable and simply query the value when the `GitlabBuilder` is created [here](https://github.com/TabbyML/tabby/blob/main/ee/tabby-webserver/src/service/background_job/gitlab.rs#L183).

---
Please reply with a 👍 if you want this feature.

**Comment by boxbeam** [comment]
This is planned! The feature will most likely be rolling out with the next release (0.12).

**Comment by wsxiaoys** [comment]
Released in 0.12
