### ISSUE TITLE
Tabby server requires authentication, but the current token is invalid.

### ISSUE THREAD

**Issue by danny-su** [TabbyML/tabby#2131]
**Describe the bug**
<img width="800" alt="image" src="https://github.com/TabbyML/tabby/assets/12178855/1eab9954-d6a1-4a1c-aba5-f2f5f6acf958">
I didn't set any token. Even if I set a token, it didn't work as well.

**Information about your version**
tabby 0.11.1

**Information about your GPU**
macOS MPS

**Additional context**
<img width="332" alt="image" src="https://github.com/TabbyML/tabby/assets/12178855/b7d9a841-c488-4c3e-aa99-fd36f13aa5a3">

**Comment by icycodes** [comment]
Hi, @danny-su
You can access http://127.0.0.1:8088/ in the browser to get your token. The web server feature (with authentication) is enabled by default after version [0.11](https://github.com/TabbyML/tabby/blob/main/CHANGELOG.md#v0110-05102024).

**Comment by danny-su** [comment]
@icycodes Thanks.

**Comment by strawberrymelonpanda** [comment]
FWIW, I just wound up here too.

**Comment by icycodes** [comment]
Thank you for your suggestions. I have make some updates to the documentation in #2389
