### ISSUE TITLE
Err(StreamError("Invalid header value: \"application/json\""))

### ISSUE THREAD

**Issue by chenglu66** [TabbyML/tabby#2184]
**Describe the bug**

**Information about your version**
Please provide output of `tabby --version`

**Information about your GPU**
Please provide output of `nvidia-smi`

**Additional context**

**Comment by chenglu66** [comment]
> Hi, please provide detailed steps to reproduce the issue, eg command you used to start tabby.
OK 
cargo run serve --device experimental-http \
  --model '{"kind": "openai", "model_name": "codellama/CodeLlama-70b-Instruct-hf", "api_endpoint": "xxxxxx:8080/v1", "prompt_template": "<prefix>"}'

**Comment by Jarlene** [comment]
@chenglu66 I have the  same issue, how to solve this problem
