### ISSUE TITLE
how to buy a license,price?

### ISSUE THREAD

**Issue by augushong** [TabbyML/tabby#2217]
**Please describe the feature you want**

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by gyxlucy** [comment]
Hi Augus, thanks for your interest in Tabby Enterprise!
Currently purchasing enterprise license goes through our sales channel - feel free to [schedule a call](https://cal.com/gyxlucy/30-mins-call) and happy to chat further.
