### ISSUE TITLE
Feature send command to all tabs

### ISSUE THREAD

**Issue by Ox0400** [TabbyML/tabby#2218]
**Please describe the feature you want**
send command to all ssh tabs.

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Guess you want https://github.com/eugeny/tabby ?

**Comment by Ox0400** [comment]
> Guess you want https://github.com/eugeny/tabby ?

ohhhhh   so sorry ...
