### ISSUE TITLE
Provide more info when config.toml of tabby is invalid

### ISSUE THREAD

**Issue by SpeedCrash100** [TabbyML/tabby#2228]
If the config file of tabby (server side) is invalid or not exists then user will not get any warning or error about that. Usage of unwrap_or_default [here](https://github.com/TabbyML/tabby/blob/62498bea561969e949303dcde7d86ed936a1bc27/crates/tabby/src/main.rs#L71C33-L71C50) should be replaced with some printing.

---
Please reply with a 👍 if you want this feature.

**Comment by darknight** [comment]
Hi @wsxiaoys I'll take this

**Comment by wsxiaoys** [comment]
Release in 0.13
