### ISSUE TITLE
Self Hosting Document Not Right?

### ISSUE THREAD

**Issue by cfancc** [TabbyML/tabby#224]
**Describe the bug**
I'm running tabby server in Mac M1, followed `https://tabbyml.github.io/tabby/docs/self-hosting/apple` guide, download binary from [tabby_aarch64-apple-darwin](https://github.com/TabbyML/tabby/releases/download/latest/tabby_aarch64-apple-darwin), found `tabby serve model --models TabbyML/T5P-220M` not work for me, so I changed to: `tabby serve --models TabbyML/T5P-220M`, it started, but got these error

```
Failed to fetch model due to 'Invalid url: https://huggingface.co/TabbyML/T5P-220M/resolve/main/ctranslate2/vocabulary.txt', is 'TabbyML/T5P-220M' a valid model id?
```

**Comment by wsxiaoys** [comment]
Thank you for reporting the bug. I'm happy to let you know that it has been resolved in this pull request: https://github.com/TabbyML/tabby/pull/225.

Furthermore, a new release with the bug fix has been made available in this repository: https://github.com/TabbyML/tabby/releases/tag/latest.

If you have any further questions or encounter additional issues, please don't hesitate to reach out to the TabbyML community for assistance.
