### ISSUE TITLE
Prompt tokens in suggestions

### ISSUE THREAD

**Issue by Zhincore** [TabbyML/tabby#2277]
**Describe the bug**
After updating the Tabby Docker container recently, most of the suggestions end with the following string: 
```
<file_sep><fim_prefix><fim_suffix>
```
Sometimes there is little more random code after that. 

**Information about your version**
`tabby 0.11.1`

**Information about your GPU**
```
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060        Off |   00000000:26:00.0  On |                  N/A |
|  0%   53C    P5             22W /  170W |    4489MiB /  12288MiB |     15%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
```

**Additional context**
- Usually happens on single-line suggestions
- Both VSCode and IntelliJ addons
- Model StarCoder2-3B, haven't had issues before

**Comment by wsxiaoys** [comment]
Hi - could you check `~/.tabby/events` and share a few log records of problematic completion?

**Comment by wsxiaoys** [comment]
Thanks for the info - this shall be fixed in the ongoing 0.12 release

**Comment by rudiservo** [comment]
This has happened to me before has well in Lazyvim, specially while trying to write comments.

`"choices":[{"index":0,"text":"// add 2 declaration<file_sep><fim_prefix><fim_suffix>nterface;"}]}}}`

this is supposed to suggest "declarationInterface"

I have added context from git projects.

**Comment by wsxiaoys** [comment]
Yes, it's very likely a regression related to Starcoder2. Consider giving [v0.12.0-rc.2](https://github.com/TabbyML/tabby/releases/tag/v0.12.0-rc.2) a try to see if it fixes the issue for you.

**Comment by rudiservo** [comment]
@wsxiaoys sure, can you update the docker for ROCm with rc2?

**Comment by Zhincore** [comment]
> Consider giving [v0.12.0-rc.2](https://github.com/TabbyML/tabby/releases/tag/v0.12.0-rc.2) a try to see if it fixes the issue for you.

Updating to docker image `tabbyml/tabby:0.12.0-rc.2` does not seem to have fixed it :/
![image](https://github.com/TabbyML/tabby/assets/21307300/b4c17987-3ded-494a-b661-5e7618956594)

**Comment by wsxiaoys** [comment]
Sending out https://github.com/TabbyML/tabby/pull/2311 to explicit fix - this will comes into rc4
