### ISSUE TITLE
mistral FIM completion api support

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2287]
**Please describe the feature you want**

Following the recent refactoring of the HttpBackend, we now have the capability to support the Mistral HTTP API:
- [x] Completion. For instance, see: https://github.com/TabbyML/tabby/blob/main/crates/http-api-bindings/src/completion/llama.rs

This will allow us utilize codestral api provided by mistral ai.
**Additional context**
https://docs.mistral.ai/api/#operation/createChatCompletion

---
Please reply with a 👍 if you want this feature.

**Comment by Phylliida** [comment]
FYI codestral encodes FIM requests like this:
```
[BOS_TOKEN][SUFFIX]suffix prompt[PREFIX]prefix prompt
```
Where 
```
BOS is token id 1
SUFFIX is token is 13
PREFIX is token is 11
```

**Comment by wsxiaoys** [comment]
fixed in https://github.com/TabbyML/tabby/releases/tag/v0.12.0 release
