### ISSUE TITLE
adapt `--chat-template` parameter of `llama-server`

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2289]
**Please describe the feature you want**

llama-server provides native support of chat template, we shall utilizing it and get rid of jinja dependencies, and get rid of `ChatCompletionImpl` completly.

References:
1. https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md
2. https://github.com/TabbyML/tabby/blob/e8dec21e556eaefe78eb43848beb8d64897ee4a6/crates/tabby/src/services/model/chat.rs#L39

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by darknight** [comment]
Hi @wsxiaoys I'll take this, thanks.

**Comment by wsxiaoys** [comment]
Released in 0.13
