### ISSUE TITLE
followed the guide for Mac M1/M2 

### ISSUE THREAD

**Issue by shinners1** [TabbyML/tabby#230]
I ran the code as described in the guide(https://tabbyml.github.io/tabby/docs/self-hosting/apple), but I got this error. 

`zsh: command not found: tabby` 

I actually expected to get this error, but the guide is confusing. Is it correct that tabby will run if I execute the steps below? 

```
1. Download the tabby binary from the Release page here.

2. Run tabby --help to verify successful installation.

3. Start the server with: `tabby serve model --models TabbyML/T5P-220M`

```

**Comment by wsxiaoys** [comment]
Hi @shinners1 ,

After downloading the binary, have you:
1. change the downloaded binary to `tabby`
2. put it in one a directory of your $PATH environment variables (for many people, it'll be `$HOME/.bin`)
3. Unlock its execution through security settings?

**Comment by shinners1** [comment]
Thank you for quick response! 


I followed this procedure, and finally got it  : 

1. I changed the downloaded tabby file name from `tabby_aarch64-apple-darwin` to just `tabby` 
2. added tabby path to PATH environment (export PATH=$PATH:/to/my/tabby/path) 
3. changed file access setting : `chmod 755 tabby` 
4. then ran this code `tabby serve --model TabbyML/T5P-220M`
