### ISSUE TITLE
cant download it

### ISSUE THREAD

**Issue by Eisbaerboy** [TabbyML/tabby#2301]
Following a guide, pasting in cmd:

(guide: https://www.youtube.com/watch?v=UaCzXLuEE1Y)

docker run --entrypoint /opt/tabby/bin/tabby-cpu -it \
  -p 8080:8080 -v C:\Daten\Models\.tabby:/data \
  tabbyml/tabby serve --model StarCoder-3B
  
Result:

C:\Users\x>  -p 8080:8080 -v C:\Daten\Models\.tabby:/data \
Der Befehl "-p" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.

(The command "-p" is either misspelled or
could not be found.)

i have an amd gpu so im tryna use cpu.

**Comment by wsxiaoys** [comment]
Hi - please follow the installation guide here: https://tabby.tabbyml.com/docs/quick-start/installation/windows/
