### ISSUE TITLE
Add codestral benchmark to leaderboard

### ISSUE THREAD

**Issue by jmservier** [TabbyML/tabby#2325]
Dear,
Thanks you for your awesome works,
Could you add  to the benchnark this model : https://mistral.ai/news/codestral/ ?
your benchmark: https://leaderboard.tabbyml.com/

![image](https://github.com/TabbyML/registry-tabby/assets/147592779/5fdfec9f-a9f2-4320-b263-457038bb8024)

**Comment by wsxiaoys** [comment]
Done!
