### ISSUE TITLE
Unable to start normally, it stays on DEBUG tabby::serve: crates/tabby/src/serve.rs:127: Starting server, this might take a few minutes...

### ISSUE THREAD

**Issue by 5bug** [TabbyML/tabby#2326]
The latest main branch

macos

Unable to start normally, it stays on DEBUG tabby::serve: crates/tabby/src/serve.rs:127: Starting server, this might take a few minutes...
After debugging, it was found that it could not start normally at let embedding = embedding::create(config.model.embedding.as_ref()).await; in crates/tabby/src/serve.rs.

**Comment by wsxiaoys** [comment]
Thanks for reporting the issue, fixing in #2327
