### ISSUE TITLE
Local Git repository support

### ISSUE THREAD

**Issue by 1e100** [TabbyML/tabby#2335]
**Please describe the feature you want**

Currently all repository access is by URL, and it requires that there is a server on the other end. That can be problematic with e.g. deployments where there's no network access, as well as with deployments where PATs are not enabled by admin. It is also not really necessary, as the complete replica of the repo usually already exists locally (except when sparse branch checkout is used). 

I would like local Git repository support as well. This could take the form of cloning a branch from the repository locally (to avoid operating on files as they are being changed). Seems like largely the same code could be re-used, only the way the cloning is done would change.

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Though not explicitly documented, this has been supported for a while: https://github.com/TabbyML/tabby/blob/ddccfee15ddff59a6598f3192529a1020ebf5585/CHANGELOG.md?plain=1#L142

**Comment by 1e100** [comment]
Confirmed, this works!
