### ISSUE TITLE
Empty lines when copy part of code blocks in Playground

### ISSUE THREAD

**Issue by SpeedCrash100** [TabbyML/tabby#2347]
**Describe the bug**
Empty lines are inserted between each line of code, when selecting code manually instead using "Copy" button.

Consider we have this code in Playground. I've selected code which one I want to copy.
![Example code](https://github.com/TabbyML/tabby/assets/57725022/351ca3fc-7054-4195-98c1-93fed860ffde)

Using "Copy" button produces this upon paste:
```rust
use rand::Rng;

fn generate_random_variable() -> f64 {
    let mut rng = rand::thread_rng();
    rng.gen::<f64>()
}

fn main() {
    println!("{}", generate_random_variable());
}
```

It is formatted well, but copies all the code block.
Using Ctrl+C on selected code and pasting it somewhere, produces:
```rust
fn generate_random_variable() -> f64 {

    let mut rng = rand::thread_rng();

    rng.gen::<f64>()

}
```

**Information about your version**
Tabby version is [v0.12.0-rc.4](https://github.com/TabbyML/tabby/releases/tag/v0.12.0-rc.4) built myself for docker using `docker/Dockerfile.rocm`

**Information about your GPU**
AMD RX 6700xt, UI related, so should not matter.

**Additional context**
 * Browser is Firefox 126.0.1 Flatpak version, seems like Chromium based browsers are unaffected

**Comment by wwayne** [comment]
Hi @SpeedCrash100, Thanks for the report.
After some investigation, I found it occurs only in Firefox.
As a workaround, I recommend using the copy button in the top-right corner instead of pressing ctrl+c when using Firefox.
