### ISSUE TITLE
Windows .exe file unavailable since version v0.12.0-rc.0

### ISSUE THREAD

**Issue by tups** [TabbyML/tabby#2358]
**Describe the bug**
Since version v0.12.0-rc.0, .exe files are no longer available in releases, contrary to the documentation: https://tabby.tabbyml.com/docs/quick-start/installation/ windows/
We only find zip files that contain two binaries llama-server and tabby

**Information about your version**
v0.12.0

**Additional context**
Is there a new way to run binaries on Windows?

**Comment by wsxiaoys** [comment]
fixing in https://github.com/TabbyML/tabby/pull/2361

as a workaround, you might rename the binary file with `.exe` suffix

**Comment by tups** [comment]
Unfortunately, just renaming the tabby and llama-server files doesn't work:
![image](https://github.com/TabbyML/tabby/assets/868611/5b414f05-205c-492e-9e89-fa53c7a670a0)
![image](https://github.com/TabbyML/tabby/assets/868611/72e3cc69-fbc0-4a08-9390-a1a3c842c8ff)

I will wait for the next build

**Comment by wsxiaoys** [comment]
as the error log shows, could you turn on following environment variable and share the output?
```
RUST_LOG=debug RUST_BACKTRACE=full ...
```

**Comment by woutermans** [comment]
I have the same issue. Here is my log with those variables enabled.
![image](https://github.com/TabbyML/tabby/assets/28774520/cdf7a223-e63c-481c-8d7b-3c973506e8c8)

**Comment by woutermans** [comment]
It seems that changing this code in supervisor.rs fixes the issue for me:

`let server_binary = std::env::current_exe()
                    .expect("Failed to get current executable path")
                    .parent()
                    .expect("Failed to get parent directory")
                    .join(&binary_name)
                    .display()
                    .to_string();
                    //+ std::env::consts::EXE_SUFFIX; Removed this line because .exe is already present now`

**Comment by wsxiaoys** [comment]
gotcha - this should be a bug for windows - when invoking llama-server subprocess, an `.exe` suffix is needed.

assigning @boxbeam to take a look

**Comment by boxbeam** [comment]
@woutermans I don't use windows, so I don't have a way of verifying this fix - if you could open a PR with your patch and show it working, that would be appreciated

**Comment by woutermans** [comment]
I created a PR #2377 . Please tell me if you want more information.

**Comment by woutermans** [comment]
Here is my PR: #2378 I hope I provided enough information.

**Comment by wsxiaoys** [comment]
Released in https://github.com/TabbyML/tabby/releases/tag/v0.12.1-rc.0
