### ISSUE TITLE
Abitity view reposotories from webui while using config.toml

### ISSUE THREAD

**Issue by bioinfornatics** [TabbyML/tabby#2360]
Dear following the discussion from [Slack](https://tabbyml.slack.com/archives/C05CWLZ0Y85/p1717664476951169?thread_ts=1717660959.924459&cid=C05CWLZ0Y85) with @wsxiaoys .

It would be great that webui used data from config.toml

![image](https://github.com/TabbyML/tabby/assets/491720/51937d4b-5e02-4ac3-a75f-5b531df43566)

Actually, after to have generated the `config.toml` progammatically (~200 repos) and launch the scheduler as following
```
tabby scheduler --now --token 'xxx'
```
The index is done but the webui can not use it, only completion feature can.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
This shall be doable if we extend repos from config.toml in [repository_list](https://github.com/TabbyML/tabby/blob/beb7d90ee13eca4bd33d7021e28cfc4b3b459bd1/ee/tabby-schema/src/schema/mod.rs#L704)

cc @boxbeam

**Comment by wsxiaoys** [comment]
done in 0.13, it's now possible to browse config.toml based repositories in Code Browser
