### ISSUE TITLE
Tabby scheduler no longer working with this last release

### ISSUE THREAD

**Issue by ainub** [TabbyML/tabby#2364]
]# tabby scheduler --now
WARN tabby_scheduler: crates/tabby-scheduler/src/lib.rs:65: No embedding configuration found, skipping scheduler...

**Comment by wsxiaoys** [comment]
The default logic for embedding should be implemented for schedule as well:

https://github.com/TabbyML/tabby/blob/beb7d90ee13eca4bd33d7021e28cfc4b3b459bd1/crates/tabby/src/serve.rs#L401
