### ISSUE TITLE
mac download TabbyML/T5P-220M failed

### ISSUE THREAD

**Issue by ToMatrgod** [TabbyML/tabby#238]
Hi, I'm running tabby in Mac M1, and i got the latest release bin file, but still got these error:

2023-06-14T09:41:51.700083Z ERROR tabby::serve: crates/tabby/src/serve/mod.rs:116: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/tabby.json): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?

**Comment by wsxiaoys** [comment]
Hi @ToMatrgod 

Could you please double-check if your network environment allows proper access to Hugging Face?

**Comment by ToMatrgod** [comment]
Hi, @wsxiaoys 
How is network considered accessible?
I can access this site as follows:
![image](https://github.com/TabbyML/tabby/assets/17420307/58d5aca1-e635-4858-b4e8-496dd3931925)

**Comment by ToMatrgod** [comment]
Hi @wsxiaoys 
I turned on the vpn network acceleration, then some successes and some failures 

Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/tabby.json
  [00:00:00] [###################################################################################################################################################################] 39B/39B (41.30 KiB/s, 0s)
Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/tokenizer.json
  [00:00:00] [##########################################################################################################################################################] 1.31 MiB/1.31 MiB (1.66 MiB/s, 0s)Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/ctranslate2/config.json
  [00:00:00] [#################################################################################################################################################################] 162B/162B (67.61 KiB/s, 0s)Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/ctranslate2/shared_vocabulary.txt
  [00:00:00] [####################################################################################################################################################] 258.50 KiB/258.50 KiB (606.42 KiB/s, 0s)2023-06-15T02:20:59.332273Z ERROR tabby::serve: crates/tabby/src/serve/mod.rs:116: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/ctranslate2/model.bin): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?

so, Is it my bad internet?

**Comment by izerok** [comment]
After I had downloaded and successfully run it for the first time, I closed it and tried to run it again. I found that it also requires a connection to Hugging Face.

**Comment by izerok** [comment]
After I had downloaded and successfully run it for the first time, I closed it and tried to run it again. I found that it also requires a connection to Hugging Face.
@wsxiaoys

**Comment by izerok** [comment]
> Hi @wsxiaoys I turned on the vpn network acceleration, then get some successes and some failures
> 
> Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/tabby.json [00:00:00] [###################################################################################################################################################################] 39B/39B (41.30 KiB/s, 0s) Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/tokenizer.json [00:00:00] [##########################################################################################################################################################] 1.31 MiB/1.31 MiB (1.66 MiB/s, 0s)Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/ctranslate2/config.json [00:00:00] [#################################################################################################################################################################] 162B/162B (67.61 KiB/s, 0s)Downloaded /Users/xyn/.tabby/models/TabbyML/T5P-220M/ctranslate2/shared_vocabulary.txt [00:00:00] [####################################################################################################################################################] 258.50 KiB/258.50 KiB (606.42 KiB/s, 0s)2023-06-15T02:20:59.332273Z ERROR tabby::serve: crates/tabby/src/serve/mod.rs:116: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/ctranslate2/model.bin): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?
> 
> so, Is it my bad internet?

Maybe you need 'Clash for Windows' to connect it.https://github.com/Fndroid/clash_for_windows_pkg

**Comment by wsxiaoys** [comment]
Hi @izerok

Nice catch, this will be addressed in #241

**Comment by izerok** [comment]
> Hi @izerok
> 
> Nice catch, this will be addressed in #241
Thanks your response @wsxiaoys 
I have a model cache, but it also seems to fail to run successfully. Furthermore, even when I turn off the network, it still cannot run.
ERROR tabby::serve: crates/tabby/src/serve/mod.rs:86: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/tokenizer.json): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?

**Comment by izerok** [comment]
> Hi @izerok
> 
> Nice catch, this will be addressed in #241
----
Thanks your response @wsxiaoys
I have a model cache, but it also seems to fail to run successfully while my network cannot access Hugging Face. Furthermore, even when I turn off the network, it still cannot run.
ERROR tabby::serve: crates/tabby/src/serve/mod.rs:86: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/tokenizer.json): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?

**Comment by wsxiaoys** [comment]
> > Hi @izerok
> > Nice catch, this will be addressed in #241
> 
> Thanks your response @wsxiaoys I have a model cache, but it also seems to fail to run successfully while my network cannot access Hugging Face. Furthermore, even when I turn off the network, it still cannot run. ERROR tabby::serve: crates/tabby/src/serve/mod.rs:86: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/tokenizer.json): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?

Hi, once #241 is released, the model serving can be run fully in offline mode. The next nightly build release is scheduled to happen in approximately 10 hours. You can find more information about it here: https://github.com/TabbyML/tabby/actions/workflows/docker.yml

**Comment by ToMatrgod** [comment]
I trigger that error link url, model.bin can download. why does the command download failed? @wsxiaoys 
![image](https://github.com/TabbyML/tabby/assets/17420307/6ddbcbaf-a158-4867-8418-facf929f330c)

**Comment by izerok** [comment]
> > > Hi @izerok
> > > Nice catch, this will be addressed in #241
> > 
> > 
> > Thanks your response @wsxiaoys I have a model cache, but it also seems to fail to run successfully while my network cannot access Hugging Face. Furthermore, even when I turn off the network, it still cannot run. ERROR tabby::serve: crates/tabby/src/serve/mod.rs:86: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/tokenizer.json): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?
> 
> Hi, once #241 is released, the model serving can be run fully in offline mode. The next nightly build release is scheduled to happen in approximately 10 hours. You can find more information about it here: https://github.com/TabbyML/tabby/actions/workflows/docker.yml

---
It's successfully running now , Thanks.

**Comment by 583175694** [comment]
> 

How to solve it? I am still
`ERROR tabby::serve: crates/tabby/src/serve/mod.rs:116: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/ctranslate2/shared_vocabulary.txt): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?`

**Comment by 583175694** [comment]
> > > > Hi 嗨 @izerok
> > > > Nice catch, this will be addressed in 
> > > > 接得好，这个问题会在 #241
> > > 
> > > 
> > > Thanks your response @wsxiaoys I have a model cache, but it also seems to fail to run successfully while my network cannot access Hugging Face. Furthermore, even when I turn off the network, it still cannot run. ERROR tabby::serve: crates/tabby/src/serve/mod.rs:86: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/tokenizer.json): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?谢谢你的回复@wsxiaoys 我有一个模型缓存，但它似乎也无法成功运行，而我的网络无法访问拥抱脸。此外，即使我关闭了网络，它仍然不能运行。错误 tabby: : service: crates/tabby/src/service/mod.rs: 86: 由于“错误发送 url 请求( https://huggingface.co/TabbyML/T5P-220M/resolve/main/tokenizer.json ) : 错误尝试连接: 连接通过错误关闭”，未能获取模型，“ TabbyML/T5P-220M”是否是有效的模型 id？
> > 
> > 
> > Hi, once #241 is released, the model serving can be run fully in offline mode. The next nightly build release is scheduled to happen in approximately 10 hours. You can find more information about it here: https://github.com/TabbyML/tabby/actions/workflows/docker.yml嗨，一旦 # 241发布，模型服务可以完全运行在脱机模式。下一个每晚发布的版本预计将在大约10个小时后发布。你可在此找到更多有关 https://github.com/tabbyml/tabby/actions/workflows/docker.yml 的资料
> 
> It's successfully running now , Thanks.
> 
> 现在已经成功运行了，谢谢。

How to solve it? I am still
```
ERROR tabby::serve: crates/tabby/src/serve/mod.rs:116: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/T5P-220M/resolve/main/ctranslate2/shared_vocabulary.txt): error trying to connect: connection closed via error', is 'TabbyML/T5P-220M' a valid model id?
```

**Comment by wsxiaoys** [comment]
Resolve the issue, as the majority of individuals experiencing this problem are simply facing network issues.
