### ISSUE TITLE
Code Browser doesn't handle gitlab project with multiple nested organization properly

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2401]
**Describe the bug**
See discussion at https://github.com/TabbyML/tabby/discussions/2400

**Information about your version**
0.12

**Comment by wsxiaoys** [comment]
cc @factor3

**Comment by liangfung** [comment]
@factor3 This bug is expected to be fixed in the upcoming 0.13.0 RC release scheduled for June 21st. 
The RC version will include an ongoing PR #2232  that optimizes the URL pattern of code browser. We plan to handle the case of multiple nested organizations within this PR.

**Comment by liangfung** [comment]
> Will the RC be in a docker container on the 21st? I will want to download and try it as soon as possible. 

Yes, it will be

**Comment by wsxiaoys** [comment]
released in 0.13
