### ISSUE TITLE
Offline install Model is always loading

### ISSUE THREAD

**Issue by lcwxz1989** [TabbyML/tabby#2402]
Describe the problem:
metal:
system OS: ubuntu 20.04
gpu: nvidia Geforce RTX 2060
cuda: 12.3
cuda driver version: 545.23.08
env: offline, no internet
docker env:
put models into /models

To Reproduce:
cpu percent: 100%

![image](https://github.com/TabbyML/tabby/assets/5106890/3aa48439-6063-4657-b60d-871297112446)
![image](https://github.com/TabbyML/tabby/assets/5106890/1d2e2040-2665-41df-9ce8-98898b5e7cc6)

**Comment by wsxiaoys** [comment]
Hi - could you provide the version number of tabby? Have you try using tabby 0.12?

**Comment by wwayne** [comment]
Hi @lcwxz1989 I tried it on my computer and it is working, let me share my steps for your reference
1. I donwload gguf from `https://huggingface.co/TheBloke/deepseek-coder-1.3b-base-GGUF/resolve/main/deepseek-coder-1.3b-base.Q8_0.gguf`
2. Go to `.tabby/models/TabbyML`, I create a new folder `DeepseekCoder-1.3B`
3. inside `TabbyML/DeepseekCoder-1.3B`, I create a `tabby.json`, the content is 
```json
{"name":"DeepseekCoder-1.3B","prompt_template":"<｜fim▁begin｜>{prefix}<｜fim▁hole｜>{suffix}<｜fim▁end｜>","urls":["https://huggingface.co/TheBloke/deepseek-coder-1.3b-base-GGUF/resolve/main/deepseek-coder-1.3b-base.Q8_0.gguf"],"sha256":"9fcdcb283ef5b1d80ec7365b307c1ceab0c0f8ea079b49969f7febc06a11bccd"}
```
4. Inside `TabbyML/DeepseekCoder-1.3B`, create a new folder `ggml` and put the gguf file into it, rename it to `model.gguf`
5. In the offline environment, I run `tabby serve --model DeepseekCoder-1.3B --device cuda`, and after a while, I can see it is running

![1](https://github.com/TabbyML/tabby/assets/5305874/7172e92a-7a09-46ec-9f68-a2250a8bfdfe)

**Comment by lcwxz1989** [comment]
> Hi @lcwxz1989 I tried it on my computer and it is working, let me share my steps for your reference
> 
> 1. I donwload gguf from `https://huggingface.co/TheBloke/deepseek-coder-1.3b-base-GGUF/resolve/main/deepseek-coder-1.3b-base.Q8_0.gguf`
> 2. Go to `.tabby/models/TabbyML`, I create a new folder `DeepseekCoder-1.3B`
> 3. inside `TabbyML/DeepseekCoder-1.3B`, I create a `tabby.json`, the content is
> 
> ```json
> {"name":"DeepseekCoder-1.3B","prompt_template":"<｜fim▁begin｜>{prefix}<｜fim▁hole｜>{suffix}<｜fim▁end｜>","urls":["https://huggingface.co/TheBloke/deepseek-coder-1.3b-base-GGUF/resolve/main/deepseek-coder-1.3b-base.Q8_0.gguf"],"sha256":"9fcdcb283ef5b1d80ec7365b307c1ceab0c0f8ea079b49969f7febc06a11bccd"}
> ```
> 
> 4. Inside `TabbyML/DeepseekCoder-1.3B`, create a new folder `ggml` and put the gguf file into it, rename it to `model.gguf`
> 5. In the offline environment, I run `tabby serve --model DeepseekCoder-1.3B --device cuda`, and after a while, I can see it is running
> 
> ![1](https://private-user-images.githubusercontent.com/5305874/339629170-7172e92a-7a09-46ec-9f68-a2250a8bfdfe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgzNDM1MDgsIm5iZiI6MTcxODM0MzIwOCwicGF0aCI6Ii81MzA1ODc0LzMzOTYyOTE3MC03MTcyZTkyYS03YTA5LTQ2ZWMtOWY2OC1hMjI1MGE4YmZkZmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTRUMDUzMzI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWJjZGJjODc5YTM0NDViNzM2MTdkM2MyMmNmNDE3ODg0MGE0ZTg3ZTUyNDFhZDFkYjE3NTk2ZDkxNGUyNjMzOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Y1QaS6R12yIemhfiRA6q2235SsQUGsW4v86K_ylsou4)

---
I run the tabby is a docker image because of offline env, how do you run the tabby
my docker is tabbyml/tabby:0.12.1-rc.0

**Comment by wwayne** [comment]
I used docker as well, the command I used is:
```sh
docker run -it --gpus all \
  -p 8080:8080 -v $HOME/.tabby:/data \
  tabbyml/tabby serve --model DeepseekCoder-1.3B --device cuda
```

I'm running from windows WSL2 (ubuntu20)

**Comment by lcwxz1989** [comment]
> I used docker as well, the command I used is:
> 
> ```shell
> docker run -it --gpus all \
>   -p 8080:8080 -v $HOME/.tabby:/data \
>   tabbyml/tabby serve --model DeepseekCoder-1.3B --device cuda
> ```
> 
> I'm running from windows WSL2 (ubuntu20)

what is the $HOME/.tabby dir tree , I really do not know where is wrong
I can use nvidia-smi in the docker and get cuda info

**Comment by wwayne** [comment]
yeah I start the server without the internet, my computer is using 3060TI, but I suppose that it has nothing to do with the GPU.
Not sure if you need to double check the content of `tabby.json`?

**Comment by lcwxz1989** [comment]
> yeah I start the server without the internet, my computer is using 3060TI, but I suppose that it has nothing to do with the GPU. Not sure if you need to double check the content of `tabby.json`?
![image](https://github.com/TabbyML/tabby/assets/5106890/0b2d06c1-6322-48b5-8f88-586ad951eb57)

**Comment by wwayne** [comment]
The tabby.json looks correct
If you are using Docker, you might want to try this method. https://tabby.tabbyml.com/blog/2024/03/25/deploy-tabby-in-air-gapped-environment-with-docker/

**Comment by lcwxz1989** [comment]
> The tabby.json looks correct If you are using Docker, you might want to try this method. https://tabby.tabbyml.com/blog/2024/03/25/deploy-tabby-in-air-gapped-environment-with-docker/

Yes, but I do not have ubuntu online, 
so I download tabby in macos
then run tabby to download the model.gguf
then transfer the model.gguf to the offline ubuntu /data/models/ dir

**Comment by wwayne** [comment]
Not sure if it's due to the different environment. Have you tried the Docker method described in the post?

**Comment by lcwxz1989** [comment]
> Not sure if it's due to the different environment. Have you tried the Docker method described in the post?

I do not have ubuntu env, and I think the post only download the model.gguf into the dir, so I download the model.guff in macos and copy the model.guff into dir of docker

**Comment by lcwxz1989** [comment]
docker run -it --gpus all \
  -p 8080:8080 -v $HOME/.tabby:/data \
  tabbyml/tabby serve --model DeepseekCoder-1.3B --device cuda
  ---
  I do not know what the dir tree in the docker, can you give me the path where the gguf located

**Comment by wwayne** [comment]
You can find them here in the docker
![docker](https://github.com/TabbyML/tabby/assets/5305874/8e5a0a71-291e-4a57-b8b4-23dea618ae48)

**Comment by wwayne** [comment]
Closing stale issue
