### ISSUE TITLE
feature request: allow specifying custom model source

### ISSUE THREAD

**Issue by Kamilcuk** [TabbyML/tabby#2421]
**Please describe the feature you want**

Currently I believe tabby hardcodes location of models at https://github.com/TabbyML/registry-tabby/blob/main/models.json .

**Additional context**

I would want to download models from https://hf-mirror.com/ because huggingface is blocked, would be great if I could specify it.

Thanks for makin tabby, it's great!

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Hi - registry can be customized by forking it and being specified as `your_github_username/model_name`

See https://tabby.tabbyml.com/docs/faq/ "How can I convert my own model for use with Tabby?"

> Users are free to fork the repository to create their own registry. If a user's registry is located at https://github.com/USERNAME/registry-tabby, the model ID will be USERNAME/model.

**Comment by Kamilcuk** [comment]
For others: it looks like you can specify the repository at https://github.com/TabbyML/tabby/blob/4c59530d62048575dc60632555879bff7342aeaa/crates/tabby-common/src/registry.rs#L28 .

**Comment by Kamilcuk** [comment]
Just noticed TABBY_HUGGINGFACE_HOST_OVERRIDE! you're rocket!
