### ISSUE TITLE
How to compile the tabby-agent.js file in IntelliJ

### ISSUE THREAD

**Issue by 5bug** [TabbyML/tabby#2423]
How to compile the tabby-agent.js file in IntelliJ? I tried running pnpm preupgrade-agent first, then pnpm upgrade-agent, but an error occurred during the upgrade-agent step: the file tabby-agent/dist/cli.js does not exist, only protocol.js is present. Packaging protocol.js does not run correctly.

thanks!

**Comment by icycodes** [comment]
Hello, @5bug! 
The current tabby-agent.js in IntelliJ is based on an outdated version, tabby-agent v1.4.0.  
The latest version of tabby-agent has a break change to only support running as an Language Server, but the IntelliJ plugin has not been updated to support this change yet. I am actively working on updating the IntelliJ plugin to align with the current version of tabby-agent.

**Comment by 5bug** [comment]
> Hello, @5bug! The current tabby-agent.js in IntelliJ is based on an outdated version, tabby-agent v1.4.0. The latest version of tabby-agent has a break change to only support running as an Language Server, but the IntelliJ plugin has not been updated to support this change yet. I am actively working on updating the IntelliJ plugin to align with the current version of tabby-agent.


Okay, thank you! I really appreciate it.

**Comment by icycodes** [comment]
After #2483, the IntelliJ directory no longer keeps a copy of tabby-agent.js. The Gradle script will now invoke pnpm turbo build to build the Tabby Agent and copy the required runtime files. 
I am closing the issue, feel free to reopen if you have further questions.
