### ISSUE TITLE
Self-Hosted Gitlab Rapository Provider with self-signed certificat will always throw `invalid peer certificate: UnknownIssuer`

### ISSUE THREAD

**Issue by LLukas22** [TabbyML/tabby#2435]
**Describe the bug**
Since the [`GitlabBuilder`](https://github.com/TabbyML/tabby/blob/main/ee/tabby-webserver/src/service/repository/third_party/fetch/gitlab.rs#L34) seams to always be initialized with the default `CertPolicy` which defaults to `Default` it is currently not possible to connect to a gitlab repository provider which uses a self-signed certificat, resulting in the following error: 

```
2024-06-18T09:21:13.549429Z ERROR tabby_webserver::service::repository::third_party: ee/tabby-webserver/src/service/repository/third_party.rs:161: Failed to fetch repositories from integration: Gitlab

2024-06-18T09:21:13.549501Z  WARN tabby_webserver::service::background_job: ee/tabby-webserver/src/service/background_job/mod.rs:59: Sync integration job failed: Other(api error: client error: communication with gitlab: error sending request for url (https://gitlab.isoad.isogmbh.de/api/v4/user?): error trying to connect: invalid peer certificate: UnknownIssuer

Caused by:

    0: client error: communication with gitlab: error sending request for url (https://gitlab.isoad.isogmbh.de/api/v4/user?): error trying to connect: invalid peer certificate: UnknownIssuer

    1: communication with gitlab: error sending request for url (https://gitlab.isoad.isogmbh.de/api/v4/user?): error trying to connect: invalid peer certificate: UnknownIssuer

    2: error sending request for url (https://gitlab.isoad.isogmbh.de/api/v4/user?): error trying to connect: invalid peer certificate: UnknownIssuer

    3: error trying to connect: invalid peer certificate: UnknownIssuer

    4: invalid peer certificate: UnknownIssuer)
```

Would it be possible to add an option to set the `CertPolicy` to `Insecure` to allow `https` connections to instances with self-signed certificates?

**Information about your version**
`tabby 0.12.0`

**Comment by wsxiaoys** [comment]
Related discussion in https://tabbyml.slack.com/archives/C05CWLZ0Y85/p1717753682849109?thread_ts=1717685765.092519&cid=C05CWLZ0Y85

cc @boxbeam 

Likely we can get this enhancement in 0.13

**Comment by LLukas22** [comment]
Just a small addition: the exact same issue also occurs in the "Mail Delivery" feature if the SMTP server used has a self-signed certificate.

**Comment by wsxiaoys** [comment]
fixed by https://github.com/TabbyML/tabby/pull/2392
