### ISSUE TITLE
other languages support

### ISSUE THREAD

**Issue by ChuKuang** [TabbyML/tabby#247]
Does replacing the model that supports other programming languages allow for direct support of other languages?

**Comment by wsxiaoys** [comment]
> Does replacing the model that supports other programming languages allow for direct support of other languages?

For core functionality , as long as model supports certain language + we configure proper stop words in
https://github.com/TabbyML/tabby/blob/main/crates/tabby/src/serve/completions/languages.rs , then it should *just work*.

**Comment by ChukuangWu** [comment]
> 
I have replaced the ”Codegen2-4B ” model and found that it works well, and other languages are also perfectly supported
