### ISSUE TITLE
Client Neovim, tabby-plugin

### ISSUE THREAD

**Issue by theCollectiv** [TabbyML/tabby#252]
I can't run the tabby-plugin in Neovim (NVIM v0.10.0-dev; so this is not an issue with TabbyML, but with the tabby-plugin for Vim/NeoVim).
I'm able to install the tabby-plugin for Vim/NeoVim successfully (with Packer as Plugin-Manager), like so

```
    use({ 'TabbyML/tabby', rtp = 'clients/vim' })
```
`:PackerStatus` confirms the tabby plugin is installed.

But in the command mode I can not call any tabby commands like `:Tabby`, `:Tabby enable`, `:Tabby disabled`, `Tabby status` (E492: Not an editor command: Tabby enabled)

Is there anybody out there, who got the tabby-plugin for Neovim up and running?

**Comment by pauchiner** [comment]
@theCollectiv The same happens to me

**Comment by wsxiaoys** [comment]
For Neovim, could you please clone Tabby to your local machine and add something like the following (I used lazy.nvim, but Packer should be similar)

```lua
return { name = "tabby", dir = '~/tabby/clients/vim', enabled = true }
```

**Comment by pauchiner** [comment]
I clonned the repo and added this line to my packer config: 
```lua
use {'~/tabby/clients/vim', as = 'tabby', enabled = true}
```
It works perfectly 😄.

After make a bit of research to know if there is an alternative command for packer like `{ rtp }` i found that the author don't want to implement this feature: [Packer Issue #163](https://github.com/folke/lazy.nvim/discussions/162)

I suggest that instead of having a repository with all clients, there is a specific one for vim, this would save a lot of trouble.

**Comment by wsxiaoys** [comment]
Currently, we still prefer maintaining all IDE/editor extensions in a mono repository for the sake of easily updating the workflow. For example, upgrading tabby-agent would require updating the bundled implementation of all extensions.

Ideally, we could integrate the functionality provided by https://github.com/Olivr/copybara-action/blob/main/docs/basic-usage.md and export the clients/vim folder to a separate Git repository. This would simplify the installation process for Vim extensions.

As a short-term solution, @pauchiner , would you be willing to contribute a pull request to improve the documentation in clients/vim/README.md regarding packer/lazy installation? Thank you!

**Comment by theCollectiv** [comment]
> use {'~/tabby/clients/vim', as = 'tabby', enabled = true}

Wow, I was trying to get it working too. But I'd never get to that syntax.

So tabby seems to run with NeoVim/Packer now. I can use `:Tabby` and command mode, and its showing me correctly, whether its enabled, disabled and the status. This is great.

If I open a file (i.e. python, rust) and I do not move the text cursor `:Tabby status` responds `Tabby online`.
As soon as I move the text cursor `:Tabby status` say `Tabby is enabled but not running`.

Is there some more to do, to get it working?

**Comment by wsxiaoys** [comment]
@theCollectiv have you started a running Tabby Server and add the proper config? https://github.com/TabbyML/tabby/tree/main/clients/vim#-packer-and-lazy

**Comment by Asthestarsfalll** [comment]
> > use {'~/tabby/clients/vim', as = 'tabby', enabled = true}
> 
> Wow, I was trying to get it working too. But I'd never get to that syntax.
> 
> So tabby seems to run with NeoVim/Packer now. I can use `:Tabby` and command mode, and its showing me correctly, whether its enabled, disabled, the status and whether the server is running or not (`Tabby cannot connect to server`). This is great.
> 
> If I open a file (i.e. python, rust) and I do not move the text cursor `:Tabby status` responds `Tabby online`. As soon as I move the text cursor `:Tabby status` says `Tabby is enabled but not running`.
> 
> There is no suggestion by Tabby and the key-bindings don't have any effect.
> 
> Is there some more to do, to get it working?

Same problem, `Tabby is enabled but not running`. Have you solved this?

**Comment by leiserfg** [comment]
For lazy it is possible to set a custom rtp, it is documented in https://github.com/folke/lazy.nvim#-migration-guide
