### ISSUE TITLE
Chat returning "G" on a loop when using the model Qwen2-1.5B-Instruct 

### ISSUE THREAD

**Issue by Srkl** [TabbyML/tabby#2550]
**Describe the bug**
When I run tabby using the chat model Qwen2-1.5B-Instruct the output is an infinity amount of 'G's for every question. 

When I change to chat model Mistral-7B I have no issues. 

<img width="917" alt="Screenshot 2024-06-29 103108" src="https://github.com/TabbyML/tabby/assets/5140629/7f279a16-afbf-479a-a50b-0933708aa8a8">

**Information about your version**

```sh
$ ./tabby --version
tabby 0.13.0
```

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:49:14_PDT_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

Does this work for anyone? 

The documentation also suggests to use a model with at least 3B parameters. However, the example uses a 1.5B model and there is no 3B parameters model in the table. I find it a bit confusing for newcomers.

**Comment by wsxiaoys** [comment]
We are unable to replicate the issue within our CUDA environment. Below are the results we obtained when making a request to the API:

```shell
-> % curl -X 'POST' \
  'https://.../v1/chat/completions' \
  -H 'accept: text/event-stream' \
  -H 'Content-Type: application/json' \
  -d '{
  "messages": [
    {
      "content": "What is tail recursion?",
      "role": "user"
    },
    {
      "content": "It's a kind of optimization used by compilers.",
      "role": "assistant"
    },
    {
      "content": "Could you share more details?",
      "role": "user"
    }
  ]
}'
```

The response received was as follows:

```
data: {"id":"chatcmpl-94b1507e-cd45-43b2-b301-6c7fb72b2823","created":1719673783,"system_fingerprint":"unused-system-fingerprint","object":"chat.completion.chunk","model":"unused-model","choices":[{"index":0,"delta":{"content":"Tail"}}]}

data: {"id":"chatcmpl-94b1507e-cd45-43b2-b301-6c7fb72b2823","created":1719673783,"system_fingerprint":"unused-system-fingerprint","object":"chat.completion.chunk","model":"unused-model","choices":[{"index":0,"delta":{"content":" recursion"}}]}

data: {"id":"chatcmpl-94b1507e-cd45-43b2-b301-6c7fb72b2823","created":1719673783,"system_fingerprint":"unused-system-fingerprint","object":"chat.completion.chunk","model":"unused-model","choices":[{"index":0,"delta":{"content":" is"}}]}

data: {"id":"chatcmpl-94b1507e-cd45-43b2-b301-6c7fb72b2823","created":1719673783,"system_fingerprint":"unused-system-fingerprint","object":"chat.completion.chunk","model":"unused-model","choices":[{"index":0,"delta":{"content":" a"}}]}

data: {"id":"chatcmpl-94b1507e-cd45-43b2-b301-6c7fb72b2823","created":1719673783,"system_fingerprint":"unused-system-fingerprint","object":"chat.completion.chunk","model":"unused-model","choices":[{"index":0,"delta":{"content":" technique"}}]}

data: {"id":"chatcmpl-94b1507e-cd45-43b2-b301-6c7fb72b2823","created":1719673783,"system_fingerprint":"unused-system-fingerprint","object":"chat.completion.chunk","model":"unused-model","choices":[{"index":0,"delta":{"content":" used"}}]}
```

Additionally, here are the screenshots from the admin UI:

![Admin UI Screenshot](https://github.com/TabbyML/tabby/assets/388154/77a9ee01-1fc5-4708-b6c1-b93170fb3734)

![Admin UI Screenshot](https://github.com/TabbyML/tabby/assets/388154/6b70003b-21ec-4f5f-8fec-0651922ce4c1)

To facilitate information gathering and debugging, could you please share the output from your `nvidia-smi` command?

**Comment by wsxiaoys** [comment]
Related issue: https://github.com/ggerganov/llama.cpp/issues/7805#issuecomment-2153341185

Workaround:
1. Try a different model.
2. Enable flash attention might fix the issue for certain gpu devices.

**Comment by plop-dev** [comment]
also experiencing this issue
the workaround isn't ideal since it's 7b

another <3b model would be appreciated if qwen2

**Comment by ila-embsys** [comment]
Don't know is this information would be useful, but I suddenly discovered, that Qwen2-1.5B-Instruct model works fine on Nvidia card if Tabby was compiled with Vulkan feature instead of Cuda. Since I can't use any another model, that require more memory, I am staying with Vulkan. The chat work fine as well as the code completion.

**Comment by XindongSu** [comment]
Same thing happened, below is the screen shot and the detail of my environment. Using cuda version always output G. After changing to using vulcan version everything is fine. 
![Screenshot 2024-07-01 at 10-35-30 i need a simple python example](https://github.com/TabbyML/tabby/assets/18639525/becd18a0-86ef-4aed-bb0b-8c9473d607bc)

![屏幕截图 2024-07-01 103745](https://github.com/TabbyML/tabby/assets/18639525/c92d181a-af2c-4516-acf7-e605593536d9)

![屏幕截图 2024-07-01 104030](https://github.com/TabbyML/tabby/assets/18639525/2548db79-9546-4a65-a043-1a8d284f3f58)

**Comment by wsxiaoys** [comment]
Hello - We are releasing version 0.13.1-rc.0, which provides a workaround to utilize the Qwen2 family model with the following settings. Please consider giving it a try if you encounter the situation described above.

```toml
[model.chat.local]
model_id = "Qwen2-1.5B-Instruct"
enable_fast_attention = true
```

**Comment by Srkl** [comment]
@wsxiaoys I've tried the version 0.13.1-rc.0. I created a config file `$ ~/.tabby/config.toml` and added the settings provided. 

When I ran tabby specifying the chat model via the command line the problem persisted. 

`./tabby serve --model StarCoder-1B --chat-model Qwen2-1.5B-Instruct --device cuda`

If I run it without the --chat-model parameter the config file is used instead and the chat model works as expected.

`./tabby serve --model StarCoder-1B --device cuda`

**Comment by wsxiaoys** [comment]
Thanks for sharing the feedback. When specifying the model configuration parameters in config.toml, you no longer need to pass the `--chat-model` flag.

A warning for such overrides has been added in https://github.com/TabbyML/tabby/pull/2559.

**Comment by wsxiaoys** [comment]
Fixed in release https://github.com/TabbyML/tabby/releases/tag/v0.13.1 for Qwen2-1.5B

**Comment by youmego** [comment]
> If I run it without the --chat-model parameter the config file is used instead and the chat model works as expected.
> 
> `./tabby serve --model StarCoder-1B --device cuda`

sorry to trouble you, which config file is used instead in your environment?

**Comment by youmego** [comment]
> @wsxiaoys I've tried the version 0.13.1-rc.0. I created a config file `$ ~/.tabby/config.toml` and added the settings provided.
> 
> When I ran tabby specifying the chat model via the command line the problem persisted.
> 
> `./tabby serve --model StarCoder-1B --chat-model Qwen2-1.5B-Instruct --device cuda`
> 
> If I run it without the --chat-model parameter the config file is used instead and the chat model works as expected.
> 
> `./tabby serve --model StarCoder-1B --device cuda`

If I run it without the --chat-model parameter the config file is used instead and the chat model works as expected.

./tabby serve --model StarCoder-1B --device cuda
@Srkl 
sorry to trouble you, which config file is used instead in your environment?
