### ISSUE TITLE
github copilot plugin support

### ISSUE THREAD

**Issue by idataitech** [TabbyML/tabby#2562]
**Please describe the feature you want**
Install a tabby server, but without tabby plugin. Instead, user can config github copilot plugin connect to tabby server.
Sample code from [localCopilot](https://github.com/FarisHijazi/localCopilot)
```
"github.copilot.advanced": {
    "debug.overrideEngine": "codegen",
    "debug.testOverrideProxyUrl": "http://localhost:8000", // address:port of middleware
    "debug.overrideProxyUrl": "http://localhost:8000",
},
```

fauxpilot support the feature too: https://github.com/fauxpilot/fauxpilot/blob/main/documentation/client.md

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
The Tabby server API is designed to work with Tabby IDE/Extensions; it is not intended to be compatible with GitHub Copilot extensions.
