### ISSUE TITLE
Incorrect endpoint URL displayed on dashboard

### ISSUE THREAD

**Issue by bendavis78** [TabbyML/tabby#2569]
When serving on a different port, the dashboard still shows "http://localhost:8080": 

![image](https://github.com/TabbyML/tabby/assets/324392/6ea8c351-61d5-4a71-ba7b-86b045475cb0)

The server was started with:

```
tabby serve --port 8078 --model TabbyML/DeepseekCoder-6.7B --chat-model TabbyML/CodeGemma-7B-Instruct
```

**version**: tabby 0.13.0-dev.0

**Comment by wsxiaoys** [comment]
Hi - endpoint url need to be manually configured in admin UI
<img width="1723" alt="image" src="https://github.com/TabbyML/tabby/assets/388154/3a2d7fd5-e9d1-42d2-b489-5d6586fedc72">
