### ISSUE TITLE
Allow customizing context length in config.toml

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2638]
**Please describe the feature you want**

Tabby currently uses a default value of 1536 for code completion context, which is not configurable. We should expose the configuration in config.toml.

Code location: https://github.com/TabbyML/tabby/blob/7474711d3c344f64a725e6867d4d93198a54fa95/crates/tabby/src/services/completion.rs#L269

https://github.com/TabbyML/tabby/blob/7474711d3c344f64a725e6867d4d93198a54fa95/crates/tabby-common/src/config.rs#L184

https://github.com/TabbyML/tabby/blob/7474711d3c344f64a725e6867d4d93198a54fa95/crates/llama-cpp-server/src/supervisor.rs#L56

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by Sma1lboy** [comment]
Would it be alright if I take this one? I am interested in contributing to this repository both now and in the future.

**Comment by wsxiaoys** [comment]
Wei has started working on this at https://github.com/TabbyML/tabby/pull/2649 - I'll open more good first issues this week.
