### ISSUE TITLE
WSL start hang on  loading model stage

### ISSUE THREAD

**Issue by Arcmoon-Hu** [TabbyML/tabby#2640]
**Describe the bug**
Use wsl start server and follow docs, the command is 
`./tabby serve --model $LLM_MODEL_PATH --chat-model $LLM_MODEL_PATH`

The log shows that the model exists and is loading.
![image](https://github.com/user-attachments/assets/2bce1048-d72e-40e9-ae95-ba1b70e95f9c)
But it consume long time and never changed.

**Information about your version**
0.13.1

**Information about your GPU**
![image](https://github.com/user-attachments/assets/d78f8db2-6706-4b11-9982-e9ba28be78dd)

**Comment by wsxiaoys** [comment]
Could you turn on `RUST_LOG=debug` and share its logs? Besides, we do support native Windows installation; you can find the instructions at https://tabby.tabbyml.com/docs/quick-start/installation/windows/, which might help you avoid dealing with WSL hassles.

**Comment by ifelsefi** [comment]
I am having same issue on 0.13.

```
Jul 19 10:22:02 hre-gn0197 systemd[1]: Started TabbyML.
Jul 19 10:22:02 hre-gn0197 tabby[898068]: 2024-07-19T15:22:02.010550Z DEBUG tabby_common::config: crates/tabby-common/src/config.rs:35: Config file /root/.tabby/config.toml not found, apply default configuration
Jul 19 10:22:02 hre-gn0197 tabby[898068]: 2024-07-19T15:22:02.010857Z  INFO tabby::services::model: crates/tabby/src/services/model/mod.rs:44: Loading model from local path /software/tabbyml/CodeLlama-13B
Jul 19 10:22:02 hre-gn0197 tabby[898068]: 2024-07-19T15:22:02.011107Z  INFO tabby::services::model: crates/tabby/src/services/model/mod.rs:44: Loading model from local path /software/tabbyml/Mistral-7B
Jul 19 10:22:02 hre-gn0197 tabby[898068]: 2024-07-19T15:22:02.018012Z DEBUG reqwest::connect: /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.12.4/src/connect.rs:497: starting new connection: https://raw.githubusercontent.com/
```

This is an air gapped server so no direct connection to the internet.  I have configured crates proxy through Artifactory.  How can we get this connection to not be attempted on startup?
