### ISSUE TITLE
tabby is loading same model 2 times when using Codestral-22B for both chat and tab complition

### ISSUE THREAD

**Issue by bubundas17** [TabbyML/tabby#2652]
When using Codestral-22B for both chat and tab complition it using 2x more vram. 
why loading the same model 2 times?

**Comment by wsxiaoys** [comment]
There is currently a limitation in the implementation of Tabby's local model backend. For now, a suitable workaround is to create a separate model server (for example, use the llama.cpp server binary) and connect the completion/chat model's HTTP endpoint to it.

**Comment by zwpaper** [comment]
this could be close since https://github.com/TabbyML/tabby/issues/2654 is done

**Comment by bubundas17** [comment]
Thanks, let me test this out.

**Comment by bubundas17** [comment]
Works. Thanks!
