### ISSUE TITLE
tabbyml 0.14 - access control permissions

### ISSUE THREAD

**Issue by ifelsefi** [TabbyML/tabby#2718]
I am noticing that any Gitlab repositories I add are available to be viewed by any user in the Community version.   I don't want users to be able to view each other's repositories.   Is this available to configure?

**Comment by wsxiaoys** [comment]
Thanks for submitting the feature request. We do have plans to support the concept of a `workspace` in the future. This will allow administrators to assign `users` and `connections` to different workspaces, essentially enabling a form of multi-tenancy.

**Comment by ifelsefi** [comment]
Thank you.   Do you have an idea on when this will be implemented?

**Comment by wsxiaoys** [comment]
This is planned for version 0.19, which is targeted for release around mid-September.
