### ISSUE TITLE
why tabby in docker works used 4 cpu cores as the linux env cpu cores is 16

### ISSUE THREAD

**Issue by beatwade** [TabbyML/tabby#272]
as the description in title.

try to use whole  cpu cores in host virtual machine. which cpu numbers are 16.
but after setup , the tabby service in docker can only use 4 cpus.

**Comment by wsxiaoys** [comment]
Hi,

Could you try `—num-replicas-per-device 4` to get a higher parallelism on CPU?

**Comment by beatwade** [comment]
if I use --num-replicas-per-device 4.  I can only use caddy to reverse proxy to the tabby service.
but how to let the service work as external ip not as localhost

**Comment by beatwade** [comment]
> Hi,
> 
> Could you try `--num-replicas-per-device 4` to get a higher parallelism on CPU?

@wsxiaoys someone has the plan to generate a deploy demo in k8s? we can release the huge resource for tabby service

**Comment by beatwade** [comment]
and in the process, find another issue for set up whole services. 
when I recreate the docker container. the tabby always show
** Attaching the tabby service......*** then try to download the mode again.

fixed this by cp the .cache_json file to model path again.

**Comment by wsxiaoys** [comment]
Hi @beatwade,

Using docker-compose under the `experimental` is currently not a supported way of deploying tabby. Please proceed with caution if you choose to use this method.

The recommended way for self-hosting is documented here: https://tabbyml.github.io/tabby/docs/self-hosting/docker.
