### ISSUE TITLE
Deploy Tabby in Air-Gapped Environment with Docker Guide does not work.

### ISSUE THREAD

**Issue by WorksButNotTested** [TabbyML/tabby#2721]
After following the [guide](https://tabby.tabbyml.com/blog/2024/03/25/deploy-tabby-in-air-gapped-environment-with-docker/), when the container is started on the air-gapped host, it attempts unsuccessfully to download:
https://huggingface.co/nomic-ai/nomic-embed-text-v1.5-GGUF/resolve/main/nomic-embed-text-v1.5.Q8_0.gguf

**Comment by wsxiaoys** [comment]
Thanks for reporting the issue, fixed in https://github.com/TabbyML/tabby/pull/2727

**Comment by WorksButNotTested** [comment]
Excellent. Thanks for the quick fix.
