### ISSUE TITLE
Cannot configure in vscode.

### ISSUE THREAD

**Issue by S-N-O-R-L-A-X** [TabbyML/tabby#273]
**Describe the bug**

**Information about your GPU**
Please provide output of `nvidia-smi`

**Additional context**

I am new to docker and feel a bit dizzy on how to make it work. I have tried the api endpoint `http(s)//localhost:8080` but it still cannot work. What should I do?
![image](https://github.com/TabbyML/tabby/assets/60914359/91ab576c-e9a6-4131-a8f5-13450da9cc61)
![image](https://github.com/TabbyML/tabby/assets/60914359/4e9b7575-6973-43a3-a55e-a7f4282593e8)
![image](https://github.com/TabbyML/tabby/assets/60914359/039dd452-81e5-46a3-a950-c402837e31e0)

**Comment by wsxiaoys** [comment]
hi, could you try:
1. Open http://localhost:8080 to see if tabby is working.
2. Run `docker ps` and copy the output here.

**Comment by S-N-O-R-L-A-X** [comment]
> hi, could you try:
> 
> 1. Open http://localhost:8080 to see if tabby is working.
> 2. Run `docker ps` and copy the output here.

![image](https://github.com/TabbyML/tabby/assets/60914359/9660ff08-7f97-47d7-98cd-1a03cf3e37f7)

After running `docker ps`
![image](https://github.com/TabbyML/tabby/assets/60914359/63f29338-e98e-429d-9b71-32be855034d0)

**Comment by wsxiaoys** [comment]
Could you check the logs of the container? e.g `docker logs 881456 -f`

**Comment by Moscato00** [comment]
I also encountered this problem, but there are no errors or logs.

The computer I use is a MacBook with an Intel processor.
<img width="1022" alt="image" src="https://github.com/TabbyML/tabby/assets/131603210/1f753b11-420d-430a-ae53-f05c3e965b8a">

**Comment by vodkaslime** [comment]
Hello, could you show the digest of the tabby image by doing `docker images` and check the `IMAGE ID` please?

**Comment by vodkaslime** [comment]
And what is the OS are you using, please? @S-N-O-R-L-A-X

**Comment by Moscato00** [comment]
> Hello, could you show the digest of the tabby image by doing `docker images` and check the `IMAGE ID` please? @S-N-O-R-L-A-X @Moscato00

REPOSITORY          TAG       IMAGE ID       CREATED       SIZE
tabbyml/tabby       latest    dd33c937594a   2 days ago    2.11GB

**Comment by S-N-O-R-L-A-X** [comment]
> Could you check the logs of the container? e.g `docker logs 881456 -f`

![image](https://github.com/TabbyML/tabby/assets/60914359/27759894-9103-4c01-88ff-f207618af612)
Got nothing.

**Comment by S-N-O-R-L-A-X** [comment]
> Hello, could you show the digest of the tabby image by doing `docker images` and check the `IMAGE ID` please? @S-N-O-R-L-A-X @Moscato00

I'm on windows10 x64.
![image](https://github.com/TabbyML/tabby/assets/60914359/7ccc2c73-49eb-44db-ba4c-a9803c9de870)

**Comment by wsxiaoys** [comment]
Seems it's the networking issue, logging could be improved to give more informative outputs.

created TAB-107

**Comment by Moscato00** [comment]
> Seems it's the networking issue, logging could be improved to give more informative outputs.
> 
> created TAB-107

how can I change the log level to see more details ?

**Comment by wsxiaoys** [comment]
I am closing the issue because the underlying problem is actually the poor internet connection to Hugging Face.
