### ISSUE TITLE
Change the execution order of the login script.

### ISSUE THREAD

**Issue by Ox0400** [TabbyML/tabby#2756]
plz support change the execution order of the login script.

**Comment by wsxiaoys** [comment]
Hi - can you elaborate your request? What's login script in this context you're referring to?

**Comment by Ox0400** [comment]
> Hi - can you elaborate your request? What's login script in this context you're referring to?

@wsxiaoys ,  SSH profiles & connections -> "LOGIN SCRIPTS"

<img width="526" alt="image" src="https://github.com/user-attachments/assets/51212729-eed3-4fcf-a465-ef612f8c8b39">

**Comment by wsxiaoys** [comment]
Should you file the issue with the other [Tabby](https://github.com/Eugeny/tabby) project?

**Comment by Ox0400** [comment]
> Should you file the issue with the other [Tabby](https://github.com/Eugeny/tabby) project?

Oh....Sorry again, I'm always confused....
