### ISSUE TITLE
Extend running model

### ISSUE THREAD

**Issue by robots** [TabbyML/tabby#276]
**Please describe the feature you want**
would it be possible to scan and teach ML on user code? Something like copilot does. 

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Hi @robots,

Could you please provide more specific details on what you would like to achieve with Tabby?

**Comment by robots** [comment]
I would like to teach model on the source code that i have already created. Eg. i would like the model to know my framework.

**Comment by prologic** [comment]
I have the same ask too

**Comment by wsxiaoys** [comment]
closing in favor of #354
