### ISSUE TITLE
vim plugin preupgrade-agent  cannot generate cli.js

### ISSUE THREAD

**Issue by Sma1lboy** [TabbyML/tabby#2768]
# Bug Report: Tabby Vim Plugin Agent Update Issue

## Describe the bug
When attempting to update the agent in the Tabby Vim plugin using `pnpm upgrade-agent`, the process fails with an error indicating that the file `../tabby-agent/dist/cli.js` doesn't exist. Even after running `pnpm preupgrade-agent` to build the tabby-agent, the required file is still not generated.

## Steps to reproduce
1. Attempted to run `pnpm upgrade-agent` in the Tabby Vim plugin directory
2. Received error: Cannot copy `../tabby-agent/dist/cli.js`: the file doesn't exist
3. Ran `pnpm preupgrade-agent` to build the tabby-agent
4. The `cli.js` file was still not generated in the expected location

## Build output
After running `pnpm preupgrade-agent`, the following build output was observed:

```
[LSP-PROTOCOL] DTS ⚡️ Build success in 1015ms
[LSP-PROTOCOL] DTS dist/protocol.d.ts 25.47 KB
[LSP-BROWSER] ESM dist/browser/index.mjs     661.85 KB
[LSP-BROWSER] ESM dist/browser/index.mjs.map 2.78 MB
[LSP-BROWSER] ESM ⚡️ Build success in 2721ms
[LSP-NODE] CJS dist/node/fsevents-X6WP4TKM.node 159.79 KB
[LSP-NODE] CJS dist/node/index.js               1.40 MB
[LSP-NODE] CJS dist/node/index.js.map           5.65 MB
[LSP-NODE] CJS ⚡️ Build success in 2718ms
[LSP-PROTOCOL] CJS dist/protocol.js 6.16 KB
[LSP-PROTOCOL] CJS ⚡️ Build success in 16ms
[LSP-PROTOCOL] DTS Build start
```

## Information about your GPU
Apple Metal

## Additional context
- The expected `cli.js` file is not present in the `dist` directory after the build process.
- The build process appears to complete successfully, but doesn't generate the required `cli.js` file.
- This issue is preventing the successful update of the agent in the Tabby Vim plugin.

## Environment
- Operating System: MacOs
- Vim version: 9.0.2142
- Node.js version: v21.7.1
- pnpm version: 9.1.0

## Questions
1. Is there a specific reason why the `cli.js` file is not being generated during the build process?
2. Are there any additional steps or configuration needed to ensure the `cli.js` file is created?
3. Is there an alternative method to update the agent in the Tabby Vim plugin?

or should I directly PR to tabby-vim repo?

**Comment by Sma1lboy** [comment]
I'm working on PR #2766  to update the parameter passing between the LSP server (tabby-agent) and the client (vim-plugin).

**Comment by icycodes** [comment]
Hi, @Sma1lboy 
The current version of the vim plugin is using an old version 1.4.0 of the tabby-agent, with a stale protocol (not LSP). As a result, an upgrade is not feasible until we transition the vim plugin implementation to use LSP.  
The LSP refactor is already on the roadmap, and will be available in Aug.
