### ISSUE TITLE
[intellij plugin] IDE Freezes During Large-Scale Text Operations (Commenting, Pasting, Formatting) 

### ISSUE THREAD

**Issue by jerryion** [TabbyML/tabby#2773]
I am experiencing a performance issue with Tabby plugin. When performing any large-scale text operations such as commenting/uncommenting an entire file, pasting a large amount of code, or formatting a large segment of code, the entire IDE freezes. This renders the IDE unusable for several minutes or even forces me to restart.

Here are the specific actions that cause the freeze:
* Commenting or uncommenting the entire code file
* Pasting large chunks of code into the editor
* Formatting a large portion of the code

Steps to Reproduce:
* Open a sizeable code file in the editor.
* Execute a bulk text operation (e.g., comment/uncomment the whole file or paste a large block of code).
* Observe the IDE freeze.

Environment:
2023.1

**Comment by icycodes** [comment]
Thank your for report this issue.  
I have made some changes to resolve it, please see #2767. This fix will be included in v1.7.

**Comment by jerryion** [comment]
> Thank your for report this issue. I have made some changes to resolve it, please see #2767. This fix will be included in v1.7.

It works fine now, thx

**Comment by icycodes** [comment]
This fix was included in v1.7.1 which is available in the marketplace now.   
I am closing this issue. Please feel free to reopen it if any further problems are found.
