### ISSUE TITLE
[intellij plugin] code completion not work after upgrading version from 1.6.3 to 1.7.0

### ISSUE THREAD

**Issue by jerryion** [TabbyML/tabby#2776]
**Expected Behavior**
After pressing the Enter key, the plugin should start inferring and suggest code completions immediately.

**Actual Behavior**
After pressing the Enter key, the status bar in the bottom right corner of the IDE shows "loading," and then changes to "completed," but no code completions appear in the editor. Surprisingly, the code completions only appear after I press the Backspace key.

**Steps to Reproduce**
1. Upgrade the plugin source code from version 1.6.3 to 1.7.0.
2. Type some code and press Enter.
3. Observe the status bar showing "loading" and then "completed."
4. Notice that no code completions appear in the editor.
5. Press the Backspace key.
6. Observe that the code completions now appear.

**Environment**
Plugin Version: 1.7.0
Previous Plugin Version: 1.6.3
IntelliJ IDEA Version: 2023.2
OS: win10

**Comment by jerryion** [comment]
Thanks for reply @5bug . But it works with Tabby 1.6.3, weird

**Comment by icycodes** [comment]
Hi, @jerryion 
Thank you for helping test it.  I have confirmed this issue and trying to address it.

**Comment by jerryion** [comment]
@icycodes is it related to this fix? https://github.com/TabbyML/tabby/pull/2767

**Comment by icycodes** [comment]
> @icycodes is it related to this fix? #2767

Yes, the offset I used [here](https://github.com/TabbyML/tabby/pull/2767/files#diff-2fb259a882d900732d366c4c2653effdf84e4a8105f8c1d5ce7afd1327989b78R181) is different from v1.6.  
But the documentChange event occurs before caretPositionChanged, so the offset is not correct.   
However, using `event.offset + event.newFragment.length` is also incorrect as it cannot handle cases where a stroke of `(` is input with an auto-append `)`.

**Comment by icycodes** [comment]
Hi, @jerryion 
The fix has been merged into the release-intellij-1.7 branch. It would be very helpful if you could test it.    
I am planning to upload version 1.7.1 to the marketplace as the first stable release of the 1.7.x.

**Comment by jerryion** [comment]
> Hi, @jerryion The fix has been merged into the release-intellij-1.7 branch. It would be very helpful if you could test it. I am planning to upload version 1.7.1 to the marketplace as the first stable release of the 1.7.x.

It works fine now, thx

**Comment by icycodes** [comment]
The Tabby IntelliJ plugin v1.7.1 is available in the marketplace now.   
I am closing this issue. Please open a new issue if any further problems are found.
