### ISSUE TITLE
Not able to enter token for endpoint

### ISSUE THREAD

**Issue by but-shuffle** [TabbyML/tabby#2789]
I installed tabby via the VSCode extension menu but there is no way to set the token.

See screenshot:
![image](https://github.com/user-attachments/assets/8f83c353-d777-4f8f-a047-1cd8e07a01b0)

Screenshot of setting page.

I also updated the config.toml file but tabby does not seem to use these information.

My Configuration:

Windows 10

VSCode: 1.72.2

Tabby: 0.4.1

Thanks!

**Comment by wsxiaoys** [comment]
Please upgrade vscode tabby extension to latest version, there's an `Set Credentials` link in settings page

<img width="651" alt="image" src="https://github.com/user-attachments/assets/7615aa86-36ad-4f55-ae33-e7afd6dca7ea">

**Comment by icycodes** [comment]
Hi @but-shuffle, you need to upgrade VSCode first, as the latest Tabby extension requires VSCode version 1.82.0 (August 2023) or later.

**Comment by Sma1lboy** [comment]
If you really don't want to update the Tabby extension, you can open the command palette by pressing Ctrl+Shift+P and call this command. 
<img width="615" alt="image" src="https://github.com/user-attachments/assets/188b89a0-cb9f-4498-ad3c-30f54557933a">
