### ISSUE TITLE
Unable to run `tabby` binary on M1

### ISSUE THREAD

**Issue by ramgrandhi** [TabbyML/tabby#279]
**Describe the bug**
1. By following the article [here](https://tabbyml.github.io/tabby/docs/self-hosting/apple)..
2. I have downloaded the release binary of `tabby` from [here](https://github.com/TabbyML/tabby/releases/tag/latest).
3. Changed the file permissions of `tabby` to 755
4. When I run `tabby --help`, it throws up with an error:
<img width="256" alt="image" src="https://github.com/TabbyML/tabby/assets/24429720/5326b668-e09e-41af-a1ac-7f28fe244c27">

**Information about your GPU**
Apple M1 Pro (Metal 3)

**Comment by ramgrandhi** [comment]
I should have known this :)

Never mind.. when I allowed the permission from Mac -> Settings -> Privacy dialog; it worked :)

**Comment by wsxiaoys** [comment]
Thanks, @ramgrandhi! If you're interested, would you like to contribute your findings on https://github.com/TabbyML/tabby/edit/main/website/docs/self-hosting/02-apple.md? It might be helpful for others who encounter similar issues.
