### ISSUE TITLE
Is the Tabby with Replicas reverse proxy a relatively immature solution?

### ISSUE THREAD

**Issue by 5bug** [TabbyML/tabby#2801]
The document I referred to: https://tabby.tabbyml.com/blog/2024/03/26/tabby-with-replicas-behind-reverse-proxy/

Deploying a single node poses no issues, but after deploying multiple nodes, the following problems arise:
1. Authentication login issues, which may be resolved by modifying the Caddyfile.
2. There are crash logs within the nodes, indicating they are not functioning properly:

The application panicked (crashed).
Message:  Failed to remove directory "/data/repositories/https_xxxx"
Location: crates/tabby-index/src/code/repository.rs:95

**Comment by wsxiaoys** [comment]
The blog post addresses a somewhat older version of Tabby, in which the `--webserver` option is disabled by default.

Running Tabby with a simple reverse proxy or replicas is only feasible when the `--webserver` option is turned off, which is equivalent to using `--no-webserver` in the latest version of Tabby.

**Comment by wsxiaoys** [comment]
Fixing documentation in https://github.com/TabbyML/tabby/commit/34c5b1d4cbfd5772db2233fd39b455cfaabb71dd

**Comment by 5bug** [comment]
I have learned a lot, thank you very much.
