### ISSUE TITLE
There is no response in chat when stream=false 

### ISSUE THREAD

**Issue by tjlcast** [TabbyML/tabby#2807]
**Describe the bug**
There is no response in chat when stream=false.

I deploy a chat tabby(Qwen2-1.5B-Instruct) in my local.
``` sh
docker run --name tabby-qwen --entrypoint /opt/tabby/bin/tabby-cpu -itd \
  -p 8087:8080 -v $PWD/qwen2-1.5:/data \
  -e RUST_BACKTRACE=1 \
  -e LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda/compat:$LD_LIBRARY_PATH \
  tabbyml/tabby serve --chat-model Qwen2-1.5B-Instruct
```

But I use curl to query(stream=false) there is no response:
``` sh
url --request POST \
  --url http://localhost:8087/v1/chat/completions \
  --header 'Authorization: Bearer auth_04167b2900ad4c79aad93270008d0218' \
  --header 'Content-Type: application/json' \
  --data '{
  "max_tokens": 2048,
  "messages": [
    {
      "content": "Hi",
      "role": "user"
    }
  ],
  "model": "qwen-72b",
  "stream": false,
  "temperature": 0
}'

```

And I saw there is a log in docker logs
<img width="1639" alt="image" src="https://github.com/user-attachments/assets/43dba4e1-ebb0-4463-a53f-323236d4a3c8">

So how can I use chat without stream=false.(Or some exmple of curl without streaming.)

**Information about your version**
root@8c8cc1e60e9f:/# tabby --version
tabby 0.14.0

**Information about your GPU**
In CPU

**Comment by wsxiaoys** [comment]
Currently, Tabby's chat completion endpoint is not fully OpenAI compatible; it only supports requests when `stream = false`. This could be improved in the future if there is a reasonable use case. Could you share a bit about what you plan to achieve?
