### ISSUE TITLE
[VSCode] Add an command item for [command-shift-p] to trigger inline chat (command-i).

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2829]
**Please describe the feature you want**
Add an command item to help user discover tabby's functionality

---
Please reply with a 👍 if you want this feature.

**Comment by Sma1lboy** [comment]
I'll take this one if nobody else is doing it. I'll update the PR ASAP :^)

**Comment by icycodes** [comment]
It already exists. 
![Screenshot 2024-08-13 004202](https://github.com/user-attachments/assets/f8740c01-1ee1-4b2d-a433-a8bd6be9e717)
