### ISSUE TITLE
How to use tabby docker image with model SantaCoder-1B directly?

### ISSUE THREAD

**Issue by MarioYoo** [TabbyML/tabby#284]
When I run the shell "docker run -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/SantaCoder-1B",
I got a error message:

ERROR tabby::serve: crates/tabby/src/serve/mod.rs:116: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/ctranslate2/shared_vocabulary.txt): error trying to connect: Connection reset by peer (os error 104)', is 'TabbyML/SantaCoder-1B' a valid model id?

So I downloaded the model from huggingface.co, and put it into path "$HOME/.tabby/models/TabbyML/SantaCoder-1B".
Then I run the same shell, I still got the same error.

How can I do so that the tabby docker image will work with the model?

**Comment by wsxiaoys** [comment]
Could you try 
cloning the https://huggingface.co/TabbyML/SantaCoder-1B to local (with lfs enabled) and pass the path to --model argument？

**Comment by MarioYoo** [comment]
Hi @wsxiaoys,
I tried the way yesterday,

there is my shell:
"
docker run -d \\
    -p 8080:8080 \\
    -v $HOME/.tabby:/data \\
    --name tabby \\
    tabbyml/tabby:latest \\
    serve --model $HOME/.tabby/models/TabbyML/SantaCoder-1B
"

but still got an error.

**Comment by wsxiaoys** [comment]
Hi, @MarioYoo 

Could you share the command you used to clone  https://huggingface.co/TabbyML/SantaCoder-1B ?

**Comment by MarioYoo** [comment]
Hi, @wsxiaoys

The model caused no problem,
it's the command:
"
git lfs install
git clone git@hf.co:TabbyML/SantaCoder-1B
"

There is a wrong with the path "serve --model $HOME/.tabby/models/TabbyML/SantaCoder-1B",
I modify it "serve --model /data/models/TabbyML/SantaCoder-1B",
and now tabby works correctly.

Thank you.

**Comment by wsxiaoys** [comment]
As mentioned in https://github.com/TabbyML/tabby/issues/284#issuecomment-1627568905, you need to provide the local path to `--model`.

glad you've figured it out.

**Comment by issaccv** [comment]
I also solved the problem by manually cloning in the host. I apologize for continuing to ask questions. I saw that only git is installed in the Dockerfile, but git-lfs is not installed by default.

Do you do this to reduce the size of the image? It appears that git-lfs is included in Ubuntu 20.04: https://packages.ubuntu.com/focal/git-lfs

https://github.com/TabbyML/tabby/blob/6a50902ca733c96cc2a3a4be492b209c7105a655/Dockerfile#L37-L42
