### ISSUE TITLE
Cannot run on offline device

### ISSUE THREAD

**Issue by shunjiu** [TabbyML/tabby#2856]
**Describe the bug**
Cannot run on offline device
- 1. I download the tabby from releases according to [tabby_docs](https://tabby.tabbyml.com/docs/quick-start/installation/linux/)
- 2. download CodeQwen1.5-7B-Chat and write tabby.json according to [MODEL_SPEC](https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md)，the model dir is  
├── ggml
│   └── model.gguf
├── tabby.json
- 3. run tabby using
```
./tabby serve --model /opt2/models/Qwen/CodeQwen1.5-7B-Chat --device cuda
```

### i got the error below

2024-08-13T02:14:03.405036Z  INFO tabby::services::model: crates/tabby/src/services/model/mod.rs:44: Loading model from local path /opt2/models/Qwen/CodeQwen1.5-7B-Chat
The application panicked (crashed).
Message:  Failed to fetch model organization <TabbyML>: Failed to download
Caused by:
    0: error sending request for url (https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json)
    1: client error (Connect)
    2: dns error: failed to lookup address information: Name or service not known
    3: failed to lookup address information: Name or service not known
Location: /__w/tabby/tabby/crates/tabby-common/src/registry.rs:62

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

It seems that I load the model, it will access GitHub, but my machine cannot connect to the internet. How can I solve this problem

**Information about your version**
0.15.0

**Information about your GPU**
Nvidia A100-40G

**Additional context**

**Comment by wsxiaoys** [comment]
Hi - Please refer to this blog post: https://tabby.tabbyml.com/blog/2024/03/25/deploy-tabby-in-air-gapped-environment-with-docker/

You need to use the `tabby download` command to download the model, which will also assist in setting up the local registry file.

**Comment by shunjiu** [comment]
Can I set up the local registry file directly?

**Comment by wsxiaoys** [comment]
Nope, not at the moment - and you'll need the `Nomic-Embed-Text` model downloaded.

**Comment by shunjiu** [comment]
ok, thanks for your reply.

**Comment by shunjiu** [comment]
ok, thanks for your reply.
