### ISSUE TITLE
[VSCode] Add a 'Generate Commit Message' icon button

### ISSUE THREAD

**Issue by Sma1lboy** [TabbyML/tabby#2873]
Using a command to perform this action might not be very intuitive.

<img width="643" alt="image" src="https://github.com/user-attachments/assets/c91c381a-ad19-4910-a964-98b03d5ad550">

Maybe adding a 'Generate Commit Message' icon in the Source Control section of VSCode to provide a better UI experience for users.

<img width="376" alt="image" src="https://github.com/user-attachments/assets/d047d73e-9ddc-4b16-9d79-d14541d7e283">

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
The last time we checked, it wasn't possible to build such a feature with VSCode (GitHub Copilot itself used a private API to achieve this).

However, it's good to keep track of this in case the situation changes in the future (or has already changed).

**Comment by Sma1lboy** [comment]
Follow up: I found a way to adding a icon on source control navigation, I will update PR ASAP

**Comment by wsxiaoys** [comment]
related: https://github.com/microsoft/vscode/issues/195474
