### ISSUE TITLE
What are the keys used by vscode plug-in to explain code in mac

### ISSUE THREAD

**Issue by qiyx2019** [TabbyML/tabby#2887]
cmd + shift + p  or cmd + i not find this dircetive

**Comment by wsxiaoys** [comment]
There's no default short cut keys - you might use `command-shift-p` to find the command, or set shortcut key for command directly

<img width="2090" alt="image" src="https://github.com/user-attachments/assets/b0360f36-c2af-486a-8d08-d8dd150e1e8a">
