### ISSUE TITLE
No position encodings are defined for positions>=2048, but got position 2384

### ISSUE THREAD

**Issue by 1651515568** [TabbyML/tabby#292]
**Describe the bug**
After deployment is completed, the container automatically exits during use with an error: terminate called after throwing an instance of 'std:: runtime_ Error 'what(): No position encodings are defined for positions>=2048, but got position 2384

**Comment by wsxiaoys** [comment]
Hi, could you share the command you used to start tabby.

**Comment by 1651515568** [comment]
> 

docker run   -p 8080:8080 -v $HOME/.tabby:/data   tabbyml/tabby serve --model TabbyML/SantaCoder-1B

**Comment by hufeng** [comment]
Yes, we met the same problem.  

log:

terminate called after throwing an instance of 'std::runtime_error'
what():  No position encodings are defined for positions >= 2048, but got position 4483

**Comment by wsxiaoys** [comment]
Hi @hufeng 

Could you also share the command you used to start tabby?

**Comment by hufeng** [comment]
sudo docker run \
  --gpus all -p 20880:8080 -v /data1/tabby:/data \
  tabbyml/tabby \
  serve --model TabbyML/SantaCoder-1B --device cuda

**Comment by wsxiaoys** [comment]
Thanks for reporting the bug, this going to be fixed in #415

**Comment by wsxiaoys** [comment]
This has been released in nightly docker image build: https://github.com/TabbyML/tabby/pkgs/container/tabby/126239803?tag=20230908

**Comment by wsxiaoys** [comment]
This has been released in v0.1.0
