### ISSUE TITLE
Tabby Edit should be able to use `tab` or other key to select and edit prompt

### ISSUE THREAD

**Issue by zwpaper** [TabbyML/tabby#2923]
**Please describe the feature you want**

Tabby Edit automatically saves history, but we can only choose the historical one directly without editing it.

it would be great if we could edit it before triggering again, for example, highlight the historical one and click `tab`(or some other key) to select it, and then we can edit and trigger again

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Nice idea! Will try bring this functionality in next release
