### ISSUE TITLE
[VSCode] When a code completion is selected, automatically invoke `import fix` code action if possible

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2965]
References: https://code.visualstudio.com/api/references/commands
![image](https://github.com/user-attachments/assets/5fb6fdfe-1969-440c-b4f9-4585ca6e0d3d)

Example:
```
const codeActions = await vscode.commands.executeCommand<vscode.CodeAction[]>(
    'vscode.executeCodeActionProvider',
    document.uri,
    range,
    vscode.CodeActionKind.QuickFix.value,
    7
  );
```

**Comment by shankarg87** [comment]
can take a look if no-one is working on this

**Comment by shankarg87** [comment]
Went through the code and a bit lost. Some follow up questions:

```When a code completion is selected``` - Can you clarify you mean by this? Are you referring to the ```inlineCompletionTriggerMode```, whenever the user triggers it ? Or do you mean once the user accepts the suggestion of the inline code completion. Trying to understand what the trigger for the code action is expected to be.

```automatically invoke import fix code action``` - I see that the existing CodeProvider registers the ```CodeAction.RefactorRewrite``` CodeAction. This can be extended to ```CodeActionKind.QuickFix```. Any thoughts on what the user workflow would look like for QuickFix? Would it also be inline editing (```tabby.chat.edit.start```) or are we looking for a new workflow.

Appreciate any pointers!

**Comment by wsxiaoys** [comment]
> When a code completion is selected - Can you clarify you mean by this? Are you referring to the inlineCompletionTriggerMode, whenever the user triggers it ? Or do you mean once the user accepts the suggestion of the inline code completion.

When I mentioned "When a code completion is selected," I specifically meant **when the user accepts the suggestion of the inline code completion**. This is the point at which the code completion is integrated into the user's code.

> automatically invoke import fix code action - I see that the existing CodeProvider registers the CodeAction.RefactorRewrite CodeAction. This can be extended to CodeActionKind.QuickFix. Any thoughts on what the user workflow would look like for QuickFix?

The work need to be done here is:

1. Verify if the generated code contains any quick fix action.

2. If the action can be classified as `import libraries`, trigger the action (such actions is usually provided by an LSP implementation for that languages)
