### ISSUE TITLE
[VSCode] add `Inline Edit` to quick fix bar

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2966]
<img width="245" alt="image" src="https://github.com/user-attachments/assets/23a56eff-4853-46cd-94a9-4a872995cf5e">

API: `registerCodeActionsProvider`: https://code.visualstudio.com/api/references/vscode-api

**Comment by Sma1lboy** [comment]
I'll take this if nobody doing right now :)
