### ISSUE TITLE
Add an command line confirmation before running migrations

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#2997]
**Please describe the feature you want**
Currently, Tabby executes database migrations without any confirmation. if we detect that the database is from an older version, we shall generate a command-line confirmation and prompt the user to manually input a specific term (e.g., 'UPGRADE') before running the migration.

**Additional context**
Code location: https://demo.tabbyml.com/files/github/TabbyML/tabby/-/blob/1e3521d622b6ff6756c3d87be6264bed1670f389/ee/tabby-db/src/lib.rs#L159

Library: https://lib.rs/crates/cliclack

---
Please reply with a 👍 if you want this feature.

**Comment by Sma1lboy** [comment]
I'll take this if nobody doing this right now :)
