### ISSUE TITLE
[VSCode] Incorrect Formatting Generated by Commit Message Generator

### ISSUE THREAD

**Issue by Sma1lboy** [TabbyML/tabby#3002]
1. **Incorrect Markdown Formatting:**
   - The generated commit message includes Markdown code block delimiters (\```) around the content, which should not be part of a commit message.
   - Example output:
     ```plain
     \```
     refactor(tabby-agent): remove unused utility function and update regex creation
     - xxxxxxx
     - xxxx
     - xxxx
     \```
     ```
   - Expected behavior: The commit message should be generated without any Markdown code block delimiters, as these are not typically used in commit messages.

**Comment by wsxiaoys** [comment]
it's good to add some rule to handle cases like this (remove "```")
