### ISSUE TITLE
failed downloading model would panic

### ISSUE THREAD

**Issue by zwpaper** [TabbyML/tabby#3003]
**Describe the bug**

when failed to download model, tabby would panic directly instead of returning a error

https://github.com/TabbyML/tabby/blob/20ac674a9e1271c3e24f221aa413ba332f82412b/crates/tabby-download/src/lib.rs#L109

**Information about your version**

main branch

**Information about your GPU**
Please provide output of `nvidia-smi`

**Additional context**

This is not urgent, but would be good improving the UX,
and this should be easy to fix, and good first issue

**Comment by wsxiaoys** [comment]
Would you suggest generating better error message, rather than output `panic!` trace?

**Comment by zwpaper** [comment]
IMHO, panic is only good for quick development, showing a error message and exit would be much more better UX for users.

when seeing a panic, it would feel like this is a fatal error and we have not handled this error.

in this case, we know this is because of the failure downloading a model, and we better told users that and exit
