### ISSUE TITLE
Problems with Ubuntu 20.04 local deployment of Tabby

### ISSUE THREAD

**Issue by csn223355** [TabbyML/tabby#301]
Hi guys I'm having this problem with a local deployment of Tabby. The system is Ubuntu 20.04.
The script that was run is below:
csn@csn-Z490M:~/Projects/Ubuntu/tabby$ sh ./run.sh 
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0000] error waiting for container:  

run.sh
docker run \
  --gpus all -p 8080:8080 -v $HOME/.tabby:/data \
  tabbyml/tabby \
  serve --model TabbyML/SantaCoder-1B --device cuda

**Comment by wsxiaoys** [comment]
Do you have an NVIDIA card with the nvndia-docker runtime installed? They are required for the GPU backend.

**Comment by marykt** [comment]
I just deploy a tabby, on Ubuntu 20.04。just run this:

apt install nvidia-driver-470 docker.io    #  ! 470 driver is recommend
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
curl -s -L https://nvidia.github.io/nvidia-container-runtime/experimental/$distribution/nvidia-container-runtime.list | sudo tee /etc/apt/sources.list.d/nvidia-container-runtime.list 
sudo apt-get update
sudo apt-get install -y nvidia-docker2

**Comment by wolf-li** [comment]
Have you been restarted docker, after you install the packages? you can run this command to test  docker gpu is work

sudo docker run -it --rm --gpus all ubuntu nvidia-smi
