### ISSUE TITLE
playground's code is open source?

### ISSUE THREAD

**Issue by qiyx2019** [TabbyML/tabby#3026]
I would like to know the details of the implementation of this editor， https://tabby.tabbyml.com/playground/

**Comment by Sma1lboy** [comment]
It should be in the /tabby/website directory, and I believe it is based on [@monaco-editor/react](https://www.npmjs.com/package/@monaco-editor/react).

**Comment by wsxiaoys** [comment]
Right - it's in https://github.com/TabbyML/tabby/blob/main/website/src/components/Monaco/index.js
