### ISSUE TITLE
support "smart" apply code from chat

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#3028]
The process can be implemented using a two-step prompting approach:

1. Identify the line range where inline editing will be applied (let LLM to generate a range)
2. Reuse inline editing, generate a prompt with context and code in editor.

![Inline Editing Example](https://github.com/user-attachments/assets/e8d6965e-4c17-4eb9-89a6-d2106e54c7c4)

For similar functionality, consider the following examples:

Cody (Smart Apply):
![Cody Smart Apply Example](https://github.com/user-attachments/assets/1e454409-f5ac-4d24-885b-3aee175d9334)

Double(CodeSnap):
[CodeSnap Feature Documentation](https://docs.double.bot/features/codesnap)

**Comment by Sma1lboy** [comment]
I can try this if nobody doing rn
