### ISSUE TITLE
[VSCode] Switching Between Tabby Chat Panel and Active Editor Using Ctrl + L

### ISSUE THREAD

**Issue by Sma1lboy** [TabbyML/tabby#3032]
**Please describe the feature you want**

When in the Tabby chat panel, Ctrl + L can be used to return to the active editor. Similarly, when in the active editor, Ctrl + L can be used to focus on the chat panel. This functionality enables quick switching between the editor and the chat panel.

Currently, the Ctrl + L shortcut functions only one-way: it can move focus from the active editor to the chat panel but not back from the chat panel to the editor. This limitation affects smooth navigation between the editor and the chat panel.

---
Please reply with a 👍 if you want this feature.

**Comment by Sma1lboy** [comment]
I'll take this one if nobody doing rn

**Comment by wsxiaoys** [comment]
released in 0.12
