### ISSUE TITLE
Offline mode for Mac OS binary

### ISSUE THREAD

**Issue by wtermini** [TabbyML/tabby#304]
I'd like to run Tabby on a machine that does not have internet access.  I pre-downloaded all the files via git and from hugging face and put them into the correct folders.

`/Users/USER_NAME/.tabby/models/TabbyML/T5P-220M/`

However it try's to download every time and hangs without network.
When i do have network  it never downloads the hugging face models and gives the error.
Manually populating the folders does not work.

`2023-07-19T00:41:03.476865Z ERROR tabby::download: crates/tabby/src/download.rs:21: Failed to fetch model due to 'Invalid url: https://huggingface.co/TabbyML/T5P-220M/resolve/main/ctranslate2/model.bin', is 'TabbyML/T5P-220M' a valid model id?`

This is where I got the tabby binary `https://github.com/TabbyML/tabby/releases/download/latest/tabby_aarch64-apple-darwin`

What I would like to see is a `--offline` option that stops this process and steps to do an offline install documented. 

Speaking of steps are their any Mac OS binary build steps?

**Comment by wolf-li** [comment]
> I'd like to run Tabby on a machine that does not have internet access. I pre-downloaded all the files via git and from hugging face and put them into the correct folders.
> 
> `/Users/USER_NAME/.tabby/models/TabbyML/T5P-220M/`
> 
> However it try's to download every time and hangs without network. When i do have network it never downloads the hugging face models and gives the error. Manually populating the folders does not work.
> 
> `2023-07-19T00:41:03.476865Z ERROR tabby::download: crates/tabby/src/download.rs:21: Failed to fetch model due to 'Invalid url: https://huggingface.co/TabbyML/T5P-220M/resolve/main/ctranslate2/model.bin', is 'TabbyML/T5P-220M' a valid model id?`
> 
> This is where I got the tabby binary `https://github.com/TabbyML/tabby/releases/download/latest/tabby_aarch64-apple-darwin`
> 
> What I would like to see is a `--offline` option that stops this process and steps to do an offline install documented.
> 
> Speaking of steps are their any Mac OS binary build steps?



You need to comment the following code without code review, the original model weight has a file in the huggingface repository to check for the conversion model. You also need to use CTranslate2 for model transformation. Note versioning issues.

crates/tabby/src/serve/mod.rs
    tabby_download::download_model(&args.model, true)
        .await
        .unwrap_or_else(|err| {
            fatal!(
                "Failed to fetch model due to '{}', is '{}' a valid model id?",
                err,
                args.model
            )
        });

**Comment by wsxiaoys** [comment]
Hello @wtermini,

Could you please try the following steps:
1. Clone the repository `https://huggingface.co/TabbyML/T5P-220M` to a local directory, for example, `~/T5P-220M`.
2. Run the tabby application using the command `tabby --model ~/T5P-220M`.

By following these instructions, you should be able to obtain an offline version of the repository that can be run locally.

**Comment by wtermini** [comment]
@wsxiaoys  I tried that before but it kept trying to download the files, I did @wolf-li  said + what you have said it seems to be doing something now :)

**Comment by wsxiaoys** [comment]
Hi @wtermini 

I believe the issue is most likely with your attempt. If TabbyML finds a local directory, it completely bypasses the downloading process. You can see this logic implemented here: 

https://github.com/TabbyML/tabby/blob/main/crates/tabby-download/src/lib.rs#L62C6-L62C6

**Comment by irunmyway** [comment]
> 



> Hi @wtermini
> 
> I believe the issue is most likely with your attempt. If TabbyML finds a local directory, it completely bypasses the downloading process. You can see this logic implemented here:
> 
> https://github.com/TabbyML/tabby/blob/main/crates/tabby-download/src/lib.rs#L62C6-L62C6

朋友，能支持离线模式吗，因为我试过我把抱脸的所有文件都下载好了，但是我在docker 容器里run tabby的时候依然会让程序去下载，能否增强一下如果有就不下载

**Comment by wolf-li** [comment]
> > 
> 
> > Hi @wtermini
> > I believe the issue is most likely with your attempt. If TabbyML finds a local directory, it completely bypasses the downloading process. You can see this logic implemented here:
> > https://github.com/TabbyML/tabby/blob/main/crates/tabby-download/src/lib.rs#L62C6-L62C6
> 
> 朋友，能支持离线模式吗，因为我试过我把抱脸的所有文件都下载好了，但是我在docker 容器里run tabby的时候依然会让程序去下载，能否增强一下如果有就不下载


支持离线 使用默认的模型 [TabbyML](https://huggingface.co/TabbyML)
/
[SantaCoder-1B(https://huggingface.co/TabbyML/SantaCoder-1B) 之后直接 docker run 就可以了，模型是放到数据卷目录下 的 models 里吗？
