### ISSUE TITLE
Increasing Concurrency for Code Completion and Q&A Chat, and Cluster Deployment Support

### ISSUE THREAD

**Issue by nianhuiY** [TabbyML/tabby#3047]
Hello TabbyML team,

I'm interested in optimizing the performance of Tabby in my self-hosted environment. I have two questions to ask:

1. Concurrency Settings: How can I increase the concurrency for code completion and Q&A chat in Tabby? Are there any configuration options or environment variables that I can adjust to achieve this? I'd like to know the recommended settings for maximizing concurrency.
2. Cluster Deployment Support: Does Tabby support cluster deployment? Are there any plans to implement load balancing and model distribution across multiple instances? In cases where device resources are limited, I'd like to know if it's possible to temporarily use smaller models as a fallback. For example, having one Tabby service instance load balance across multiple larger model instances to distribute the computational load.

I'd appreciate any guidance or insights on these topics. Thank you for your time and consideration.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Hello - The LLM inference workload can be deployed and scaled as an individual HTTP service. For an example, please visit https://tabby.tabbyml.com/docs/references/models-http-api/mistral-ai/.
