### ISSUE TITLE
model.bin not found in hugface? how can i fetch this file and run tabby? 

### ISSUE THREAD

**Issue by irunmyway** [TabbyML/tabby#305]
** console error shows **
```
ERROR tabby::serve: crates/tabby/src/serve/mod.rs:118: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/ctranslate2/model.bin): error trying to connect: Connection reset by peer (os error 104)', is 'TabbyML/SantaCoder-1B' a valid model id?
```
can author check or change mode fetch source ? or provide offline model to load config and run tabby?

**Comment by wolf-li** [comment]
> ** console error shows **
> 
> ```
> ERROR tabby::serve: crates/tabby/src/serve/mod.rs:118: Failed to fetch model due to 'error sending request for url (https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/ctranslate2/model.bin): error trying to connect: Connection reset by peer (os error 104)', is 'TabbyML/SantaCoder-1B' a valid model id?
> ```
> 
> can author check or change mode fetch source ? or provide offline model to load config and run tabby?


代码没有问题，如果你是使用 docker 启动的最好发一下 docker run 命令，这个模型很大 13G，你在docker 挂载的数据卷种查看一下模型文件是否下载完整

**Comment by irunmyway** [comment]
xfs 的硬盘格式 ，空间是有20g的，但是docker下载完了只有500m，然后看起来是模型没有下载下来
他报错是请求这个接口 https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/ctranslate2/model.bin
找不到文件了，是不是抱脸的这个项目文件被移除或者挪新地方了，能不能对应改正一下，现在看来是找不到

**Comment by wolf-li** [comment]
> xfs 的硬盘格式 ，空间是有20g的，但是docker下载完了只有500m，然后看起来是模型没有下载下来 他报错是请求这个接口 https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/ctranslate2/model.bin 找不到文件了，是不是抱脸的这个项目文件被移除或者挪新地方了，能不能对应改正一下，现在看来是找不到

你的容器大小不对啊 我下载完 2.11G ，huggingface 仓库模型文件没有问题 你可以尝试手动下载 huggingface 文件 在 docker 启动

**Comment by irunmyway** [comment]
下载后这个bin文件就够了吗，有没有提供offline 文件的目录结构 都需要哪些文件，我尝试一下手动下载和存放。

**Comment by wolf-li** [comment]
> 下载后这个bin文件就够了吗，有没有提供offline 文件的目录结构 都需要哪些文件，我尝试一下手动下载和存放。

你需要把仓库内所有文件都下载下来

**Comment by wsxiaoys** [comment]
Hi @irunmyway 

Based on the error message, it seems that there is a problem with your network access to huggingface.
