### ISSUE TITLE
[Answer Engine] switching between models (or select different models to answer the question)

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#3097]
1. For HttpModelConfig, adding `supported_models` field of api endpoint, thus allowing users select different models to complete tasks.
2. Add `/v1/models` interface to list supported models for chat / completion endpoint (if exists) ([example](https://github.com/TabbyML/tabby/blob/d5bde52de4855f94baba5cd92dc03ae78ac055e5/crates/tabby/src/routes/server_setting.rs))

https://github.com/TabbyML/tabby/blob/d5bde52de4855f94baba5cd92dc03ae78ac055e5/crates/tabby-common/src/config.rs#L247

**Comment by antimonyGu** [comment]
Start working on this issue.

**Comment by wanyukang** [comment]
Wow, looking forward to this feature

**Comment by antimonyGu** [comment]
One thing need to be confirmed that is `supported_models` field retrieve models info from `crates/tabby-common/src/registry.rs`'s `load_remote_registry` and `load_local_registry` functions? @wsxiaoys
