### ISSUE TITLE
Endpoints in the UI don't match the hostname

### ISSUE THREAD

**Issue by jtmarmon** [TabbyML/tabby#3113]
**Describe the bug**
Both the endpoint URL in the home page and the invite URLs are hardcoded to `localhost`, it'd be great if they use the hostname the user is accessing from.

**Comment by wsxiaoys** [comment]
The configuration server requires admin setup. For detailed instructions, visit [this link](https://demo.tabbyml.com/settings/general).

**Comment by jtmarmon** [comment]
Ah thank you. This would be helpful to add to the docs, maybe under the admin section
