### ISSUE TITLE
[VSCode] Fix This: add IDE & LSP error message as LLM context.

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#3129]
<img width="475" alt="image" src="https://github.com/user-attachments/assets/2ee608e1-e6cd-442e-b3b2-f24daf1ff15c">

Should be implemented as an `inline edit` type, similar to `Quick Fix - Fix using copilot`, but with IDE/LSP errors enhanced as context.

**Comment by Sma1lboy** [comment]
I will take this one if nobody doing right now
