### ISSUE TITLE
Can't connect to tabby

### ISSUE THREAD

**Issue by rdanter** [TabbyML/tabby#313]
**Describe the bug**
Following the Getting Started, I created a ~/tabby/config.toml file with the provided URL (copy and paste from the web page), then run the docker command for use on a CPU (not CUDA). The Docker image is downloaded and it looks like it is running (no errors shown). When I then try to open the web page in my browser (localhost:8080) it says there is no response. I checked for firewall rules, and even turned the firewall off, but it did not help.

Is there more needed for this to work than just creating the config file and running the Docker command?

**Information about your GPU**
Not using GPU.

**Additional context**
Host is a Linux Mint 20.3 machine.

**Comment by wsxiaoys** [comment]
Hi @rdanter 

Could you share the docker command you use to start tabby？

**Comment by rdanter** [comment]
I used this:

```
docker run \
  -p 8080:8080 -v $HOME/.tabby:/data \
  tabbyml/tabby serve --model TabbyML/SantaCoder-1B
```

Exactly as per the Getting Started guide. First time I ran it it downloaded the image and ran it, subsequently it just ran it. No errors seen at all.

**Comment by Jazzylol** [comment]
I have also encountered a similar situation. I even downloaded all the model files in advance, but the Docker command that quickly started will still download all the models, and the entire container does not have a single log line when it starts, completely unaware of what happened. I tried on two computers, PC succeeded, Mac failed

Strongly request to add more start logs!

**Comment by wsxiaoys** [comment]
> I used this:
> 
> ```
> docker run \
>   -p 8080:8080 -v $HOME/.tabby:/data \
>   tabbyml/tabby serve --model TabbyML/SantaCoder-1B
> ```
> 
> Exactly as per the Getting Started guide. First time I ran it it downloaded the image and ran it, subsequently it just ran it. No errors seen at all.

Hi, could you try starting with a smaller model, such as `TabbyML/T5P-220M` ? I suspect that the model may not have finished loading into your RAM, which could be causing the issue.

> Strongly request to add more start logs!
Agree - definitely something Tabby could improve.

**Comment by rdanter** [comment]
Hi @wsxiaoys 

With the smaller T5P-220M model I was able to see it start, connect via a web browser and even link the VS Code extension with it. :)

Even this small model took quite some time to download, so I guess I didn't wait long enough for the larger model. You comment prompted me to watch the network and CPU load, and I could see it was busy downloading. I am now trying the original model, just leaving it download whilst I get on with other things. Do the models get downloaded every time or just the first time you use them?

+1 on the log messages during start-up, even better if it could show download progress periodically.

I appreciate that you are focused on the application development right now, but it may be worth investing a little time on the docs too so it's a little clearer for a newbie to understand what they need to do and what to expect. You may get more users and more feedback that way. Right now I have no idea what the config.toml file actually needs, in fact I forgot to even create one before trying the small model and yet it still seemed to work. Other things that I think a beginner would want to know is how to train the model on their own code since one the the huge benefits of a self hosted tool is that it can be used with in-house code.

Thanks for the help!
Rich

**Comment by wsxiaoys** [comment]
> Do the models get downloaded every time or just the first time you use them?

The initial download will cache the model in ~/.tabby.

> even better if it could show download progress periodically.

Could you please confirm if you are running Tabby on a Windows environment? We have observed that the progress bar is displaying correctly on macOS and Linux environments, but we have received a few reports that the progress bar is not shown on Windows. Just want to confirm this information.

**Comment by rdanter** [comment]
I am on a Linux Mint 20.3 machine. Just to be clear, after I start the docker container I see nothing at all in the terminal until the model is downloaded and the server really starts, like this:

```
$ docker run   -p 8080:8080 -v $HOME/.tabby:/data   tabbyml/tabby serve --model TabbyML/SantaCoder-1B
2023-07-26T10:03:47.412463Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:131: Listening at 0.0.0.0:8080
```

The good news is the SantaCoder-1B model worked once I waited long enough for it. Took about 30+ minutes on my slow network.

> The initial download will cache the model in ~/.tabby.

What happens if the model is updated? Will it detect that and re-download it?

**Comment by icycodes** [comment]
> Could you please confirm if you are running Tabby on a Windows environment? We have observed that the progress bar is displaying correctly on macOS and Linux environments, but we have received a few reports that the progress bar is not shown on Windows. Just want to confirm this information.

Tested running Tabby docker image on Ubuntu and Windows, and there was no download progress bar logging from docker.
