### ISSUE TITLE
Error - message: "Operation not permitted" on deployment by duplicating Hugging Face Space

### ISSUE THREAD

**Issue by leafOfTree** [TabbyML/tabby#3132]
Steps:
- Duplicate Hugging Face space https://huggingface.co/spaces/TabbyML/tabby-template-space
- It got a runtime error

===== Application Startup at 2024-09-12 05:10:03 =====

The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
Location: crates/tabby/src/main.rs:68

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
The application panicked (crashed).
Message:  called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }
Location: crates/tabby/src/main.rs:68

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

**Comment by wsxiaoys** [comment]
Thanks for reporting the issue. It was caused by a recent permission model change in HuggingSpace. I've fixed it in [this commit](https://huggingface.co/spaces/TabbyML/tabby-template-space/commit/7568c103e4ec7df6b9f55ee4bc0ae68d09e4205b). Please try again, thank you!

**Comment by leafOfTree** [comment]
Thanks. It's working now.
