### ISSUE TITLE
tabby has no concept of codebase ？

### ISSUE THREAD

**Issue by qiyx2019** [TabbyML/tabby#3157]

**Comment by wsxiaoys** [comment]
Context providers allow connections to a source code repository to integrate the codebase as context. Is that what you're looking for? https://tabby.tabbyml.com/docs/administration/context/

**Comment by qiyx2019** [comment]
yes ! I'd like to know this detail. Do you have more detailed documentation ? @wsxiaoys

**Comment by wsxiaoys** [comment]
Nope - it's briefly discussed in how we handle [code completion](https://github.com/TabbyML/tabby/issues/2657) / [q&a](https://github.com/TabbyML/tabby/issues/2657) though.
