### ISSUE TITLE
Dynamically show which part context we are referencing in Clients' TabbyChatView

### ISSUE THREAD

**Issue by Sma1lboy** [TabbyML/tabby#3260]
**Please describe the feature you want**

This is useful for users to see all the context they will be passing in the chat view.
https://github.com/user-attachments/assets/b0678da7-5c0f-426b-af4d-953d3799f0a9

---
Please reply with a 👍 if you want this feature.

**Comment by ronaksingh27** [comment]
@Sma1lboy Could you please assign me this issue ? Additionally, I would appreciate it if you could provide some guidance on where I should begin.

**Comment by Sma1lboy** [comment]
Hi @ronaksingh27,

Thank you for taking the time to help with this issue. Here's some guidance:

- Use `onDidChangeActiveTextEditor` and `onDidChangeTextEditorSelection` to track the current context.
- Please take a look at how we communicate between WebView and the VS Code client:
  - https://github.com/TabbyML/tabby/blob/main/clients/tabby-chat-panel/src/index.ts
  - https://github.com/TabbyML/tabby/blob/main/clients/vscode/src/chat/chatPanel.ts
  - https://github.com/TabbyML/tabby/blob/main/ee/tabby-ui/app/chat/page.tsx

Let me know if you need any further clarification or have any questions.
