### ISSUE TITLE
[Eclipse] Allow keyboard shortcut customization

### ISSUE THREAD

**Issue by joaodinissf** [TabbyML/tabby#3274]
**Please describe the feature you want**

In Eclipse, as a user with a keyboard layout other than EN-US-QWERTY, it would be good to have the ability to customize the keyboard shortcuts to interact with Tabby.

For example, it is not possible to manually trigger completions (through ALT + \\) on a German keyboard. See also the related issue: https://github.com/TabbyML/tabby/issues/1202

The only workaround at the moment is to toggle the keyboard layout at the OS level.

**Additional context**

It is possible to customize keybindings the extension settings in VS Code, for example. It would be nice to have the same possibility in Eclipse.

![Screenshot 2024-10-16 112840](https://github.com/user-attachments/assets/aa939bbf-ce4a-4f89-9bb2-16175d876f96)

---
Please reply with a 👍 if you want this feature.

**Comment by icycodes** [comment]
Hi, @joaodinissf 
Thank you for reporting this issue.  

The keyboard shortcuts for each action can be customized in Eclipse by going to Window -> Preferences -> General -> Keys settings, and filter the actions by `Tabby`. 
Could you please try this to see if it resolves the problem on a German keyboard?  

![Screenshot from 2024-10-14 10-57-47](https://github.com/user-attachments/assets/6051e84f-5454-4bb5-886c-2be67283ca2d)

**Comment by joaodinissf** [comment]
Thanks for the quick response, @icycodes.
I overlooked this. You're right, the issue can be closed.
