### ISSUE TITLE
Support Req - Jetbrains Pycharm

### ISSUE THREAD

**Issue by QuantumForced** [TabbyML/tabby#328]
**Support for Jetbrains Pycharm, pretty please**

---
Please reply with a 👍 if you want this feature.

**Comment by icycodes** [comment]
Hi, @QuantumForced 
I am working on Tabby plugin for IntelliJ Platform IDEs, but it is still in development for now. You can follow up development progress in issue #76.
The first version will be published on IntelliJ Platform plugin marketplace in a few days.
