### ISSUE TITLE
vim position calculation error when code contains chinese

### ISSUE THREAD

**Issue by godsakurapeng** [TabbyML/tabby#329]
**Describe the bug**
vim position calculation error when code contains chinese

**Additional context**
The completion content is obviously wrong, and it will not change no matter how you input
<img src="https://github.com/TabbyML/tabby/assets/138603914/26472d90-f8e4-4834-a9ea-0de5edc6e9ad" width="250"><img src="https://github.com/TabbyML/tabby/assets/138603914/8f980039-17b1-4b9c-ad55-982e693d603a" width="250">
Looking at the log, it can be judged that the calculation of the position of fim is wrong, my input position is not the fim position
<img src="https://github.com/TabbyML/tabby/assets/138603914/8b298816-f4ac-4127-b0f7-749b74409a20" width="800">
See how the code calculates the fim position, the line2byte function is used to calculate the number of bytes, and Chinese is generally a multi-byte character, which leads to a position calculation error. [this file](https://github.com/TabbyML/tabby/blob/main/clients/vim/autoload/tabby.vim#L553)
<img src="https://github.com/TabbyML/tabby/assets/138603914/cfab090f-b3d2-41e2-b1af-0dbf3c14ed4a" width="600">
so I try to use another method to calculate the position,it seems work
<img src="https://github.com/TabbyML/tabby/assets/138603914/20ed7e0b-6399-47b4-a58f-79d20e84d4ff" width="600">
<img src="https://github.com/TabbyML/tabby/assets/138603914/bdd3a066-e50b-4b7e-a911-1102e801ef15" width="400"><img src="https://github.com/TabbyML/tabby/assets/138603914/00b55016-2423-46ed-8cff-f61dc3c7a34d" width="400">
<img src="https://github.com/TabbyML/tabby/assets/138603914/66a2eeac-8393-42c7-9371-acce98fec613" width="600">
Of course, this is just my simple try. Although it seems work, i cannot make sure that it will not cause other bugs. I look forward to the official solution : )

**Comment by icycodes** [comment]
Hi, @godsakurapeng. 
Thank you for pointing out this bug. It is true that the current calculation of the FIM position is not suitable for Chinese and all multibyte characters.
`strchars(join(getline(1, line('.') - 1), "\n"))` looks good for counting characters in previous lines. But `virtcol('.')` seems not to always work for counting characters in the current line, for example when there are some multibyte characters or `\t` indent. 
Thank you again for your solution and I will fix this later.
