### ISSUE TITLE
Swagger-UI fails, as it does not attempt to authenticate.

### ISSUE THREAD

**Issue by gmatht** [TabbyML/tabby#3383]
**Describe the bug**
If we go to swagger-ui/ and try e.g. /v1/completion the server responds that we are not authorized. According to the displayed Curl command the swagger-ui isn't even trying to send the header needed to authenticate.

**Information about your version**
tabby 0.19.0

**Information about your GPU**
A770M

**Comment by zwpaper** [comment]
Hi @gmatht, did you input the token here:
![CleanShot 2024-11-06 at 21 04 26@2x](https://github.com/user-attachments/assets/fc431c1a-0ab3-4712-a1a8-cc60bf407779)

**Comment by gmatht** [comment]
No, I authenticated with the main page. Using that Authentication button fixes the issue. It is unintuitive that I would have to authenticate again; maybe instead of just saying Authentication Denied, the UI could prompt us to authenticate again?

**Comment by wsxiaoys** [comment]
The Swagger UI is a separate component bundled with Tabby, and its functionality is not maintained by us. Thus we are unable to alter its behavior.

**Comment by gmatht** [comment]
It looks like Swagger-UI as an API to set the Authentication token. Perhaps if we are logged into the Tabby server it could just pass an authentication token into Swagger-UI?

**Comment by wsxiaoys** [comment]
> It looks like Swagger-UI as an API to set the Authentication token. Perhaps if we are logged into the Tabby server it could just pass an authentication token into Swagger-UI?

The library we used to build swagger-ui is https://github.com/juhaku/utoipa/blob/478b7c9d4caaf861cc9f806b275f540e7209421c/utoipa-swagger-ui/src/lib.rs#L1245 -  could you point the api to set the auth token?
