### ISSUE TITLE
How to build `tabby` server for self hosting on m1 mac?

### ISSUE THREAD

**Issue by prashanthsadasivan** [TabbyML/tabby#340]
**Describe the bug**
I'm trying to build the crates using `cargo build` and running into issues with `ruy` / `cpuinfo` not compiling on m1 mac. it seems like it thinks it's running on an x86 cpu, but it should be selecting ARM? do I need to specify any environment variables or something? what's the right build command for m1 mac?

**Information about your GPU**
m1 mac

**Additional context**
Stack trace
```
 error: redefinition of 'cpuinfo_isa' with a different type: 's
truct cpuinfo_arm_isa' vs 'struct cpuinfo_x86_isa'
  struct cpuinfo_arm_isa cpuinfo_isa = {
                         ^
  /Users/prashanthsadasivan/llms/tabby/crates/ctranslate2-bindings/CTranslate2/third_party/ruy/third_party/cpuinfo/include/cpuinfo.h:772:32: note: previous declaration is here
          extern struct cpuinfo_x86_isa cpuinfo_isa;
                                        ^
```

a bunch of other similar issues follow.

**Comment by wsxiaoys** [comment]
Hi,

To obtain an M1 binary, I recommend downloading it directly from https://github.com/TabbyML/tabby/releases. This link will provide you with the most recent build from the `main` branch.

However, if you do wish to build it from scratch, using the command `cargo build` should be sufficient. You might consider use `cargo build --target aarch64-apple-darwin` if there's multiple cross tool chain installed on your system.
