### ISSUE TITLE
Llama support

### ISSUE THREAD

**Issue by SharanSMenon** [TabbyML/tabby#352]
So, will we see support for other models, like llama? Maybe through llama.cpp or langchain, or Ollama. Cause continue.dev has support for Ollama and such so I was wondering if models like Llama 2 is on the roadmap?

**Comment by wsxiaoys** [comment]
We won't integrate any models above 4b for completion at the moment because of the tradeoff between latency, serving cost, and quality.

For chat and Q&A purposes, models like llama are more suitable as they have lower latency requirements. This is being tracked in issue #222

**Comment by 06kellyjac** [comment]
I guess this would also mean [code llama](https://ai.meta.com/blog/code-llama-large-language-model-coding/) at 7b minimum wouldn't fly either

**Comment by wsxiaoys** [comment]
In issue #370, we introduced support for the Code Llama feature. However, its performance is currently suboptimal due to the significantly larger model size.

**Comment by wsxiaoys** [comment]
related: https://github.com/ggerganov/llama.cpp/pull/2768#issuecomment-1692116354

Performance on M1 Metal shader seems superior with ggml

**Comment by xxhh1112** [comment]
+1

**Comment by wsxiaoys** [comment]
llama has been fully supported since v0.1.0
