### ISSUE TITLE
Add plugin for Eclipse based ides

### ISSUE THREAD

**Issue by niriak** [TabbyML/tabby#356]
**Please describe the feature you want**
Please add support for Eclipse Desktop IDE.

---
Please reply with a 👍 if you want this feature.

**Comment by avirtualfuture** [comment]
👍

**Comment by ouyanghd** [comment]
👍

**Comment by ivanrododendro** [comment]
@selamanse looks interesting. Did you made it available as standalone download?

**Comment by selamanse** [comment]
@ivanrododendro still working on it. will post here as soon as there is a package. feel free to build it locally though. #621

**Comment by ivanrododendro** [comment]
It looks to me that clients_eclipse does not exist anymore ? Am I wrong ?

**Comment by joaodinissf** [comment]
@icycodes, this issue can likely be closed, on account of https://github.com/TabbyML/tabby/tree/main/clients/eclipse, right?
