### ISSUE TITLE
Ubuntu 20.04 Linux subsystem Docker tabby cannot autocompletion 

### ISSUE THREAD

**Issue by duhuangwen** [TabbyML/tabby#358]
**Describe the bug**

I have installed the Ubuntu 20.04 Linux subsystem on a Windows 10 system, and within the subsystem, I've set up a Docker service. I used this Docker service to install TabbyML. I can access http://localhost:8080/swagger-ui/# in my browser, and the request to the local endpoint v1/completion keeps loading indefinitely. When using IDEs like IntelliJ IDEA or Visual Studio Code, they indicate a successful connection to the Tabby service, but code autocompletion is not functioning.

**Information about your GPU**
Please provide output of `nvidia-smi`

  tabby:
    # https://github.com/TabbyML/tabby
    image: tabbyml/tabby:latest
    container_name: tabby
    restart: always
    ports:
      - 8080:8080
    command: serve --model TabbyML/SantaCoder-1B
    volumes:
      #使Docker容器时间与主机时间一致
      - ~/docker/tabby/data:/data
      - /etc/localtime:/etc/localtime:ro

**Additional context**
![image](https://github.com/TabbyML/tabby/assets/37618226/6c6ee065-f758-4e5e-b864-96dcd7eed929)
![image](https://github.com/TabbyML/tabby/assets/37618226/1530da0e-45be-496e-9d33-c55b15248916)

**Comment by wsxiaoys** [comment]
Hi @duhuangwen ,

Could you please copy the `curl` command and try running it in your terminal to see how long it takes? It would be great if you could wrap it with`time` to measure the duration.

Based on my assumption, running the model on CPU with a relatively large model (1B) might result in high latency, making Tabby less useful. You may want to consider using a smaller model like TabbyML/T5P-220M for CPU usage.

**Comment by duhuangwen** [comment]
I waited for ten minutes and there was no response. My computer is equipped with an Intel(R) Core(TM) i5-10210U processor.

![image](https://github.com/TabbyML/tabby/assets/37618226/03b8e769-ff63-4d5e-927f-426069474f86)

**Comment by duhuangwen** [comment]
![image](https://github.com/TabbyML/tabby/assets/37618226/8dc268de-9d97-4864-8fb0-d36d312b8edb)

**Comment by wsxiaoys** [comment]
Hi @duhuangwen 

What's the setup for your second screenshot? How long does it take to generate the result?

**Comment by duhuangwen** [comment]
![image](https://github.com/TabbyML/tabby/assets/37618226/2b4c755a-4ebc-43ec-95ab-ba989df052b6)

The setup is as follows ：
  tabby:
    # https://github.com/TabbyML/tabby
    image: tabbyml/tabby:latest
    container_name: tabby
    restart: always
    ports:
      - 9988:8080
    command: serve --model TabbyML/SantaCoder-1B
    volumes:
      #使Docker容器时间与主机时间一致
      - ~/docker/tabby/data:/data
      - /etc/localtime:/etc/localtime:ro

and  it took me about ten minutes 。

**Comment by wsxiaoys** [comment]
Cool, then it matches the assumption - running models with such parameter size on CPU is simply slow.

Could you try using a smaller model, say `TabbyML/T5P-220M`?

**Comment by duhuangwen** [comment]
only update command: serve --model TabbyML/T5P-220M ?

**Comment by wsxiaoys** [comment]
Closing this as the problem appears to have been identified, and a workaround has been provided. Please feel free to reopen if you encounter any new issues.
