### ISSUE TITLE
Homebrew is out of date (0.20.0)

### ISSUE THREAD

**Issue by peterwilli** [TabbyML/tabby#3588]
**Describe the bug**

```
➜  ~ brew install tabbyml/tabby/tabby

==> Auto-updating Homebrew...
Adjust how often this is run with HOMEBREW_AUTO_UPDATE_SECS or disable with
HOMEBREW_NO_AUTO_UPDATE. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Warning: tabbyml/tabby/tabby 0.20.0 is already installed and up-to-date.
To reinstall 0.20.0, run:
  brew reinstall tabby
```

I tried upgrading all brew packages to see if this changes but it seems to be stuck at 0.20.0

**Information about your version**

Irrelevant

**Information about your GPU**

Mac Book Air M2

**Comment by wsxiaoys** [comment]
Fixed in https://github.com/TabbyML/homebrew-tabby/commit/402106b70506c533abab337d8f52c8eaa96955d0
