### ISSUE TITLE
VIM Client

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#36]
It'll be nice if we could support completion in vim.

Maybe starts with an omni func: https://vim.fandom.com/wiki/Omni_completion

**Comment by wsxiaoys** [comment]
Related: https://github.com/github/copilot.vim

**Comment by tricktux** [comment]
It would be amazing if you support `neovim`

[This](https://github.com/hrsh7th/nvim-cmp) is the most popular code completion engine on `neovim`

There's also [copilot.lua](https://github.com/zbirenbaum/copilot.lua)

Thanks for the excellent work!

**Comment by nzlov** [comment]
Try [cmp-tabby](https://github.com/nzlov/cmp-tabby)

**Comment by wsxiaoys** [comment]
> Try [cmp-tabby](https://github.com/nzlov/cmp-tabby). But it's Implemented very simple, i need full doc of tabby.
> 
> When callback event has error:
> 
> ```
> curl -X POST http://192.168.1.109:5000/v1/events -H 'Content-Type: application/json' --data '{
>     "type":"completion",
>     "completion_id":"cmpl-GUyycQ60ls5nq23vLELW5RJMntRhU",
>     "choice_index":0
> }'
> "invalid event"
> ```

Thank you for your contribution! @icycodes has already provided a Neovim-compatible extension on https://github.com/TabbyML/tabby/tree/main/clients/vim that you might want to try out.

**Comment by wsxiaoys** [comment]
I am closing this issue for now. If you encounter any further issues related to the Vim extension, please feel free to open a new issue
