### ISSUE TITLE
Universal Copilot in any app - Cotypist ALTERNATIVE 

### ISSUE THREAD

**Issue by fire17** [TabbyML/tabby#3608]
I'm looking for an opensource Cotypist ALTERNATIVE 

Basically an opensource version of it - a copilot that works anywhere, 

Do you think that's possible?
Amazing if it can be crossplatform
Thanks and all the best!

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Tabby itself focuses on developer use cases. While it is possible to create a client that can be used in any input box (still utilizing Tabby as its API backend), this is currently not within the scope of the project.

Closing this as not planned.
