### ISSUE TITLE
Cannot build docker image from dockerfile

### ISSUE THREAD

**Issue by leiwen83** [TabbyML/tabby#403]
Hi,

I try build the docker image from the dockerfile, but got below error:
```
# docker build .
Sending build context to Docker daemon  23.78MB
Error response from daemon: Dockerfile parse error line 29: Unknown flag: mount
```

So what's correct way to launch the docker build for your dockerfile?

**Comment by wsxiaoys** [comment]
Hi,

Tabby needs to be build with build kit enabled, could you please try `DOCKER_BUILDKIT=1 docker build .`?

**Comment by leiwen83** [comment]
> Hi,
> 
> Tabby needs to be build with build kit enabled, could you please try `DOCKER_BUILDKIT=1 docker build .`?

Still get failed...
```
# DOCKER_BUILDKIT=1 docker build .
[+] Building 0.0s (2/2) FINISHED
 => [internal] load .dockerignore                                                                                                                       0.0s
 => => transferring context: 66B                                                                                                                        0.0s
 => [internal] load build definition from Dockerfile                                                                                                    0.0s
 => => transferring dockerfile: 1.44kB                                                                                                                  0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: Dockerfile parse error line 29: Unknown flag: mount

```

**Comment by wsxiaoys** [comment]
Ah, I see - it actual requires a proper setup of docker buildx for proper cache handling: https://docs.docker.com/engine/reference/commandline/buildx_build/

Will update back to this issue once I got a testing environment to figuring out a correct command

**Comment by leiwen83** [comment]
seems to me it need to add below text in the head of Dockerfile:
```
# syntax = docker/dockerfile:experimental
```

After add this, "docker buildx build ." could execute fine.
