### ISSUE TITLE
How to build tabby binary?

### ISSUE THREAD

**Issue by leiwen83** [TabbyML/tabby#404]
Hi,

Thank you for creating such interesting proj, I'd like to get further investigate and make some modifcation. But it seems to me there is little doc that explain how to build out whole proj.
So do we have any doc for build tabby binary?

**Comment by leiwen83** [comment]
Got it. Thx~

**Comment by yanpeiqiong7133** [comment]
> Hi, I just added a section in README on building tabby, check it out: https://github.com/TabbyML/tabby#-contributing

Hi, how to build a tabby binary that can work on many linux. I build a binary on centos9，but it can not work in other linux operating systems. Thank you~
