### ISSUE TITLE
Some other serve backend?

### ISSUE THREAD

**Issue by leiwen83** [TabbyML/tabby#409]
Hi,

I wonder that whether tabby could add more inference backend like vllm?
Since vllm did a good job in serving batching inference, I think it shall also benefit tabby if deployed at scale.

If this idea is accepted, I'd like to contribute my PR for it.

**Comment by wsxiaoys** [comment]
One idea I have in mind is to create an HTTP API binding for implementing Text Generation. Since vllm provides support for an OpenAPI-like interface, the support should be straightforward.

However, there are certain challenges in the implementation process, such as HTTP cancellation propagation and the need for flexible support for different HTTP backends (e.g., OpenAI, TGI, Palm). Because of these challenges, I haven't started implementing it yet.

**Comment by leiwen83** [comment]
Is there some demo for your prototype http-api-bindings? So that other people could follow your desgin?

For "HTTP cancellation propagation", do you mean like vscode lose server connection, you want to tabby server flush out its previous request?

I think maybe current llama.cpp servering could also be made as http server to provide http interface. So that [TextGeneration](https://github.com/TabbyML/tabby/blob/main/crates/tabby-inference/src/lib.rs) could directly talk to those different cient at will smoothly?

**Comment by wsxiaoys** [comment]
Hi @leiwen83 

#419 integrated an `experimental-http` interface which integrates `Codey` model into tabby as a special type of backend.

> I think maybe current llama.cpp servering could also be made as http server to provide http interface.
While it is technologically feasible, doing so would be incorrect :). Fundamentally, vllm, OpenAI, TGI, and Vertex are individual services or remote APIs that can only be accessed through HTTP API. The inclusion of this support is primarily for quality evaluation purposes at the moment.

**Comment by leiwen83** [comment]
Hi @wsxiaoys ,

I am very excited for this change, and begin to do some experiment base on it.

As the first step, I try to follow your README.md in the new component, to run "cargo run --example simple", but got below error. I am run it within the docker built with latest Dockerfile, so is there anything I missed?

```
error: failed to run custom build command for `openssl v0.10.52`

Caused by:
  process didn't exit successfully: `/data/aigc/workset/code/tabby/target/debug/build/openssl-e51f637ee7c7173e/build-script-build` (exit status: 1)
  --- stderr
  /data/aigc/workset/code/tabby/target/debug/build/openssl-e51f637ee7c7173e/build-script-build: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /data/aigc/workset/code/tabby/target/debug/build/openssl-e51f637ee7c7173e/build-script-build)
  /data/aigc/workset/code/tabby/target/debug/build/openssl-e51f637ee7c7173e/build-script-build: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /data/aigc/workset/code/tabby/target/debug/build/openssl-e51f637ee7c7173e/build-script-build)
  /data/aigc/workset/code/tabby/target/debug/build/openssl-e51f637ee7c7173e/build-script-build: /usr/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /data/aigc/workset/code/tabby/target/debug/build/openssl-e51f637ee7c7173e/build-script-build)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `native-tls v0.2.11`
```
