### ISSUE TITLE
Do we have any roadmap for this project?

### ISSUE THREAD

**Issue by leiwen83** [TabbyML/tabby#433]
Hi,

I think maybe have a roadmap could give people a big picture how this proj would be?
Like cody: https://handbook.sourcegraph.com/strategy-goals/strategy/cody/#strategy--plans

And I am interested to know whether do we have plan to make tabby as a code repo level assistent?

Thx~

**Comment by wsxiaoys** [comment]
Our roadmap is listed at https://tabby.tabbyml.com/docs/roadmap. I'd be happy to discuss it further if you have any questions.

**Comment by leiwen83** [comment]
It is great~
