### ISSUE TITLE
[Proposal] Add a test connection button to check tabby server endpoint availability

### ISSUE THREAD

**Issue by sunny0826** [TabbyML/tabby#438]
**Please describe the feature you want**
I propose the addition of a `test connection` button to assist users in verifying the accessibility of the tabby server host. 

**Details:**
1. **Location**: The `test connection` button should be positioned adjacent to the host input box, ensuring it's easily noticeable and accessible.
2. **Functionality**: Upon clicking the "test" button, a request should be made to the `v1/health` endpoint.
3. **Feedback Mechanism**: 
   - If the endpoint returns a positive response, a green checkmark or a message like "Host is accessible" should be displayed to the user.
   - If the endpoint returns an error or is not reachable, an error message should be displayed detailing the nature of the issue. For instance, "Host not reachable" or "Error: [specific error message from the endpoint]".
4. **Error Handling**: Proper error handling mechanisms should be in place to catch any exceptions or issues during the request, ensuring the user is always informed of the outcome.

   **IntelliJ**:
    <img width="500" alt="image" src="https://github.com/TabbyML/tabby/assets/24563928/68c7bfab-fd30-46dc-ac87-475d1393771f">
    **VS Code**:
    <img width="500" alt="image" src="https://github.com/TabbyML/tabby/assets/24563928/0e52617d-00a8-490a-844c-bde888408de8">

**Additional context**

Currently we can only see the status of the tabby server through the `StatusBar`. There is no very obvious means of detecting whether a tabby server is available. 

For example, when the tabby server cannot be accessed due to a proxy issue, the only way to troubleshoot the problem at the moment is to look at `idea.log`. 
Reference: [Slack discussion](https://tabbyml.slack.com/archives/C05CWLZ0Y85/p1693311149305459)

This feature is crucial for improving the user experience. By providing immediate feedback on the host's accessibility, users can rectify any issues immediately, ensuring smoother operations and reducing potential frustrations.

**Real world example**

<img src="https://github.com/TabbyML/tabby/assets/24563928/86ab5845-3c55-470a-9e54-201c6a1f6911" width = "500" />
<img src="https://github.com/TabbyML/tabby/assets/24563928/d8c47807-e598-41cf-b181-64da8faf797a" width = "500" />

---
Please reply with a 👍 if you want this feature.

cc @wsxiaoys

**Comment by icycodes** [comment]
Released in extensions v1.1.0:

For the IntelliJ plugin: we have added a `Check Connection` button. You can now use this button to verify the connection.

For the VSCode extension: since we utilize the default settings page of VSCode, adding a `Check Connection` button is not feasible. Instead, we have added a notification when the connection fails after modifying the endpoint configuration. If you need more error information, you can click on the `Detail` button to view it.
