### ISSUE TITLE
 IntelliJ IDEA  prompts  time out 

### ISSUE THREAD

**Issue by duhuangwen** [TabbyML/tabby#442]
**Describe the bug**
My laptop is Lenovo thinkbook 14+, i7-13700H, 32GB, no graphics card, running model is StarCoder-1B, call http://localhost:8080/v1/completions It takes about 4s, but the IntelliJ IDEA  prompts me to time out and let me use the smaller model.
I would like to know which model I can use and can I provide documentation for the configuration and the relationship of the model

**Information about your GPU**
Please provide output of `nvidia-smi`
no GPU

**Additional context**

**Comment by wsxiaoys** [comment]
Hi @duhuangwen,

I agree – this is something we should definitely document. I will prioritize it and aim to have the documentation updated by the end of this week.

In the meantime, I recommend trying `TabbyML/T5P-220M`, which is listed in the [Models Directory](https://tabby.tabbyml.com/docs/models/). You can choose this model based on your machine's configuration.

**Comment by duhuangwen** [comment]
@wsxiaoys thankyou for your help. I will try TabbyML/T5P-220M

**Comment by wsxiaoys** [comment]
Fixed in https://github.com/TabbyML/tabby/commit/5897a776bba9b3c0ac60e1a974d2bb62c7e24843
