### ISSUE TITLE
Metal option for --device not working 

### ISSUE THREAD

**Issue by trodriguez** [TabbyML/tabby#444]
**Describe the bug**
--device metal doesn't work

**Information about your GPU**
Apple M1 Max CPU/GPU

**Additional context**
Output when trying to run the latest version

<img width="565" alt="SCR-20230913-levj" src="https://github.com/TabbyML/tabby/assets/49533/40dac4d1-2b4e-4aa2-b8ea-3835f71c2beb">

**Comment by wsxiaoys** [comment]
hi, could you share the output of `tabby serve --help` and `which tabby`?

**Comment by trodriguez** [comment]
<img width="844" alt="SCR-20230913-puxs" src="https://github.com/TabbyML/tabby/assets/49533/c626b664-e39c-4422-9da0-a4a35d72b796">

Version 0.1.0 per the initial screenshot

**Comment by trodriguez** [comment]
Sorry you meant the command 'which tabby'... here you go:
<img width="224" alt="SCR-20230913-pvim" src="https://github.com/TabbyML/tabby/assets/49533/6ead62ec-342f-47e8-9c86-0b5f7a9f0a80">

**Comment by trodriguez** [comment]
I think I found the issue - I noticed that 'metal' in my command was underlined not sure how... I just retyped it and it seems to be working now.

**Comment by wsxiaoys** [comment]
So from first screen shot, `metal` is listed as a device. Could you try again with `tabby serve --device metal --model TabbyML/CodeLlama-7B`?

**Comment by trodriguez** [comment]
Sorry, another typo. I put 'Tabby/CodeLlama-7B' instead of 'TabbyML/CodeLlama-7B'
