### ISSUE TITLE
Other way to Download model 

### ISSUE THREAD

**Issue by XunHang** [TabbyML/tabby#448]
**Please describe the feature you want**
Because of net problem, I can not download model through init step of docker run.
So I git clone model from hugging face to my local path.

But when I git clone complete, dock still throw invalid model error:
![image](https://github.com/TabbyML/tabby/assets/17587962/2ba23d2f-81d8-49e7-9e43-0230d4135939)

**Additional context**
Maybe there is a way to download model file manual?

---
Please reply with a 👍 if you want this feature.

**Comment by XunHang** [comment]
And I am sure that I download all model files:
```shell
ll CodeLlama-7B         
total 51G
-rw-rw-r-- 1 xh xh  636 Sep  14 08:45 config.json
drwxrwxr-x 2 xh xh 4.0K Sep  14 09:26 ctranslate2
-rw-rw-r-- 1 xh xh  116 Sep  14 08:45 generation_config.json
drwxrwxr-x 2 xh xh 4.0K Sep  14 09:06 ggml
-rw-rw-r-- 1 xh xh 6.9K Sep  14 08:45 LICENSE
-rw-rw-r-- 1 xh xh 9.3G Sep  14 09:20 model-00001-of-00002.safetensors
-rw-rw-r-- 1 xh xh 3.3G Sep  14 09:11 model-00002-of-00002.safetensors
-rw-rw-r-- 1 xh xh  25K Sep  14 08:45 model.safetensors.index.json
-rw-rw-r-- 1 xh xh 9.3G Sep  14 09:20 pytorch_model-00001-of-00002.bin
-rw-rw-r-- 1 xh xh 4.6G Sep  14 09:18 pytorch_model-00001-of-00006.bin
-rw-rw-r-- 1 xh xh 3.3G Sep  14 09:11 pytorch_model-00002-of-00002.bin
-rw-rw-r-- 1 xh xh 4.6G Sep  14 10:21 pytorch_model-00002-of-00006.bin
-rw-rw-r-- 1 xh xh 4.6G Sep  14 08:59 pytorch_model-00003-of-00006.bin
-rw-rw-r-- 1 xh xh 4.6G Sep  14 08:59 pytorch_model-00004-of-00006.bin
-rw-rw-r-- 1 xh xh 4.6G Sep  14 08:59 pytorch_model-00005-of-00006.bin
-rw-rw-r-- 1 xh xh 2.6G Sep  14 09:18 pytorch_model-00006-of-00006.bin
-rw-rw-r-- 1 xh xh  24K Sep  14 08:45 pytorch_model.bin.index.json
-rw-rw-r-- 1 xh xh 6.5K Sep  14 08:45 README.md
-rw-rw-r-- 1 xh xh  411 Sep  14 08:45 special_tokens_map.json
-rw-rw-r-- 1 xh xh  143 Sep  14 08:45 tabby.json
-rw-rw-r-- 1 xh xh  745 Sep  14 08:45 tokenizer_config.json
-rw-rw-r-- 1 xh xh 1.8M Sep  14 08:45 tokenizer.json
-rw-rw-r-- 1 xh xh 489K Sep  14 09:11 tokenizer.model
-rw-rw-r-- 1 xh xh 4.7K Sep  14 08:45 USE_POLICY.md

```

**Comment by wsxiaoys** [comment]
Hi @XunHang 

Once you cloned the URL, please pass the absolute path to the cloned dir, instead of using model id format `TabbyML/CodeLlama-7B`.

In your case, below command should just work
```bash
docker run -it \
  --gpus all -p 8080:8080 -v $HOME/.tabby:/data \
  tabbyml/tabby \
  serve --model /data/models/TabbyML/CodeLlama-7B --device cuda
```

**Comment by XunHang** [comment]
Thank you! It works!

**Comment by wsxiaoys** [comment]
Just FYI, in version 0.2.1, we introduced an alternative registry in ModelScope. You can learn about its usage at https://tabby.tabbyml.com/docs/models/#alternative-registry

**Comment by Crescentz** [comment]
> Hi @XunHang
> 
> Once you cloned the URL, please pass the absolute path to the cloned dir, instead of using model id format `TabbyML/CodeLlama-7B`.
> 
> In your case, below command should just work
> 
> ```shell
> docker run -it \
>   --gpus all -p 8080:8080 -v $HOME/.tabby:/data \
>   tabbyml/tabby \
>   serve --model /data/models/TabbyML/CodeLlama-7B --device cuda
> ```

thread 'main' panicked at crates/tabby-common/src/registry.rs:119:9:
Invalid model id /home/zhang/StarCoder-1B
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
