### ISSUE TITLE
How do I convert codellama to the desired form of Tabby?

### ISSUE THREAD

**Issue by cxj01** [TabbyML/tabby#456]
How do I convert codellama to the desired form of Tabby?

**Comment by wsxiaoys** [comment]
Although we haven't provided comprehensive documentation, we've transformed the CodeLlama checkpoint into two versions: https://huggingface.co/TabbyML/CodeLlama-7B and https://huggingface.co/TabbyML/CodeLlama-13B, which you can use directly.

Or are you in the process of converting a fine-tuned checkpoint?

**Comment by cxj01** [comment]
@wsxiaoys I saw both versions and huggingface was too slow to download. I have the huggingface version of native codellama and want to convert it to the format required by tabby. I wonder if it is convenient to provide the corresponding documentation.

**Comment by Lucavon** [comment]
Sorry if this is Hijacking this post, but I've got a question regarding these models @wsxiaoys - I noticed that there is no 34B Model. Is it possible to use quantized 34B Models, such as https://huggingface.co/TheBloke/WizardLM-1.0-Uncensored-CodeLlama-34B-GGUF with Tabby, or will it be possible in the future? I've got this model running using llama.cpp and find it quite impressive, and was hoping I'd be able to use it with Tabby. 
Is it possible for me to convert it myself, maybe, as cxj01 originally asked?

**Comment by wsxiaoys** [comment]
Hi @cxj01 and @Lucavon, I've drafted https://github.com/TabbyML/tabby/pull/457 regarding Tabby's model specifications. You should be able to create a Tabby-compatible model directory by following the instructions in this document. Please let me know if you encounter any issues.

Thank you!

**Comment by wsxiaoys** [comment]
@Lucavon, Considering the model's size of 34B, I doubt it will be very useful given that we currently only support the code completion use case (a 33B model is likely to be very slow in completing a snippet).

Perhaps it will become useful after https://github.com/TabbyML/tabby/issues/306 is implemented.

**Comment by Lucavon** [comment]
Thanks for the update @wsxiaoys , I will do some experiments!

**Comment by cxj01** [comment]
@wsxiaoys 
I have converted the ctranslate2 format, but the class error is still reported!
![image](https://github.com/TabbyML/tabby/assets/37614132/4eb5e52d-a759-4f73-9444-3f9be01a4052)

**Comment by wsxiaoys** [comment]
> @wsxiaoys I have converted the ctranslate2 format, but the class error is still reported! ![image](https://user-images.githubusercontent.com/37614132/268598940-4eb5e52d-a759-4f73-9444-3f9be01a4052.png)

Could you try the latest docker image (`v0.1.1`)? Which should have upgraded model revision.

**Comment by cxj01** [comment]
I tried version 0.1.1 and still got the same error! Will it be my model turning problem?
![image](https://github.com/TabbyML/tabby/assets/37614132/8280f128-bc71-4ade-a9fb-7bc8a5f83e21)

**Comment by wsxiaoys** [comment]
That's pretty weird - the relevant commit https://github.com/TabbyML/tabby/commit/86e48afbe07ea94a70f0fec0fe26e20c9bbf45e4 is included in `v0.1.1`.

Could you share your ctranslate2 python package version, and might give `tabbyml/tabby:nightly` a try?

**Comment by cxj01** [comment]
ctranslate2==3.19.0   （Convert codellama to ctranslate2）

**Comment by cxj01** [comment]
> ctranslate2==3.19.0 （Convert codellama to ctranslate2）

@wsxiaoys

**Comment by cxj01** [comment]
I tried tabbyml/tabby:nightly and still got the same error! 
![image](https://github.com/TabbyML/tabby/assets/37614132/b050af14-81b0-43a4-a4cf-5fa185f41e41)

**Comment by cxj01** [comment]
@wsxiaoys 
I tried tabbyml/tabby:nightly and still got the same error!
![image](https://github.com/TabbyML/tabby/assets/37614132/2c805f30-7a43-4247-9a66-d54c9a1d39aa)

**Comment by wsxiaoys** [comment]
Fixed in #460 , could  you try latest tag `v0.1.2`?

**Comment by cxj01** [comment]
> Fixed in #460 , could you try latest tag `v0.1.2`?

Thank you! It work!
