### ISSUE TITLE
CodeGeex2 Support？

### ISSUE THREAD

**Issue by lxfriday** [TabbyML/tabby#462]
**Please describe the feature you want**

Will  CodeGeex2 be supported？

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Considering the [CodeGeeX2 license](https://github.com/THUDM/CodeGeeX2/blob/main/MODEL_LICENSE) explicitly prohibits commercial usage, it's unlikely that the Tabby team will maintain a supported version.

On the flip side, individuals could potentially create a Tabby-compatible model directory for CodeGeeX2 by following the guidelines outlined in the [MODEL_SPEC.md](https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md), provided it remains supported by ctranslate2.
