### ISSUE TITLE
Setup bump-homebrew-formula for tabby

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#464]
https://github.com/marketplace/actions/bump-homebrew-formula

target repo:
https://github.com/TabbyML/homebrew-tabby

**Comment by Zekrom-7780** [comment]
Can I work on this Issue?

**Comment by wsxiaoys** [comment]
Of course! Feel free to [DM me](https://twitter.com/mzh1024) if you require any environment variable settings in the workflow (such as a committer token?).
