### ISSUE TITLE
tabby docker keep redownloading the model

### ISSUE THREAD

**Issue by Red0Hood** [TabbyML/tabby#469]
**Describe the bug**
installed tabby docker downloaded model all good then restarted the pc and check the tabby log it redownload the model again i live in a shitty place where they give credit for bandwidth so yeah 
 is there a way to access where the model is place and manually do that 

**Information about your GPU**
Please provide output of `nvidia-smi`
gpu 1660 super
 NVIDIA-SMI 536.67                 Driver Version: 536.67       CUDA Version: 12.2

**Additional context**

**Comment by wsxiaoys** [comment]
Hi, could you share the log output from your docker daemon? Tabby does cache the model locally, but still going to output something like "downloading the model" before the cache check.

**Comment by wsxiaoys** [comment]
The logging information have been improved in v0.2.1
