### ISSUE TITLE
failed to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by ghavart** [TabbyML/tabby#481]
**Describe the bug**
Failed to build using 'cargo build'

**Information about your GPU**
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+

**Additional context**
'''
  running: cd "/home/art/code/third_party/tabby/target/debug/build/ctranslate2-bindings-8206bb512cd672a7/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/art/code/third_party/tabby/crates/ctranslate2-bindings/." "-DCMAKE_BUILD_TYPE=Release" "-DBUILD_CLI=OFF" "-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON" "-DBUILD_SHARED_LIBS=OFF" "-DWITH_MKL=OFF" "-DOPENMP_RUNTIME=NONE" "-DWITH_OPENBLAS=ON" "-DCMAKE_INSTALL_PREFIX=/home/art/code/third_party/tabby/target/debug/build/ctranslate2-bindings-8206bb512cd672a7/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -msse4.1 -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc"
  -- The C compiler identification is GNU 11.4.0
  -- The CXX compiler identification is GNU 11.4.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- ALL_LINK_LIBRARIES : 
  -- ALL_LIBS : 
  -- Configuring incomplete, errors occurred!

  --- stderr

  CXX include path:
    /home/art/code/third_party/tabby/target/debug/build/ctranslate2-bindings-8206bb512cd672a7/out/cxxbridge/include
    /home/art/code/third_party/tabby/target/debug/build/ctranslate2-bindings-8206bb512cd672a7/out/cxxbridge/crate
  CMake Error at CMakeLists.txt:5 (add_subdirectory):
    The source directory

      /home/art/code/third_party/tabby/crates/ctranslate2-bindings/CTranslate2

    does not contain a CMakeLists.txt file.

  thread 'main' panicked at '
  command did not execute successfully, got: exit status: 1

  build script failed, must exit now', /home/art/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/std/src/panicking.rs:593:5
     1: core::panicking::panic_fmt
               at /rustc/d5c2e9c342b358556da91d61ed4133f6f50fc0c3/library/core/src/panicking.rs:67:14
     2: cmake::fail
     3: cmake::run
     4: cmake::Config::build
     5: build_script_build::main
     6: core::ops::function::FnOnce::call_once

'''

**Comment by wsxiaoys** [comment]
It appears that the submodule has not been cloned. Please refer to https://github.com/TabbyML/tabby#get-the-code for instructions on how to clone the submodules.

**Comment by ghavart** [comment]
Thanks @wsxiaoys! This resolves my issue.
