### ISSUE TITLE
mac sonoma failed assertion computeFunction must not be nil

### ISSUE THREAD

**Issue by itswcg** [TabbyML/tabby#485]
**Describe the bug**
run `cargo run -- serve --device metal --model TabbyML/CodeLlama-13B`

console error:
Running `target/debug/tabby serve --device metal --model TabbyML/CodeLlama-13B`
INFO tabby::serve: crates/tabby/src/serve/mod.rs:154: Starting server, this might takes a few minutes...
ggml_metal_init: allocating
ggml_metal_init: found device: Apple M2 Max
ggml_metal_init: picking default device: Apple M2 Max
-[MTLComputePipelineDescriptorInternal setComputeFunction:withType:]:722: failed assertion `computeFunction must not be nil.'

**Information about your GPU**
Apple M2 Max

**Additional context**
mac version: sonoma

**Comment by wsxiaoys** [comment]
Could you share a bit more information about your system? I cannot reproduce the error you encounter on an Apple M2 Max + Sonoma mac

**Comment by itswcg** [comment]
code commit: 1d6ac783

Hardware Overview:
  Model Name: MacBook Pro
  Model Identifier: Mac14,5
  Chip: Apple M2 Max
  Total Number of Cores: 12 (8 performance and 4 efficiency)
  Memory: 64 GB
  System Firmware Version: 10151.1.1
  OS Loader Version: 10151.1.1
  Activation Lock Status: Enabled
  
sw_vers 
ProductName:            macOS
ProductVersion:         14.0
BuildVersion:           23A344

cargo --version                                                                                                                                                                                           
cargo 1.72.0 (103a7ff2e 2023-08-15)

**Comment by wsxiaoys** [comment]
After upgrading the Xcode command-line tools, I started encountering the same issue, looking into it...

**Comment by wsxiaoys** [comment]
fix in #486
