### ISSUE TITLE
VSCode Chat Window

### ISSUE THREAD

**Issue by Blumlaut** [TabbyML/tabby#506]
**Please describe the feature you want**
I've been loving the new "Chat Playground" Tabby has, one feature i would love to have in the official plugin would be the ability to have the Chat in a tab in VSCode, so i do not have to tab out / open it on a seperate browser, i have written a custom implementation for something like that for my own little plugin, it's essentially just an iframe, here is a [minimal example](https://gist.github.com/Blumlaut/f33af1b238a638bf9a7ddb49a40360d3) i threw together in an afternoon.

**Additional context**
Here is how this feature could look, if implemented:
![](https://github.com/TabbyML/tabby/assets/13604413/c1376bcb-8bea-4acf-93f4-b52a8dbfdbb4)

Thank you for your attention.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Hello! Thank you for the feature suggestion and the impressive extension demo!

At the moment, we are actively exploring the best UX to seamlessly integrate the playground into the IDE/Editor Extension. Therefore, the definitive plan is still in the process of being finalized.

In the meantime, as a temporary solution, you may find it helpful to utilize the "Simple Browser" command in Visual Studio Code, as illustrated in the screenshot, to achieve the same experience in this case.

<img width="2039" alt="image" src="https://github.com/TabbyML/tabby/assets/388154/1531bbe1-3c21-48ed-9c4d-e8d4c9be51db">

**Comment by Blumlaut** [comment]
thanks for your swift reply, I didn't even know simple browser was a thing, the more you know! 😆
