### ISSUE TITLE
is always Failed to fetch model 'TabbyML/SantaCoder-1B'

### ISSUE THREAD

**Issue by newyorkthink** [TabbyML/tabby#515]
my local folder is have SantaCoder-1B 
![image](https://github.com/TabbyML/tabby/assets/87791643/24cb36e7-e038-4551-80e7-66b1ea745ce1)

but is always show

![image](https://github.com/TabbyML/tabby/assets/87791643/533604df-0b84-4cb6-9e1b-69e71c5215bd)

**Comment by wsxiaoys** [comment]
Hi, were you able to access huggingface? what's the output of following command in your environment?

```bash
curl -v https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/tabby.json
```

**Comment by newyorkthink** [comment]
> Hi, were you able to access huggingface? what's the output of following command in your environment?
> 
> ```shell
> curl -v https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/tabby.json
> ```

![image](https://github.com/TabbyML/tabby/assets/87791643/5a3e6a59-834b-428f-9663-e8cf483fce9a)

**Comment by newyorkthink** [comment]
> Hi, were you able to access huggingface? what's the output of following command in your environment?
> 
> ```shell
> curl -v https://huggingface.co/TabbyML/SantaCoder-1B/resolve/main/tabby.json
> ```

```
{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim-prefix>{prefix}<fim-suffix>{suffix}<fim-middle>"
}

```

**Comment by newyorkthink** [comment]
![image](https://github.com/TabbyML/tabby/assets/87791643/5725783a-59c6-49d6-b1b9-889d4aa35c52)

**Comment by wsxiaoys** [comment]
In this case - could you try remove the ~/.tabby/models/TabbyML/SantaCoder-1B dir, and retry the downloading?

**Comment by newyorkthink** [comment]
> In this case - could you try remove the ~/.tabby/models/TabbyML/SantaCoder-1B dir, and retry the downloading?

i try this ,but i allow show Failed to fetch model too

**Comment by wsxiaoys** [comment]
Is this happen for you on all models (e.g TabbyML/StarCoder), or just on SantaCoder-1B

**Comment by newyorkthink** [comment]
> Is this happen for you on all models (e.g TabbyML/StarCoder), or just on SantaCoder-1B

is happen for all models 

![image](https://github.com/TabbyML/tabby/assets/87791643/9ab77ffe-e848-4935-b35d-0dbe8ea66e8b)

![image](https://github.com/TabbyML/tabby/assets/87791643/2d932e20-39a6-47d6-9629-ba51b27664d3)

**Comment by wsxiaoys** [comment]
In that case, it's likely related to your network or VPN configurations.

Are you a user from mainland China? If so, you might want to consider trying an alternative registry at https://tabby.tabbyml.com/docs/models/#alternative-registry.

**Comment by newyorkthink** [comment]
> In that case, it's likely related to your network or VPN configurations.
> 
> Are you a user from mainland China? If so, you might want to consider trying an alternative registry at https://tabby.tabbyml.com/docs/models/#alternative-registry.

![image](https://github.com/TabbyML/tabby/assets/87791643/196e78b3-5cd9-4f4c-bf9f-38e42fed4187)

is error

**Comment by newyorkthink** [comment]
![image](https://github.com/TabbyML/tabby/assets/87791643/27637996-8822-4ab6-adb6-5d0e670e3cec)

**Comment by wsxiaoys** [comment]
Hi, to set environment variable for docker, you need to use `-e` parameter, so it should be something like:
```bash
docker run -e TABBY_REGISTRY=modelscope ..... tabbyml/tabby serve --model TabbyML/SantaCoder-1B ....
```

**Comment by newyorkthink** [comment]
> In that case, it's likely related to your network or VPN configurations.
> 
> Are you a user from mainland China? If so, you might want to consider trying an alternative registry at https://tabby.tabbyml.com/docs/models/#alternative-registry.

![image](https://github.com/TabbyML/tabby/assets/87791643/a48ad393-2b50-4494-b20e-9c8930ce1a94)

i try , but not work
![image](https://github.com/TabbyML/tabby/assets/87791643/dc126f84-18de-40d7-b970-882ec83ed187)

**Comment by wsxiaoys** [comment]
Hi, forgot to mention, we only support models listed in https://tabby.tabbyml.com/docs/models/#alternative-registry

so you probably wanna use `TabbyML/SantaCoder-1B` instead

**Comment by newyorkthink** [comment]
> Hi, forgot to mention, we only support models listed in https://tabby.tabbyml.com/docs/models/#alternative-registry
> 
> so you probably wanna use `TabbyML/StarCoder-1B` instead

not working again
![image](https://github.com/TabbyML/tabby/assets/87791643/2beea1d6-9e35-4674-a2b9-46597ee6b996)

![image](https://github.com/TabbyML/tabby/assets/87791643/76339c21-b878-4957-a3e2-af2e6e189f5c)

**Comment by newyorkthink** [comment]
i use this , 
![image](https://github.com/TabbyML/tabby/assets/87791643/f5a56c1f-fd5b-4d74-a900-f0d9d39293af)

it can download
![image](https://github.com/TabbyML/tabby/assets/87791643/db307da8-a7df-4cbd-b96b-d10c331daf75)


but ,i move this folder in ~/.tabby/models/TabbyML

it allow show : ``` ERROR tabby::serve: crates/tabby/src/serve/mod.rs:276: Failed to fetch model```

**Comment by wsxiaoys** [comment]
Hi, if you clone the directory directly, then you can pass its path to `--model` as is, instead of copying it to `~/.tabby/models/TabbyML`

**Comment by newyorkthink** [comment]
> Hi, if you clone the directory directly, then you can pass its path to `--model` as is, instead of copying it to `~/.tabby/models/TabbyML`

it is this command

```
docker run -it \
  --gpus all -p 8080:8080 -v $HOME/.tabby:/data \
  -e TABBY_REGISTRY=modelscope \
  tabbyml/tabby \
  serve --model /home/thinker/Downloads/StarCoder-1B --device cuda
```

**Comment by newyorkthink** [comment]
to change this path

**Comment by newyorkthink** [comment]
i try, when i downloaded, i try this command

**Comment by wsxiaoys** [comment]
You still need to mount the directory to docker image to access it, so let's say you cloned the directory to `/home/thinker/Downloads/StarCoder-1B`, you might use the following snippet:

```bash
docker run -it \
  --gpus all -p 8080:8080 -v $HOME/.tabby:/data -v  /home/thinker/Downloads/StarCoder-1B:/models/StarCoder-1B \
  tabbyml/tabby \
  serve --model /models/StarCoder-1B --device cuda
```

**Comment by newyorkthink** [comment]
> You still need to mount the directory to access it, so let's say you cloned the directory to `/home/thinker/Downloads/StarCoder-1B`, you might use the following snippet:
> 
> ```shell
> docker run -it \
>   --gpus all -p 8080:8080 -v $HOME/.tabby:/data -v  /home/thinker/Downloads/StarCoder-1B:/models/StarCoder-1B \
>   tabbyml/tabby \
>   serve --model /models/StarCoder-1B --device cuda
> ```

![image](https://github.com/TabbyML/tabby/assets/87791643/152c2573-cafc-4639-90c3-633f7d77bed1)
![image](https://github.com/TabbyML/tabby/assets/87791643/f2c8510f-7972-47b7-98d7-2e4a73219269)

it is ok?

**Comment by newyorkthink** [comment]
> You still need to mount the directory to access it, so let's say you cloned the directory to `/home/thinker/Downloads/StarCoder-1B`, you might use the following snippet:
> 
> ```shell
> docker run -it \
>   --gpus all -p 8080:8080 -v $HOME/.tabby:/data -v  /home/thinker/Downloads/StarCoder-1B:/models/StarCoder-1B \
>   tabbyml/tabby \
>   serve --model /models/StarCoder-1B --device cuda
> ```

i gpu is laptop 2080 , so, what is better model to laptop

**Comment by newyorkthink** [comment]
Code Llama 7B vs  StarCoder- 7B
what is better?

**Comment by wsxiaoys** [comment]
Closing as this is resolved
