### ISSUE TITLE
CMake Error at CTranslate2/CMakeLists.txt:269 (message):   Intel OpenMP runtime libiomp5 not found

### ISSUE THREAD

**Issue by gaojing8500** [TabbyML/tabby#519]
![image](https://github.com/TabbyML/tabby/assets/20908110/58ddd043-7259-4dd3-8913-e185e20b7f85)

**Comment by gaojing8500** [comment]
sh cmake/debug_cmake.sh

**Comment by wsxiaoys** [comment]
Hi @gaojing8500 - Could you share the process the command to reproduce your issue?

**Comment by gaojing8500** [comment]
![image](https://github.com/TabbyML/tabby/assets/20908110/cc611f28-3881-4938-9a93-fe3d2169cf77)
The main problem that CUDA cannot be used

**Comment by wsxiaoys** [comment]
Hello! If your goal is to run Tabby with CUDA, would you consider using our packaged Docker image? An example command can be found here: https://tabby.tabbyml.com/docs/installation/docker.

**Comment by gaojing8500** [comment]
> ![image](https://user-images.githubusercontent.com/20908110/273429354-cc611f28-3881-4938-9a93-fe3d2169cf77.png) The main problem that CUDA cannot be used

The problem has been resolved
1、git clone https://github.com/OpenNMT/CTranslate2.git && git submodule update --init --recursive
2、Adding one line of code as shown in the following figure can compile tabby that supports cuda
![image](https://github.com/TabbyML/tabby/assets/20908110/7f906129-543c-4f07-ae84-33387c500196)

**Comment by wsxiaoys** [comment]
Great, you've figured it out! Currently, we only support CUDA through a shared library build, wherein CTranslate2 is prebuilt with CUDA in the Docker image.

Are you looking for a solution with a statically built binary? Could you share the use case?

**Comment by thangld201** [comment]
Hi @gaojing8500 @wsxiaoys , I also see 
```
Intel OpenMP runtime libiomp5 not found
```
when compiling, how did you solve the error ?
