### ISSUE TITLE
StarCoder-7B model suggests irrelevant metadata

### ISSUE THREAD

**Issue by jtbr** [TabbyML/tabby#523]
When using the StarCoder-7B model with Python, I'm getting suggestions that contain metadata, rather than just the code itself.
eg:

```
<fim-prefix>import torch<fim-suffix>
<fim-prefix>import torch.nn as nn<fim-suffix>
<fim-prefix>import torch.nn.functional as F<fim-suffix>
<fim-prefix>import torch.optim as optim<fim-suffix>
<fim-middle>
<fim-prefix>class Net(nn.Module):<fim-suffix>
```

This does not happen with SantaCoder-1B or CodeLlama-7B. I'm using a Nvidia 2060 desktop GPU for the -7B models, CPU for SantaCoder. The suggestions are via the Tabby plugin to VS Code.

Many thanks for your efforts, very impressed with Tabby so far!

**Comment by wsxiaoys** [comment]
This is indeed a bug in the `prompt_template`! I have fixed it in this pull request: [Link to the pull request](https://huggingface.co/TabbyML/StarCoder-7B/commit/d9f361fdf808e8b236fa4d51d45ac2e8b98d677f)

Thank you for reporting this!
