### ISSUE TITLE
error while loading shared libraries: libopenblas.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by newyorkthink** [TabbyML/tabby#528]
the v0.2.2 version have bug
![image](https://github.com/TabbyML/tabby/assets/87791643/fba9bddf-580f-4c26-9c8d-6d2cad58066f)

i suggestion: merge libopenblias in Appimage Format

Appimage format files it can run every

I have to build some good software to appimage,  like Vandyke software 
![image](https://github.com/TabbyML/tabby/assets/87791643/7bc3aa1b-da3c-4842-9e5f-3a00a66152f1)

**Comment by newyorkthink** [comment]
and like nvtop have appimage too
![image](https://github.com/TabbyML/tabby/assets/87791643/e89bad71-40c0-4ff4-b705-949b226916d3)

**Comment by newyorkthink** [comment]
https://github.com/Syllo/nvtop/issues/169

**Comment by wsxiaoys** [comment]
The `libopenblas-dev` library is a runtime requirement for the currently released Linux binary (https://github.com/TabbyML/tabby/blob/main/ci/prepare_build_environment.sh#L8). This requirement should be documented prior to the release on package manager channels, such as Homebrew.

**Comment by newyorkthink** [comment]
> The `libopenblas-dev` library is a runtime requirement for the released cpu binary (https://github.com/TabbyML/tabby/blob/main/ci/prepare_build_environment.sh#L8). This requirement should be documented prior to the release on package manager channels, such as Homebrew.

linux is better , mac os not have support appimage format file.

**Comment by newyorkthink** [comment]
the modern cmd or other software there have support appimage
