### ISSUE TITLE
Add support for Refact

### ISSUE THREAD

**Issue by Corly** [TabbyML/tabby#533]
**Please describe the feature you want**

Refact is leading the charts for code generation when taking into account the ratio between model size and accuracy. I am particularly interested in support for Apple M1/M2, but this feature request targets every scenario where it can be used.

**Additional context**
Recently llama.cpp added support for converting Refact hf to gguf. So, I think this should be similar to the starcoder integration. Thank you!

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Thank you for sharing the FR. Creating a HF model for refact on metal should be relatively straightforward, following the guidelines outlined in https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md

However, as of now, ctranslate2 does not support this feature, so the model won't run on a CUDA/CPU device at the moment.

**Comment by oleksii-shyman** [comment]
Hi @wsxiaoys, I am completely new to AI \ models \ this project, but I am interested in contributing.
It is not really clear what should be done.
Do I understand correctly that:

1. There is a `refact` model somewhere on huggingface
2. The goal of this task is:
2.a. to add deployment scripts to the model on the users machine
2.b. to add json file from the link above
