### ISSUE TITLE
change port

### ISSUE THREAD

**Issue by firien** [TabbyML/tabby#534]
**Describe the bug**
Trying to change to port 8081
> tabby serve --device metal --model TabbyML/StarCoder-1B --port 8081

Starts fine and reports `Listening at 0.0.0.0:8081`, but
> curl -X POST http://localhost:8081/v1/health

just hangs. Omitting the port and using default `8080` - everything works.

**Information about your GPU**
Using tabby [v0.2.2](https://github.com/TabbyML/tabby/releases/tag/v0.2.2) with Apple `M1` chip

**Additional context**
I am running the [tabby_aarch64-apple-darwin](https://github.com/TabbyML/tabby/releases/download/v0.2.2/tabby_aarch64-apple-darwin) executable directly. I did not install via homebrew.

**Comment by firien** [comment]
Well, crap I must have had another service running on 8081. Other ports seem to work.

**Comment by wsxiaoys** [comment]
Glad you've figure it out!

**Comment by incoggnito** [comment]
![image](https://github.com/TabbyML/tabby/assets/44142874/fc28959c-de76-4a36-ac06-0181db176bf9)

Strange maybe i'm also wrong. But  the swagger ui and the curl posts are working:
`{"model":"TabbyML/StarCoder-1B","device":"cuda","arch":"x86_64","cpu_info":"Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz","cpu_count":8,"cuda_devices":["NVIDIA GeForce RTX 2060"],"version":{"build_date":"2023-12-15","build_timestamp":"2023-12-15T05:54:46.222708135Z","git_sha":","git_describe":"v0.7.0"}}`

I've already restarted vscode, but it seems not to work.
