### ISSUE TITLE
vim cannot accept auto-completion

### ISSUE THREAD

**Issue by newdee** [TabbyML/tabby#551]
**Describe the bug**
I use Plug to add tabby, and enable it, so it can show the code suggestion, 
<img width="1340" alt="image" src="https://github.com/TabbyML/tabby/assets/12610440/93068a2f-7022-48a1-a690-32617b48120c">

<img width="1340" alt="image" src="https://github.com/TabbyML/tabby/assets/12610440/389d55d8-6a35-46bd-8531-993456e186f3">
but when i use tab, it just input tab, cannot accept the suggestion.
<img width="1340" alt="image" src="https://github.com/TabbyML/tabby/assets/12610440/f9814ded-27d7-4304-bea5-7d4a91b54b25">
Even if I change the binding key, it still doesn’t take effect。
what should i do? Any answer will be helpful.
Thanks

**Information about your GPU**

I use it in MacOS, M2

**Comment by icycodes** [comment]
Hi, @newdee

Do you have other plugins that might change the behavior of `<tab>`, such as other completion providers?  
And could you share the output of `:map!`?

You can also try to remap keybinding manually using `imap <script><silent><nowait><expr> <tab> tabby#Accept("\t")` to see if it works.

**Comment by newdee** [comment]
> Hi, @newdee
> 
> Do you have other plugins that might change the behavior of `<tab>`, such as other completion providers? And could you share the output of `:map!`?
> 
> You can also try to remap keybinding manually using `imap <script><silent><nowait><expr> <tab> tabby#Accept("\t")` to see if it works.

Thanks @icycodes
I haven't found any plugin to bind the tab key，and after using imap <script><silent><nowait><expr> <tab> tabby#Accept("\t"), it still cannot accept the suggestion,
<img width="1340" alt="image" src="https://github.com/TabbyML/tabby/assets/12610440/6f3282f9-b70d-41c4-a273-a84a961b1d17">
<img width="1340" alt="image" src="https://github.com/TabbyML/tabby/assets/12610440/d4d2a731-4061-48c0-b6b3-d689bd5b8cf3">
my vimrc config is as follows:
```
set nocompatible
filetype off
filetype plugin on
filetype plugin indent on
set foldenable
set foldlevel=1
set foldmethod=indent

set fenc=utf-8
set fencs=utf-8,usc-bom,euc-jp,gb18030,gbk,gb2312,cp936
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4

set showcmd
set showmode
set report=0
set showmatch
set ignorecase
set smartcase
set incsearch
set autoindent
set smartindent
set paste

set undofile
set undodir=/Users/dfine/.vim/.undodir
set undolevels=1000

set nu
set laststatus=2
syntax on

set cursorcolumn
set cursorline

set history=2000

set backspace=2
set ruler
set rulerformat=%20(%2*%<%f%=\ %m%r\ %3l\ %c\ %p%%%)


"save fold info
autocmd BufWinLeave * mkview
autocmd BufWinEnter * silent loadview
"autocmd BufWinEnter * if get(v:argv, 1, '') != '-' | silent loadview | endif





if !has('gui_running')
  set t_Co=256
endif


let g:lightline = {
      \ 'colorscheme': 'wombat',
      \ }


call plug#begin()


Plug 'preservim/nerdtree'
Plug 'preservim/nerdcommenter'
Plug 'Yggdroot/LeaderF', {'do': ':LeaderfInstallCExtention' }
Plug 'itchyny/lightline.vim'
Plug 'airblade/vim-gitgutter'
Plug 'jiangmiao/auto-pairs'
Plug 'axiaoxin/vim-json-line-format'
Plug 'ycm-core/YouCompleteMe'
Plug 'airblade/vim-gitgutter'
Plug 'NLKNguyen/papercolor-theme'
Plug 'rust-lang/rust.vim'
Plug 'racer-rust/vim-racer'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'prabirshrestha/vim-lsp' " 代码补全、错误检查等
Plug 'dense-analysis/ale' " 异步语法检查和代码格式化
"Plug 'vim-airline/vim-airline' " 状态栏美化
Plug 'TabbyML/tabby', {'rtp': 'clients/vim'}





call plug#end()



let g:rustfmt_autosave = 1 " 保存时自动格式化
let g:rustfmt_command = "rustfmt" " 自定义格式化命令
" ALE 配置
let g:ale_linters = {'rust': ['cargo', 'clippy'],}
let g:ale_fixers = {'rust': ['cargo', 'rustfmt'],}
let g:ale_rust_cargo_use_clippy = 1 " 使用 clippy 进行更严格的检查


" Set URL of Tabby server
let g:tabby_server_url = 'http://127.0.0.1:8080'
let g:tabby_accept_binding = '<tab>'
let g:tabby_dismiss_binding = '<C-]>'

" 快捷键映射
" 在可视模式下选中一段文本，执行 ft 进行格式化
vnoremap <leader>ft :RustFmtRange<CR>
" 普通模式下执行 ft 进行格式化
nnoremap <leader>ft :RustFmt<CR>
" 普通模式下，按Meta/Option键+r，执行运行
nnoremap <M-r> :RustRun<CR>
" 普通模式下，按Meta/Option键+t, 执行测试
nnoremap <M-t> :RustTest<CR>


colorscheme PaperColor

"map keys
map <C-n> :NERDTreeToggle<CR>


```

**Comment by icycodes** [comment]
Hi, @newdee 
It seems that the issue is related to the `set paste` option.  
Tabby uses a [paste command `<C-R><C-O>`](https://github.com/TabbyML/tabby/blob/main/clients/vim/autoload/tabby.vim#L451) to insert completion text. When `set paste` is on, this command will not work as intented.

Could you try to run `:set nopaste` and accept a completion again?

**Comment by newdee** [comment]
> Hi, @newdee It seems that the issue is related to the `set paste` option. Tabby uses a [paste command `<C-R><C-O>`](https://github.com/TabbyML/tabby/blob/main/clients/vim/autoload/tabby.vim#L451) to insert completion text. When `set paste` is on, this command will not work as intented.
> 
> Could you try to run `:set nopaste` and accept a completion again?

yes, it worked after set nopaste,
thank you
