### ISSUE TITLE
Mac Silicon supported?

### ISSUE THREAD

**Issue by aldoyh** [TabbyML/tabby#56]
Hello,

I tried it on my Mac OS and I got this error:

https://app.warp.dev/block/0irl2mLPBzNRJCWZIXUtFI

Any help?

**Comment by tleers** [comment]
You should be able to avoid this error by adding `--platform linux/amd64`.

E.g. 

> docker run \
  -it --rm \
  -v ./data:/data \
  -v ./data/hf_cache:/home/app/.cache/huggingface \
  -p 5000:5000 \
  --platform linux/amd64 \
  -e MODEL_NAME=TabbyML/J-350M \
  tabbyml/tabby

**Comment by wsxiaoys** [comment]
close in favor of #57

**Comment by glennfu** [comment]
I got past this and just wanted to confirm regarding the original Issue title: Is it actually possible to use this with an M1 Mac? As far as I can tell, it's not possible to install CUDA on an M1 Mac.

When I try myself with this I get `[FT][ERROR] CUDA runtime error: CUDA driver version is insufficient for CUDA runtime version /workspace/build/fastertransformer_backend/build/_deps/repo-ft-src/src/fastertransformer/utils/cuda_utils.h:327`

**Comment by JakeSchroeder** [comment]
Any update on this?

> I got past this and just wanted to confirm regarding the original Issue title: Is it actually possible to use this with an M1 Mac? As far as I can tell, it's not possible to install CUDA on an M1 Mac.
> 
> When I try myself with this I get `[FT][ERROR] CUDA runtime error: CUDA driver version is insufficient for CUDA runtime version /workspace/build/fastertransformer_backend/build/_deps/repo-ft-src/src/fastertransformer/utils/cuda_utils.h:327`

Any progress on this? Im also hoping to run on my m1 🥹

**Comment by glennfu** [comment]
I think the creation of this new thread clarifies that the current answer is "no" but that there's a great deal of interest: https://github.com/TabbyML/tabby/issues/66
