### ISSUE TITLE
idea plugins bug not fixed, 

### ISSUE THREAD

**Issue by newyorkthink** [TabbyML/tabby#562]
![image](https://github.com/TabbyML/tabby/assets/87791643/52b887f6-f65d-4986-bf44-52a3105feb67)

**Comment by wsxiaoys** [comment]
Hi @newyorkthink, thanks for reporting the issue. Can you configure node path in Tabby plugging config?

**Comment by newyorkthink** [comment]
> Hi @newyorkthink, thanks for reporting the issue. Could you set node path in Tabby plugin config?

how to set node path in Tabby plugin config

**Comment by newyorkthink** [comment]
![Uploading image.png…]()
it work
