### ISSUE TITLE
detected dubious ownership in repository

### ISSUE THREAD

**Issue by bubundas17** [TabbyML/tabby#569]
I am using the 
Reposotry context index option as mentioned in this page.
https://tabby.tabbyml.com/docs/configuration

i am manually indexing the repo after i pushed some changes. by opening Docker Desktop and running.
```./tabby  scheduler --now```

But getting This error:
```sh
root@f9def54c9ee9:/opt/tabby/bin# ./tabby  scheduler --now
2023-10-16T19:56:59.375047Z  INFO tabby_scheduler: crates/tabby-scheduler/src/lib.rs:15: Syncing repositories...
fatal: detected dubious ownership in repository at '/data/repositories/<redacted>.git'
To add an exception for this directory, call:

        git config --global --add safe.directory /data/repositories/<redacted>.git
2023-10-16T19:56:59.397967Z ERROR tabby_scheduler: crates/tabby-scheduler/src/lib.rs:18: Failed to sync repositories, err: 'Failed to pull remote '<redacted>.git'. Consider remove dir '/data/repositories/<redacted>.git' and retry'
```

**Comment by wsxiaoys** [comment]
Hi @bubundas17,

Could you try the nightly docker tag (`tabbyml/tabby:nightly`) to see if #571 fix the issue for you?

**Comment by bubundas17** [comment]
Yes it fixes it for me.

**Comment by wsxiaoys** [comment]
Wonderful! The change will be included in the upcoming patch release, v0.3.1.

**Comment by bubundas17** [comment]
Think you for the quick fix. 
Have been using this project for a week now. I must say its really good.

Keep up the good work.

**Comment by wsxiaoys** [comment]
Released in https://github.com/TabbyML/tabby/releases/tag/v0.3.1

**Comment by qy527145** [comment]
@bubundas17 你创建index花了多久，我一直卡在crates/tabby-scheduler/src/lib.rs:30: Indexing repositories...，目前已经40分钟了，查看/data/index，发现里面的文件不断变化，这种情况正常吗？
