### ISSUE TITLE
Error when using relative paths for Docker data volumes

### ISSUE THREAD

**Issue by tleers** [TabbyML/tabby#57]
Following the README.md and using `Docker version 20.10.21, build baeda1f` on Mac M1 with the following commands:

```bash
docker run \
  -it --rm \
  -v ./data:/data \
  -v ./data/hf_cache:/home/app/.cache/huggingface \
  -p 5000:5000 \
  -e MODEL_NAME=TabbyML/J-350M \
  tabbyml/tabby
```
leads to the following error:

> docker: Error response from daemon: create ./data: "./data" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.

**SOLUTION**

```bash
docker run \    
  -it --rm \
  -v "/$(pwd)/data:/data" \
  -v "/$(pwd)/data/hf_cache:/home/app/.cache/huggingface" \
  -p 5000:5000 \
  --platform linux/amd64 \
  -e MODEL_NAME=TabbyML/J-350M \
  tabbyml/tabby
```

for explanation, see:
https://docs.docker.com/storage/bind-mounts/
https://stackoverflow.com/questions/46526165/docker-invalid-characters-for-volume-when-using-relative-paths

**Comment by icycodes** [comment]
Updated documentation in #60.
