### ISSUE TITLE
Time out for CPU setup

### ISSUE THREAD

**Issue by FGora** [TabbyML/tabby#570]
When using the docker container with CPUs only I will run into the time out of 3s. I tried with the setup:
model: TabbyML/J350M
device: cpu
arch: x86_64
cpu_info: Common KVM processor
cpu_count: 16

Is there a possibility to configure the timeout limit? 
Is there a minimal CPU set up that is not running in this timeout?

Thanks for your help and all the good work
Best

**Comment by wsxiaoys** [comment]
Hi, could you please share the command to start the container?

Currently, the timeout is not configurable, as anything beyond 3 seconds would not be very practical to use.

However, I am open to add this timeout config in the following file: https://github.com/TabbyML/tabby/blob/main/crates/tabby-common/src/config.rs#L12

**Comment by FGora** [comment]
Thanks for the fast reply.
The command is:
docker run -ti -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/J-350
I agree that every request over 3s is not really usable, but I would like to get a minimal setup with CPUs before I invest more in a more scalable solution. The solution via the config file would be great.
Best

**Comment by Red007Master** [comment]
+ testing bigger model and i would like to know "how it works" without "Most completion requests timed out.".

**Comment by wsxiaoys** [comment]
Thank you for the feedback. I agree that the current experience is not optimal. CPU users should, at the very least, be able to try out the suggestion quality.

As a workaround, please visit https://tabby.tabbyml.com/playground if you don’t have access to GPU devices.
