### ISSUE TITLE
"mkdir: cannot create directory '/data/config': Operation not permitted" when running Tabby Docker container on Mac M1

### ISSUE THREAD

**Issue by tleers** [TabbyML/tabby#58]
Using Mac M1 and the following for running the Docker container:

```bash
# Create data dir and grant owner to 1000 (Tabby run as uid 1000 in container)
sudo mkdir -p data/hf_cache && chown -R 1000 data

docker run \
  -it --rm \
  -v "/$(pwd)/data:/data" \
  -v "/$(pwd)/data/hf_cache:/home/app/.cache/huggingface" \
  -p 5000:5000 \
  --platform linux/amd64 \
  -e MODEL_NAME=TabbyML/J-350M \
  tabbyml/tabby
```

I get this error output:

> WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
>    Use the NVIDIA Container Toolkit to start this container with GPU support; see
>    https://docs.nvidia.com/datacenter/cloud-native/ .
> 
> ERROR: This container was built for CPUs supporting at least the AVX instruction set, but
>        the CPU detected was , which does not report
>        support for AVX.  An Illegal Instrution exception at runtime is likely to result.
>        See https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX .
> 
> **mkdir: cannot create directory '/data/config': Operation not permitted**

Is this error related to incompatibility with Mac M1, the docker run command, or something entirely different?

**Comment by agilob** [comment]
You executed `sudo mkdir -p data/hf_cache && chown -R 1000 data`

but then you are mounting `"/$(pwd)/data`

I know it's a bit wrong to give such permissions, but this isn't "deployment or repo problem, but it's on your side, just do 
`sudo chmod 777 "/$(pwd)/data" -R` or wherever you **really** created the `data/hf_cache`

**Comment by tleers** [comment]
good spot, thanks @agilob 

for those who make the same mistake:
`sudo chown -R $USER data`
works perfectly for local deployment on Mac M1.
