### ISSUE TITLE
Evaluation page for models

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#590]
**Please describe the feature you desire:**

Create an evaluation page for following models:
- https://huggingface.co/TabbyML/StarCoder-1B
- https://huggingface.co/TabbyML/StarCoder-3B
- https://huggingface.co/TabbyML/StarCoder-7B
- https://huggingface.co/TabbyML/CodeLlama-7B
- https://huggingface.co/TabbyML/CodeLlama-13B

To accomplish this, generate an evaluation result for tabby API for each model in various languages. Specifically, we need to compute `rg1_bm25`, so this evaluation will utilize the following four files as prompts:

```
./crosscodeeval_data/python/line_completion_rg1_bm25.jsonl
./crosscodeeval_data/typescript/line_completion_rg1_bm25.jsonl
./crosscodeeval_data/java/line_completion_rg1_bm25.jsonl
./crosscodeeval_data/csharp/line_completion_rg1_bm25.jsonl
```

Tasks
- [ ] Provide python script + instructions to run evaluation job on modal (PR to ./experimental/cceval)
- [ ] Run evaluation on all models x languages, providing the evaluation result (including output under `output_dir`).

**Additional context:**
1. Please present results for one run on small model ensure the correctness before doing the remainings.
2. Overall, this requires a total of 4 x 5 = 20 runs. Based on a quick estimate, this will likely take around 30 hours on a A100 (costing $3.73 per hour on modal.com).
3. Relevant example: https://github.com/TabbyML/tabby/blob/main/experimental/eval/tabby.py

**Comment by wsxiaoys** [comment]
/bounty 300

We will provide an API token to execute the job on the modal, ensuring that the GPU cost is covered by us.

**Comment by wsxiaoys** [comment]
Hello @evoxf1, we are seeking someone with experience in working with Transformers, specifically LLM, and PyTorch. If you encounter any challenges beyond what was mentioned above, I will be more than happy to assist you. Feel free to reach out to us on the Slack channel.

**Comment by evoxf1** [comment]
@evoxf1  sorry but I resign, I am new.

**Comment by NishanthMolleti** [comment]
@yan91083 can I join you on this task?

**Comment by leiwen83** [comment]
Hi ~,

where those files located?
```
./crosscodeeval_data/python/line_completion_rg1_bm25.jsonl
./crosscodeeval_data/typescript/line_completion_rg1_bm25.jsonl
./crosscodeeval_data/java/line_completion_rg1_bm25.jsonl
./crosscodeeval_data/csharp/line_completion_rg1_bm25.jsonl
```

I cannot find in current repo...

**Comment by rFantic** [comment]
Hi @wsxiaoys, from cceval paper, I assume this need to calculate both Code Match and Identifier Match metrics for each run, right? Is there anything else?

**Comment by wsxiaoys** [comment]
that's pretty much of it - but kindly remind that @yan91083 has started working on this.

**Comment by rFantic** [comment]
> that's pretty much of it - but kindly remind that @yan91083 has started working on this.

Ah, i didn't notice, thanks for clarifying.
