### ISSUE TITLE
Add docs on how to add an API key or other headers to the http requests

### ISSUE THREAD

**Issue by pypeaday** [TabbyML/tabby#598]
I put my tabby server behind traefik reverse-proxy and I would like to protect the route with an apikey, however I do not know how to add my apikey to my tabby requests

**Additional context**
I use Vim - should be irrelevant since I imagine this would be (or is and I just don't know where to do it) a general tabby configuration setting

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
If you're validating an API key embedded in the HTTP header, you may want to refer to the documentation located at `~/.tabby-client/agent/config.toml`. Additionally, there is an example in the [Hugging Face documentation](https://tabby.tabbyml.com/docs/installation/hugging-face/#connect-vscode-extension-to-space-backend) that utilizes the authorization header.

**Comment by pypeaday** [comment]
Thanks that's great!
