### ISSUE TITLE
Adding model supporting CJK characters to model directory

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#603]
**Please describe the feature you want**
For now models listed supports only latin characters, it'll be nice if there can be choices supporting CJK characters.

**Additional context**

https://github.com/TabbyML/tabby/issues/600

---
Please reply with a 👍 if you want this feature.

**Comment by yusiwen** [comment]
👍

**Comment by wsxiaoys** [comment]
Related: https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-base

MIT licensed

**Comment by wsxiaoys** [comment]
Both DeepseekCoder / CodeQwen supports CJK well
