### ISSUE TITLE
how do I access the cli if the docker container is non interactive?

### ISSUE THREAD

**Issue by RUGMJ** [TabbyML/tabby#606]
Or is it possible to serve the backend without docker?

**Comment by wsxiaoys** [comment]
Could you provide further details regarding your goal? For instance, what command would you like to execute if the container is interactive?

**Comment by RUGMJ** [comment]
from the docs it seems there a `tabby` binary with some cli commands, seeing as the docker container is non interactive how would I access this binary to execute the extra commands like `tabby scheduler`

**Comment by wsxiaoys** [comment]
You could start a separate container, e.g

```
docker run -it -v $HOME/.tabby:/data tabbyml/tabby scheduler --now
```

**Comment by RUGMJ** [comment]
would that interact correctly with the existing instance though?

**Comment by RUGMJ** [comment]
yeah all good thanks
