### ISSUE TITLE
Build with compute capability 6.1

### ISSUE THREAD

**Issue by luanshaotong** [TabbyML/tabby#62]
Nice to have access to such a great open source project. I tried running it on my tesla p40 but failed. Can you please provide the compilation method of the model so that I can try to compile it myself using compute capability 6.1.
By the way, is there a model with more parameters to try?

**Comment by wsxiaoys** [comment]
Yes, we could add SM 60~62 for Pascal support.

We’re working on releasing our own models, please follow the progress in #51

**Comment by LoopControl** [comment]
+1 for Compute 6.1 (I'm also have a P40)

**Comment by wsxiaoys** [comment]
https://github.com/TabbyML/fastertransformer_backend/commit/b3804e0cf07bfe3310599b9a572d06f8a8325ed8

**Comment by LoopControl** [comment]
5 minute response with a code commit? <3

**Comment by wsxiaoys** [comment]
Support for Pascal NVIDIA GPUs has been added to the latest docker image (sha256:ea0cdcb2d4bba01f1e9dc58ce3799b875f751bf41f286b3d87fe85948478aee1), Please give it a try!

**Comment by LoopControl** [comment]
Works for me after pulling latest image thanks!

```
-------------------------------+----------------------+----------------------+
|   1  Tesla P40           Off  | 00000000:02:00.0 Off |                  Off |
| N/A   48C    P0    52W / 130W |   2180MiB / 24576MiB |      0%      Default |
```

**Comment by LoopControl** [comment]
Also, from above log, it says "`max_length` is set to 128". Is there an environment variable or something that would increase that 128 token limit to get longer suggestions?

**Comment by wsxiaoys** [comment]
> Also, from above log, it says "`max_length` is set to 128". Is there an environment variable or something that would increase that 128 token limit to get longer suggestions (both input and output token max length)?

Nope. If this is something that interests you, please open a new issue for it.

**Comment by wsxiaoys** [comment]
Fixed in https://github.com/TabbyML/tabby/commit/b9f902e5fc9d10e667d99e688ff72082e392bf41
