### ISSUE TITLE
Invalid metadata file: /data/models/SantaCoder-1B/tabby.json

### ISSUE THREAD

**Issue by jingshne** [TabbyML/tabby#641]
I downloaded santacoder-1B locally, but when running it,：
docker run -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model /data/models/SantaCoder-1B
I got the following error message:

2023-10-26T01:58:28.587043Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:143: Starting server, this might takes a few minutes...
2023-10-26T01:58:28.587726Z ERROR tabby::serve::engine: crates/tabby/src/serve/engine.rs:109: Invalid metadata file: /data/models/SantaCoder-1B/tabby.json

What is the problem here and how should I resolve it?"

**Comment by wsxiaoys** [comment]
Could youshare the filetree located at ~/.tabby/models/SantaCoder-1B? I'm particularly interested in the content of the tabby.json file. Additionally, could you provide the SHA version of the Docker image?

**Comment by jingshne** [comment]
ok,
this file tree :
└── SantaCoder-1B
    ├── config.json
    ├── ctranslate2
    │   ├── config.json
    │   ├── model.bin
    │   └── vocabulary.txt
    ├── model.safetensors
    ├── pytorch_model.bin
    ├── README.md
    ├── special_tokens_map.json
    ├── tabby.json
    ├── tabby.json.backup
    ├── tokenizer_config.json
    └── tokenizer.json
content of the tabby.json:
{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim-prefix>{prefix}<fim-suffix>{suffix}<fim-middle>"
}

the SHA version of the Docker image:
tabbyml/tabby   latest    sha256:48c86dd6e752c2773222b70463399eaf9643ca00b28b309dc581246fd669411f   50f0da20e2ad

**Comment by jingshne** [comment]
{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim-prefix>{prefix}<fim-suffix>{suffix}<fim-middle>"
}

**Comment by jingshne** [comment]
content of the tabby.json:
`{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim-prefix>{prefix}<fim-suffix>{suffix}<fim-middle>"
}`

**Comment by wsxiaoys** [comment]
Could you try with the latest released docker image - `v0.4.0`?

**Comment by jingshne** [comment]
> Could youshare the filetree located at ~/.tabby/models/SantaCoder-1B? I'm particularly interested in the content of the tabby.json file. Additionally, could you provide the SHA version of the Docker image?

I have provided further information, thank you for your help

**Comment by jingshne** [comment]
> Could you try with the latest released docker image - `v0.4.0`?

I do not have a NVIDIA graphics card, and after using the 0.4.0 source code to perform a Docker build, I was prompted that no graphics card was detected. Is there an option to control whether to use the CPU or GPU during the Docker build? 
Thank you for your help！

**Comment by shaozhaozhao** [comment]
#711  refers to my solution by set up alias name with model id

**Comment by wsxiaoys** [comment]
fixed in 0.5.5
