### ISSUE TITLE
Apple Silicon Support ( w/ CPU inference)

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#66]
Currently, we only support inference on CUDA. However, it would be advantageous to expand our support to include M1/M2, as many developers work on Mac laptops.

We'd like to revisited the feature once ggml became stable

References
1. https://github.com/ggerganov/ggml
2. https://github.com/NolanoOrg/cformers

Please reply with a 👍 if you want this feature.

**Comment by cwwmbm** [comment]
Definitely +1 on the M1 support!

**Comment by wsxiaoys** [comment]
related: https://github.com/mlc-ai/mlc-llm

**Comment by wsxiaoys** [comment]
Hello!

Thank you for your message. I wanted to let you know that I have just added the very first version of Apple Silicon support. If you're interested, I would appreciate it if you could give it a try by following these steps:

1. Download the `tabby_aarch64-apple-darwin` file from this link: https://github.com/TabbyML/tabby/suites/13205372288/artifacts/719099228.
2. Execute the following commands in your terminal:

```bash
# Download the model locally.
tabby download --model TabbyML/J-350M

# Serve the model.
PORT=8080
tabby serve --model TabbyML/J-350M --port $PORT
```

After completing these steps, you can configure the API endpoint to http://localhost:8080/ in the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=TabbyML.vscode-tabby).

I would be very interested in hearing about your experience with the new feature and learning from your feedback. Thank you in advance!

**Comment by wsxiaoys** [comment]
FYI, just added automatic release process at: https://github.com/TabbyML/tabby/releases/tag/latest

**Comment by chanansh** [comment]
followed the instruction above. The server is running and `Listening at 0.0.0.0:8080`
the vscode extension is installed and by default configured to endpoint http://localhost:8080
however, I don't get any sweet suggestions :-(

**Comment by wsxiaoys** [comment]
Hi @chanansh 

Could you please share some examples of bad suggestions that you have received?

**Comment by chanansh** [comment]
I don't get suggestions at all. That's the issue.
When I logged in to the server via browser it seems to work. I guess the client in the vscode extension is faulty (p.s. there is no validation "connected to server successfully"). Or,.maybe the inference is too slow.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by wsxiaoys** [comment]
Could you please try opening Swagger UI at `http://localhost:8080` and check if it provides any response when accessing the `/v1/completions` endpoint?

**Comment by chanansh** [comment]
I did that. That's what I meant when I said the server works when I visit it in the url.
Anyway, it seems like I have started to get suggestions! Maybe there is a warmup period. However most of them are pretty bad. Too long and halosinations.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
