### ISSUE TITLE
 Failed to fetch model '<any model>' due to 'Failed to fetch url...

### ISSUE THREAD

**Issue by vimasig** [TabbyML/tabby#663]
**Describe the bug**
The issue I am experiencing is that no matter what I try, I always receive an error message when attempting to use Tabby. I have attempted to use a VPN with different countries, but this has not resolved the issue. I am not located in China. I have also tried following the steps outlined in #515, which involved manually cloning the StarCoder-1B model and providing the exact location in the docker command. this resulted in a different error message.
![image](https://github.com/TabbyML/tabby/assets/70583277/d5176be3-72bb-4c93-ba4b-d0ef03d5b25e)

**Information about your GPU**
nvidia-smi is not installed. I am currently using a Linux virtual machine.

**Additional context**
I have also tried removing the $HOME/.tabby directory and changing the volume path to "$HOME/.tabby2", but this did not resolve the issue.

I have attempted to use different models, including CodeLlama-7B, StarCoder-3B, and StarCoder-1B, but all of them have failed.

**Comment by wsxiaoys** [comment]
It seems you're running at a old docker version - could you double check?

> Unsupported model binary version.
This executable supports models with binary version v6 or below, but the model has binary version 1936876918. This usually means that the model was generated by a later version of CT
ranslate2. (Forward compatibility is not guaranteed.)

**Comment by vimasig** [comment]
My docker version is
![image](https://github.com/TabbyML/tabby/assets/70583277/815e5080-dae5-4cef-8365-f4aee12e1e25)

Which is new enough according to [docker.com](https://docs.docker.com/engine/release-notes)
![image](https://github.com/TabbyML/tabby/assets/70583277/eb48945c-d2e8-4a24-b7c6-081c1261103a)

But still, I updated it to 24.0.7 which is the latest version of Docker right now as of 10/30/2023
![image](https://github.com/TabbyML/tabby/assets/70583277/f57e4e06-0ec9-4ca9-b9f0-affe12d7d3e0)

Same result ☹️
![image](https://github.com/TabbyML/tabby/assets/70583277/f7489a62-41d7-4626-a518-5b9053b23f96)

**Comment by wsxiaoys** [comment]
sorry - by old `docker version` i really mean that you probably use an old docker image version. Could you try replacing `tabbyml/tabby` with `tabbyml/tabby:0.4.0` in your command?

**Comment by vimasig** [comment]
Tried these, still same
![image](https://github.com/TabbyML/tabby/assets/70583277/76bb9740-9282-48ae-8a8e-21e0e45204aa)

**Comment by wsxiaoys** [comment]
<img width="296" alt="image" src="https://github.com/TabbyML/tabby/assets/388154/22679743-ff26-4897-9660-14cc0a28f482">

Just realized the parsed binary version of ctranslate2 is an invalid number - this usually means that the file you downloaded is broken or incomplete. How did you download the model? Could you share the command?

**Comment by wsxiaoys** [comment]
Have you installed git lfs https://git-lfs.com/ ?

**Comment by vimasig** [comment]
Just realized that StarCoder-1B folder was 4MB 😮
Now it works using locally installed model

In case anyone needs the command: `sudo apt install git-lfs -y`

![image](https://github.com/TabbyML/tabby/assets/70583277/e57c440c-675c-41e1-8ac5-3105ad23238a)

I don't know if we should close this issue as resolved because my problem (and issue title) was connection.
I'm ok with using manually installed models though

**Comment by vimasig** [comment]
![image](https://github.com/TabbyML/tabby/assets/70583277/b5cb9090-fa09-4ee3-9e9f-0b64cc531586)

```bash
kubuntu@kubuntu-pc:~$ sudo docker run -it -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B
2023-10-31T05:21:34.694908Z ERROR tabby::serve: crates/tabby/src/serve/mod.rs:278: Failed to fetch model 'TabbyML/StarCoder-1B' due to 'Failed to fetch url https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json'
kubuntu@kubuntu-pc:~$ curl https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json
{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim_prefix>{prefix}<fim_suffix>{suffix}<fim_middle>"
}
kubuntu@kubuntu-pc:~$ sudo docker run -it -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby download --model TabbyML/StarCoder-1B
2023-10-31T05:26:01.777562Z ERROR tabby::download: crates/tabby/src/download.rs:24: Failed to fetch model 'TabbyML/StarCoder-1B' due to 'Failed to fetch url https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json'
kubuntu@kubuntu-pc:~$
```

**Comment by wsxiaoys** [comment]
It appears that you are unable to access Hugging Face. Since you are not based in China, I would assume that some specific network configuration has blocked Hugging Face. If this is the case, there isn't much we can do to resolve the issue....

**Comment by vimasig** [comment]
Actually, I can access to huggingface website. But I don't know the correct response for "https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json" URL. As I said, I tried different countries using VPN and tried Tor too. Always getting the same response from that URL. 
I don't know if that response is what it should be. Should I get a different response from that URL?

![image](https://github.com/TabbyML/tabby/assets/70583277/9cb780a6-523d-4a3d-b02c-84c54dae3fb9)

**Comment by wsxiaoys** [comment]
Are you able to access the file through the command line? e.g

```bash
% curl https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json
{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim_prefix>{prefix}<fim_suffix>{suffix}<fim_middle>"
}

```

**Comment by vimasig** [comment]
![image](https://github.com/TabbyML/tabby/assets/70583277/549dc819-2155-4a8c-a645-4284ad7bd40e)

```bash
kubuntu@kubuntu-pc:~$ curl https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json
{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim_prefix>{prefix}<fim_suffix>{suffix}<fim_middle>"
}
kubuntu@kubuntu-pc:~$
```

**Comment by vimasig** [comment]
Just found out that my docker containers cannot access to anything
```bash
kubuntu@kubuntu-pc:~$ sudo docker run -it --rm curlimages/curl google.com
curl: (6) Could not resolve host: google.com
kubuntu@kubuntu-pc:~$ sudo docker run -it --rm alpine/curl https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json
curl: (6) Could not resolve host: huggingface.co
kubuntu@kubuntu-pc:~$
```

I don't know how is this possible with default Docker installation, but I'll figure it out.
Sorry for wasting your time, we can close this issue 🙂

**Comment by wsxiaoys** [comment]
No worries, glad we've figured it out!
