### ISSUE TITLE
How to load custom LLM CodeGeneration model with tabby docker image?

### ISSUE THREAD

**Issue by bonuschild** [TabbyML/tabby#686]
## Background

I would like to run a custom codellama model like the below on WSL2 nvidia docker:
- https://huggingface.co/codellama/CodeLlama-7b-hf
- https://huggingface.co/TheBloke/CodeLlama-7B-Instruct-AWQ

I've also noticed that tabbyML also host some same name model on huggingface. What is the difference? I saw there are both `pytorch model` and `safetensors` exists at the same time, whcih make the repository download size doubled and don't know which version of model is the tabbyML used.

Now I've pass local model direcotry on windows to the docker with command:
```bash
docker run -it --gpus all -p 8080:8080 \
-v $HOME/.tabby:/data \
-v /mnt/e/Downloads/models:/models \
tabbyml/tabby serve --model XXX
```
## Question(s)
- Is my operation correct? And will setting variable `XXX` to `/models/path/to/custom/CodeLLAMA/model` works?
  > Because my GPU is 3060 with only 12GB VRAM so that it can not run the full 7B codellama model...that is why I would like to run the quantized model instead :)
- Is tabby vscode extension uses standard OpenAI API? I am thinking if tabby extension works with other backend server that serves with same OpenAI API like [vllm](https://github.com/vllm-project/vllm) and others. In this way I can not only benefit from the convenience of tabby plugin but also skip the unclearance of binding-usage of tabby self-hosted model.
  > Because for now I still not figure out whether tabby docker image can use alternative LLM model or not yet.

**Comment by icycodes** [comment]
Hi, @bonuschild 
* Your command to run the local model is correct. You can find our [models directory here](https://tabby.tabbyml.com/docs/models/), and detailed [explanation here](https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md).
* Tabby VSCode extension uses [Tabby server API](https://tabby.tabbyml.com/api/completion).

**Comment by wsxiaoys** [comment]
Note this will be greatly simplified in release of v0.5:

See https://github.com/TabbyML/tabby/blob/simplify-download-management/MODEL_SPEC.md for details

**Comment by hxt365** [comment]
Hi @icycodes @wsxiaoys, I plan to run big models like Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4 with Tabby. Does Tabby support running arbitrary LLM models on HF? Or any recommended way?
Currently I'm running Qwen/Qwen2.5-72B-Instruct-GPTQ-Int4 with vLLM and it works very well. I'm afraid of moving to Ollama or Llama.cpp as vLLM is apparently faster

**Comment by wsxiaoys** [comment]
You can connect Tabby to the VLLM-served chat API through the `[model.chat.http]` configuration in `config.toml`. Please check https://tabby.tabbyml.com/docs/references/models-http-api/openai/ for more information.
