### ISSUE TITLE
support brew services

### ISSUE THREAD

**Issue by Metallicbai** [TabbyML/tabby#687]
I expect tabby to support brew services。

**Comment by wsxiaoys** [comment]
Great idea, especially considering that we've already made some progress in that direction: https://github.com/TabbyML/tabby/issues/624#issuecomment-1778283444.

Should be something on our list once we have autostart functionality integrated into the tabby server

**Comment by G07cha** [comment]
Having a background service might require storing some of the CLI flags in configuration files, would extending `~/.tabby/config.toml` be an appropriate place for it?

**Comment by wsxiaoys** [comment]
Looking at redis's service: https://github.com/Homebrew/homebrew-core/blob/d44658d419d2cc661ad63c77546eb18300adc662/Formula/r/redis.rb#L43

It seems the argument could be passed in as environment flag in the formula?

**Comment by G07cha** [comment]
Do you mean something like `CONFIG_FILE=... brew services start tabby`?

**Comment by wsxiaoys** [comment]
initial support added in https://github.com/TabbyML/homebrew-tabby/pull/6
