### ISSUE TITLE
repo context feature broken in the latest 6.0-dev?

### ISSUE THREAD

**Issue by leiwen83** [TabbyML/tabby#703]
Hi,

In the last time, I test tabby with its 5.x, the repo context completion feature works well, as it demo in [blog](https://tabby.tabbyml.com/blog/2023/10/16/repository-context-for-code-completion/). It correctly find the right file completions.rs, and get the right result.

However, with latest code, I try this feature again, but find now tabby cannot give the right context. So where shall I begin to debug to find this error?
```
// Path: crates/http-api-bindings/src/fastchat.rs
// struct Request {
//     model: String,
//     prompt: Vec<String>,
//     max_tokens: usize,
//     temperature: f32,
// }
//
// Path: crates/http-api-bindings/src/fastchat.rs
// self
//             .client
//             .post(&self.api_endpoint)
//             .json(&request)
//             .send()
//             .await
//             .expect("Failed to making completion request")
//
// Path: crates/http-api-bindings/src/fastchat.rs
// resp.json().await.expect("Failed to parse response")
//
// Path: crates/http-api-bindings/src/fastchat.rs
// println!("Request failed: {}", err)
//
// Path: crates/http-api-bindings/src/lib.rs
// serde_json::from_str(model).expect("Failed to parse model string")
//
// Path: crates/http-api-bindings/src/lib.rs
// fn get_param(params: &Value, key: &str) -> String {
//     params
//         .get(key)
//         .unwrap_or_else(|| panic!("Missing {} field", key))
//         .as_str()
//         .expect("Type unmatched")
//         .to_string()
// }
```

Beside this, I find only vscode completion could triggle the repo context feature, while I try with intellij, it seems to me there is no context being generated for prompt template.

**Comment by wsxiaoys** [comment]
Can you please confirm if it is functional in version 0.5.0? It appears to me that there have been no changes related to the repository context since version 0.5.0.
You can review the changes here: https://github.com/TabbyML/tabby/compare/v0.5.0...main

**Comment by leiwen83** [comment]
I try 0.5.0, but found context is the same. not sure which component is broken, so where shall I begin to investigate this issue? Do you have any suggestion?

**Comment by wsxiaoys** [comment]
So this means the below statement no longer holds, correct?
>  I test tabby with its 5.x, the repo context completion feature works well

**Comment by leiwen83** [comment]
> So this means the below statement no longer holds, correct?
> 
> > I test tabby with its 5.x, the repo context completion feature works well

This statement is what I try some times before, which I verified. But in the current time&env, I no longer get it working...

**Comment by leiwen83** [comment]
I try git bisect to locate the problem, and confirm before below patch, indexing works well, while with this patch, the error occurs.

```
From e4efcc4091b3083a560089331a69011e86c294fd Mon Sep 17 00:00:00 2001
From: Meng Zhang <meng@tabbyml.com>
Date: Thu, 2 Nov 2023 18:13:28 -0700
Subject: [PATCH] fix: avoid special keywords (e.g AND) failed the query
 parsing (#695)
```

**Comment by wsxiaoys** [comment]
Based on my debugging the repository context is working as intended - maybe some filtering logic inside for `completion_prompt.rs` caused the diff you observed
