### ISSUE TITLE
raise error "misaligned address" when using with VS Code Plugin

### ISSUE THREAD

**Issue by bonuschild** [TabbyML/tabby#707]
**Describe the bug**
execute `docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data -e TABBY_DISABLE_USAGE_COLLECTION=1 tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda` successfully but come with error output about 2 minutes later:
```
2023-11-06T05:39:01.947324Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:145: Starting server, this might takes a few minutes...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3060, compute capability 8.6
2023-11-06T05:39:12.906458Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:164: Listening at 0.0.0.0:8080

CUDA error 716 at /root/workspace/crates/llama-cpp-bindings/llama.cpp/ggml-cuda.cu:7280: misaligned address
current device: 0
```
**Information about your version**

- run with latest docker version of tabby on Nov 6, 2023

**Information about your GPU**
```
Mon Nov  6 13:45:06 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.05              Driver Version: 536.23       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3060        On  | 00000000:07:00.0  On |                  N/A |
| 30%   40C    P8              11W / 170W |   1906MiB / 12288MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```
**Additional context**
- Error occurs when cooperate with VS Code plugins `tabby` writing this code:
 
```python
def main():
    a = 1
    b = 2
    # calculate a+b
    # crash when cursor in this pos :(


if __name__ == "__main__":
    main()
```

**Comment by wsxiaoys** [comment]
Hey - could you try if 0.5.5 release fixes the issue for you @bonuschild ?

**Comment by bonuschild** [comment]
@wsxiaoys Yup and I'll try it out later!

**Comment by Aismaelinc** [comment]
Hi @wsxiaoys

I have the same problem with the CUDA error after running TabbyML with StarCoder-1B. I tried updating to version 0.5.5, but it didn't fix it. The error still happens a couple of minutes after starting. Any ideas on what to do next?

Thanks!

**Comment by wsxiaoys** [comment]
Hey @Aismaelinc - could you share the system information (e.g output of `/v1/health`) here?

**Comment by Aismaelinc** [comment]
Hi, thank you for your response. I believe I might have a solution for my situation.

Below is my Docker build command script:

`sudo docker run -m="24g" -e "LLAMA_CPP_PARALLELISM=1" --name=TabbyML-StarCoder-3B  -it --gpus '"device=1"' -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-3B --device cuda`

I'm using WSL2 on Windows 11 with Ubuntu 20.04 in the subsystem.

In my previous setup, I had a GT-1030 as a secondary graphics adapter for display outputs and an RTX 3070 as the primary graphics adapter. When I ran the script, I received the following output after a few minutes:

`File exists. Resuming.
🎯 Downloaded https://huggingface.co/TabbyML/StarCoder-3B/resolve/main/ggml/q8_0.v2.gguf to /data/models/TabbyML/StarCoder-3B/ggml/q8_0.v2.gguf.tmp
   00:04:02 ▕████████████████████▏ 3.15 GiB/3.15 GiB  13.33 MiB/s  ETA 0s.                                              2023-11-11T11:25:27.409892Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:146: Starting server, this might takes a few minutes...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3070, compute capability 8.6
  Device 1: NVIDIA GeForce GT 1030, compute capability 6.1
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce RTX 3070) as main device
2023-11-11T11:25:45.348974Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:165: Listening at 0.0.0.0:8080

CUDA error 716 at /root/workspace/crates/llama-cpp-bindings/llama.cpp/ggml-cuda.cu:7293: misaligned address
current device: 0`

However, when I tested this on a plain Ubuntu 22.04 system with the same hardware configuration, it worked without any issues.

Also, replacing the GT-1030 with a GTX-1080 as the secondary graphics card in the system resulted in successful and stable operation:

`2023-11-13T07:16:27.758407Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:146: Starting server, this might takes a few minutes...
ggml_init_cublas: GGML_CUDA_FORCE_MMQ:   no
ggml_init_cublas: CUDA_USE_TENSOR_CORES: yes
ggml_init_cublas: found 2 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3070, compute capability 8.6
  Device 1: NVIDIA GeForce GTX 1080, compute capability 6.1
ggml_cuda_set_main_device: using device 0 (NVIDIA GeForce RTX 3070) as main device
2023-11-13T07:17:14.590258Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:165: Listening at 0.0.0.0:8080`


This leads me to believe that the issue might be related to the specific combination of graphics cards in the WSL2 environment.
