### ISSUE TITLE
How to use specified model to be loaded into tabby?

### ISSUE THREAD

**Issue by bonuschild** [TabbyML/tabby#708]
I run tabby with docker like official tutorial:
```bash
docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B --device cuda
```
And then I found that it always use the `GGUF` format file as model instead of `pytorch_model.bin` or `*.safetensors`. How is this happen and can we specific which one to use? Even in `GGUF` format there are some alternative to choose.

And this is using the model in `tabbyML` repositories. Can I use the original repositories from `codellama-7/13/34b` model? How can I make this?

**Comment by wsxiaoys** [comment]
Hi, loading gguf after version 0.5.0 is working as intended (WAI). The model registry is defined using a JSON file, which you can find at https://github.com/TabbyML/registry-tabby/blob/main/models.json. All other files, such as `pytorch_model.bin`, are irrelevant.

If you'd like to specify a different gguf, you can create your own registry by forking the TabbyML/registry-tabby repository.

**Comment by bonuschild** [comment]
> Hi, loading gguf after version 0.5.0 is working as intended (WAI). The model registry is defined using a JSON file, which you can find at https://github.com/TabbyML/registry-tabby/blob/main/models.json. All other files, such as `pytorch_model.bin`, are irrelevant.
> 
> If you'd like to specify a different gguf, you can create your own registry by forking the TabbyML/registry-tabby repository.

And how to load my modified registry json file? I would prefer to load them on disk(downloaded before) instead of downloading from huggingface in realtime.

**Comment by wsxiaoys** [comment]
Loading a local model differs slightly. For more details, please refer to https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md.

**Comment by wsxiaoys** [comment]
Document updated
