### ISSUE TITLE
How to specify download mirror 

### ISSUE THREAD

**Issue by shaozhaozhao** [TabbyML/tabby#710]
Hi guys

I wonder if anyone can show me how to use the instrction in here 
https://tabby.tabbyml.com/docs/models/#model-mirrors

I have try different ways to use this command,
first I use this in shell 
`export TABBY_DOWNLOAD_HOST=modelscope.cn`
'docker run -it -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B'

It does not work as it still fetch model from Hugging Face, 

Later I maunally change the model configuration file at ~/.tabby/model.json and replace the "StarCoder-1B" url path to "ttps://modelscope.cn/api/v1/models/TabbyML/StarCoder-1B/repo?FilePath=ggml/q8_0.v2.gguf", still, it failed by redirct to hugging face. 

any suggestion to use this command?

**Comment by icycodes** [comment]
Hi, @shaozhaozhao 
To pass environment variables into a Docker container, you can use the -e flag. Here's an example command:
```
docker run -it -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby -e TABBY_DOWNLOAD_HOST=modelscope.cn serve --model TabbyML/StarCoder-1B
```

**Comment by shaozhaozhao** [comment]
![Capture](https://github.com/TabbyML/tabby/assets/108786165/4229c79f-bc20-4fb1-aece-5200df504900)

Thanks for instant reply, its sees that the command is not correct.

I simply copy and paste the command to the shell and it throws errors. Did I miss something in there?

**Comment by shaozhaozhao** [comment]
Hi I resolve the problem by put the -e ahead as 
`docker run -it -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby  serve --model TabbyML/StarCoder-1B`

now it can download the model
