### ISSUE TITLE
Docker: Use CPU docker version but it raise a CUDA error

### ISSUE THREAD

**Issue by shaozhaozhao** [TabbyML/tabby#711]
**Describe the bug**
Hi when I run the CPU docker command, it download the model but can not start the service. 

**Information about your version**
tabbyml/tabby     latest    b1a3f710d841   2 days ago    2.14GB

**Information about your GPU**
Only CPU

**Additional context**
input 
`docker run -it -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby  serve --model TabbyML/StarCoder-1B`

get output 
`CUDA error 35 at /root/workspace/crates/llama-cpp-bindings/llama.cpp/ggml-cuda.cu:5740: CUDA driver version is insufficient for CUDA runtime version`

Since I get a images which updates 2 days ago, perhaps someone update  a decifent one to the docker?
![Capture](https://github.com/TabbyML/tabby/assets/108786165/bc6bc8aa-e605-4b0e-8ae6-a65a02750d80)

**Comment by wsxiaoys** [comment]
Please note that version 0.5.0 has a problem supporting CPU-only use cases, as indicated by this warning: https://github.com/TabbyML/tabby/releases/tag/v0.5.0.

We are actively collaborating with the upstream team to address this issue as soon as possible.

**Comment by shaozhaozhao** [comment]
I wonder if there is alternative solution, I use this command for pathway
`docker run -it -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby:0.4.0  serve --model TabbyML/StarCoder-1B`

it ends with 
"2023-11-07T02:06:37.547338Z ERROR tabby::serve: crates/tabby/src/serve/mod.rs:278: Failed to fetch model 'TabbyML/StarCoder-1B' due to 'Failed to fetch url https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/tabby.json'"

sees that for use in China who does not have GPU avaible can not experience the tabbyml feature at the moment.

**Comment by wsxiaoys** [comment]
Could you give it a try with the `0.5.2-rc.0`: https://hub.docker.com/layers/tabbyml/tabby/0.5.2-rc.0/images/sha256-e4372b38b4486259a7838a45d97b1d174f7910991a69c1bd5c228c2ad3957f61?context=explore ?

**Comment by shaozhaozhao** [comment]
I use this command to fetch the latest version

docker run -it -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby:0.5.2-rc.0  serve --model TabbyML/StarCoder-1B

it end with 

Failed to fetch model organization <TabbyML>: error sending request for url (https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

I try the following command to verify it 
wget https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json

see that the docker container can not read the dns properly
![Capture](https://github.com/TabbyML/tabby/assets/108786165/76bea142-63c9-4cae-84da-fbcc76f03799)

If there is any suggetion to overpath the problem , just to let me know and I will try it

**Comment by wsxiaoys** [comment]
The reason is that raw.githubusercontent.com appears to be blocked in mainland China

**Comment by shaozhaozhao** [comment]
I did read the page you mentioned. But I may have some miss understanding. Hope you can point out where I get wrong

1. make sure the local model is loaded, which means the file exit "q8_0.v2.gguf"
the model to the local file, see the pciture below
![model_downloaded](https://github.com/TabbyML/tabby/assets/108786165/563f3f0f-df7d-40ea-8367-0dd9f509227a)


2. run the docker and spcify the model 
when I run the docker command, as following, 408e1dc1ecf4 is the container id
docker run -it -p 8080:8080  408e1dc1ecf4 serve --model TabbyML/StarCoder-1B

it throw an error message as:
Failed to fetch model organization <TabbyML>: error sending request for url (https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

3. the article show one can change the "models.json" file. the local model path is "/root/.tabby/models/TabbyML/StarCoder-1B/ggml/q8_0.v2.gguf" and I found there is model json file at "/root/.tabby/models/TabbyML/models.json", and I modified the file, within the file, find "StarCoder-1B", replace the url "https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/ggml/q8_0.v2.gguf" with "/root/.tabby/models/TabbyML/StarCoder-1B/ggml/q8_0.v2.gguf"

run  the command again
"docker run -it -p 8080:8080  408e1dc1ecf4 serve --model TabbyML/StarCoder-1B"
it sees that I misunderstad the concept of model id

4. find a article which tell me that model id can be replaced. So I change the model id by 
docker run -it -p 8080:8080 -v $HOME/.tabby:/data -v  /root/.tabby/models/TabbyML/StarCoder-1B:/models/StarCoder-1B  tabbyml/tabby:0.5.2-rc.0  serve --model /models/StarCoder-1B 

it shows 
'''
2023-11-08T02:44:23.939513Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:135: Loading model from local path /models/StarCoder-1B
2023-11-08T02:44:23.939565Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:146: Starting server, this might takes a few minutes...
'''
but when I use docker ps -a, all containers are dead. 
![model_id_replaced](https://github.com/TabbyML/tabby/assets/108786165/fdda31f2-dfaf-4fb6-adab-5b2138ddb262)

something is wrong in here, but where I can find a log to give your more information?

**Comment by shaozhaozhao** [comment]
I did read the page you mentioned. But I may have some miss understanding. Hope you can point out where I get wrong

1. make sure the local model is loaded, which means the file exit "q8_0.v2.gguf"
the model to the local file, see the pciture below
![model_downloaded](https://github.com/TabbyML/tabby/assets/108786165/134983d3-926b-445d-8319-1913006f61b9)

2. run the docker and spcify the model 
when I run the docker command, as following, 408e1dc1ecf4 is the container id
docker run -it -p 8080:8080  408e1dc1ecf4 serve --model TabbyML/StarCoder-1B

it throw an error message as:
Failed to fetch model organization <TabbyML>: error sending request for url (https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

3. the article show one can change the "models.json" file. the local model path is "/root/.tabby/models/TabbyML/StarCoder-1B/ggml/q8_0.v2.gguf" and I found there is model json file at "/root/.tabby/models/TabbyML/models.json", and I modified the file, within the file, find "StarCoder-1B", replace the url "https://huggingface.co/TabbyML/StarCoder-1B/resolve/main/ggml/q8_0.v2.gguf" with "/root/.tabby/models/TabbyML/StarCoder-1B/ggml/q8_0.v2.gguf"

run  the command again
"docker run -it -p 8080:8080  408e1dc1ecf4 serve --model TabbyML/StarCoder-1B"
Same error

4. find a article which tell me that model id can be replaced. So I change the model id by 
docker run -it -p 8080:8080 -v $HOME/.tabby:/data -v  /root/.tabby/models/TabbyML/StarCoder-1B:/models/StarCoder-1B  tabbyml/tabby:0.5.2-rc.0  serve --model /models/StarCoder-1B 

it shows 
'''
2023-11-08T02:44:23.939513Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:135: Loading model from local path /models/StarCoder-1B
2023-11-08T02:44:23.939565Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:146: Starting server, this might takes a few minutes...
'''

but when I use docker ps -a, all containers are dead. 


something is wrong in here, but where I can find a log to give your more information?

**Comment by shaozhaozhao** [comment]
Finally I figure out how to set up, hope this instruction can help people in China

use root to perform the following command

1. docker the TabbyML 
1.1 get the dokcer
# docker run -it -p 8080:8080 -e TABBY_DOWNLOAD_HOST=modelscope.cn -v $HOME/.tabby:/data tabbyml/tabby  serve --model TabbyML/StarCoder-1B

1.2 re-download the language model mirror with, you can replace "q8_0.v2.gguf" to other language models
# wget https://modelscope.cn/api/v1/models/TabbyML/StarCoder-1B/repo?FilePath=ggml/q8_0.v2.gguf

1.3 confirm the model exit in following path with 1.28G
#ll /root/.tabby/models/TabbyML/StarCoder-1B/ggml/q8_0.v2.gguf

1.4 create a tabby.json file under "/root/.tabby/models/TabbyML/StarCoder-1B/". paste following content 
{
  "auto_model": "AutoModelForCausalLM",
  "prompt_template": "<fim_prefix>{prefix}<fim_suffix>{suffix}<fim_middle>"
}

verify the file
#ll /root/.tabby/models/TabbyML/StarCoder-1B/tabby.json

2. set up the service 
2.1 find the docker images id
# docker images,

2.2 set up the alias name with model ID, in my case, the docker images id is 408e1dc1ecf4
docker run -it -p 8080:8080 -v $HOME/.tabby:/data -v  /root/.tabby/models/TabbyML/StarCoder-1B:/models/StarCoder-1B  408e1dc1ecf4 serve --model /models/StarCoder-1B 

2.3 verify the service, visit
http://{your ip address}:8080/v1/health

**Comment by nate-kot** [comment]
Worked on this side of the GFW:
```
# docker run -it -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby:0.5.2-rc.0  serve --model TabbyML/StarCoder-1B
Unable to find image 'tabbyml/tabby:0.5.2-rc.0' locally
0.5.2-rc.0: Pulling from tabbyml/tabby
6b851dcae6ca: Already exists
06539ded452e: Already exists
23ddea9c5377: Already exists
ceb5944230f9: Already exists
e9783fd39993: Already exists
91d0d349e26f: Already exists
3eb4fd8a2aeb: Already exists
ce5cf596bde1: Already exists
ce5c9df3e523: Already exists
ee55198b1a09: Pull complete
d5a6735ea522: Pull complete
0c120cfadc55: Pull complete
b6d7259cdf2f: Pull complete
Digest: sha256:182892136a9671f072ac738f74b8f52630105053b9d3aa06a7385226c0575852
Status: Downloaded newer image for tabbyml/tabby:0.5.2-rc.0
2023-11-08T04:24:42.235278Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:145: Starting server, this might takes a few minutes...
2023-11-08T04:24:44.244251Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:164: Listening at 0.0.0.0:8080

  TELEMETRY

  As an open source project, we collect usage statistics to inform development priorities. For more
  information, read https://tabby.tabbyml.com/docs/configuration#usage-collection

  We will not see or any code in your development process.

  To opt-out, add the TABBY_DISABLE_USAGE_COLLECTION=1 to your tabby server's environment variables.

  Welcome to Tabby!

  If you have any questions or would like to engage with the Tabby team, please join us on Slack
  (https://tinyurl.com/35sv9kz2).
```
