### ISSUE TITLE
Question: how can i run models in google colab to test?

### ISSUE THREAD

**Issue by erfanium** [TabbyML/tabby#712]
I want to use Google Colab to test models memory usage, before i buy a new hardware.
```py
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

checkpoint = "TabbyML/StarCoder-1B"
device = "cuda" # for GPU usage or "cpu" for CPU usage


tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = AutoModelForCausalLM.from_pretrained(checkpoint)
mode.to(device)
```

this code works, but TabbyML/StarCoder-1B uses 4.4GB of vram in google colab. It's incorrect, because I have deployed this model via tabby docker image and it only uses 1.6GB of vram.

I think that's because i dont't use int8. but I don't know how can i run my model in int8 mode in google colab.
How can i run it with less memory usage?

**Comment by wsxiaoys** [comment]
We currently do not offer an method for running Tabby in Colab. The only supported approach to run Tabby on Linux is by using a container, which is not available in Colab's runtime environment.

In the meantime, I recommend estimating VRAM usage based on the information provided in the FAQ, which can be found here: https://tabby.tabbyml.com/docs/faq/. As a rough guideline, you can assume approximately 1x VRAM usage for each parameter.
