### ISSUE TITLE
Cannot terminate the docker container.

### ISSUE THREAD

**Issue by MicahZoltu** [TabbyML/tabby#717]
**Describe the bug**
Pressing ctrl-c after doing `docker container run -it ...` doesn't terminate the container.  `docker container stop ...` also doesn't result in a clean exit of the container (it waits 10 seconds after SIG_INT and then does a SIG_KILL).

**Information about your version**
tabby 0.5.3

**Information about your GPU**
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.43.02              Driver Version: 535.98       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Quadro RTX 4000                On  | 00000000:01:00.0  On |                  N/A |
|  0%   51C    P5              23W / 125W |   5340MiB /  8192MiB |     20%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        20      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        22      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        26      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

**Additional context**
This is on Windows, but the terminal is WSL (Ubuntu) so I doubt the Windows part has anything to do with it.  Usually this is just a problem of the root process in the docker container not listening for and responding properly to SIGINT.  My guess is that the solution is to just make the tabby process listen for and cleanly shutdown when SIGINT is received.

**Comment by wsxiaoys** [comment]
According a discussion of this thread https://forums.docker.com/t/docker-run-cannot-be-killed-with-ctrl-c/13108 , it seems to be WAI for `Ctrl-C` doesn't sends an SIGINT.

**Comment by MicahZoltu** [comment]
This project is already using the recommended form of `ENTRYPOINT ["/opt/tabby/bin/tabby"]`, which suggests that the problem different than the one linked.

We can also verify that the issue is that the tabby process isn't handling SIGINT by execing into the container and doing `kill -2 1` (which will send SIGINT to process 1, which is `/op/tabby/bin/tabby`).  Notice that this doesn't appear to have any effect on the process.

**Comment by wsxiaoys** [comment]
Hey @MicahZoltu - would you mind to run a experiment with [tabby_x86_64-unknown-linux-gnu](https://github.com/TabbyML/tabby/releases/download/v0.5.4/tabby_x86_64-unknown-linux-gnu) binary (which is a cpu only backend, but otherwise compiles exact same) to see if it could reproduce the issue for you? By doing so we could ensure it's irrelevant to the docker setup.

**Comment by MicahZoltu** [comment]
Is this available in a published docker image, or would I need to build my own docker image?

**Comment by wsxiaoys** [comment]
it's a static linux binary

**Comment by MicahZoltu** [comment]
This binary doesn't appear to work properly.  It just terminates immediately on startup, before listening for incoming connections.

Reproduction steps as follows:

```Dockerfile
FROM tabbyml/tabby
COPY ./tabby_x86_64-unknown-linux-gnu /opt/tabby/bin/tabby
```
```sh
# run the production image with CPU device and reasonable settings
> docker container run --rm -it --mount='type=volume,source=tabby,target=/data' --name tabby tabbyml/tabby serve --model TabbyML/StarCoder-3B --device cpu
2023-11-11T10:24:29.972490Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:146: Starting server, this might takes a few minutes...
2023-11-11T10:24:33.206357Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:165: Listening at 0.0.0.0:8080
# NOTE: I have to kill -9 the process here, I cannot SIGINT (ctrl-c or docker stop)

# build docker image with https://github.com/TabbyML/tabby/releases/download/v0.5.4/tabby_x86_64-unknown-linux-gnu as the binary being run
> docker image build --tag tabby-test
# run the new image using same options as above
> docker container run --rm -it --mount='type=volume,source=tabby,target=/data' --name tabby tabby-test serve --model TabbyML/StarCoder-3B --device cpu
2023-11-11T10:23:37.819320Z  INFO tabby::serve: crates/tabby/src/serve/mod.rs:146: Starting server, this might takes a few minutes...
# ends immediately, doesn't appear to actually run.
[SIGILL]>
```

**Comment by kuhung** [comment]
I met the same. Stop container but GPU still in use.

**Comment by wsxiaoys** [comment]
Filing #830 to track the feature
