### ISSUE TITLE
Run chat-model on secondary GPU?

### ISSUE THREAD

**Issue by PeterTucker** [TabbyML/tabby#721]
**Please describe the feature you want**
Any way to run chat-model on a secondary GPU?

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Hey, could you test this feature in 0.6.0? You could register a separate worker process for chat model with following command

```
tabby worker::chat --model TabbyML/Mistral-7B  --url <IP of webserver node>:8080 --token <registeration token, can be found in webserver node's dashboard>
```
