### ISSUE TITLE
DeepSeek Coder Model Support

### ISSUE THREAD

**Issue by razorback16** [TabbyML/tabby#733]
**DeepSeek Coder**
Is there a plan to support [DeepSeek Coder](https://deepseekcoder.github.io) model?
Their performance is very impressive and supports Code Completion, Code Insertion, Repository Level Code Completion. This will help getting much better completion.

Is there a way to test this locally with some changes quickly?
---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
related https://github.com/TabbyML/tabby/issues/603

**Comment by wsxiaoys** [comment]
I added it to my [personal registry](https://github.com/wsxiaoys/registry-tabby), so anyone interested could try with `--model wsxiaoys/DeepseekCoder-1.3B`

**Comment by wsxiaoys** [comment]
Added to main registry: https://tabby.tabbyml.com/docs/models/

**Comment by Sytronik** [comment]
It seems DeepseekCoder models don't exist under the TabbyML registry: https://huggingface.co/TabbyML .
Am I missing something?

**Comment by wsxiaoys** [comment]
Since 0.5 registry is maintained on gihub directly: https://github.com/TabbyML/registry-tabby

**Comment by Sytronik** [comment]
> Since 0.5 registry is maintained on gihub directly: https://github.com/TabbyML/registry-tabby

Thanks, I should've updated the docker image.
