### ISSUE TITLE
Only 4 cores are used in CPU only model for model StarCoder-1B

### ISSUE THREAD

**Issue by shaozhaozhao** [TabbyML/tabby#734]
**Describe the bug**
when I use tabby in vscode, the tabby client show slow response, and I check on server side, it only 4 cores work whereas I have 24 cores cpu in the docker,
![only_4_cores_top](https://github.com/TabbyML/tabby/assets/108786165/95c8d59e-b4ef-415f-a7e7-3491719d1b98)

initially, I think its my configuration issues, and use
`docker run -it -p 8080:8080  --cpus=22 -v $HOME/.tabby:/data -v  /root/.tabby/models/TabbyML/StarCoder-1B:/models/StarCoder-1B  tabbyml/tabby:0.5.4 serve --model /models/StarCoder-1B `

Things does not change on server side. as a result, I wonder if this is related to the article #726

**Information about your version**
docker only cpus

Please provide output of `tabby --version`
V0.5.4

**Information about your GPU**
None

**Additional context**
in article #726, i notice that  parallelism = 4, is that also affect the CPU environment? if its, how can I change the docker command to let it use all cpu resources?

**Comment by wsxiaoys** [comment]
Hi,

it's not related to #726 (request level parallelism). But we do set 4 as default number of threads used in inference.

While I agree there should be a config settings to control the behavior.

**Comment by wsxiaoys** [comment]
Filing https://github.com/TabbyML/tabby/issues/738 to track the feature

**Comment by erfanium** [comment]
@wsxiaoys you can close this

**Comment by wsxiaoys** [comment]
Will do once 0.6.0 release

**Comment by shaozhaozhao** [comment]
Hi @wsxiaoys  
I notice that the lastest version is availbale and I have successfully installed on my server, now the question is how to let the docker container to use all CPU resources? 

here is the docker commands I run:
docker run -it -p 8080:8080  --cpus=22 -v $HOME/.tabby:/data -v  /root/.tabby/models/TabbyML/StarCoder-1B:/models/StarCoder-1B  tabbyml/tabby:0.6.0 serve --model /models/StarCoder-1B 

![tabblyml_6cores](https://github.com/TabbyML/tabby/assets/108786165/615b2888-9050-4c1f-b208-482abd556c65)

**Comment by wsxiaoys** [comment]
Hey - you could set `LLAMA_CPP_N_THREADS` to allow usage of more threads.

ref: https://github.com/TabbyML/tabby/pull/742

**Comment by erfanium** [comment]
@shaozhaozhao I a side note, based on llama.cpp docs, using more threads doesn't always mean you will get a better performance. for you may test various numbers for `LLAMA_CPP_N_THREADS` to see which one performs better

https://github.com/ggerganov/llama.cpp/blob/master/docs/token_generation_performance_tips.md
