### ISSUE TITLE
Add environment variable to control the intra-thread number of thread

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#738]
Create an environment variable `LLAMA_CPP_N_THREADS` and pass it to llama_set_n_threads.

Code location:  https://github.com/TabbyML/tabby/blob/03ff80efdb792e7e504d28ccedf622d8a851423b/crates/llama-cpp-bindings/src/engine.cc#L291C66-L291C66

Reference: https://github.com/ggerganov/llama.cpp/blob/57ad015dc3011b046ed5a23186c86ea55f987c54/llama.h#L488C20-L488C39

**Comment by erfanium** [comment]
@wsxiaoys Can i work on it?

**Comment by wsxiaoys** [comment]
Sure! Feel free to send out a PR
