### ISSUE TITLE
Stop generation on request abort

### ISSUE THREAD

**Issue by erfanium** [TabbyML/tabby#751]
It's not rare that a user starts typing in the middle of an ongoing text generation process. In this situation, the IDE extension client should [abort](https://developer.mozilla.org/enUS/docs/Web/API/AbortSignal) the completion request.

On the server side, we should also abort the text generation loop when the request has been closed.

This approach is a significant performance optimization, as it prevents unnecessary processing of outdated requests.

**Comment by erfanium** [comment]
I checked the source code, seams this issue has been already resolved. sorry

**Comment by wsxiaoys** [comment]
Yes - there's a slightly outdated blog on the topic: https://tabby.tabbyml.com/blog/2023/09/30/stream-laziness-in-tabby
