### ISSUE TITLE
Add plugin for IntelliJ based ides

### ISSUE THREAD

**Issue by dannkunt** [TabbyML/tabby#76]
There are currently plugins for VIM and VS Code, it would be great to have one for pycharm as well

---
Please reply with a 👍 if you want this feature.

**Comment by liar666** [comment]
Hi,

Nice work!

I'm more interested in an Emacs package.

Is'nt there simpler way to support most recent IDE/TextEditors than developing a plugin for each?

Would  impletmenting the [LSP](+ https://www.cerebras.net/blog/cerebras-gpt-a-family-of-open-compute-efficient-large-language-models/) be a solution?

**Comment by Nbosung** [comment]
Just saw the directory below, and I'm wondering when the official release of IntelliJ plugin in the marketplace is.
https://github.com/TabbyML/tabby/tree/main/clients

Would someone tell me the release date of Tabby plugin for IntelliJ?

**Comment by icycodes** [comment]
Hi, @Nbosung 
I have uploaded the latest build to the IntelliJ plugin marketplace. It is under review and will take a few days to be available.

https://plugins.jetbrains.com/plugin/22379-tabby

**Comment by Nbosung** [comment]
> Hi, @Nbosung I have uploaded the latest build to the IntelliJ plugin marketplace. It is under review and will take a few days to be available.
> 
> https://plugins.jetbrains.com/plugin/22379-tabby

Hi, @icycodes 
Thanks for the quick reply.

Would the review take more than a week from now? 
It would be great if you share us the approximate schedule.

**Comment by icycodes** [comment]
> > Hi, @Nbosung I have uploaded the latest build to the IntelliJ plugin marketplace. It is under review and will take a few days to be available.
> > https://plugins.jetbrains.com/plugin/22379-tabby
> 
> Hi, @icycodes Thanks for the quick reply.
> 
> Would the review take more than a week from now? It would be great if you share us the approximate schedule.

Yes, the review will take less than one week.
I am also working on updating the plugin in the coming weeks with improvements and bug fixes. Please stay tuned and feel free to share your feedback with us.
