### ISSUE TITLE
Document context for repository

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#790]
Related discussions:

- https://twitter.com/holdenmatt/status/1724514688493363454
- https://snowshoe.dev/tabbyml/GdexRngzGRN

These features typically require the integration of relevant snippets from developer documentation into the Tabby system.

Considerations:

1. Such features typically require the integration of developer documentation into Tabby's system.
2. The process could begin by establishing a curated registry, akin to [cursor's docs.jsonl](https://github.com/getcursor/docs/blob/main/docs.jsonl), allowing for extensibility to include versioned information.
3. Integration with completion/chat workers could provide additional context, similar to the approach taken with repository context.

Tasks:

- [ ] #791
- [x] #822
- [x] #814
- [ ] Integrate the document context with chat api

**Comment by davidemusi** [comment]
Hi, 
Can I work on this issue?

**Comment by wsxiaoys** [comment]
Hi! Is there a smaller scope task you'd like to getting start with (e.g any leaf-node issues)?

**Comment by wsxiaoys** [comment]
This will be part of 0.13 release
