### ISSUE TITLE
Tabby client does not follow redirect

### ISSUE THREAD

**Issue by Wats0ns** [TabbyML/tabby#796]
**Please describe the feature you want**
Currently, when setting the server endpoint, it's not possible to set an endpoint that is a redirect to something else. 

**Additional context**
This is something that would be useful, for example when your inference server is not always the same, but you have a domain that redirect to it, changing the redirect configuration instead of the tabby client one is more practical.

---
Please reply with a 👍 if you want this feature.

**Comment by icycodes** [comment]
Hi, @Wats0ns,

Thank you for reporting this bug. Could you please provide more context on how you have set up the redirection? This will help in reproducing the issue and finding a solution.

About the behavior of the Tabby client, it utilizes Node.js' `fetch` method for http requests. By default, fetch should automatically follow redirects with status codes 3xx.

**Comment by icycodes** [comment]
Hi, @Wats0ns,

I tried to reproduce this bug by setting up a local server that redirects requests to another local server path with a code 307, but I found that Tabby client worked properly. Could you provide additional contextual information to help reproduce the bug?

I am changing the bug status to unconfirmed, please feel free to add more details or provide steps to reproduce the issue.

**Comment by Wats0ns** [comment]
Hmm, sorry i'm not able to reproduce, closing for now
