### ISSUE TITLE
show spinning icon when tabby completion request is pending 

### ISSUE THREAD

**Issue by erfanium** [TabbyML/tabby#802]
It would be great to have an spinning animation here while a completion request is processing.
![Screenshot from 2023-11-16 13-51-05](https://github.com/TabbyML/tabby/assets/47688578/860badc0-addd-4cef-9359-3b28c51ed8cd)

I can help implementing this for vscode extension if you want!

**Comment by icycodes** [comment]
Hi, @erfanium,

Thank you for providing feedback. Currently, the spinning icon is available for the manual trigger mode. I will add the spinning icon for the auto trigger mode as well in the next release.

**Comment by icycodes** [comment]
Released in Tabby VSCode extension v1.1.0.
