### ISSUE TITLE
tabby_x86_64-unknown-linux-gnu not support cuda device

### ISSUE THREAD

**Issue by tyyod** [TabbyML/tabby#826]
**Describe the bug**
I downloaded tabby_x86_64-unknown-linux-gnu from the Release of [v0.5.5](https://github.com/TabbyML/tabby/releases/tag/v0.5.5) using the following link:
_https://github.com/TabbyML/tabby/releases/download/v0.5.5/tabby_x86_64-unknown-linux-gnu_

However, when using the command `./tabby_x86_64-unknown-linux-gnu serve --device cuda --model TabbyML/CodeLlama-13B` to run on Ubuntu 20.04.3 system, I received the error message in the screenshot below.
<img width="962" alt="截屏2023-11-18 15 57 56" src="https://github.com/TabbyML/tabby/assets/67462382/baa0503c-1165-4bd4-9bb2-2af793957fb3">

I want to know how to run it on cuda device, hope I can get help.

**By the way**: This Ubuntu 20.04.3 system currently runs in a docker image, so it has to use this method. Because it's very difficult to use `docker run -it -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B`

**Information about your version**
`tabby --version`: v0.5.5

**Information about your GPU**
GPU ：NVIDIA GeForce RTX 3080, 1

**Additional context**
System Info: Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-126-generic x86_64)

**Comment by wsxiaoys** [comment]
Hey - this is work as intended. To utilize cuda, please use [docker image](https://tabby.tabbyml.com/docs/installation/docker)

**Comment by tyyod** [comment]
Is it possible to use tabby_x86_64-unknown-linux-gnu to run on a GPU device?
Because I rented the Ubuntu 20.04.3 docker image, I tried many times and failed to start docker on the docker image.

**Comment by wsxiaoys** [comment]
Filing #828 to track the FR

**Comment by tyyod** [comment]
Thank you for your help 👍
