### ISSUE TITLE
Distribute cuda enabled linux binary

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#828]
For certain docker based GPU runtime, e.g https://github.com/TabbyML/tabby/issues/826

---
Please reply with a 👍 if you want this feature.

**Comment by tyyod** [comment]
Really looking forward to this new feature

**Comment by sundaraa-deshaw** [comment]
Hi,

Our firm does not use docker due to security concerns. Is it possible to provide the binary with cuda support, so we can run this on GPUs?

Arun

**Comment by wsxiaoys** [comment]
Hey - please give `tabby_x86_64-manylinux2014-cuda117` in https://github.com/TabbyML/tabby/actions/runs/6994413859 - which is built on manylinux2014 ABI binary with cuda 11.7.

**Comment by wsxiaoys** [comment]
Confirmed it’s working - in 0.6.0 we include the manylinux2014-cuda117 as part of distribution:

https://github.com/TabbyML/tabby/releases/tag/v0.6.0
