### ISSUE TITLE
Graceful shutdown of tabby process

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#830]
Currently, Tabby does not support graceful shutdown. It would be advantageous to implement this feature to enhance the organization of top-level resources, particularly threads.

Related: #717 

---
Please reply with a 👍 if you want this feature.

**Comment by MicahZoltu** [comment]
I would be content with just respecting SIGINT signals.  I don't actually care if Tabby "gracefully" shuts down or not as long as it eventually shuts down when SIGINT signal is received.  I don't know Rust, but in NodeJS this would just be:
```ts
process.on('SIGINT', () => { process.exit(0) })
```

May also want one for SIGTERM and SIGHUP, but SIGINT is the one I care about for docker.
