### ISSUE TITLE
Support for exllama / self-hosted inference engines

### ISSUE THREAD

**Issue by sundaraa-deshaw** [TabbyML/tabby#854]
**Please describe the feature you want**
Tabby model spec, https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md, says it supports only the .gguf files consumed by llama.cpp inference engine.

It will be good to be able to support other faster (on GPU) inference engines like exllama[v2].

Self-hosting a LLM usually means running a HTTP or WS based backend that runs off these engines (besides llama.cpp).

Are there ways to currently serve Tabby off such an engine? I checked the source and it seems only "vertex-ai", "fastchat" are supported to talk to an external API. 

**Additional context**

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Close as dup of https://github.com/TabbyML/tabby/issues/795 (let’s continue the disucssion there)
