### ISSUE TITLE
Docker image is no longer starting

### ISSUE THREAD

**Issue by ainub** [TabbyML/tabby#856]
**Describe the bug**
I haven't used it for some time and decided to update the image and give it a shot.
(traps: tabby[382782] trap invalid opcode ip:55b5f1164829 sp:7ffd27c1fb20 error:0 in tabby[55b5f0133000+1067000])
The executable is no longer starting with or without cuda. I suspect is something related to AVX/AVX2? Are you using such flags when compiling it?
Oobabooga seem to have a different list of requirements regarding that issue.

**Information about your version**
tabby 0.5.5

**Information about your GPU**
0  NVIDIA GeForce GTX 1070
1  NVIDIA GeForce GTX 1070

It used to work at some point.
CPU flagx: AVX, not AVX2

**Comment by wsxiaoys** [comment]
Could you provide the command you used to start tabby? And confirm if `0.4.0` works for you?

**Comment by ainub** [comment]
Yes. 0.4.0 is working as intended.
The command to run it is:
docker run -it -e TABBY_DISABLE_USAGE_COLLECTION=1 --gpus '"device=1"' -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby:0.4.0 serve --model TabbyML/StarCoder-3B --device cuda

**Comment by wsxiaoys** [comment]
Potential related: https://github.com/ggerganov/llama.cpp/issues/1583
A fix is being working on https://github.com/ggerganov/llama.cpp/pull/809, but seems becoming stale

**Comment by ainub** [comment]
No, unfortunately, the problem persists. Maybe the image is not yet updated:
Digest: sha256:b2be09111141a26ae309e788c1449f4c67e241657729ffc7bf05f8952e89ee35
Status: Downloaded newer image for tabbyml/tabby:nightly

docker run -it --gpus all -p 8080:8080 -e RUST_BACKTRACE=1 -e TABBY_DISABLE_USAGE_COLLECTION=1 -v $HOME/.tabby:/data tabbyml/tabby:nightly serve --model TabbyML/StarCoder-3B --device cuda

traps: tabby[509035] trap invalid opcode ip:557fe6681569 sp:7ffd0e961010 error:0 in tabby[557fe52a4000+1415000]

**Comment by wsxiaoys** [comment]
After giving a second look of https://github.com/ggerganov/llama.cpp/commit/c41ea36eaa3548776de4cb3d5d49b925cd3fc0f2 , it seems the avx2 check happens only at compile time. There seems no runtime detection for avx / avx2 branch.

**Comment by ainub** [comment]
It is probably why oobabooga provide two different requirement files for llama: one with avx2 and one without. The optimization is related to CPU processing though, it shouldn't affect GPU and yet...

**Comment by yayitazale** [comment]
Same problem, only `0.4.0` starts. There is no error on the logs of the container it just doesn't start.

Information about your version
tabby 0.5.5 (cuda and not cuda)

Information about your GPU
0 NVIDIA GeForce GTX 1060

It used to work at some point.
CPU flags: not AVX, not AVX2 (Intel® Pentium® Gold G5600 CPU)

**Comment by rowanfuchs** [comment]
Same problem, the docker instance is running but tabby doesn't start. Using:

``version: '3.5'

services:
  tabby:
    container_name: tabby
    restart: always
    image: tabbyml/tabby
    command: serve --model TabbyML/StarCoder-1B
    volumes:
      - /tabby:/data
    ports:
      - 8181:8080``

**Comment by justaCasualCoder** [comment]
After compiling from source , it works with just `avx`.

**Comment by wsxiaoys** [comment]
Filing https://github.com/TabbyML/tabby/issues/1142 to track the issue
