### ISSUE TITLE
Invalid model_id for J-350M and T5P-220M

### ISSUE THREAD

**Issue by praktiskt** [TabbyML/tabby#857]
**Describe the bug**

Unable to run _some_ of the models available on TabbyML huggingface. 

Reproducible examples:
```sh
# TabbyML/J-350M fails
docker run tabbyml/tabby:0.5.5 serve --model TabbyML/J-350M

# TabbyML/T5P-220M fails
docker run tabbyml/tabby:0.5.5 serve --model TabbyML/T5P-220M

# TabbyML/StarCoder-1B works just fine
docker run tabbyml/tabby:0.5.5 serve --model TabbyML/StarCoder-1B
```

**Information about your version**

Tabby 0.5.5, using the docker-container `tabbyml/tabby:0.5.5`.

**Information about your GPU**

No GPU, just CPU.

**Additional context**

Setting  `RUST_BACKTRACE=1` yields the following stacktrace for T5P-220M. J-350M yields an identical error.
```
thread 'main' panicked at crates/tabby-common/src/registry.rs:72:32:
Invalid model_id <TabbyML/T5P-220M>
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
   1: core::panicking::panic_fmt
             at ./rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
   2: tabby_common::registry::ModelRegistry::get_model_info
   3: tabby_download::download_model::{{closure}}
   4: tabby::serve::main::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: tokio::runtime::runtime::Runtime::block_on
   8: tabby::main
```

**Comment by wsxiaoys** [comment]
Hey - since 0.4.0, we removed T5P-220M / J-350M from supported model list: https://tabby.tabbyml.com/docs/models/

If you're interested in using a customized model in tabby, please refer the `How can I convert my own model for use with Tabby?` in https://tabby.tabbyml.com/docs/faq

**Comment by praktiskt** [comment]
Gotcha. Might make sense to remove the models from [Huggingface](https://huggingface.co/TabbyML) if they are no longer supported (or flag them as such in their respective READMEs).

Closing since there's nothing else to be done. Thanks for the swift response :+1:
