### ISSUE TITLE
Linker error when trying to compile it locally

### ISSUE THREAD

**Issue by ainub** [TabbyML/tabby#865]
**Describe the bug**

So, I wanted to try and compile it myself in order to get a working version with CUDA. Everything seems fine until the last step:

error: linking with `cc` failed: exit status: 1

[cut]

 "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-62b22437ddb6fa36.rlib" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-8d03ea52f472873a.rlib" "-Wl,-Bdynamic" "-lstdc++" "-lstdc++" "-lllama" "-lggml_static" "-lcudart" "-lculibos" "-lcublas" "-lcublasLt" "-lstdc++" "-ldl" "-lz" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/tools/tabby/target/release/deps/tabby-7412201e8488e52d" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs"

  = note: /usr/bin/ld: /tools/tabby/target/release/build/llama-cpp-bindings-a50008514a8189c6/out/build/libllama.a(ggml-cuda.cu.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a PIE object; recompile with -fPIE
          /usr/bin/ld: failed to set dynamic section sizes: bad value
          collect2: error: ld returned 1 exit status

warning: `tabby` (bin "tabby") generated 1 warning
error: could not compile `tabby` (bin "tabby") due to previous error; 1 warning emitted

**Information about your version**
both 0.5.5 and current 0.6.0-dev version behave in the same way.

**Information about your GPU and environment**
WSL2 - Fedora 37

NVIDIA-SMI 545.29.01              Driver Version: 546.01       CUDA Version: 12.3
0  NVIDIA GeForce RTX 4070 Ti
Using the official CUDA toolkit from Nvidia.

I am not sure this is a bug but more of a compiler detection flags or something that creates an incompatibility at some point.

Any help would be appreciated,
Thank you

**Comment by wsxiaoys** [comment]
Unfortunately, I don't have WSL setup to reproduce the error.

Would you be able to get a successful build without `--feature cuda`?

**Comment by ainub** [comment]
Yes, without `--feature cuda` both versions compile and work as intended. The problem is with llama somewhere. I'm trying to compile it separately and see if I can manually add some flags to make it work.

**Comment by ainub** [comment]
Worked using cuda-toolkit-11.7. Before I was using cuda-toolkit-12.3 and is throwing that error.
