### ISSUE TITLE
Question: on what data tabbyML is trained? how can I share code to help training?

### ISSUE THREAD

**Issue by sonique6784** [TabbyML/tabby#866]

**Comment by wsxiaoys** [comment]
Hey - could you elaborate a bit on the use case? Is this code public / private? Would https://tabby.tabbyml.com/docs/configuration/#repository-context-for-code-completion be something suitable?

**Comment by sonique6784** [comment]
It is public apache 2.0 code.
It would be great to know what code is Tabby trained on by default.

**Comment by wsxiaoys** [comment]
You might refer https://tabby.tabbyml.com/docs/models/ for details of each model (they're trained on different setup / dataset).

at the moment we don't publish our own foundation model
