### ISSUE TITLE
Extract dependencies for python `poetry.lock` / `pyproject.toml`

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#878]

**Comment by Someet-Git** [comment]
Hey @wsxiaoys I am trying to solve this issue but was not able to find where to get started. can you help me?
I am learning about stuffs and trying to contribute to good first issues.

**Comment by wsxiaoys** [comment]
Hey, you can refer to https://github.com/TabbyML/tabby/pull/874 for an example of how we extract dependencies for Rust's `Cargo.lock`/`Cargo.toml`.

If you don't have a preference for which issue to start with, I suggest beginning with #877. You can use https://crates.io/crates/package-lock-json-parser/0.1.1 directly to implement it, similar to what's done in rust.rs.
