### ISSUE TITLE
IntelliJ plugins fails to connect to tabby server

### ISSUE THREAD

**Issue by SQLExceptionPhil** [TabbyML/tabby#881]
We are currently running a tabby server behind a reverse proxy with ssl. The certificate is authorized in the windows ca store but nodejs doesn't use this by default. With this in mind Tabby (IntelliJ) can't connect to the server:

![image](https://github.com/TabbyML/tabby/assets/35815130/b3053682-5159-4f14-9daf-b409ab37c481)

In VSCode there is an option to include local certificates - not in IntelliJ when using a nodejs agent. 
I have seen that there is a npm module, which would include windows ca (https://www.npmjs.com/package/win-ca) - I think that the agent should work as expected when using this.

---
Please reply with a 👍 if you want this feature.

**Comment by icycodes** [comment]
Thank you for reporting this issue.

As a workaround, you can try setting the system environment variable `NODE_EXTRA_CA_CERTS` to a PEM file that includes the required certificate.

**Comment by SQLExceptionPhil** [comment]
> Thank you for reporting this issue.
> 
> As a workaround, you can try setting the system environment variable `NODE_EXTRA_CA_CERTS` to a PEM file that includes the required certificate.

Thanks, that worked - if someone has a similar issue you can download the pem certificate from your browser (see https://superuser.com/questions/1291416/download-pem-via-browser-only). There is also another workaround to set the environment variable `NODE_TLS_REJECT_UNAUTHORIZED` to 0 (not recommended).

**Comment by 64q** [comment]
Hi

What's the state of this issue? Seems something has been merged in February but the doc is not updated. Has this feature been released in the agent?

Thank you.
