### ISSUE TITLE
server down ’cause no internet connection

### ISSUE THREAD

**Issue by woodvillage** [TabbyML/tabby#888]
I use docker-compose to run the server-end tabby on my GPU server, 
but my GPU server has no internet connection, is there any way to run the server without internet?

docker log:
```
thread 'main' panicked at /root/workspace/crates/tabby-common/src/registry.rs:52:21:
Failed to fetch model organization <TabbyML>: error sending request for url (https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json): error trying to connect: tcp connect error: Connection timed out (os error 110)
Caused by:
    0: error trying to connect: tcp connect error: Connection timed out (os error 110)
    1: tcp connect error: Connection timed out (os error 110)
    2: Connection timed out (os error 110)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by icycodes** [comment]
You can download model manually on a device with internet, and copy it into your GPU server then specify the local model path. Here is an example: 

```
docker run -it -v $HOME/.tabby:/data tabbyml/tabby:0.6.0-rc.0 download --model TabbyML/StarCoder-1B

# sync ~/.tabby dir to your server

docker run -it --gpus all -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby:0.6.0-rc.0 serve --model /data/models/TabbyML/StarCoder-1B --device cuda
```

**Comment by woodvillage** [comment]
thx very much, I'll try it out!

**Comment by wsxiaoys** [comment]
related https://github.com/TabbyML/tabby/issues/846

**Comment by woodvillage** [comment]
can I download the model directly by the urls below? and then put the gguf file to my server?
```
 {
    "name": "StarCoder-7B",
    "provider_url": "https://huggingface.co/bigcode/starcoderbase-7b",
    "license_name": "BigCode-OpenRAIL-M",
    "license_url": "https://huggingface.co/spaces/bigcode/bigcode-model-license-agreement",
    "prompt_template": "<fim_prefix>{prefix}<fim_suffix>{suffix}<fim_middle>",
    "urls": [
      "https://huggingface.co/TabbyML/StarCoder-7B/resolve/main/ggml/q8_0.v2.gguf",
      "https://modelscope.cn/api/v1/models/TabbyML/StarCoder-7B/repo?FilePath=ggml/q8_0.v2.gguf"
    ],
    "sha256": "33dfcc7e216f1a072b4e16cd3bb19a0e55f5874ed319416435c8fc99216b8bfa"
  },
```

**Comment by wsxiaoys** [comment]
> can I download the model directly by the urls below? and then put the gguf file to my server?

You can refer to https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md to manually create the directory, rather than relying on `tabby download` (although it is not recommended).

> 
furthermore, since I don't have internet connection in my server, should I download the this json file (https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json), and put it somewhere?

If you point `--model` to a local directory, there's no need to download the file.

**Comment by woodvillage** [comment]
got it! thank you!

> > can I download the model directly by the urls below? and then put the gguf file to my server?
> 
> You can refer to https://github.com/TabbyML/tabby/blob/main/MODEL_SPEC.md to manually create the directory, rather than relying on `tabby download` (although it is not recommended).
> 
> > 
> 
> furthermore, since I don't have internet connection in my server, should I download the this json file (https://raw.githubusercontent.com/TabbyML/registry-tabby/main/models.json), and put it somewhere?
> 
> If you point `--model` to a local directory, there's no need to download the file.
