### ISSUE TITLE
Ruby Support

### ISSUE THREAD

**Issue by glennfu** [TabbyML/tabby#89]
**Please describe the feature you want**
Support Ruby in tabby

* [ ]  backend change
* [ ]  extension support

**Additional context** Add any other context or screenshots about the feature request here.

I believe that the LanguagePresets should look like this:
```
    Language.RUBY: LanguagePreset(
        max_length=128,
        stop_words=[
            "\n\n",
            "\ndef",
            "\n#",
            "\nrequire",
            "\ninclude",
            "\nclass",
            "\nmodule",
        ],
    ),
```  

However I don't know how to implement the extension support.

Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
> However I don't know how to implement the extension support.

@icycodes is currently working on implementing extension support using `openapi.json`, which means that adding support for new languages only requires defining their language preset

Therefore, you have all the necessary components for submitting a pull request for this feature. :smile:
