### ISSUE TITLE
Can't install package: The arm architecture is required for this software

### ISSUE THREAD

**Issue by lepinejf** [TabbyML/tabby#891]
**Describe the bug**

I'd love some guidance here, as I can't even install the package even though i'm using arm architecture.

![Screenshot 2023-11-24 at 12 49 02 PM](https://github.com/TabbyML/tabby/assets/15265343/c2e1e077-fa7c-4a1b-b76b-636cab677ba9)

![Screenshot 2023-11-24 at 1 02 01 PM](https://github.com/TabbyML/tabby/assets/15265343/cc0714c5-6c38-44d7-a367-b4b375e7f8e5)

**Comment by wsxiaoys** [comment]
Looks like homebrew detects the wrong architecture for you, I didn't find anything useful through a quick google search.

You might consider asked in their issue list: https://github.com/Homebrew/brew/issues
