### ISSUE TITLE
Windows build for tabby

### ISSUE THREAD

**Issue by wsxiaoys** [TabbyML/tabby#909]
llama.cpp itself is fully compatible for windows, tabby itself doesn't relies on any system specific libs, so it's possible to refactor and generates a windows native build for tabby.

For now windows users have to relies on WSL2 for native cuda support.

**Comment by darknight** [comment]
I do find a platform specific dependence which is `aim = "1.8.5"` from `tabby-download`, it has no support on windows os.

Need to find an alternative I suppose.
