### ISSUE TITLE
tabby.toml usage

### ISSUE THREAD

**Issue by bschrib** [TabbyML/tabby#91]
Is there any direction on how to use the tabby.toml file to add additional projects? Specifically if they're in a private repo?

Would love for it to be documented in the README.md.

**Comment by AlexFielder** [comment]
Is there a possibility of extending this request to include local repositories on Windows also? (or should I submit a new issue?)

**Comment by nowfred** [comment]
@bschrib haven't put it in the README but you can set it up like so to download private repo(s):
```
[projects]

[projects.$REPO_NAME]
name = "$REPO_NAME"
git_url = "https://$GH_USERNAME:$GH_CLASSIC_TOKEN_WITH_RW@github.com/$ORG/$REPO.git"
```

@AlexFielder have you tried copying the repository into the data/repositories folder, and omitting the `git_url` key/value in the appropriate TOML section?

**Comment by AlexFielder** [comment]
> @bschrib haven't put it in the README but you can set it up like so to download private repo(s):
> 
> ```
> [projects]
> 
> [projects.$REPO_NAME]
> name = "$REPO_NAME"
> git_url = "https://$GH_USERNAME:$GH_CLASSIC_TOKEN_WITH_RW@github.com/$ORG/$REPO.git"
> ```
> 
> @AlexFielder have you tried copying the repository into the data/repositories folder, and omitting the `git_url` key/value in the appropriate TOML section?

When I can next catch a breath and dedicated some time to this I will give that a try, thank you.
