### ISSUE TITLE
vim client bug - VimEnter Autocommands

### ISSUE THREAD

**Issue by markis** [TabbyML/tabby#918]
**Describe the bug**
Vim client bug. After installing the plugin with lazy.nvim.  When I close and open vim, I get this error on open.

```
Error detected while processing VimEnter Autocommands for "*"..function tabby#OnVimEnter[44]..tabby#keybindings#Map:
line    7:
E716: Key not present in Dictionary: "rhs) == '<NOP>'"
Error detected while processing VimEnter Autocommands for "*"..function tabby#OnVimEnter[44]..tabby#keybindings#Map:
line    7:
E116: Invalid arguments for function toupper
```

Lazy vim config:
```
  { "TabbyML/vim-tabby" },
```

**Information about your version**
tabby: `tabby 0.6.0`
tabby-vim: `ba27138 release: vim-tabby version 1.1.1 (10 days ago)`

**Information about your GPU**
Apple M1

**Additional context**
n/a

**Comment by icycodes** [comment]
Hi, @markis. 
Thank you for reporting this bug. It appears to be the same bug as #862.  
Do you have any other plugins that modify the `<Tab>` keymapping?

**Comment by markis** [comment]
Yes, looks like it's a duplicate of #862, I also use LazyVim.  However, setting the keybinding didn't work for me.  It's still erroring even with the global setting.

```lua
--- lua
vim.g.tabby_keybinding_accept = '9'
```
