### ISSUE TITLE
Dockerfile RUST_TOOLCHAIN variable not set

### ISSUE THREAD

**Issue by snoopiedoom** [TabbyML/tabby#922]
**Describe the bug**
`docker build`  fails at installing rust, with the following error:
```
Step 9/23 : RUN curl https://sh.rustup.rs -sSf | bash -s -- --default-toolchain ${RUST_TOOLCHAIN} -y
 ---> Running in e045be8fe86f
info: downloading installer
error: error: The argument '--default-toolchain <default-toolchain>' requires a value but none was supplied
```
in the Dockerfile, variable is set like dis, `ARG RUST_TOOLCHAIN stable`, 
works fine after adding an equals sign: `ARG RUST_TOOLCHAIN=stable`.

thoughts?

**Information about your version**
`tabby 0.7.0-dev`

**Information about your GPU**
amd

**Comment by wsxiaoys** [comment]
Nice catch - wanna create a 🚀  PR for it? https://github.com/TabbyML/tabby/edit/main/Dockerfile
