### ISSUE TITLE
No suggestions when running on CPU, timeout messages appear but no event logs.

### ISSUE THREAD

**Issue by pablomc87** [TabbyML/tabby#942]
**Describe the bug**
I have run Tabby's container with the following message:
docker run -it -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/StarCoder-1B
Since my work laptop doesn't have a nvidia GPU. I'm able to connect to the server, test swagger, and I have installed the plugin to PyCharm and everything looks good except for the fact that I'm not getting any suggestion. I can even see the process wheel working and not showing anything in the end.

Swagger test:
```
curl -X 'POST' \
  'http://localhost:8080/v1/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "language": "python",
  "segments": {
    "prefix": "def fib(n):\n    ",
    "suffix": "\n        return fib(n - 1) + fib(n - 2)"
  }
}'
```
Response:
```
{
  "id": "cmpl-08964834-c30e-4643-ac71-98916223198b",
  "choices": [
    {
      "index": 0,
      "text": "    if n <= 1:\n            return n"
    }
  ]
}
```

I've also tried editing `~/.tabby-client/agent/config.toml` and the time of "running" visual doesn't change significantly (even if I multiplied by 100 the timeout parameter).

**Information about your version**
I'm using the containerized version with the command stated earlier.

**Information about your CPU**
My CPU is: AMD Ryzen 7 PRO 5850U with Radeon Graphics (16 cores)

**Additional context**
![image](https://github.com/TabbyML/tabby/assets/100563286/14a3d62d-3ce9-4af2-aeac-a8d763f605c0)
![image](https://github.com/TabbyML/tabby/assets/100563286/92b3ee7f-bdea-4193-9f2f-ba8efc438447)

Feel free to ask for more information that I might provide to replicate the issue.

**Comment by icycodes** [comment]
You should also uncomment the line `[completion]` above. 

```
[completion]
timeout = 400000 # 4s
```

**Comment by pablomc87** [comment]
Well, that did the trick... Not feeling the brightest star in the sky.

**Comment by wwa132** [comment]
How to change the timeout setting on server configuration
https://slack.tabbyml.com/PR5Ob20dq45
