### ISSUE TITLE
Tabby not suggest indexed repo both chat and completion

### ISSUE THREAD

**Issue by katopz** [TabbyML/tabby#943]
**Describe the bug**
Tabby not suggest indexed repo both chat and completion

**Information about your version**
tabby 0.6.0

**Information about your GPU**
Apple M3 Max

**Additional context**

## Source
> https://github.com/katopz/tabby-test.git
<img width="892" alt="image" src="https://github.com/TabbyML/tabby/assets/97060/12ce87da-7bbd-4799-bf28-4b9e5db416d6">

## Tabby indexing fined
```
% tabby scheduler --now                                          
Syncing repositories...
Already up to date.
Already up to date.
Cloning into '/Users/katopz/.tabby/repositories/https_github.com_katopz_tabby-test.git'...
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (6/6), done.
Building dataset...
100%|████████████████████████████████████████| 1/1 [00:00<00:00, 12090.73it/s]                                          
Indexing repositories...
100%|████████████████████████████████████████| 1330/1330 [00:00<00:00, 117557.81it/s]   
```
## files.json
```json
{"git_url":"https://github.com/katopz/tabby-test.git","filepath":"README.md","content":"# About Todsaporn Banjerdkit\n1. His nick name is katopz.\n2. He's Rustaceans.\n3. He love cats.\n","language":"markdown","max_line_length":28,"avg_line_length":22.5,"alphanum_fraction":0.7340425,"tags":[]}
```

## Server is ready, already try restart
```
tabby serve --device metal --model TabbyML/DeepseekCoder-6.7B --chat-model TabbyML/Mistral-7B
2023-12-04T14:20:24.347440Z  INFO tabby::serve: crates/tabby/src/serve.rs:103: Starting server, this might takes a few minutes...
2023-12-04T14:20:24.349409Z  INFO tabby::services::code: crates/tabby/src/services/code.rs:53: Index is ready, enabling server...    
2023-12-04T14:20:25.524857Z  INFO tabby::routes: crates/tabby/src/routes/mod.rs:35: Listening at 0.0.0.0:8080
```
But both chat and completion can't provide right information.

<img width="773" alt="image" src="https://github.com/TabbyML/tabby/assets/97060/33ccb0b7-60c8-40d2-b6b9-5e15d2c3e689">

<img width="505" alt="image" src="https://github.com/TabbyML/tabby/assets/97060/9a51adc1-74cd-4983-a6af-0c1463fc9448">

---

Maybe `Tabby` tend to suggest only code? Or maybe I am doing it wrong?

**Comment by katopz** [comment]
Thanks for clarification really looking forward to it.
Anyway I still can't get expected completion via my repo code `main.rs`.

<img width="1370" alt="image" src="https://github.com/TabbyML/tabby/assets/97060/0efe7262-11f3-474c-9cf3-196c20e10751">

## Step
- [x] Reindexing
- [x] Cross check `dataset/files.jsonl`
- [x] Restart `tabby`

## Expected
```rust
fn main() {
    println!("The quick black cat jumps over the lazy dog");
}
```

## Got
```rust
fn main() {
    println!("Hello, black cat!");
}
```

But still no joy, not sure what I miss?

**Comment by wsxiaoys** [comment]
could you check the events log under `~/.tabby/events` to see the actual request / response for your testing request?

**Comment by katopz** [comment]
Sure, here is more specified test by using [Saturating](https://doc.rust-lang.org/stable/std/num/struct.Saturating.html#examples-1) which is available on `Rust 1.74.0` to ensure model didn't have this knowledge and to test that tabby will pick up the example from repo or not.

> ~/.tabby/events/2023-12-05.json
```json
{"ts":1701791232478,"event":{"view":{"completion_id":"cmpl-535f7d4b-6ce1-4fba-8b61-40577df14bc2","choice_index":0}}}
```

<img width="1380" alt="image" src="https://github.com/TabbyML/tabby/assets/97060/12dcfdc3-9b7b-42dc-a20e-0961e6ac6248">


It's seem not working as expected at the moment.

**Comment by grebdioZ** [comment]
Not sure if it's related: When I tried out tabby 0.6.0-rc0 for the first time, code completion seemed to work fine. Then I tried indexing of a larger repo with C++ and python code, which worked quite fast. It also provided some documents/chunks as embedding for completion, but they were always the same and had no relation to the (python) code I had started to write (which was `from <some_internal_module> import `. However, I did not not have time to investigate further and just disabled the index again.

**Comment by wsxiaoys** [comment]
I have tested and verified that the majority of the repository context is functioning correctly. However, currently, there are few visualizations indicating what is actually indexed and what is happening underneath. This causes confusion among users, leaving them wondering whether it is genuinely useful.

Issue #538 is expected to address and resolve this situation.

**Comment by wsxiaoys** [comment]
With introducing of embedding based context ranking, the triggering rate for code context should be much higher now, see https://tabby.tabbyml.com/blog/2024/06/11/rank-fusion-in-tabby-code-completion/ for details
