### ISSUE TITLE
feat: add `path` segment

### ISSUE THREAD

**Issue by erfanium** [TabbyML/tabby#945]
we can add more context to the prompt by adding current file project path.

example prompt:
```ts
//src/server.test.ts    <-- model knows it's a typescript test file for the server
import app from "./server" // <-- this line will be completed by tabby, which wasn't possible without path context

```

```ts
//src/components/Counter.tsx    <-- model knows it's a typescript react component


```

maybe it could fix https://github.com/TabbyML/tabby/issues/870

ref for prompt template:
https://github.com/deepseek-ai/DeepSeek-Coder#4-repository-level-code-completion

**Comment by erfanium** [comment]
Cody also do the same
![Screenshot from 2023-12-17 15-37-53](https://github.com/TabbyML/tabby/assets/47688578/9d20152c-31b5-4448-9f5d-daee24535f11)

![image](https://github.com/TabbyML/tabby/assets/47688578/7ba2b2a2-e80f-4904-b5b8-9769eadf08d4)

**Comment by wsxiaoys** [comment]
Code location: https://github.com/TabbyML/tabby/blob/1e9ce3e2c658fdc32790a11c4e029898df03fa94/crates/tabby/src/services/completion.rs#L106

**Comment by wsxiaoys** [comment]
@icycodes is working on something very similar
