### ISSUE TITLE
Magicoder Model Support

### ISSUE THREAD

**Issue by Nitschi** [TabbyML/tabby#949]
**Magicoder**
Is there a plan to support the [Magicoder](https://github.com/ise-uiuc/magicoder) model?
The performance seems [to surpass DeepSeek Coder](https://evalplus.github.io/leaderboard.html).

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Should be easy to try out with:
1. https://huggingface.co/TheBloke/Magicoder-S-DS-6.7B-GGUF
2. https://tabby.tabbyml.com/docs/faq

**Comment by lampewebdev** [comment]
I tried with both flags `--model` and `--chat-model` same outcome

**Comment by kitckso** [comment]
```
Compatibility

These quantised GGUFv2 files are compatible with llama.cpp from August 27th onwards, as of commit [d0cee0d](https://github.com/ggerganov/llama.cpp/commit/d0cee0d36d5be95a0d9088b674dbb27354107221)
```

Is it the cause? Which version of llama.cpp used by Tabby?

**Comment by kitckso** [comment]
0.6 using efbd009d2f151feb1a1d3fdd27effbb650a245d4
seems this is not the cause…

**Comment by kitckso** [comment]
https://huggingface.co/TheBloke/Magicoder-S-DS-6.7B-GGUF/discussions/1

**Comment by erfanium** [comment]
@wsxiaoys
It would be great to have Magicoder being lister here:

https://leaderboard.tabbyml.com/

**Comment by hytxx** [comment]
> I tried with both flags `--model` and `--chat-model` same outcome

Have you solved the problem?

**Comment by hytxx** [comment]
> I tried with both flags `--model` and `--chat-model` same outcome

@lampewebdev Have you solved the problem?
