### ISSUE TITLE
Documentation regarding running multiple model worker.

### ISSUE THREAD

**Issue by piti118** [TabbyML/tabby#957]
**Please describe the feature you want**

I have seen in the release note that it can run multiple models at the same time being distributed etc. The question is what does it do? Does it randomly pick one worker and give the completion or it give the user choices?

**Additional context**
Thanks a bunch for this lovely tool.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
this is replaced by http based model backend https://tabby.tabbyml.com/docs/administration/model/
