### ISSUE TITLE
Fetch repository context from local filesystem instead of Github

### ISSUE THREAD

**Issue by taoeffect** [TabbyML/tabby#962]
I noticed in the [configuration page](https://tabby.tabbyml.com/docs/configuration/) it seems to suggest that the only way to make Tabby project-aware is to link to a remote repository.

But wouldn't it make much more sense for a self-hosted solution like this, for it to work without requiring Internet access? It would be much cooler if I could tell Tabby "Please index the files in this local directory, and ignore these subdirectories". It could even figure out what to ignore by parsing the `.gitignore` file.

Maybe you could even add a command to the `tabby` command like `tabby index .`, and it would update the tabby config file for you to add the current directory to its index.

Also - is there a way to make sure that Tabby doesn't get "confused" if there are multiple projects indexed? I want to make sure that it only loads/thinks about the project that I have currently open, and not any other project, even if there are multiple projects being indexed.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Thanks for the feedback - local repository is actually supported, just sending out #963 to document it.

> It could even figure out what to ignore by parsing the .gitignore file.

This is actually supported as well 😃
