### ISSUE TITLE
Improve UX for slow completions / (Was: doesn't autocomplete, sometimes "Times out")

### ISSUE THREAD

**Issue by taoeffect** [TabbyML/tabby#965]
**Describe the bug**

I'll run tabby with:

```
tabby serve --device metal --model TabbyML/DeepseekCoder-1.3B
```

Or

```
tabby serve --device metal --model TabbyML/DeepseekCoder-6.7B
```

And sometimes it won't autocomplete. I have it set to autocomplete manually (when I press <kbd>Option+\ </kbd>), but it doesn't do anything. There's a brief spinning circle in the status bar next to "Tabby" but it doesn't do anything. No indication that it's thinking. And often, especially with the `TabbyML/DeepseekCoder-6.7B` model, it will say that all the requests timed out and will completely stop working from that point on.

Ideally, it would behave this way:

1. It would work well with both models (as this laptop can handle `TabbyML/DeepseekCoder-6.7B`, it might just take a while and I prefer waiting for better quality output)
2. It gives the user a visual indication that it's thinking the entire time. Would be cool if maybe it could even build the autocompletion "live" so that you can see its progress.
3. It doesn't time out, but waits for the completion to finish, especially if there have been no edits to the document (I can wait patiently)
4. And if the user makes changes to any relevant code, it interrupts the model's thinking (so that it doesn't have to wait for the previous "thinking" to complete but can instead immediately begin anew with the new code)

**Information about your version**

```
-> % tabby --version
tabby 0.6.0
```

On macOS M2 processor with 24GB RAM, using VSCodium.

**Information about your GPU**

M2

**Comment by wsxiaoys** [comment]
add @icycodes for comments
