### ISSUE TITLE
Tabby Jetbrains plugin breaks

### ISSUE THREAD

**Issue by piti118** [TabbyML/tabby#967]
**Describe the bug**
<img width="382" alt="image" src="https://github.com/TabbyML/tabby/assets/591316/0104617d-61be-4b2d-9583-77460a27550c">

After upgrade to WebStorm 2023.3 ... it breaks.

**Information about your version**
Please provide output of `tabby --version`

**Information about your GPU**
Please provide output of `nvidia-smi`

**Additional context**

**Comment by icycodes** [comment]
@piti118 
Thank for report this issue. I will release a hotfix version 1.1.2 to support the latest version of IntelliJ IDEs.
