### ISSUE TITLE
backspace key not working

### ISSUE THREAD

**Issue by spandanpradhan** [TabbyML/tabby#973]
**Describe the bug**
backspace key not working

**Information about your version**
1.0.205

**Additional context**
While accessing Nokia/Huawei OLT through telnet, the backspace key doesn't function and you have to use the Ctrl+H key. 
Whereas the SSH connection to switches and routers the backspace key works fine.

**Comment by wsxiaoys** [comment]
Guess you wanna post to https://github.com/Eugeny/tabby
