### ISSUE TITLE
Remove the timeout limit for manual trigger

### ISSUE THREAD

**Issue by icycodes** [TabbyML/tabby#975]
When users manually trigger a completion, it means that they are willing to wait for the completion process to finish, regardless of how long it takes. Moreover, users can also cancel the ongoing completion process by moving the cursor or typing anything. 
Therefore, it is unnecessary to set a timeout limit at the client side for manual trigger.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Note we'll still have server side timeout regardless of client side timeout.

**Comment by taoeffect** [comment]
Something else that would be interesting (I don't know if it's possible though), would be to see if the autocompletion (they gray text) can be shown as it's being built-up. This would give the user immediate feedback even with large models, and they'd be able to more quickly decide whether or not they like what they're seeing (and move the cursor to stop the autocompletion if they don't like it)

**Comment by BoccheseGiacomo** [comment]
> Note we'll still have server side timeout regardless of client side timeout.
@wsxiaoys 

is there a way to change the timeout server side?

**Comment by icycodes** [comment]
The client-side timeout limit for completion requests has been removed since v1.3.0.
