### ISSUE TITLE
Tabby agent generates daily logs though configured to be "silent"

### ISSUE THREAD

**Issue by sundaraa-deshaw** [TabbyML/tabby#990]
**Describe the bug**
In the Tabby agent configuration, we have configured this:

```
[logs]
level = "silent"
```

However, due to the default rotating log stream, an empty file is created everyday. Though empty this can consume the inode usage over a period of time. 

**Information about your version**
tabby version: 0.5.5 / 0.6

Can we turn off the rotation or generation if the agent logs are disabled or configured to be silent?

**Comment by icycodes** [comment]
Hi, @sundaraa-deshaw  

Thank you for reporting this issue. 
The fix has been released in Tabby IDE plugins version 1.2.0. Please try to upgrade Tabby plugin to the latest version.
