### ISSUE TITLE
Run in Kaggle or Colab with CUDA

### ISSUE THREAD

**Issue by tastypear** [TabbyML/tabby#998]
**Please describe the feature you want**

Is there anyway to run in Kaggle or in Colab?

**Additional context**

I tried to run tabby in Kaggle with `udocker` like this:
```
!mkdir -p /root/.tabby
!pip install udocker
!udocker --allow-root install
!udocker --allow-root run -p 8080:8080 -v $HOME/.tabby:/data tabbyml/tabby serve --model TabbyML/DeepseekCoder-6.7B --device cuda
```

There appears an error: `CUDA error 35 at /root/workspace/crates/llama-cpp-bindings/llama.cpp/ggml-cuda.cu:478: CUDA driver version is insufficient for CUDA runtime version
current device: 0
`

BTW, run with CPU is OK.

---
Please reply with a 👍 if you want this feature.

**Comment by wsxiaoys** [comment]
Since 0.6.0 we distribute manylinux cuda binary directly - could you try it?

https://github.com/TabbyML/tabby/releases/tag/v0.6.0

**Comment by tastypear** [comment]
I forgot to try the bin first. It works!
Thank you very much!
